### PR TITLE
3.0 - PostgreSQL & quoting identifier

### PR DESCRIPTION
**Pull request by HavokInspiration**
I am waiting for Travis to see if the error reported on #5871 is not just from my local set up
(I actually wanted to do that on my fork to confirm what I initially observed without creating a PR just for the failing test but I'm quite tired and messed up when chosing my target, sorry about that).

Extract from my issue ticket :

Hi there.

I don't know if it's a bug since I basically know nothing about PostgreSQL, but I found a strange behavior when making a query on PostgreSQL with the `quoteIdentifiers` option set to `true` on on my connection config.

Consider the following test (based on the QueryTest::testSelectGroup() from the core) :

``` php
ConnectionManager::config('test', [
    'className' => 'Cake\Database\Connection',
    'driver' => 'Cake\Database\Driver\Postgres',
    //[...]
    'quoteIdentifiers' => true
]);

$query = new Query(ConnectionManager::get('test'));
$result = $query
            ->select(['total' => 'count(author_id)', 'author_id'])
            ->from(['Articles' => 'articles'])
            ->join(['table' => 'authors', 'alias' => 'a', 'conditions' => 'Articles.author_id = a.id'])
            ->group('Articles.author_id')
            ->execute();
$expected = [['total' => 2, 'author_id' => 1], ['total' => '1', 'author_id' => 3]];
$this->assertEquals($expected, $result->fetchAll('assoc'));
```

This test pass on SQLite, MySQL but triggers an error on PostgreSQL.
On PostgreSQL, the resulting query looks like this :

``` sql
SELECT count("author_id") AS "total", "author_id" FROM "articles" "Articles" INNER JOIN "authors" "a" ON Articles.author_id = a.id GROUP BY "Articles"."author_id"
```

which triggers the following error and hint `ERROR:  invalid reference to FROM-clause entry for table "articles"` ;  `HINT:  Perhaps you meant to reference the table alias "Articles".`

However, if I wrap the `Articles` with a `"` from `[...] ON Articles.[...]`, the query does not trigger the error.

I created a failing and am waiting for Travis to see if it's just on my local set up

### CODE REVIEW

**Comment by AD7six** [comment]
What is the sql you expect, and what is the sql that actually gets executed?

(Please answer by adding a description).

**Comment by HavokInspiration** [comment]
@AD7six Yeah, sorry about that, I actually targeted my fork (hence the lack of description) but as I said in the description, I quite tired messed when choosing my target.
I updated the initial description.

Apparently, it is not just my local set up...
I need however the opinion of someone who knows Postgre since I don't know if it is a proper way to create such a Query.

**Comment by markstory** [comment]
The issue is that some of your identifiers are quoted and some are not. In postgres when identifiers are quoted they become case sensitive and no longer match their unquoted brethren. If you want to write your conditions in a platform agnostic way, you must use array conditions. Identifier quoting does not manipulate QueryExpression objects as they can be filled with arbitrary SQL that we cannot parse and manipulate safely.

**Comment by HavokInspiration** [comment]
@markstory Ok, you confirmed what I suspected.

I guess you can close this as a won't fix then.
To be honest, I did not encounter the bug while coding for an app, I was working on the connection prefix and stumbled upon this while running some tests, so I don't really think this is something that will be encountered quite a lot.
Maybe it is worth mentionning that behavior in the documentation when talking about identifiers quoting ? By stating that identifiers should be manually quoted in join conditions if the `quoteIdentifiers` option is set to `true`.

Because if a developer tries with an array of conditions : 

```php
$result = $query
            ->select(['total' => 'count(author_id)', 'author_id'])
            ->from('articles')
            ->join([
                'table' => 'authors',
                'alias' => 'a',
                'conditions' => ['articles.author_id' => 'a.id']
            ])
            ->group('author_id')
            ->execute();
```

The resulting query will be : `SELECT count("author_id") AS "total", "author_id" FROM "articles" INNER JOIN "authors" "a" ON "articles"."author_id" = :c0 GROUP BY "author_id"`.

**Comment by markstory** [comment]
You're right, I forgot that conditions treat string values as bound parameters. To get correct join conditions one would need to use something like:

```php
$result = $query
            ->select(['total' => 'count(author_id)', 'author_id'])
            ->from('articles')
            ->join([
                'table' => 'authors',
                'alias' => 'a',
                'conditions' => ['articles.author_id' => new IdentifierExpression('a.id')]
            ])
            ->group('author_id')
            ->execute();
```

**Pull request closed without merging**
