### PR TITLE
Add an interface for the Application.

### PR DESCRIPTION
**Pull request by markstory**
I wasn't too happy about the coupling between Console and Http, and this new interface lets us not have that. Instead Http and Console will depend on Core (which they already do). I also felt a bit icky adding more typehints against concreteish implementations, as they have caused pain in the past.

I contemplated adding a ConsoleApplication and HttpApplication interface to  separate the `middleware` and `console` hooks, but thought that might be a bit overkill.

I'm completely open to scrapping this, or adding the additional interfaces based on what you folks think.

### CODE REVIEW

**Comment by robertpustulka** [comment]
I'd really like to see the seperate Console/Http app interfaces. I mentioned something like that on slack AFAIR some time ago. It could help develop console-only applications and sepere the console package out of the core.

**Comment by markstory** [comment]
@robertpustulka Would you put the console/http application interfaces in the http & console packages, or in core?

**Comment by robertpustulka** [comment]
@markstory maybe in the core. Standalone console package would depend on core anyway. And we'd keep application-related interfaces and classes in one place. What about `Cake\Core\Application` namespace for that?

**Comment by markstory** [comment]
@robertpustulka I've updated the interfaces now.

**Review by lorenzo — APPROVED** [review]
I like how his turned out!

**Pull request merged**
