### PR TITLE
Allow Cell name containing "Cell"

### PR DESCRIPTION
**Pull request by markusramsak**
i.e. CellotapesCell doesn't work at the moment

### CODE REVIEW

**Comment by ceeram** [comment]
Can you please add a test for this as well to prevent regression

**Comment by mdlouhy** [comment]
I don't know how to do that, sorry.

**Comment by markstory** [comment]
I'll merge this and take care of adding the test case.

**Comment by markstory** [comment]
Tests added in c644474f9965f020483f489b90643c4266c3f83b

**Comment by mdlouhy** [comment]
thanks ;)

**Pull request merged**
