### PR TITLE
Bug in CakeEmail matching pattern

### PR DESCRIPTION
**Pull request by IonutBurlacu**

### CODE REVIEW

**Comment by dereuromark** [comment]
We should have a test case with such an example domain to prevent regressions.

**Comment by gemal** [comment]
can this be merged?

**Comment by dereuromark** [comment]
I mentioned above that a test case is critical for this to be mergable.

**Comment by gemal** [comment]
ok. sorry. we are doing the test case now

**Review by dereuromark — APPROVED** [review]

**Comment by IonutBurlacu** [comment]
Not sure why the tests failed but it seems that it's not caused by my changes.

**Comment by dereuromark** [comment]
Yes, unrelated. I re-triggered it.

**Comment by thaJeztah** [comment]
Are underscores actually allowed in domain names?

**Comment by dereuromark** [comment]
I was reading https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it

**Comment by markstory** [comment]
I'll get this merged and ported to 3.x

**Pull request merged**
