### PR TITLE
Consolidate placeholders to new syntax. Eases 4.x migration.

### PR DESCRIPTION
**Pull request by dereuromark**
Follow up on https://github.com/cakephp/cakephp/pull/11540
Resolves https://github.com/cakephp/cakephp/issues/11524

Docs: https://github.com/cakephp/docs/pull/5478

Consolidating translation strings.

This eases migration for 4.0 as this can be cleaned up in 3.6 with migration guide.
Also less confusion for those upgrading from 2.x and str-replacing all placeholders to discover that some do not function as expected.

### CODE REVIEW

**Comment by inoas** [comment]
IMHO we should however keep a list of the %s strings in some deprecated dummy php file just so that i18n extract can pick them up when updating cakephp/localized so that we can for some time still support 3.0 < 3.6?

**Comment by dereuromark** [comment]
Sure, also cakephp/localized can still contain them as dummy content.

**Comment by inoas** [comment]
So can you add `src/View/Helper/FormHelper_deprecated_translations.php` to this PR
```php
<?php
// @deprecated since 3.6, will be removed in 4.0, use {0} syntax instead.
__d('cake', 'New %s');
__d('cake', 'Edit %s');
```

**Comment by dereuromark** [comment]
No, in this PR it makes no sense, once you cross to 3.6 and applied the migration you need to handle this old one on your own.
This is only required if you use an older CakePHP version and here localized plugin can handle this extra ones.

**Pull request merged**
