### PR TITLE
Mismatched entity virtual fields cache names

### PR DESCRIPTION
**Pull request by zesarone**
Fix of mismatched cache index name when using camel cased name of virtual field in entity.

### CODE REVIEW

**Comment by zesarone** [comment]
This content class gave me `{allUrls:null}` after JSON-serializing, seems  `Inflector::underscore` is used to save to the cache, later fetching from the cache does not.

```
class Content extends Entity
{
   protected $_virtual = ['allUrls'];
   protected function _getAllUrls()
   {
    ...
     return [...];
   }
}
```

**Comment by lorenzo** [comment]
One of the goals of the refactor that introduced this error was to avoid the inflector call. Is there any other way in which we don't need to call it every single time?

**Comment by jadb** [comment]
@lorenzo, maybe if we don't [inflect](https://github.com/zesarone/cakephp/blob/6c5c6cb04ba59d2193b59e37298793e4b2013d83/src/Datasource/EntityTrait.php#L517) before caching it?

**Comment by markstory** [comment]
@zesarone Have you tried using `dev-master`? A similar issue #8247 has already been fixed.

**Comment by zesarone** [comment]
@markstory, I missed that issue,  I will try it out and have a look at it on monday when I'm back.

**Comment by zesarone** [comment]
I have now tried the fix for issue #8247, and it works fine as a fix for me as well, I believe this is the better fix if we are to limit the use of `Inflector`.
I am just wondering why we need `$snakefield` (returned from `Inflector`), since I cant se that it is used later from the cache?

**Comment by lorenzo** [comment]
It is because both the snake case and the camelized version are strored in the cache now

**Pull request closed without merging**
