### PR TITLE
Fix ConsoleOutput styles() API.

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/cakephp/issues/13559

One of the last god wrapper beasts dismantled into a clean API.

### CODE REVIEW

**Comment by markstory** [comment]
Looks good to me. I'm pretty sure rector can handle refactoring this method, and it should be infrequently used by applications/plugins.

**Review by ADmad — APPROVED** [review]
LGTM, just the CS error needs to be fixed.

**Comment by ADmad** [comment]
> I'm pretty sure rector can handle refactoring this method

We should create an issue to keep track of add such refactoring which we need to added else many would be missed.

**Comment by markstory** [comment]
@Admad I will add the rector pull tonight. Thus far I have been adding them as we go. There are likely some we have missed but we can fix that as we and others start using the upgrade tool/rector.

**Comment by markstory** [comment]
Rector rule added in rectorphp/rector#2172

**Pull request merged**
