### PR TITLE
3.1 fix a render issue when the result of the progress is a float

### PR DESCRIPTION
**Pull request by antograssiot**

### CODE REVIEW

**Comment by HavokInspiration** [comment]
I was preparing a similar PR :)

I'll add the test I added as another commit.

**Comment by HavokInspiration** [comment]
Test added.

**Comment by antograssiot** [comment]
@HavokInspiration I forgot to stage the test file, I did just update an already existing test but thank's anyway :stuck_out_tongue:

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/cakephp/pull/6618

**Comment by markstory** [comment]
Thanks @antograssiot :+1:

**Pull request merged**
