### PR TITLE
Removing Exception typehints in the error handling to account for PHP 7

### PR DESCRIPTION
**Pull request by lorenzo**
Since PHP 7 is around the corner, I think we should tho this sooner rather than later. This is probably controversial, and definitely BC breaking, but I can't think of a realistic better way.

Maybe we could offer some `sed` foo for people upgrading to the next version?

### CODE REVIEW

**Comment by markstory** [comment]
I am not a fan of a BC change in  bugfix release. However, I think it is better than our other options of: Do nothing, Wait until 3.2, and Go to 4.0.

**Comment by rchavik** [comment]
What's wrong with going to 4.0?

**Comment by josegonzalez** [comment]
Wait till 3.2?

**Comment by markstory** [comment]
@rchavik Just marketing-ese, and no auto-updates from composer. I also feel it is a tiny bit silly to bump a major version because we are adapting to things in new versions of PHP.

Is there an alternative where we do something like what [whoops did](https://github.com/filp/whoops/pull/312/files)? It would require people migrating to PHP7 to use a different PHP7 compatible handler method - which could become the new default.

**Comment by ADmad** [comment]
This should definitely not go into master, 3.2 at the earliest.

**Comment by markstory** [comment]
@ADmad What about a _new_ method that had more liberal typehints that were compatible with PHP7? We could recommend people who wanted to use PHP7 to use that method _instead_ of the current one.

**Comment by ADmad** [comment]
@markstory That sounds reasonable

**Comment by lorenzo** [comment]
More than a new method we need a set of new classes without the type hints.

**Comment by markstory** [comment]
@lorenzo Why a new set of classes. If the existing ExceptionHandler had a `handleErrorException` method that had PHP7 compatible typehints, that method could cast that error into an `Exception` that could be passed onto the existing method. That is the approach that whoops took as well based on my reading of the changes.

**Comment by lorenzo** [comment]
@markstory to begin with, the constructor of the ExceptionRenderer class has a typehint for `Exception`, so we would need another renderer at the very least

**Comment by markstory** [comment]
@lorenzo Well that's annoying. Could the PHP7 compatible handler functions cast/wrap errors before the Renderer is created/invoked?

**Comment by lorenzo** [comment]
@markstory That's a good idea, I'll look into that

**Comment by lorenzo** [comment]
@markstory @ADmad I re-implemented this and made it backwards compatible

**Comment by ADmad** [comment]
@lorenzo :+1:

**Comment by markstory** [comment]
Looks good to me. We'll need to update the documentation for PHP7 users.

**Comment by lorenzo** [comment]
@markstory I don't think this requires any changes in documentation, what do you have in mind?

**Comment by markstory** [comment]
@lorenzo Perhaps just a note about how to get PHP7 compatibility.

**Comment by lorenzo** [comment]
@markstory It's automatic... no need to do anything. Perhaps the only thing that should be mentioned is that in custom error handlers / exception renderers, the exception should be unwrapped if you get a `PHP7ErrorException`

**Comment by markstory** [comment]
@lorenzo You're totally right! For some reason I thought we still had the Configure values, but we don'!

**Pull request merged**
