### PR TITLE
Consolidate single HTML tags to have a closing /> tag element.

### PR DESCRIPTION
**Pull request by dereuromark**
`<input/>` is a single element just as br, hr, meta, img and CO.
So for consistency this tag needs the closing `/`, as well.

We can backport this to 2.8 afterwards.

### CODE REVIEW

**Comment by markstory** [comment]
Sounds good.

**Comment by dereuromark** [comment]
I checked, 2.x is fine already. No need to backport. 
This seems to be a regression in 3.x, but a backport to 3.0 seems too late now, so sticking to 3.1 is fine ;)

**Comment by ADmad** [comment]
3.x generates HTML5 so there was no need for this change.

**Comment by dereuromark** [comment]
Sorry, but you are wrong.
HTML5 does not mean that is must not be applied.
Also, this was mainly about consistency, and that implies that the other tags are already in that form, which they are:
- https://github.com/cakephp/cakephp/blob/94adbbaf084ea24d13413ea5143e0470670850a7/src/View/Helper/HtmlHelper.php#L57
- https://github.com/cakephp/cakephp/blob/94adbbaf084ea24d13413ea5143e0470670850a7/src/View/Helper/HtmlHelper.php#L58
- https://github.com/cakephp/cakephp/blob/94adbbaf084ea24d13413ea5143e0470670850a7/src/View/Helper/HtmlHelper.php#L75
- https://github.com/cakephp/cakephp/blob/94adbbaf084ea24d13413ea5143e0470670850a7/src/View/Helper/HtmlHelper.php#L77
- https://github.com/cakephp/cakephp/blob/94adbbaf084ea24d13413ea5143e0470670850a7/src/View/Helper/HtmlHelper.php#L61

**Comment by ADmad** [comment]
> Sorry, but you are wrong.

Guess that settles the discussion.

**Comment by markstory** [comment]
Lets try and be civil. I didn't know that close tag style was another tab/space holy war. I mergedthis because we we're usimg both styles and having one consistent style seemed like a good idea.

**Comment by dereuromark** [comment]
Exactly.
I dont know why the comment of @admad was necessary in the first place.

**Comment by ravage84** [comment]
:+1:

**Comment by jhli** [comment]
It is not a holy war. Tabs vs spaces is merely cosmetic (I liked tabs but meh).

Having self closing tags allows to ship in:

* HTML5 as text/html
* HTML5 as xml/application also containing other xml dialects such as embedded mathml or svg possibly
* XHTML as xml/application
...allowing dtd validation, xml schema, xsl(t) etc.

Thanks for the PR.

**Pull request merged**
