### PR TITLE
Avoid local issue in PHPStan check.

### PR DESCRIPTION
**Pull request by dereuromark**
Small issue on local run (PHP 8.3)
```
  Line   Http/Client/FormData.php                                                                                                                                                                                            
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  160    Offset 'uri' on array{timed_out: bool, blocked: bool, eof: bool, unread_bytes: int, stream_type: string, wrapper_type: string, wrapper_data: mixed, mode: string, ...} on left side of ?? always exists and is not  
         nullable.                                                                                                                                                                                                           
         🪪  nullCoalesce.offset                                                                                                                                                                                             
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
```

Addition to
https://github.com/cakephp/cakephp/pull/18014

cc @LordSimal

### CODE REVIEW

**Comment by dereuromark** [comment]
But I also get that on current 5.x already, maybe we should patch that instead?

**Comment by LordSimal** [comment]
@dereuromark I get the same error locally but for some reason - as you can see - the CI doesn't get that error. I always just removed that ignore line from the baseline file.

**Comment by dereuromark** [comment]
Quite annoying that you cannot trust the local output here.
I wonder whats causing that.

**Comment by dereuromark** [comment]
Well, I guess I close it for now, will just be annoying locally for a while longer then.

**Pull request closed without merging**
