### PR TITLE
clone stored message to prevent overwrite

### PR DESCRIPTION
**Pull request by bradmcnaughton**
Fix for Issue 17030 https://github.com/cakephp/cakephp/issues/17030

### CODE REVIEW

**Comment by markstory** [comment]
It would be good to have a test covering the issue this is fixing. If you need help adding a test let us know. I'm happy to help with adding tests.

**Comment by bradmcnaughton** [comment]
Hi @markstory - good idea, I have added a test case to EmailTraitTest , if any issues with it please let me know :) Thanks.

**Comment by markstory** [comment]
@bradmcnaughton Thanks for adding the test. This looks good to merge once we have the code-style error fixed up.

**Comment by markstory** [comment]
Thank you 🎉

**Pull request merged**
