### PR TITLE
Added a .varci.yml file to automate some issue maintenance tasks

### PR DESCRIPTION
**Pull request by lorenzo**
More ideas for automation are welcomed

### CODE REVIEW

**Comment by ADmad** [comment]
There should be a rule to auto close issues with empty description. In spite of our issues template there have been such cases.

**Comment by antograssiot** [comment]
also in addition to @ADmad 's suggestion maybe also auto close issue when the description is equal to the provided layout if that's possible

**Comment by markstory** [comment]
Looks like a good start to me.

**Comment by lorenzo** [comment]
I'll add the other suggested rules as another PR

**Pull request merged**
