### PR TITLE
Throw exception if argument passed to Table::connection() is of incorrec...

### PR DESCRIPTION
**Pull request by ADmad**
...t type

Refs #6199

### CODE REVIEW

**Comment by markstory** [comment]
Looks good to me.

**Comment by ndm2** [comment]
Is there a reason for not using typehints instead? And in case an exception must be used, wouldn't  `InvalidArgumentException` be more appropriate?

**Comment by ADmad** [comment]
You are right, just typehinting would be enough. Silly me.

**Comment by lorenzo** [comment]
Yeah, I would say using the typehint was more appropriate

**Comment by ADmad** [comment]
I'll change it.

**Pull request merged**
