### PR TITLE
Option to use application's element with same name from plugin

### PR DESCRIPTION
**Pull request by hashmode**
The changes are discussed in this issue https://github.com/cakephp/cakephp/issues/9240

### CODE REVIEW

**Comment by ADmad** [comment]
Tests required for the new feature

**Comment by markstory** [comment]
@hashmode Do you need a hand with writing tests?

**Comment by hashmode** [comment]
@markstory actually it would be great (cant seem to manage my time), I ticked the "allow edits from maintainers" checkbox, thanks and sry for the delay

**Comment by markstory** [comment]
Merged into master in 17a9199c759bb535bf6a9bf4eb3fd53d5b065090

**Comment by inoas** [comment]
@hashmode could you update the cakephp/docs for this?

**Comment by markstory** [comment]
I think this could be an API docs only thing. We can't reasonably fit every use case and scenario into the book :smile:

**Comment by inoas** [comment]
Took a look at the tests and it wasn't directly obvious how to use it from a view template. 
From the issue #9240 - Is this the syntax? `<?php echo $this->element('my_element', [], ['plugin' => false]);?>` I can add that one line to the docs then.

**Comment by markstory** [comment]
@inoas The example you have is correct.

**Pull request closed without merging**
