### PR TITLE
Throw exception on duplicate plugin loading.

### LINKED ISSUE #17627: Double loading of plugin
Due to a user error, I had `$this->addPlugin('Authorization');` at the end of my `getAuthenticationService` function in Application.php, as well as in its correct location in the `bootstrap` function. This caused errors complaining about the lack of authorization policies defined for various entity tables. I am using entity authorization policies but not table policies in my app.

Obviously this is a wholly avoidable error but I thought I would share this info in case others report similar errors, or if there was a way of preventing the plugin from being added twice.

### PR DESCRIPTION
**Pull request by ADmad**
Closes #17627

### CODE REVIEW

**Comment by othercorey** [comment]
Looks good to me.

**Comment by LordSimal** [comment]
This breaks my whole testsuite since I get a bunch of 
```
Plugin named `DebugKit` is already loaded
```

as it seems the migrations plugin (called by the Migrator in the tests/bootstrap.php) causes the plugin collection to be initialized before the testsuite creates the application object, therefore causing my issue
https://github.com/cakephp/migrations/blob/4.x/src/Util/UtilTrait.php#L78
https://github.com/cakephp/cakephp/blob/5.next/src/Core/Plugin.php#L45

**Comment by LordSimal** [comment]
Besides the fact that `$dispatcher->resolveUrl($url);` calls bootstrap via
https://github.com/cakephp/cakephp/blob/5.next/src/TestSuite/IntegrationTestTrait.php#L495C16-L495C46
https://github.com/cakephp/cakephp/blob/5.next/src/TestSuite/MiddlewareDispatcher.php#L79

And `$server->run()` does as well
https://github.com/cakephp/cakephp/blob/5.next/src/TestSuite/MiddlewareDispatcher.php#L141
https://github.com/cakephp/cakephp/blob/5.next/src/Http/Server.php#L85

So just a simple
```
$this->get([
    'controller' => 'MyController',
    'action' => 'myAction',
    1234,
]);
```
does double bootstrapping.

---

 I would be in favor of reverting this change.

**Comment by othercorey** [comment]
Should we trigger a warning for any of these cases instead of just silently ignoring?

**Comment by dereuromark** [comment]
Doesnt this double bootstrapping as route cause need to be removed instead? Indicates at least also some dirtyness here.
Or that we use more isLoaded() checks instead of loading twice?

**Comment by LordSimal** [comment]
Preventing the application to be bootstrapped twice/multiple times would be a nice addition.

**Comment by ADmad** [comment]
I don't think preventing duplicate bootstrapping is feasible. Besides integrations tests there are tests for `Application` class too which run bootstrapping multiple times.

So cleaning up any shared/static state before each test run seems to be the only option.

**Pull request merged**
