### PR TITLE
add fo-fo

### PR DESCRIPTION
**Pull request by gemal**

### CODE REVIEW

**Comment by dereuromark** [comment]
Is this already present in cake4 and cake3?

**Comment by gemal** [comment]
> 
> 
> Is this already present in cake4 and cake3?

Sorry. I'm not sure

**Comment by dereuromark** [comment]
You need to first make a PR against master, then backport to 3.x and then to 2.x
Otherwise we have inconsistencies higher up.

**Comment by ADmad** [comment]
> Is this already present in cake4 and cake3?

With the use of `intl` extension Cake 3/4 doesn't need to maintain this list.

**Review by dereuromark — APPROVED** [review]

**Pull request merged**
