### PR TITLE
Fix errors reported by psalm and phpstan.

### PR DESCRIPTION
**Pull request by ADmad**
Plus don't merge PRs with failed `static-analysis` node of scrutinizer :slightly_smiling_face:. 

Psalm / phpstan reported quite a few actual errors for #13330.

### CODE REVIEW

**Comment by markstory** [comment]
@ADmad My mistake, I confused that failure with the `Inspection` one that has been broken for a while now.

**Comment by ADmad** [comment]
@markstory No worries. We need to wait for new release of slevomat/coding-standard for the `Inpections` build to be fixed :/.

**Comment by dereuromark** [comment]
Cant we use dev-master until then?

**Comment by ADmad** [comment]
@dereuromark I would wait a few days more and if there isn't a release use it's `dev-master`.

**Pull request merged**
