### PR TITLE
[4.x] Removing deprecated methods from I18n

### PR DESCRIPTION
**Pull request by burzum**
Refs #11934

### CODE REVIEW

**Comment by burzum** [comment]
@markstory do we need to change the existing prefixed `_` methods and properties as well? I would prefer to keep them.

**Comment by ADmad** [comment]
> do we need to change the existing prefixed _ methods and properties as well?

I don't think we should go about renaming all existing properties/methods with underscore prefixes.

**Comment by burzum** [comment]
@ADmad OK, but we should decide to use one of both conventions and not mix them?

**Comment by ADmad** [comment]
We have stopped adding underscore prefix to new protected properties/methods but the mix will stay for a while due to existing properties. Also there are features like entity getter/setter which rely on having prefixed method names.

**Comment by markstory** [comment]
I'm with @ADmad on the topic of renames. We shouldn't rename tons of methods/properties for cosmetic reasons. We can gradually fix them if we want later on.

**Pull request merged**
