### PR TITLE
Update Shell.php

### PR DESCRIPTION
**Pull request by kminek**
missing check

### CODE REVIEW

**Comment by jadb** [comment]
@kminek thanks! 

I can see it apparently resolves an issue with the interactive mode not being checked before prompting the user for input - could you confirm that and please elaborate more on future PRs so we can quickly understand the scope without having to look into the code.

**Comment by kminek** [comment]
i'm expecting that createFile method should work as per documentation: http://book.cakephp.org/3.0/en/console-and-shells.html#creating-files

**Comment by jadb** [comment]
And what's not exactly working? Please explain or paste what you are getting. I want to help you get this PR merged ASAP.

**Comment by kminek** [comment]
setting my shell class property `interactive` to false triggers user prompt which is wrong behavior

**Comment by markstory** [comment]
Changes look good. It would be double awesome to have a test case. If you don't know how to add one, we can take care of it.

**Comment by dereuromark** [comment]
Just adding this third check might be dangerous.
What if `if (is_file($path) && empty($this->params['force']))` and not interactive?
Then it would now always create the file, where it before most likely skipped the creation due to the prompting.
I don't think it should directly run into the else, but instead check if the file exists and force is off and in that case skip the creation (in non interactive mode).

**Comment by dereuromark** [comment]
Never mind, I just saw the docs comment:

>  If the shell’s interactive property is false, no question will be asked and the file will simply be overwritten.

So it is documented that it will force-overwrite in that case. So the changes look fine indeed.

**Comment by lorenzo** [comment]
@kminek Thanks for the great work!!

**Pull request merged**
