### PR TITLE
Wrong exception class call in DateTimeType, FloatType

### PR DESCRIPTION
**Pull request by nojimage**
I found invalid exception class call.

### CODE REVIEW

**Comment by dereuromark** [comment]
Looks good to me.

**Comment by ADmad** [comment]
@nojimage For future reference please use proper commit messages, not generic default ones Github pre-fills for you.

**Comment by nojimage** [comment]
@ADmad Okay.



—
Mailbox から送信

**Comment by markstory** [comment]
Something is funny with phpunit/travis. Going to merge anyways.

**Pull request merged**
