### PR TITLE
Made FormHelper autoSetCustomValidity option true by default.

### PR DESCRIPTION
**Pull request by ADmad**
Refs #11837

### CODE REVIEW

**Comment by markstory** [comment]
I feel like this is something that should be featured prominently in the formhelper docs. Any ideas on where this behavior should be mentioned?

**Comment by ADmad** [comment]
There a section [Using Custom Validators](https://book.cakephp.org/3.0/en/views/helpers/form.html#using-custom-validators). Perhaps that could be renamed and the section updated to include info about this option.

I also think it would be nice to be able to have `autoSetCustomValidity` as an option for `FormHelper::create()` too.

**Comment by markstory** [comment]
> I also think it would be nice to be able to have autoSetCustomValidity as an option for FormHelper::create() too.

Should we be doing that change now?

**Comment by ADmad** [comment]
> Should we be doing that change now?

I guess so, on the 4.x branch for docs.

**Pull request merged**
