### PR TITLE
Revised ExtractTask::_extractTokens() to delegate pass FormHelper::in…

### LINKED ISSUE #13303: I18N ExtractTask does not extract those strings generated and passed to Gettext through core helpers
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.10.18
* Platform and Target: Nginx 1.14.0, PHP 7.2.17, MySQL 5.7.26

### Current functionality
FormHelper::input(), ::radio() and Paginator::sort() all use Inflector to generate strings for HTML output and pass this output to Gettext.

However, ExtractTask::_extractTokens() currently only calls ExtractTask::_parse() to process user-defined strings through the __?() functions and not those generated and passed to Gettext through its core helpers.  

### Proposed enhancement
Form::input(), Form::radio() and Paginator::sort() should be passed in as an array to the $functionName argument when calling ExtractTask::_parse() (similar to call_user_func() when passing a class method) and ExtractTask::_parse() statements added to ExtractTask::_extractTokens() to process these.

ExtractTask::_parse() should have a if() check for token of type T_OBJECT_OPERATOR and if the token being parsed matches the $functionName an additional if() check be performed for an array of options and if there is no match for a 'label' or 'legend' option pass the token string as $fieldName argument to a new protected ::_formatLabel() to split and humanize the token string (e.g. a Model.Field token string) before passing to ::_addTranslation()

FormHelper::label() currently performs similar functionality to the proposed ::_formatLabel() - it passes the strings it generates to Gettext but these strings are never extracted which this proposed enhancement will address.

### Enhancement as plugin
The proposed enhancement extends the core I18nShell and ExtractTask. Attached is a pluginized version that we use across all our projects / CakePHP apps. This alleviates the need to define a 'label' or 'legend' option on every FormHelper::input() or ::radio() just to pass the same string as the default inflected field name to __() when the core helpers already do this.

[I18n.zip](https://github.com/cakephp/cakephp/files/3234866/I18n.zip)

### PR DESCRIPTION
**Pull request by trenshaw**
…put(), ::radio() and PaginatorHelper::sort() as array callables to ExtractTask::_parse()

Revised ExtractTask::_parse() to check for and match T_OBJECT_OPERATOR tokens against passed array callables skipping any 'label' or 'legend' strings passed in $options array (in either full or short array syntax) passing labels that would be generated by these helpers to new protected ::_formatLabel() before passing to ::_addTranslation()

Fixes #13303 pull requested for 3.next and 2.10.20 milestone

### CODE REVIEW

**Comment by ADmad** [comment]
Merge conflicts need to be resolved. It would be easier if you add your changes on top of current `3.next` HEAD.

**Comment by ADmad** [comment]
Tests also required.

**Comment by trenshaw** [comment]
Sorry I can't do the tests for 3.x - we are not there yet! Migration of our apps to 3.x won't start until 2020. Hopefully someone else can contrib the tests?

**Comment by dereuromark** [comment]
@trenshaw You can give us some of the code snippets that would now be parsed.
That could help for someone who is able to write a few tests on top here.

**Comment by trenshaw** [comment]
@dereuromark happy to .. will do!

**Comment by trenshaw** [comment]
@dereuromark just saw 3.8.6 release .. any chance we can get the I18n enhancements in for 3.8.7? I don't think I have write access to resolve the conflict?

**Comment by othercorey** [comment]
@trenshaw Your branch is very old.  You need to merge from upstream for this conflict to resolve.

**Pull request closed without merging**
