### PR TITLE
Fix regression caused by PR #6942.

### PR DESCRIPTION
**Pull request by ADmad**
@lorenzo @markstory Fixed regression while still allowing dot in name :)

### CODE REVIEW

**Comment by lorenzo** [comment]
Great job @ADmad

**Comment by lorenzo** [comment]
@Admad can you backport to master?

**Comment by ADmad** [comment]
@lorenzo Done in 9b857d090f0301852ea2d200a12debde4a5172de. You should have just pointed out to me that the original patch was done for 3.0 not 3.1 :)   I mistakenly thought it was on 3.1.

**Comment by lorenzo** [comment]
I realized it was in 3.1 right after I merged, sorry

**Comment by ADmad** [comment]
No worries, it was my fault not yours :)

**Pull request merged**
