### PR TITLE
Run testsuite on PHP 8.4

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
```
Fatal error: Declaration of Cake\Chronos\Chronos::createFromTimestamp(int $timestamp, DateTimeZone|string|null $timezone = null): static must be compatible with DateTimeImmutable::createFromTimestamp(int|float $timestamp): static in /home/runner/work/cakephp/cakephp/vendor/cakephp/chronos/src/Chronos.php on line 743
```

Woot, they added a new method to the interface in 8.4?

**Comment by ADmad** [comment]
> Woot, they added a new method to the interface in 8.4?

https://github.com/php/php-src/pull/12413

Great, so we will need to make a breaking change in Chronos for 8.4 compatibility.

**Comment by othercorey** [comment]
The risk of extending PHP classes although this is a very rare change.

**Comment by ADmad** [comment]
> /home/runner/work/_temp/44f45290-edee-4698-9f8b-a3393e518a01.sh: line 14:  3276 Segmentation fault      (core dumped) vendor/bin/phpunit

~~Need help with this :)~~

**Comment by ADmad** [comment]
Yay, only 1 error.

```
1) Cake\Test\TestCase\I18n\Formatter\IcuFormatterTest::testBadMessageFormat
Failed asserting that exception of type "Exception" is thrown.
```

**Comment by ADmad** [comment]
Welp, now it's failing at composer install itself

```
Error: Composer\Platform\Runtime::invoke(): Argument #1 ($callable) must be of type callable, array given, called in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php on line 341
```

**Comment by othercorey** [comment]
> Welp, now it's failing at composer install itself
> 
> ```
> Error: Composer\Platform\Runtime::invoke(): Argument #1 ($callable) must be of type callable, array given, called in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php on line 341
> ```

I didn't see any 8.4 upgrade notes about callable type changes.

**Comment by ADmad** [comment]
I have opened an issue with composer about the error.

**Pull request merged**
