### PR TITLE
Change method visibility from public to protected

### PR DESCRIPTION
**Pull request by chinpei215**
This change may break B/C, but I would like to make 3.4 safer.

### CODE REVIEW

**Comment by markstory** [comment]
We'll have to include this in the migration guide, but I think it is worth doing :+1:

**Comment by chinpei215** [comment]
Can I add the new section after the `Behavior Changes` section ?
```rst
Visibility Changes
==================

* ``MailerAwareTrait`` will now become protected.
* ``CellTrait::cell`` will now become protected.
```

**Comment by ADmad** [comment]
>  ``MailerAwareTrait`` will now become protected.

@chinpei215  Should be ``MailerAwareTrait::getMailer()``.   Also it would be nice to mention why the change was made.

**Comment by chinpei215** [comment]
@ADmad Oops. Thank you. Also, I came up with the following sentence.

> If traits are used in controllers, their public methods become actions. These changes will make your application secure if you are using them in your controllers.

**Comment by ADmad** [comment]
@chinpei215 The message sounds good.

**Comment by chinpei215** [comment]
@ADmad Thank you.

**Comment by lorenzo** [comment]
What's the reason for this change?

**Comment by chinpei215** [comment]
@lorenzo Now are you okay with this change? Or do you have another idea?

**Comment by ADmad** [comment]
An alternative way is to use a bit of extra reflection and ensure that the `getMailer()` method isn't provided by the `MailerAwareTrait` https://gist.github.com/ADmad/3dde6c994733e5dd47763d6bbb122708

We can add similar check for `CellTrait::cell()`.

So for majority cases we are adding two extra string check when invoking an action.

**Comment by lorenzo** [comment]
No, I think merging this is fine

**Comment by chinpei215** [comment]
@lorenzo Thank you.

**Pull request merged**
