### PR TITLE
Add assertResponseNotContains

### PR DESCRIPTION
**Pull request by dereuromark**
Pendant for assertResponseContains() to quickly negate it in test cases.

### CODE REVIEW

**Comment by lorenzo** [comment]
A test? :)

**Comment by dereuromark** [comment]
Those a more cumbersome for test suite test methods, though :)
If you insist I will do it.

**Comment by markstory** [comment]
Looks fine to me.

**Comment by lorenzo** [comment]
@dereuromark You usually test that by expecting a failure, that is try-catch the exception thrown by phpunit

**Comment by dereuromark** [comment]
We didnt do that way in the current tests, yet, though.

**Pull request merged**
