### PR TITLE
Add per-TestCase fixture strategy setup and teardown

### PR DESCRIPTION
**Pull request by othercorey**
This allows support for more specialized strategies. Changing the interface in the future will be difficult.

### CODE REVIEW

**Comment by markstory** [comment]
What kind of scenarios do you see the additional hook methods being useful in? I'm not against them but I also can't think of when I would need them either.

**Comment by othercorey** [comment]
> What kind of scenarios do you see the additional hook methods being useful in? I'm not against them but I also can't think of when I would need them either.

The scenario I was trying to keep open is static fixtures that dont need to rebuild each test. 

Might be useful only for large numbers of tests.

**Comment by othercorey** [comment]
I suppose you could setup a temp db with this but I wasn’t planning anything like that.

**Comment by markstory** [comment]
> The scenario I was trying to keep open is static fixtures that dont need to rebuild each test.

Not rebuilding the fixture objects multiple times per test run could help with performance. I don't think we're getting that with this change though as we dereference the fixtures in the teardownafterclass step.

**Comment by othercorey** [comment]
> Not rebuilding the fixture objects multiple times per test run could help with performance. I don't think we're getting that with this change though as we dereference the fixtures in the teardownafterclass step.

This solution would allow static fixtures for a TestCase not an entire test run. 

If we wanted static textures for an entire test run, then we would have to keep a static array of fixtures in the strategy.

**Pull request closed without merging**
