### PR TITLE
EntityContext: Introspect 'null' to determine use of 'required' attribute

### PR DESCRIPTION
**Pull request by rchavik**
Allow browsers to take advantage of html5 validation

### CODE REVIEW

**Comment by ADmad** [comment]
I don't really understand what this patch is meant for.

**Comment by rchavik** [comment]
It adds 'required' attribute in form input element when field is not null. that allows the browser html5 validation to be triggered.

**Comment by saeideng** [comment]
When you use require validator,that added automatically

**Comment by ADmad** [comment]
I don't really like adding the required attribute directly based on schema. As @saeideng mentioned it's already added based on your validation rules so you should add proper validation for your fields instead.

**Comment by markstory** [comment]
Moving to 3.5, as changing the default behavior of FormHelper can cause unexpected behavior that shouldn't be part of bugfix releases.

**Comment by rchavik** [comment]
Ok.  I'm ok to close then.

**Comment by dereuromark** [comment]
I like the idea of the database schema (default and null) reflect in the form output defaults.
But as said before the schema-influenced (baked) validation rules then already do that.
It could get weird, if the schema says required and the validation rules say not required, which one takes precedence then?

**Comment by markstory** [comment]
@dereuromark Good point about needing to reflect the validation rules, also shouldn't this kind of code be located in the `EntityContext::isRequired()` with the other logic?

**Comment by rchavik** [comment]
I'll try to rework this based on input.

Thanks

**Comment by markstory** [comment]
Ping

**Comment by rchavik** [comment]
I've not had time to get back to this yet.  As this is not critical, let's close this for now.

I'll reopen if I had a chance to pursue this again.

**Comment by rchavik** [comment]
Branch has been deleted.

I will keep it in my fork:
- https://github.com/rchavik/cakephp/tree/3.4-required-fields This PR
- https://github.com/rchavik/cakephp/tree/3.4-required-fields-new Improvement on this PR based on comments. test not passing.

**Pull request closed without merging**
