### PR TITLE
5.x Fix up class name issue on loading components

### PR DESCRIPTION
**Pull request by dereuromark**
This fixes the issue for me.

Refs https://github.com/cakephp/cakephp/issues/17435

### CODE REVIEW

**Comment by PaulHendriks** [comment]
Yes, this fixes the problem for me as well.

**Review by markstory — COMMENTED** [review]
Looks good, having a test for this seems important as a regression here will be frustrating to find and fix in the future.

**Comment by dereuromark** [comment]
I didnt find a way for meaningful test that most importantly would fail with status quo..

**Comment by dereuromark** [comment]
This does however seem to break one of my apps

```
1) App\Test\TestCase\Controller\Admin\EventsControllerTest::testAddPostUpload
Cake\Core\Exception\CakeException: Unknown object `FileStorage`.

/shared/httpd/de/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php:235
/shared/httpd/de/vendor/dereuromark/cakephp-file-storage/src/Model/Behavior/FileStorageBehavior.php:213
/shared/httpd/de/vendor/cakephp/cakephp/src/Event/EventManager.php:329
/shared/httpd/de/vendor/cakephp/cakephp/src/Event/EventManager.php:307
/shared/httpd/de/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php:88
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Table.php:2114
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Table.php:2080
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Table.php:1969
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Table.php:1600
/shared/httpd/de/vendor/cakephp/cakephp/src/Database/Connection.php:632
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Table.php:1600
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Table.php:1968
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Table.php:2001
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Association.php:1171
/shared/httpd/de/vendor/dereuromark/cakephp-file-storage/src/Model/Behavior/FileAssociationBehavior.php:157
/shared/httpd/de/vendor/dereuromark/cakephp-file-storage/src/Model/Behavior/FileAssociationBehavior.php:118
/shared/httpd/de/vendor/cakephp/cakephp/src/Event/EventManager.php:329
/shared/httpd/de/vendor/cakephp/cakephp/src/Event/EventManager.php:307
/shared/httpd/de/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php:88
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Table.php:2114
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Table.php:2080
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Table.php:1969
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Table.php:1600
/shared/httpd/de/vendor/cakephp/cakephp/src/Database/Connection.php:632
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Table.php:1600
/shared/httpd/de/vendor/cakephp/cakephp/src/ORM/Table.php:1968
/shared/httpd/de/vendor/dereuromark/cakephp-shim/src/Model/Table/Table.php:378
/shared/httpd/de/src/Controller/Admin/EventsController.php:126
/shared/httpd/de/vendor/cakephp/cakephp/src/Controller/Controller.php:498
/shared/httpd/de/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php:139
/shared/httpd/de/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php:114
/shared/httpd/de/vendor/cakephp/cakephp/src/Http/BaseApplication.php:332
/shared/httpd/de/vendor/cakephp/cakephp/src/Http/Runner.php:86
/shared/httpd/de/vendor/lordsimal/cakephp-sentry/src/Middleware/CakeSentryPerformanceMiddleware.php:80
/shared/httpd/de/vendor/cakephp/cakephp/src/Http/Runner.php:82
/shared/httpd/de/vendor/lordsimal/cakephp-sentry/src/Middleware/CakeSentryQueryMiddleware.php:43
/shared/httpd/de/vendor/cakephp/cakephp/src/Http/Runner.php:82
/shared/httpd/de/vendor/cakephp/cakephp/src/Http/Middleware/BodyParserMiddleware.php:162
/shared/httpd/de/vendor/cakephp/cakephp/src/Http/Runner.php:82
/shared/httpd/de/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php:118
/shared/httpd/de/vendor/cakephp/cakephp/src/Http/Runner.php:82
/shared/httpd/de/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php:69
/shared/httpd/de/vendor/cakephp/cakephp/src/Http/Runner.php:82
/shared/httpd/de/vendor/markstory/asset_compress/src/Middleware/AssetCompressMiddleware.php:64
/shared/httpd/de/vendor/cakephp/cakephp/src/Http/Runner.php:82
/shared/httpd/de/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:116
/shared/httpd/de/vendor/cakephp/cakephp/src/Http/Runner.php:82
/shared/httpd/de/vendor/cakephp/cakephp/src/Http/Runner.php:67
/shared/httpd/de/vendor/cakephp/cakephp/src/Http/Server.php:103
/shared/httpd/de/vendor/cakephp/cakephp/src/TestSuite/MiddlewareDispatcher.php:141
/shared/httpd/de/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php:499
/shared/httpd/de/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php:401
/shared/httpd/de/tests/TestCase/Controller/Admin/EventsControllerTest.php:123
```

We might have to revert this if we cannot find the issue here, as this could break applications in a non bc way?

Interesting enough the code that breaks is to find the behavior attached to a different model from the same behavior:
```php
//FileStorage\Model\Behavior\FileStorageBehavior
$tableConfig = $this->table()->behaviors()->get('FileStorage')->getConfig();
```

**Comment by dereuromark** [comment]
I debugged it and it does contain the necessary behavior on the primary table here:
```
'_loaded' => [
  (int) 0 => 'Timestamp',
  (int) 1 => 'FileStorage',
]
```
But somehow the other table ends up with
```
[
  'Timestamp' => object(Cake\ORM\Behavior\TimestampBehavior) id:0 { },
  'FileStorage.FileStorage' => object(FileStorage\Model\Behavior\FileStorageBehavior) id:3 { },
]
```
So some normalization got lost

**Comment by dereuromark** [comment]
The main issue why this isnt too easily fixable is that 

        Cache::setConfig('cache.dotted', [
            'className' => 'File',
            'path' => CACHE,
            'prefix' => 'cache_value_',
        ]);

Uses a dot syntax for keys, whereas for the rest it is only a plugin syntax.

So I cannot just fix up ObjectRegistry::load() here :/

**Comment by dereuromark** [comment]
Actually, the FileStorage behavior itself is a bit a bad boy, setting the alias as such:

    $this->table()->addBehavior('FileStorage.FileStorage', $tableConfig);
    
So maybe people have to be a bit more vigilant about how they set the alias here, in case the className is also given.

With that we can probably just make sure the release notes mention the extra strictness needed here.

In my case:
```diff
               $tableConfig = $this->table()->behaviors()->get('FileStorage')->getConfig();
+              if (empty($tableConfig['className'])) {
+                  $tableConfig['className'] = 'FileStorage.FileStorage';
+              }
               $this->table()->removeBehavior('FileStorage');
               $this->table()->saveOrFail($entity, ['checkRules' => false]);
-              $this->table()->addBehavior('FileStorage.FileStorage', $tableConfig);
+              $this->table()->addBehavior('FileStorage', $tableConfig);
```

**Pull request merged**
