### PR TITLE
Fix for invalid dates being converted by the DateTimeWidget

### LINKED ISSUE #5581: 3.0 RC1 - Invalid dates changed
If a user enters an invalid date in a date field (eg 31 Feb), it correctly fails validation with rule:
      ->add('date_of_birth', 'valid', ['rule' => 'date'])

However, when the form is displayed again with the error, it has changed it to 3 March (or 2nd if it's a leap year). The object should contain the original, invalid date.

### PR DESCRIPTION
**Pull request by dakota**
Resolves #5581 by ensuring that invalid dates are not converted on displaying the fields to the user.

### CODE REVIEW

**Comment by lorenzo** [comment]
@dakota you have a couple CS errors

**Comment by dakota** [comment]
Of course I do. Still getting used to PSR-2 :) Fixed now

**Comment by lorenzo** [comment]
Awesome!!

**Comment by markstory** [comment]
Nice work :+1:

**Pull request merged**
