### PR TITLE
Fixed bug in FormHelper::error()

### PR DESCRIPTION
**Pull request by oyas**
In FormHelper::error(), param array $text doesn't work.
Fixed it.

### CODE REVIEW

**Comment by ADmad** [comment]
Please provide test case or example code to reproduce the issue.

**Comment by thinkingmedia** [comment]
That changes switches $e with the rule identifier and not the error message.

**Comment by markstory** [comment]
What does this fix? How does someone reproduce the issue you're having?

**Comment by oyas** [comment]
I'm sorry for my little request message.

I tried to use this param array $text for setting validation error message that was not setted in model.

In CakePHP 2.x, default validation error message is rule name.
However, In CakePHP 3.x, default validation error message is 'The provided value is invalid'.

So, the output is different in spite of the same param $text.

For same output, you must:
In CakePHP2.x, use error() with $text = ['rule name' => 'new error message'].
In CakePHP3.x, use error() with $text = ['The provided value is invalid' => 'new error message'].

I suggest to fix it get same output with $text = [ 'rule name' => 'new error message' ].

Thank you.



Example code:

CakePHP 2.8:

$ cat app/Controller/TestController.php 

	<?php
	App::uses('AppController', 'Controller');

	class TestController extends AppController {
		public function a() {
			$this->Test->set($this->request->data);
			$this->Test->validates();
			debug( $this->Test->validationErrors );
		}
	}

$ cat app/Model/Test.php 

	<?php
	App::uses('Model', 'AppModel');
	
	class Test extends AppModel {
		public $validate = [
			'field1' => [
				'rule1' => [
					'rule' => 'email',
					'allowEmpty' => true,
				],
			],
		];
	}



$ cat app/View/Test/a.ctp 

	<?= $this->Form->create('Test'); ?>
	
	<?= $this->Form->input('field1'); ?>
	
	<?php $test = ['rule1' => 'new error message']; ?>
	<?= $this->Form->error('field1', $test); ?>
	
	<?= $this->Form->submit(); ?>
	<?= $this->Form->end(); ?>


result:

debug( $this->Test->validationErrors ) outputs:

	array(
		'field1' => array(
			(int) 0 => 'rule1'
		)
	)

Form::error() outputs:

	new error message


CakePHP 3.2:

$ cat src/Controller/TestController.php 

	<?php
	namespace App\Controller;
	
	use Cake\Controller\Controller;
	use Cake\ORM\TableRegistry;
	
	class TestController extends AppController {
		public function a() {
			$Entity = TableRegistry::get('Test')->newEntity($this->request->data);
			debug( $Entity->errors() );
			$this->set('Entity', $Entity);
		}
	}

$ cat src/Model/Table/TestTable.php

	<?php
	namespace App\Model\Table;
	
	use Cake\ORM\Table;
	use Cake\Validation\Validator;
	
	class TestTable extends Table {
		public function validationDefault(Validator $validator) {
			$validator
				->allowEmpty('field1')
				->add('field1', [
					'rule1' => [
						'rule' => 'email',
					]
				]);
			return $validator;
		}
	}

$ cat src/Template/Test/a.ctp 

	<?= $this->Form->create($Entity); ?>
	
	<?= $this->Form->input('field1'); ?>
	
	<?php $test = ['rule1' => 'new error message']; ?>
	<?= $this->Form->error('field1', $test); ?>
	
	<?= $this->Form->submit(); ?>
	<?= $this->Form->end(); ?>


result:

debug( $Entity->errors() ) outputs:
	
	[
		'field1' => [
			'rule1' => 'The provided value is invalid'
		]
	]

Form::error() outputs:

	The provided value is invalid

**Comment by markstory** [comment]
Thanks for providing more context @oyas. This change causes a number of [tests to fail](https://travis-ci.org/cakephp/cakephp/jobs/144235127) which indicates that is it breaking existing behavior.

**Comment by markstory** [comment]
Would it be possible to get a test for the new behavior?

**Comment by oyas** [comment]
I modified this change.
And I found that I had mistakes.
If array $text has no replace message, it replace $e(= rule key). It was fixed.

This change is compatible with allowing replacement by either the message, or the rule key.
And the order of priority to apply is:

1. 'rule key' => 'new error message'
2. 'error message' => 'new error message'
3. Otherwise, the error message is not replaced.


Example code:

$ cat src/Template/Test/a.ctp 

	<?= $this->Form->create($Entity); ?>
	
	<?= $this->Form->input('field1'); ?>
	
	<?php
		$test = [
			'rule1' => 'new error message 1',
			'The provided value is invalid' => 'new error message 2',
		];
	?>
	<?= $this->Form->error('field1', $test); ?>
	
	<?= $this->Form->submit(); ?>
	<?= $this->Form->end(); ?>


Form::error() outputs:

	new error message 1

**Comment by oyas** [comment]
More detail example:

$ cat src/Template/Test/a.ctp 

	<?= $this->Form->create($Entity); ?>
	
	<?= $this->Form->input('field1'); ?>
	
	<?php
		$test1 = [
			'rule1' => 'new error message 1',
			'The provided value is invalid' => 'new error message 2',
		];
		$test2 = [
			'The provided value is invalid' => 'new error message 2',
			'rule1' => 'new error message 1',
		];
		$test3 = [
			'The provided value is invalid' => 'new error message 2',
		];
		$test4 = [
		];
	?>
	<?= $this->Form->error('field1', $test1); ?>
	<?= $this->Form->error('field1', $test2); ?>
	<?= $this->Form->error('field1', $test3); ?>
	<?= $this->Form->error('field1', $test4); ?>
	
	<?= $this->Form->submit(); ?>
	<?= $this->Form->end(); ?>


Form::error() outputs:

	new error message 1
	new error message 1
	new error message 2
	The provided value is invalid

**Comment by markstory** [comment]
Thanks for the example code @oyas I can turn that into automated regression tests :smile:

**Comment by markstory** [comment]
Thanks @oyas

**Comment by oyas** [comment]
Thank you very much.

**Pull request merged**
