### PR TITLE
wrap findOrCreate with transactional

### LINKED ISSUE #9006: Table::findOrCreate should be done as a transaction
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: MySQL, PHP7, Windows

### Actual Behavior

The method `findOrCreate` should be transactional to ensure database state is represented correctly. Without a transaction it's possible under heavy load for this to create duplicates.

Proposed change:

```
    public function findOrCreate($search, callable $callback = null)
    {
        return $this->connection()->transactional(function() use($search, $callback) {
            $query = $this->find()->where($search);
            $row = $query->first();
            if ($row) {
                return $row;
            }
            $entity = $this->newEntity();
            $entity->set($search, ['guard' => false]);
            if ($callback) {
                $callback($entity);
            }
            return $this->save($entity) ?: $entity;
        });
    }
```

### PR DESCRIPTION
**Pull request by thinkingmedia**
closes #9006

### CODE REVIEW

**Comment by dakota** [comment]
:+1: on the idea, but there must be some way of disabling the transaction (like the atomic option for saves)

**Comment by markstory** [comment]
@dakota Are you thinking of cases where the findOrCreate() is inside an existing transaction?

**Comment by thinkingmedia** [comment]
I can't think of a case where a developer would want to execute findOrCreate without a transaction, and transactions can be nested so that shouldn't be an issue.

**Comment by thinkingmedia** [comment]
Not sure why the tests failed. Will take a look at that tomorrow.

**Comment by jippi** [comment]
one case where it could be not ideal is the fact that it would be nested transactions, or part of an outer transaction already, where a nested transaction is not wanted - e.g. the rollback is just for the inner transaction, which can lead to odd behavior if you are unaware
 
also, performance wise, doing many minor nested transactions will have a performance impact, so it should be possible to opt out :)

**Comment by lorenzo** [comment]
The transaction system is already aware of nested transactions. So it is 100% safe to always star one in this method

**Comment by jippi** [comment]
@lorenzo I know its aware of them, but its not always desired to start and stop nested transactions automatically :)

**Comment by markstory** [comment]
Builds are [failing](https://travis-ci.org/cakephp/cakephp/jobs/138992298) you'll need to get that fixed.

**Comment by lorenzo** [comment]
@jippi the beating is emulated in PHP, not in the database

**Comment by thinkingmedia** [comment]
I'll fix the tests today. I've been off sick for a while.

**Comment by lorenzo** [comment]
Thanks!

**Pull request merged**
