### PR TITLE
Enable App::build added paths for plugins

### PR DESCRIPTION
**Pull request by letstalk-nl**
Using App::build in a plugin does not add any paths when then loading files from this plugin. 
I think either it should be mentioned in the documentation that App::build cannot be used for plugins, this piece of code should be added, or App::build should be modified to accept 'PluginName.Model' keys (might be a prettier solution)

### CODE REVIEW

**Comment by davidyell** [comment]
I like the idea of this change. With such a small code change it will bring greater flexibility and also gives people with lots and lots of models an easy way to better organise their files.

**Comment by markstory** [comment]
Could we get a test case for this change?

**Comment by dereuromark** [comment]
@letstalk-nl Any update regarding this?

**Comment by letstalk-nl** [comment]
I will try to write a test case soon, haven't had much time for this yet

**Comment by markstory** [comment]
This will probably need to be reopened against 2.6 as master is now 3.x.

**Comment by markstory** [comment]
Closing as this pull request is pretty messy now, and #6507 has the same changes.

**Pull request closed without merging**
