### PR TITLE
3.next Deprecate 2.x-style-finder options

### PR DESCRIPTION
**Pull request by inoas**
Ref: https://github.com/cakephp/cakephp/issues/11148

### CODE REVIEW

**Comment by inoas** [comment]
Seems a ton of unit tests are using the old style finder options - right?
https://ci.appveyor.com/project/cakephp/cakephp/build/1.0.8421

**Comment by lorenzo** [comment]
This may affect the Table::get() function and I'm not sure that is intended

**Comment by saeideng** [comment]
I think this is not useful 
because travis says 
```
2.x-style finder options will be removed in 4.0, 
but you supplied following 2.x-style finder options: 
conditions - /home/travis/build/cakephp/cakephp/src/ORM/Table.php, line: 1181
```

`deprecationWarning` says enduser using this line ,that is not useful to member

this method should say for example 
```
2.x-style finder options will be removed in 4.0, 
but you supplied following 2.x-style finder options: 
conditions - App/src/ArticlesController.php, line: 10
``` 

so I think you should deprecated some of option in 
 https://github.com/cakephp/cakephp/blob/d4eadb8a76363cf030196586088c2e285a21570e/src/ORM/Table.php#L1176

**Comment by inoas** [comment]
> This may affect the Table::get() function and I'm not sure that is intended

- Can't we recommend `find()->first()` over `get()`?
- Which keywords of the 2.x-style options would you want to keep usable?

@saeideng I'll take a look!

**Comment by inoas** [comment]
Followup #11157

**Pull request closed without merging**
