### PR TITLE
3.next - Add Cookie->isExpired()

### PR DESCRIPTION
**Pull request by markstory**
Make it easier and less repetitive to check if a cookie is expired or not.

Refs #10406

### CODE REVIEW

**Comment by robertpustulka** [comment]
Shouldn't this method go to the interface as well?

**Comment by dereuromark** [comment]
For BC reasons this can usually only happen with the next major.

**Comment by robertpustulka** [comment]
@dereuromark new cookies implementation targets 3.5.0 which hasn't been released yet, am I correct?

**Comment by dereuromark** [comment]
If the whole class is new, then you are right :)

**Comment by robertpustulka** [comment]
@dereuromark it's been introduced here #10328 so we can still change the interface, right?

**Comment by robertpustulka** [comment]
I believe this method has to be added to the interface because of this line: [CookieCollection:106](https://github.com/cakephp/cakephp/blob/a4b663daac64dd8ba78185d234c42de4eb7b8bd2/src/Http/Cookie/CookieCollection.php#L106)

We allow `CookieInterface` to be added to the `$cookies` property. If someone added their own implementation, the `isExpired()` check would fail.

**Pull request merged**
