### PR TITLE
3.2 Better CLI API around exiting (exceptions)

### PR DESCRIPTION
**Pull request by markstory**
This is an alternate implementation of #7908 that uses exceptions instead of exit(). I want to get away from exit() longer term and using a specific exception class seems like good way to get there.

### CODE REVIEW

**Comment by markstory** [comment]
ping @dereuromark

**Comment by dereuromark** [comment]
:+1:

**Comment by markstory** [comment]
Any other input on this. If not I'll start the documentation changes.

**Comment by HavokInspiration** [comment]
I like the idea.
It will make testing way lot easier than with an ``exit()`` call.

**Comment by lorenzo** [comment]
Good job!

**Pull request merged**
