### PR TITLE
Avoiding circular object reference in SmptTransport

### PR DESCRIPTION
**Pull request by Linnk**
This fixes a memory leak while sending multiple emails.

Fixes: #9198

### CODE REVIEW

**Comment by lorenzo** [comment]
a similar fix was done in 3.x, son I'm :+1: with this

**Comment by Linnk** [comment]
Thanks @lorenzo. I will update my code to make it pass the checks from continuous integration as soon as I get to my office.

**Comment by Linnk** [comment]
Apparently, AppVeyor fails because there is no appveyor.yml in the branch. Looks like this was added for the 3.x, but might not apply for branches 2.x & 2.next. Should I leave the code as it is now?

**Comment by markstory** [comment]
Nice work!

**Pull request merged**
