### PR TITLE
Test using ubuntu 22.04 image

### PR DESCRIPTION
**Pull request by othercorey**

### CODE REVIEW

**Comment by othercorey** [comment]
@markstory can you take a look at the openssl error?

**Comment by LordSimal** [comment]
The change made by openssl seems to create more headaches then they anticipated...
https://github.com/openssl/openssl/issues/11378

**Comment by othercorey** [comment]
If this issue is in OpenSSL 1.1, then why don't we see it with ubuntu 20.04 (OpenSSL 1.1.1f-1ubuntu2.16)?

**Comment by LordSimal** [comment]
See https://www.openssl.org/news/cl111.txt
Exactly at 1.1.1f it says
```
Revert the change of EOF detection while reading in libssl to avoid
     regressions in applications depending on the current way of reporting
     the EOF. As the existing method is not fully accurate the change to
     reporting the EOF via SSL_ERROR_SSL is kept on the current development
     branch and will be present in the 3.0 release.
```

**Comment by LordSimal** [comment]
And as we see here the OpenSSL 3 Support in PHP was introduce in 8.1.7 and not backported
https://www.php.net/ChangeLog-8.php#8.1.7
https://github.com/php/php-src/issues/8369

Don't know why the Github Actions fail for 8.1.7 then 🤔

**Comment by othercorey** [comment]
Hmm. I know the RM for Fedora contacted us about OpenSSL failures so I thought the changes @markstory made would work. I wonder if this change was made after that release.

**Pull request closed without merging**
