### PR TITLE
Escape exception message content.

### PR DESCRIPTION
**Pull request by markstory**
It is possible for exception messages to have unsafe content in them.

### CODE REVIEW

**Comment by chinpei215** [comment]
Couldn't we change ExceptionRenderer? It breaks BC?

**Comment by ADmad** [comment]
@chinpei215 Escaping should be kept in templates imo.

**Comment by chinpei215** [comment]
@ADmad If in normal cases, I also think so. But several exception classes seem to have a safe guard.
```php
try {
    new SplFileObject('&');
} catch (Exception $e) {
    echo $e->getMessage();
}
```
This message would be escaped automatically if this script is executed via the web server.
And besides, `$url` would be escaped [here](https://github.com/cakephp/cakephp/blob/2224d73f86ff6a13e7bb276791a1651089d60170/src/Error/ExceptionRenderer.php#L176).

**Comment by lorenzo** [comment]
I remember removing the h() calls from the templates because it would make the exception messages unreadable in some cases. Let's see how this plays out :)

**Comment by chinpei215** [comment]
@lorenzo I found the related PR. #4526. I'll see it.

**Pull request merged**
