### PR TITLE
Allow keeping existing tab indentation for plugin load

### PR DESCRIPTION
**Pull request by dereuromark**
When working with existing files that have tab indentation set up, this would rewrite the whole file.
This fixes it.

### CODE REVIEW

**Comment by dereuromark** [comment]
I do have one failing test
```
1) Cake\Test\TestCase\Command\PluginLoadedCommandTest::testLoaded
Failed asserting that 'TestPlugin' is in output,
```
That should not be related, but is.

//EDIT: OK, I needed to clean up after the exec() call.

**Comment by LordSimal** [comment]
why go with tab indentation just for the config file?

**Comment by dereuromark** [comment]
What do you mean? All files would be the same indentation, this is the only one getting wrongly overwritten though with the plugin load command.

**Comment by LordSimal** [comment]
I'd rather stick with keeping it as is and let the user auto cs-fix it via their preferred CS tool.
Doing this would also suggest we add the same tab option to all the bake templates.

**Comment by dereuromark** [comment]
bake and other tools are plugins, this is a core internal issue.
It seems quite trivial to be indentation compliant, so either way works for me.

**Comment by ADmad** [comment]
I am with @LordSimal, just use your auto fixer tool post running the commands, there's no need to add unnecessary extra code to the commands here.

**Comment by dereuromark** [comment]
I guess having the cs sniffer re-fix it is an option.

**Pull request closed without merging**
