### PR TITLE
[Network][Http] Migration from 2.x to 3.x

### PR DESCRIPTION
**Pull request by egeloen**
Hey!

i'm currently migrating my library (egeloen/ivory-http-adapter#103) from CakePHP 2.x to 3.x, I discover some missing features and one bug.
- My first commit adds support for OPTIONS/TRACE verb. 
- The second commit allows to set an http version on the request (I have checked and the stream uses the one comming from the request, so, IMO we should be able to set it).
- The third commit fixes an issue about the stream adapter. Given you reuse the same adapter for multiple requests, the context options were not resetted and so, it results some strange behavior when for example, you firstly send a request with data and then, send an other request without data. Before this fix, the context still wrap the previous one.

### CODE REVIEW

**Comment by ADmad** [comment]
New features need to target the 3.1 branch. So you will have to split your pull request accordingly.

**Comment by dereuromark** [comment]
*Critical* missing features, that don't break BC, might actually be allowed for 3.0.
I guess some of the lead devs should answer that.
All non-critical ones better go into 3.1 for sure.

**Comment by markstory** [comment]
@ADmad I think none of these 'features' are big enough to warrant waiting until 3.1.

**Comment by ADmad** [comment]
Okay, :+1:

**Comment by egeloen** [comment]
So, should I split my PRs or is it Ok as it is? Additionally, is there something to rework?

**Comment by ADmad** [comment]
@egeloen No need to split, it's fine.

**Comment by ADmad** [comment]
Please add tests for the new methods.

**Comment by lorenzo** [comment]
Thanks @egeloen !

**Comment by egeloen** [comment]
You're welcome! Btw, can someone merge the master branch into the 3.1 one? It would be really appreciated in order to make my related PR green :)

**Comment by markstory** [comment]
@egeloen Done :smile:

**Comment by egeloen** [comment]
Thank you!

**Pull request merged**
