### PR TITLE
Added some missing annotations

### PR DESCRIPTION
**Pull request by Theaxiom**
This is me splitting up a larger PR, please see #10532 for details.

### CODE REVIEW

**Comment by lorenzo** [comment]
Thanks for this, but without an explanation of why the exceptions are thrown I find the annotations to just add noise, especially because unlike java, PHP does not have checked exceptions so there is little value in annotating the methods without an explanation of what could happen.

**Comment by dereuromark** [comment]
I also prefer Automation via sniffer if we add this to more than the actual throwing method. Or it can become Out of sync and even lying once the method loses the throw.

**Comment by inoas** [comment]
I am with lorenzo. I think the exception annotations are good but only really useful when they have a textual explanation alongside.

**Comment by Theaxiom** [comment]
All of these annotations were confirmed via automation and static code analysis. If you use this plug-in, it can help to ensure annotation integrity:

- https://plugins.jetbrains.com/plugin/7622-php-inspections-ea-extended-
- https://github.com/kalessil/phpinspectionsea

That being said, I understand your reasoning about having the annotations explained. I simply prefer it for IDE auto-completion. Feel free to close this PR.

**Comment by ADmad** [comment]
I too am not thrilled about this additional annotations for exceptions. We should stick to listing only those that are directly throw by a method.

**Comment by Theaxiom** [comment]
@ADmad ok I will remove them

**Comment by dereuromark** [comment]
I have a sniffer we can use to assert exactly that. See Spryker ones, feel free to implemenent for cakephp for future consistency.

**Pull request closed without merging**
