### PR TITLE
Always store touched entity field value in _original.

### PR DESCRIPTION
**Pull request by dereuromark**
I want to see if the tests all pass, and if this could be done.
The changes seem to be a requirement for logic like https://github.com/dereuromark/cakephp-shim/pull/107 to work it seems.
Maybe there is also a different way, just proposing to take a look at this.

It sure would add a bit more memory consumption to the duplicating of touched field values with the same value being rewritten.

### CODE REVIEW

**Comment by LordSimal** [comment]
Initially this was introduced in https://github.com/cakephp/cakephp/pull/4809 for reference

**Comment by markstory** [comment]
Changing this behavior would also result in more fields being updated when records are persisted. I don't know if that will matter much but it is a behavior difference.

**Comment by dereuromark** [comment]
> Changing this behavior would also result in more fields being updated when records are persisted

Does it need to be?
We could filter out the truly modified fields prior to this, similar to the code shown in the linked plugin code to demonstrate actual field changes.

**Comment by fabian-mcfly** [comment]
The new behavior would work like that:

```php
$entity = new Entity([]); // > $_original = [];
$entity->set('foo', 'bar'); // > $_original = [];
$entity->set('foo', 'baz'); // > $_original = ['foo' => 'bar'];
```

Like I said on discord, this is still not correct, arguably maybe even worse than before.

Changing the if to only 
```php
if (!array_key_exists($name, $this->_original)) {
    $this->_original[$name] = $this->_fields[$name] ?? null;
}
```
would result in 

```php
$entity = new Entity([]); // > $_original = [];
$entity->set('foo', 'bar'); // > $_original = ['foo' => null];
$entity->set('foo', 'baz'); // > $_original = ['foo' => null];
```

And while both versions do not reflect the real initial value (`foo` not being set), a null value could be used as a hint to not take the value for granted, while very other value gives no such clue.

**Comment by fabian-mcfly** [comment]
I made "some" changes myself (currently without a PR since I don't wanna make a mess here):
https://github.com/fabian-mcfly/cakephp/commit/e77249604066d0ed90f878331915de8376b8166b

This maintains full BC*, while making it a bit more clear what "original" means. These points are my interprations of "original". Feel free to correct me:
- fields which are present when instantiating an entity class
- all fields that are present when `clean()` gets called, creating a new "original"-state
- all fields that are present when an entity was successfully saved (the same as calling `clean()` manually)
- fields that were manually marked as clean (`setDirty('field', false)`)

*The BC exception being that it breaks when one implemented `EntityInterface` without using `EntityTrait`, since additional method signatures were introduced (and one changed). And `getOriginal()` returns no original values for entities created with an empty array as argument (`newEntity([])`/`newEmptyEntity()`).

An additional second argument for `getOriginal()` allows to bypass the fallback to the current value, resulting in an InvalidArgumentException when called on a non-original field.

I also added additional methods to check whether a field is original, retreive the current original fields (without a value), as well as setting the field names manually.

And last but not least: I added tests and slightly modified two existing.

I would really love seeing this being used in the future, yet I am still open to feedback.

At https://github.com/fabian-mcfly/cakephp/commit/e77249604066d0ed90f878331915de8376b8166b#commitcomment-123067800 I show the result of those new changes.

**Comment by dereuromark** [comment]
Maybe you open an alternative PR for your case so we can discuss in more concrete detail based on your changes.

**Comment by dereuromark** [comment]
Closing in favor of https://github.com/cakephp/cakephp/pull/17208 then

**Pull request closed without merging**
