### PR TITLE
Add orderBy() and groupBy() to match sql

### PR DESCRIPTION
**Pull request by othercorey**
Now that Query doesn't proxy Collection, we can add orderBy() and groupBy() that match the sql statements like other functions.

### CODE REVIEW

**Comment by ADmad** [comment]
Should be mark the old methods as deprecated then? Keeping 2 methods for each operation seems unnecessary.

**Comment by othercorey** [comment]
I was thinking soft deprecation for 5.0 would make this less noisy.

**Comment by ADmad** [comment]
Yup soft deprecation sounds good.

**Review by markstory — COMMENTED** [review]
Looks good to me. We should have some tests for the new method signatures as well.

**Comment by othercorey** [comment]
> Looks good to me. We should have some tests for the new method signatures as well.

Now that we're deprecating, I'll switch all use over to the new functions and add a call the old function.

~Currently, I'm just doing a pass-through to the new functions.~

Converted all order() and group() calls and added a test for deprecated functions.

**Pull request merged**
