### PR TITLE
Add FailedRouteCacheException and throw when route caching fails

### PR DESCRIPTION
**Pull request by othercorey**
Refs https://github.com/cakephp/cakephp/issues/15484 https://github.com/cakephp/cakephp/issues/12129

### CODE REVIEW

**Comment by ADmad** [comment]
Mitigating problems created by a broken feature :unamused:

**Comment by othercorey** [comment]
> Mitigating problems created by a broken feature 😒

If you're saying route caching is broken, then I'd agree.

**Comment by steinkel** [comment]
Thank you for the fix @othercorey

I'd like to help here, as I initially introduced this feature to mitigate the slow routing initialization, specially when the routes depend on the database.
https://github.com/cakephp/cakephp/pull/11765#issuecomment-371139620

I've used it a couple times already since then...

I see other routing libs are having similar issues with serialization https://github.com/nikic/FastRoute/issues/141
I'll play a bit with the serialization issues to provide a better support by the router cache.

Or do you think it would be better to deprecate and move this feature into a plugin outside of the core?

**Comment by othercorey** [comment]
> Or do you think it would be better to deprecate and move this feature into a plugin outside of the core?

I asked about doing this since we don't have explicit support or checks for support with all routing features. 

All I did was add a bandage.  I think it needs a revisit to keep it.

**Comment by steinkel** [comment]
The approach I'm going to try is only storing the serializable routes into the cache and fallback to the non-cached route behavior if the cache missed. I'll play with it in the following days and get back to you. Thanks,

**Comment by steinkel** [comment]
So, updating progress here, I've tried breaking the route collection in 2 groups or routes, serializable and non serializable ones but I did not get to a workable solution and the amount of changes would not justify in my opinion the benefits, specially if you are not using routing cache at all...

Using external libraries for serialization as suggested https://github.com/nikic/FastRoute/issues/141 like opis/closure is not really an option as it won't provide a stable feature as they suggest here > https://github.com/opis/closure#arbitrary-object-serialization

I think the remaining options are:

* Deprecating this feature and moving it to a plugin providing a `CachedRoutingMiddleware` you can easily switch in your Application::middleware method. I can handle the deprecation warning in another pull request and create a plugin for 4.x and up.
* Do nothing, leaving the feature in the core as useful for the use cases with many routes & no serialization issues.

What do you think?

**Comment by othercorey** [comment]
@markstory objections to deprecating route caching?

**Comment by markstory** [comment]
Sounds good to me. It hasn't worked out well over time.

**Comment by ADmad** [comment]
+1 for deprecating routes caching.

**Comment by steinkel** [comment]
middleware extracted here > https://github.com/CakeDC/cakephp-cached-routing I'll be working on the deprecation changes next week and post them in the context of a new PR.

**Pull request merged**
