### PR TITLE
Add Validator proxies for money() and multiple()

### PR DESCRIPTION
**Pull request by markstory**
Add missing proxy methods.

Refs #8495

### CODE REVIEW

**Comment by ADmad** [comment]
These are the two I noticed,  can you please check if there aren't anymore missed out.

**Comment by markstory** [comment]
@ADmad There are missing proxies for deprecated methods and the following methods:

* comparison - I don't think this is necessary, given we have the various operators implemented.
* custom - Again not necessary
* extension - This could be useful, but uploadedFile() does have a proxy.
* luhn - But it has been rolled into the `creditCard` proxy.
* mimeType - Could be useful, but uploadedFile() does have a proxy.
* fileSize - Could be useful, but uploadedFile() does have a proxy.
* uploadError - Could be useful, but uploadedFile() does have a proxy.
* geoCoordinate - exists as latLong

I'm not sure there are any must-haves there.

**Comment by lorenzo** [comment]
I left those out because I found them confusing or redundant. I still think `multiple()` is a confusing name since it reads like it will validate multiple fields, like a nested validator.

**Comment by lorenzo** [comment]
I also left `money()` out because the implementation is not compatible with the intl support we have in the project. So it will only cause confusion. We would need instead to offer a new implementation using the `Number::parse()` function

**Comment by markstory** [comment]
@lorenzo Those are good reason to not include the proxies as it stands. We could give 'multiple' a better name. Perhaps 'multipleOptions' or 'multipleSelect'?

**Comment by lorenzo** [comment]
I like `multipleOptions`

**Comment by markstory** [comment]
@lorenzo I renamed the method.

**Comment by lorenzo** [comment]
@markstory should we wait until we have a new implementation for `money()`?

**Comment by markstory** [comment]
@lorenzo That's reasonable. I'll remove the current proxy until we have a better solution.

**Pull request merged**
