### PR TITLE
Changes to remove features deprecated in PHPUnit 11

### PR DESCRIPTION
**Pull request by othercorey**
- [x] Convert test annotations to attributes
- [x] Replaced removed Constraint::exporter()
- [ ] Clean up added error handlers in tests
- [x] Fix mock error

### CODE REVIEW

**Comment by othercorey** [comment]
Need some help with the last 2 issues.

**Comment by ADmad** [comment]
I took care of the error in `Cake\Test\TestCase\ORM\Query\SelectQueryTest::testHydrateBelongsToCustomEntity`.

**Comment by othercorey** [comment]
Updated deprecation warning for `addMethods()` and wrapped test in deprecated() to suppress the warning.

PHPUnit will still print a list of internal deprecations at the end.

**Review by markstory — APPROVED** [review]
Nice work :clap: :clap:

**Pull request merged**
