### PR TITLE
Remove use of TestCase::getMock() from tests.

### PR DESCRIPTION
**Pull request by ADmad**
Everyone is welcome to contribute to this one namespace at a time :)

Namespaces taken care of:
- [x] Auth
- [x] Cache
- [x] Collection
- [x] Console
- [x] Controller
- [x] Core
- [x] Database
- [x] Datasource
- [x] Error
- [x] Event
- [x] Filesystem
- [x] Form
- [x] I18n
- [x] Log
- [x] Mailer
- [x] Network
- [ ] ORM
- [x] Routing
- [x] Shell
- [ ] TestSuite
- [x] Utility
- [x] Validation
- [x] View 
- [x] All usages with single argument.

### CODE REVIEW

**Comment by ADmad** [comment]
Only 1751 deprecated notices to go :)

**Comment by ADmad** [comment]
@Marlinc You earned yourself 2 namepaces to fix :stuck_out_tongue:

**Comment by lorenzo** [comment]
Great job!

**Comment by markstory** [comment]
:clap:

**Pull request merged**
