### PR TITLE
Show PHP version in shell welcome message

### PR DESCRIPTION
**Pull request by rchavik**

### CODE REVIEW

**Comment by antograssiot** [comment]
:+1: 

maybe even a
```php
        if(version_compare(phpversion(),'5.4.16', '<')) {
            $this->out('<error>Your PHP version is not high enougth</error>');
            $this->_stop();
        }
```
to prevent errors to be thrown

**Comment by ceeram** [comment]
:+1: on having some php version check/info in welcome

2015-03-24 11:17 GMT+01:00 Anto <notifications@github.com>:

**Comment by rchavik** [comment]
@antograssiot @ceeram 

I realized that this won't be useful if PHP <= 5.3 as it will die very early.  However, it might prove useful info later.

If we do want to warn CLI users, the warning needs to be in the app repo's `bin/cake.php`.

**Comment by jadb** [comment]
There is no need for a php version check IMO - composer already does that. Can't have cake installed if it doesn't meet min. requirements.

**Comment by markstory** [comment]
Looks good to me :+1:

**Pull request merged**
