### PR TITLE
Bump Carbon version

### PR DESCRIPTION
**Pull request by bcrowe**

### CODE REVIEW

**Comment by GuidoHendriks** [comment]
`Cake\I18n\Time::diffForHumans()` seems to be incompatible with Carbon 1.20:

    Declaration of Cake\I18n\Time::diffForHumans() should be compatible with Carbon\Carbon::diffForHumans(Carbon\Carbon $other = NULL, $absolute = false) [CORE/src/I18n/Time.php, line 27]

**Comment by lorenzo** [comment]
Reverting, see https://github.com/cakephp/cakephp/issues/6509

**Comment by dereuromark** [comment]
So we bump it for 3.1?

**Comment by lorenzo** [comment]
@dereuromark we need a replacement for it that does not intruduce more libs that we want to support

**Comment by dereuromark** [comment]
Right.

**Pull request merged**
