### PR TITLE
RFC - Enable Behaviors to participate in marshalling

### PR DESCRIPTION
**Pull request by markstory**
This is a rough sketch of what it could look like for behaviors to be able to participate in marshalling by providing a map of the fields they can marshal. Each behavior could implement an interface opt-ing it into the marshalling process. The behavior would then return an updated map of fields -> marshalling functions.

Each marshalling function is expected to convert the request value into a hydrated object. The unified interface lets database types, associations, and behaviors work the same way.
### TODO
- [x] Complete tests.
- [x] Add interface mentioned in comments.
- [x] Complete documentation.
- [x] Fix merge conflicts.

These changes are based on those started by @albertcansado in #9130. Given how close 3.3.0 is, and how large of a change this is, I would recommend this go into 3.4.0

### CODE REVIEW

**Comment by markstory** [comment]
I've added the interface now. I'm not in love with the name `MarshalParticipantInterface` and would love better alternatives.

**Comment by lorenzo** [comment]
PropertyMarshalInterface?

**Comment by markstory** [comment]
@lorenzo That works for me.

**Comment by markstory** [comment]
I think I'm done with this. Tests have been added/completed.

**Comment by lorenzo** [comment]
Looks good to me. I'm a bit concerned about building 2 closures per association per entity marshalled, but I guess we can tackle that later.

**Comment by markstory** [comment]
@lorenzo You mean the part that builds the closures and then tosses one of them away? I could build them inside an `if` saving the extra allocation.

**Comment by lorenzo** [comment]
@markstory that would be good

**Comment by markstory** [comment]
@lorenzo Updated now.

**Comment by lorenzo** [comment]
Great job!

**Comment by markstory** [comment]
I'll update the 3.3 docs tonight.

**Pull request merged**
