### PR TITLE
Remove unnecessary quotes and \r\n in FormData format

### PR DESCRIPTION
**Pull request by littleylv**
Refs #13673

### CODE REVIEW

**Comment by littleylv** [comment]
OMG. Sorry for the second commit. I am attending to open a new PR for #13676 . I should have create a new branch for it.
What should I do now?

**Comment by saeideng** [comment]
> What should I do now?

for this PR you changed the your `master` branch ( you could )
but you can create any number new branch that you need
1 for this PR , another for mentioned PR 
and better to keep `master` as is was in your local 
this helps you to sync and fetch new commits and keeping original branch sync with original repo on github ( search for `git  upsteam concept  ` for more info )

**Comment by littleylv** [comment]
@saeideng Thanks a lot! I have reset my `master` branch and keep this pr clean without other commit.
Then I have created a new branch and maked another pr.

**Comment by markstory** [comment]
Thank you 👍

**Pull request merged**
