### PR TITLE
cake 5: Move Filesystem to Utility

### PR DESCRIPTION
**Pull request by othercorey**
This follows the removal of File and Folder classes.

### CODE REVIEW

**Comment by dereuromark** [comment]
The alternative would be to just not split this file into its own repo anymore.

**Comment by ADmad** [comment]
> The alternative would be to just not split this file into its own repo anymore.

That's what's done here. The `cakephp/filesystem` repo is killed.

**Comment by dereuromark** [comment]
Sure, I meant that the need to move the file is then not given anymore
`Cake\Filesystem\Filesystem` could remain if we wanted to.

**Comment by othercorey** [comment]
The `console` package does depend on it at least.

**Pull request merged**
