### PR TITLE
Pass headers from RedirectException to RedirectResponse

### PR DESCRIPTION
**Pull request by andrii-pukhalevych**
Pass headers from RedirectException to RedirectResponse if present

### CODE REVIEW

**Review by markstory — COMMENTED** [review]
The change looks good. It would be good to have a test covering this behavior though so we don't regress it in the future. Would you be able to add a test or do you need a hand?

**Comment by andrii-pukhalevych** [comment]
Yes, will do today

**Comment by andrii-pukhalevych** [comment]
I can't find a way to create test. Inside try block, there are only calls of `Router::setRequest()` and `Router::parseRequest()`

But redirect routes does not support adding headers yet, so no good way to create test.

**Comment by markstory** [comment]
> But redirect routes does not support adding headers yet, so no good way to create test.

We would need an integration style test here. You could have a controller raise a RedirectException with headers and ensure that those headers are in the final response.

**Comment by andrii-pukhalevych** [comment]
> You could have a controller raise a RedirectException.

The subject of this PR is change of `catch` block inside `RoutingMiddleware::process()`.
But in corresponding `try` block controller is not involved:
https://github.com/cakephp/cakephp/blob/960e8464d37c786f793b979baede76828af03849/src/Routing/Middleware/RoutingMiddleware.php#L156-L173

Only `Router::parseRequest()` can be used to raise a `RedirectException`. 
Should I create new route class `HeadersRedirectRoute` in test app?

Or rebase this PR to 4.next / 5.X and add new option 'headers' for `RedirectRoute`?

**Comment by markstory** [comment]
> Only Router::parseRequest() can be used to raise a RedirectException.

Couldn't we use a RedirectRoute then?

**Comment by andrii-pukhalevych** [comment]
RedirectRoute does not support headers option.

I see 2 ways to create test:
- create new route class `HeadersRedirectRoute` in test app.
- or rebase this PR to 4.next / 5.X and add new option 'headers' for core `RedirectRoute`.

**Comment by markstory** [comment]
> RedirectRoute does not support headers option.

Right, I forgot about that. So if there are no ways to get the framework to create this state, or application code (like in a controller) why does this scenario need to be handled?

**Comment by markstory** [comment]
@andrii-pukhalevych I've pushed a test to your branch. Is that the kind of usage your application has? Or what is different about the scenario I've setup?

**Comment by andrii-pukhalevych** [comment]
@markstory yes, its exactly my case 👍

**Pull request merged**
