### PR TITLE
3.0 - Fix table callback argument types

### PR DESCRIPTION
**Pull request by ndm2**

### CODE REVIEW

**Comment by markstory** [comment]
Why are the types changing? Is it to make this consistent with other callbacks?

**Comment by ndm2** [comment]
Kind of, the docblock already said that in `beforeFind` `$options` would be an `ArrayObject`, which is consistent with the other callbacks, it just wasn't true in code.

And for the `afterRules` callback the arguments were documented [in the `save` docblock](https://github.com/ndm2/cakephp/blob/3.0-fix-table-callback-argument-types/src/ORM/Table.php#L1215) just like they appear in code, and since the rules checker isn't really useful after it has already done its work, I assumed that this is what the signature should actually look like.

**Comment by markstory** [comment]
Looks good to me. Some of the tests are missing asseetions, but I guess the typehints kind of count. It would be even better to ensure that all the callbacks are actually invoked as well. Some could be skipped right now and the tests would continue to pass.

**Comment by ndm2** [comment]
Yep, I was intentionally relying on the typehint throwing an error on mismatch. I guess I could add further logic to make sure the callbacks are really being invoked, I was a little lazy and thought I could just rely on the code doing what I would expect it to do as its rather simple and already covered by other tests that would fail in case something's wrong.

**Comment by lorenzo** [comment]
What is the benefit of changing the argument to ArrayObject?

**Comment by markstory** [comment]
Travis ci tests are failing.

@lorenzo I think the only benefit is consistency with other events.

**Comment by ndm2** [comment]
@lorenzo, just like @markstory said, it's pretty much only consitency. To be honest, I never really understood why the events are using array objects anways, but whatever they use I think should be consistent. That being said, I just noticed that I forget the `beforeFind` event triggered by associations.

**Comment by lorenzo** [comment]
They are using ArrayObject because it lets you modify the data inside for the other listeners and for the main action as well.

**Comment by ndm2** [comment]
Ah, of course, that would be another reason for using an ArrayObject in beforeFind too then I guess :)

**Comment by markstory** [comment]
Other than consistency, changing from array to ArrayObject doesn't _add_ anything and only makes things a tiny bit slower as we have to create more objects.

**Comment by ndm2** [comment]
@markstory Well, it adds the ability for the listeners to pass on modifications? If that is considered useful for the other listeners, isn't it useful for `beforeFind` too?

**Comment by dereuromark** [comment]
Labeling as defect as people start to experience issues with this. See http://irc.cakephp.org/logs/link/3490618#message3490628 for example.

**Comment by hmic** [comment]
Got trapped too, please fix!

Eighter the docblock OR the implementation. Like now it is really stupid as you implement as documented and get errors thrown all over the place.

**Comment by markstory** [comment]
Fixing the docblock is obviously the simpler and lighter of the two approaches. I'm not sure using an ArrayObject is entirely a good idea yet.

**Comment by dereuromark** [comment]
I am for consistency. Especially with so many (different) events these days. And I bet most would also appreciate that over a tiny advantage in speed.

**Comment by markstory** [comment]
Rebased and merged in 73ad7253be1e6c983c729101b1c938c78798dd27. I agree that right now consistency is more useful than the micro optimization on creating an extra ArrayObject instance.

**Pull request closed without merging**
