### PR TITLE
Use constants instead of strings.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Review by dereuromark — APPROVED** [review]
Nice one

**Comment by dereuromark** [comment]
Whats with those new scrut failures?

> src/View/SerializedView.php#L1
An error occurred during processing; checking has been aborted. The error message was: Undefined property: PHPStan\PhpDocParser\Ast\Type\ArrayShapeNode::$name in /home/scrutinizer/build/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationTypeHelper.php on line 167

**Comment by markstory** [comment]
Looks like slevomat is using parts of PHPStan that no longer exist.

**Comment by dereuromark** [comment]
Ah ;) https://github.com/slevomat/coding-standard/issues/709

**Pull request merged**
