### PR TITLE
Optimize Hash::extract() for simple cases.

### PR DESCRIPTION
**Pull request by markstory**
When extracting simple dot paths from arrays use a more efficient approach.

ping @ADmad @jrbasso 

Refs #7541

### CODE REVIEW

**Comment by jrbasso** [comment]
There is one test failing, I will look into it.

**Comment by jrbasso** [comment]
Checking that, I believe we can't apply this patch anymore. It doesn't consider some edge cases and would be would require extra checks, which probably would kill the performance gains.

The failing test is because the `$data` is an array, but the values inside the array aren't. Which makes array_column not to extract the right data.

Another edge case is `array_column` extracts all the values, independently the key. Since we have things like `{n}`, we would have to check all the array keys to filter it. Ie of the edge case:
```php
        $data = [
            0 => [
                'id' => 4,
                'name' => 'Neo'
            ],
            1 => [
                'id' => 5,
                'name' => 'Morpheus'
            ],
            'stringKey' => [
                'name' => 'Fail'
            ]
        ];
        $result = Hash::extract($data, '{n}.name');
        $expected = ['Neo', 'Morpheus'];
        $this->assertEquals($expected, $result);
```
Using `array_column` the `Fail` is also returned.

Unless someone has any idea on how to by pass it, I don't think it is viable.

**Comment by markstory** [comment]
@jrbasso We'll have to go with the code as it is then :smile:

**Comment by ADmad** [comment]
@jrbasso Sorry that the optimizations are gone, I must have tried to keep them when I made the fix. It was just too long ago to remember :)

**Comment by jrbasso** [comment]
@ADmad not a problem at all. At the end, it had some gaps for mixed integer/string indexes.

**Pull request closed without merging**
