### PR TITLE
Add new ChainedEngine for Cache to manage fallback config (927 - DebugKit)

### PR DESCRIPTION
**Pull request by ajibarra**
@ADmad @markstory I have implemented the ChainedEngine to manage the fallback config. In the future we could think about allowing multiple configs instead of main/fallback configs only. 

Please let me know if the approach is correct so I will fix/implement any required tests.

Thank you

### CODE REVIEW

**Review by markstory — COMMENTED** [review]
I like the approach. It creates the opportunity for application code to nest fallbacks as they need :clap:

**Comment by ADmad** [comment]
- If we are going to decorate every engine with `ChainedEngine` perhaps we could have this feature in the base class itself?
- This wrapping will likely cause test cases to break for everyone checking for specific class name as it does for our tests.
- As I commented [here](https://github.com/cakephp/debug_kit/issues/927#issuecomment-1536612496) the original issue with debug kit might be solvable in an easier way.

**Comment by markstory** [comment]
Good point about changing the classname and potentially method set of every engine. We can't do that as it will break custom engines that users have built. ADmad's suggestion of having the chaining on the base class would help solve that issue.

**Comment by ADmad** [comment]
The primary issue which promoted this change has been addressed in https://github.com/cakephp/debug_kit/pull/938. Perhaps we can revisit chained engines at a later date.

**Pull request closed without merging**
