### PR TITLE
3.x ExceptionRenderer should always report filename & line (if debug=true) (PHP 7)

### PR DESCRIPTION
**Pull request by inoas**
Pass through file name and line number from `PHP7ErrorException` up to `ExceptionRenderer`

Replacement PR for https://github.com/cakephp/cakephp/pull/10399

### CODE REVIEW

**Comment by thinkingmedia** [comment]
You shouldn't have to check if debug is true. The exception render doesn't output the error when debug is disabled.

**Comment by lorenzo** [comment]
This looks good to me. Where there any tests to change after this?

**Comment by thinkingmedia** [comment]
Oh I get it now. The original exception is bring wrapped. This looks good to me too. Nice fine.

**Comment by inoas** [comment]
@thinkingmedia wrote:
> You shouldn't have to check if debug is true. The exception render doesn't output the error when debug is disabled.

Assumed the same. Empirically not true.
`$viewVars` would get the line and file serialized and json requests would render those even if debug was set to false.

**Comment by inoas** [comment]
@lorenzo there were, right now it should be okay.
Good to merge?

**Comment by thinkingmedia** [comment]
Looks good to me.

**Comment by lorenzo** [comment]
Thanks @ionas!

**Pull request merged**
