### PR TITLE
Auth setuser

### PR DESCRIPTION
**Pull request by ADmad**
Refs #6628.

Will look into creating storage interface/class later on.

### CODE REVIEW

**Comment by ADmad** [comment]
How does this look https://github.com/cakephp/cakephp/compare/cakephp:3.1...ADmad:auth-storage

Adding extra param to AuthComponent::setUser() isn't needed. For stateless operation can configure it to use `NullStore` storage instead of `SessionStorage`.

**Comment by AD7six** [comment]
@ADmad in principle that's exactly what I had in mind (would also avoid the bit-eww boolean argument)

**Comment by markstory** [comment]
These changes look good so far :+1:

**Comment by markstory** [comment]
@ADmad Shouldn't the NullStorage actually be a MemoryStorage? Don't you just want to avoid a persistent storage of the user data?

**Comment by ADmad** [comment]
@markstory It should be. Will change it and add docblocks and tests to get it ready for PR.

**Comment by ADmad** [comment]
Super seeded by #6664

**Pull request closed without merging**
