### PR TITLE
Console Commands: Add default value for arguments

### PR DESCRIPTION
**Pull request by alphp**
Notice: Creation of dynamic property Cake\Console\ConsoleInputArgument::$_default is deprecated

### CODE REVIEW

**Comment by ADmad** [comment]
How did you get this error? The class doesn't have any use of `$_default` property.

**Comment by dereuromark** [comment]
I remember seeing this before, mainly when creating it using an array
Maybe we should check on property defined before doing

    $this->{'_' . $key} = ...

?
And throw an exception instead?
Or just check against a manual whitelist of sorts?

**Comment by alphp** [comment]
> How did you get this error? The class doesn't have any use of `$_default` property.

```php
    public function buildOptionParser (ConsoleOptionParser $parser): ConsoleOptionParser {
	$parser = parent::buildOptionParser($parser);
	$parser->addArgument('date', [
		'help' => __('Date to query'),
		'default' => 'yesterday',
		'required' => false,
	]);

	return $parser;
    }
```

**Comment by alphp** [comment]
The idea of the default parameter is the following:
Calling the command without the argument is the same as calling the command with the argument with the value specified as "default".

Example:
```php
    public function buildOptionParser (ConsoleOptionParser $parser): ConsoleOptionParser {
	$parser = parent::buildOptionParser($parser);
	$parser->addArgument('date', [
		'help' => __('Date to query'),
		'default' => 'yesterday',
		'required' => false,
	]);

	return $parser;
    }
```
Getting the argument:
```php
    $date = $args->getArgument('date');
```
Instead of:
```php
    $date = $args->getArgument('date')  ?: 'yesterday';
```
Obviously this functionality does not exist yet.

**Comment by ADmad** [comment]
> Obviously this functionality does not exist yet.

Well making changes for non-existent functionality doesn't make sense :)

**Comment by dereuromark** [comment]
@alphp you can make a PR in 5.x to add functionality .
If merged, it can be backported afterwards.

**Comment by alphp** [comment]
> @alphp you can make a PR in 5.x to add functionality . If merged, it can be backported afterwards.

Done #17643

**Comment by dereuromark** [comment]
I recommend closing this for now, until https://github.com/cakephp/cakephp/pull/17643 is merged.
As this will have to be redone for 4.next, if we put your PR into 5.next.

Then you don't have to keep this PR in sync, and save some resources.

**Pull request merged**
