### PR TITLE
Clean up the expected input scope.

### PR DESCRIPTION
**Pull request by dereuromark**
I might have been misunderstood in terms of how to resolve this in the cleanest way without the need to suppress stan checks.
=> https://github.com/cakephp/cakephp/pull/13154 addon

### CODE REVIEW

**Comment by dereuromark** [comment]
If stan does not like this, we can also first assign and then, and then use $name to check.

**Comment by ADmad** [comment]
The root cause of the problem is `View::$layout` is used to hold the layout file name and well as control whether layout should be rendered. Ideally there should be a separate property/method to control layout rendering.

**Comment by ADmad** [comment]
If a minor BC break is acceptable we can just disallow setting layout to false. One can instead just use `ViewBuilder::disableAutoLayout()` / `View::disableAutoLayout()` to turn off layout rendering.

**Comment by dereuromark** [comment]
I agree on the ideal case. But until then now, and cleanup can be done I think this is the best way forward without hiding issues. Especially since they can only occur if you really coded/extended it in a bad and unexpected way.

**Review by ADmad — APPROVED** [review]

**Pull request merged**
