### PR TITLE
remove extract function in the Validation::comparison

### PR DESCRIPTION
**Pull request by ichikaway**
It should remove extract() in the Validation::comparison().

### CODE REVIEW

**Comment by jippi** [comment]
why?

**Comment by markstory** [comment]
@jippi It allows naughty users to manipulate what should be a scalar into an array, and bypass validation.

**Comment by ichikaway** [comment]
same reason as this commit.
https://github.com/cakephp/cakephp/commit/18544c5aaaab92e6e5aa1801b77ebb0611bd9b86

**Comment by chinpei215** [comment]
@markstory No. `if ((float)$check1 != $check1))` can protect us.

**Comment by markstory** [comment]
Good point @chinpei215.

**Comment by chinpei215** [comment]
@markstory But might it be overwrite other arguments? Why did us overlook this at that time..?

**Comment by ADmad** [comment]
There's  a CS error.

**Comment by ichikaway** [comment]
I fixed the CS error.

**Comment by chinpei215** [comment]
Looks good to me.

**Comment by markstory** [comment]
@chinpei215 It was a large diff. This was probably lost in the sea of other changes. While this is a break in compatibility, I feel that potential security issues are worth the pain. I also suspect very few if any people actually use these call styles.

**Comment by chinpei215** [comment]
@markstory Come to think of it, I did check where was changed, but I didn't check where wasn't changed. Even though I knew all where we should fix :pensive:

**Comment by lorenzo** [comment]
I'm with @markstory. It is more important to get rid of the security issue, more than keeping compatibility with an undocumented feature

**Comment by ichikaway** [comment]
Thank you for merging :)

**Pull request merged**
