### PR TITLE
add `direction:ltr` - Debugger::printVar()/debug()

### PR DESCRIPTION
**Pull request by saeideng**

### CODE REVIEW

**Comment by dereuromark** [comment]
Does it have to be noisy inline css?
Can't it just be in the CSS file - for class cake-debug-output?

**Comment by saeideng** [comment]
do you want to add `cake-debug-output` class into product css ?

**Comment by dereuromark** [comment]
That class is added by default.
As such, you should modify cakephp/app to have this in the default template.
For those few that need it. All others (9x%) don't need this inline css or any other such fix.

**Comment by saeideng** [comment]
we can remove `cake-debug-output` class at cake 4 :)

**Comment by dereuromark** [comment]
No why should we?

**Comment by saeideng** [comment]
probably we able to add this class in footer like the adding debug_kit 
```php
<style>
  .cake-debug-output{
    direction:ltr;
   }
<style>
</body>
```

**Comment by dereuromark** [comment]
Why not just using basic css stylesheets?

**Comment by ADmad** [comment]
Inline css for debugging code is just fine. I wouldn't want to include a css file just for debugging.

**Comment by ADmad** [comment]
> Does it have to be noisy inline css?

Debug out itself is noisy.

**Comment by dereuromark** [comment]
I can see the point for dd() usage.

**Pull request merged**
