### PR TITLE
Updated phpunit.xml.dist default mysql DB_DSN

### PR DESCRIPTION
**Pull request by othercorey**
Updated phpunit.xml.dist default mysql DB_DSN to disable ONLY_FUL_GROUP_BY for local tests

Updated the readme test steps to be more specific about what setting up local db for tests.

### CODE REVIEW

**Comment by dereuromark** [comment]
Why updating the default?
Shouldnt we instead make an example in docs somewhere to explain how to do that?

**Comment by othercorey** [comment]
> Why updating the default?
> Shouldnt we instead make an example in docs somewhere to explain how to do that?

Because it's required? Following the readme steps didn't work.

**Comment by ADmad** [comment]
Ideally the relevant tests should be be updated so that disabling `ONLY_FULL_GROUP_BY` is not required.

**Comment by othercorey** [comment]
> Ideally the relevant tests should be be updated so that disabling `ONLY_FULL_GROUP_BY` is not required.

This is just doing what you do in the travis and github unit tests.  I'll cancel it though.

**Comment by ADmad** [comment]
>  This is just doing what you do in the travis and github unit tests

I know, but disabling it on travis and GH was just me being lazy :P

**Pull request closed without merging**
