### PR TITLE
Fix type error in help generation

### LINKED ISSUE #13128: Cake 4 - Baking fixture with -h throws an exception
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0-alpha1
* Platform and Target: PHP 7.3.2

### What you did
I ran `bin/cake bake fixture -h`

### What happened
```
$ bin/cake bake fixture -h
Exception: strlen() expects parameter 1 to be string, int given in [/Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/ConsoleInputOption.php, line 175]
2019-04-17 09:48:02 Error: [TypeError] strlen() expects parameter 1 to be string, int given in /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/ConsoleInputOption.php on line 175
Stack Trace:
#0 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/ConsoleInputOption.php(175): strlen(1)
#1 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/HelpFormatter.php(173): Cake\Console\ConsoleInputOption->usage()
#2 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/HelpFormatter.php(97): Cake\Console\HelpFormatter->_generateUsage()
#3 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/ConsoleOptionParser.php(737): Cake\Console\HelpFormatter->text(72)
#4 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/Command.php(197): Cake\Console\ConsoleOptionParser->help(NULL, 'text')
#5 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/Command.php(173): Cake\Console\Command->displayHelp(Object(Cake\Console\ConsoleOptionParser), Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))
#6 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/CommandRunner.php(161): Cake\Console\Command->run(Array, Object(Cake\Console\ConsoleIo))
#7 /Users/davidyell/Sites/CakePHP4/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#8 {main}
```

### What you expected to happen
I thought that the options for the bake fixture command would be output. Such as record importing and count, etc.

### Notes
I realise that this might be better in `cakephp/bake`, but as the exception was thrown from the core I submitted it to this repo.

### PR DESCRIPTION
**Pull request by markstory**
Fix type error cause by putting numbers into `strlen()`. When an optino has a default value that is an integer/float generating help should continue to work.

Fixes #13128

### CODE REVIEW

**Comment by saeideng** [comment]
https://github.com/cakephp/cakephp/blob/38aff204eadee0c63f69b18f2149d8d9675aea8e/src/Console/ConsoleInputOption.php#L61-L63

now should be `@var string|int|bool` !! ?

**Comment by markstory** [comment]
@saeideng Another option would be to string cast the default value if it isn't a string or boolean. Any value from the command line will be a string anyways.

**Comment by davidyell** [comment]
I'm using commit `2459485b (HEAD -> 4.x, origin/4.x, composer/4.x) Remove double declare()` and I am still having the issue

**Comment by saeideng** [comment]
@davidyell  use latest commit of `cakephp/cakephp` , not `bake`
I tested and it works well

**Comment by davidyell** [comment]
Thanks @saeideng

**Pull request merged**
