### PR TITLE
Cakephp should be in the required packages

### PR DESCRIPTION
**Pull request by gmponos**
Cakephp should be in the required packages

### CODE REVIEW

**Comment by markstory** [comment]
Thanks :+1:

**Comment by ravage84** [comment]
Is that really the case?

**Comment by markstory** [comment]
That the app relies on CakePHP? Yes.

**Comment by ravage84** [comment]
@markstory we are talking about CakePHP 2.x here. The CakePHP framework is already contained in the [lib/Cake](https://github.com/cakephp/cakephp/tree/2.9.5/lib/Cake) folder. That's why I am asking. I _could_ see the need for it in the ``require-dev``, but as actual dependency?

**Comment by dereuromark** [comment]
For composer people it is a require dependency. For all others that composer file can be ignored.

**Comment by ravage84** [comment]
@dereuromark sure, but since when do we "support" to install CakePHP 2.x through misusing the frameworks **own** ``composer.json``?

Reading the [related Coobook section](https://book.cakephp.org/2.0/en/installation/advanced-installation.html#create-a-cakephp-project), one gets told to create a ``composer.json`` of his/her own and requring ``cakephp/cakephp`` therein.

**Comment by rchavik** [comment]
This does seem a bit off to me. cake is already installed in `../lib`

**Comment by gmponos** [comment]
Guys Guys...

There are two composer files. [first one](https://github.com/cakephp/cakephp/blob/2.x/composer.json) in in the parent folder with the lib installed already in.

[Second one](https://github.com/cakephp/cakephp/blob/2.x/app/composer.json) is inside `app/` folder without the lib installed (for those who choose to install cakephp using composer)

**Comment by rchavik** [comment]
> Second one is inside app/ folder without the lib installed (for those who choose to install cakephp using composer)

For this type of install, I believe you're better off using https://github.com/FriendsOfCake/app-template then install cakephp from its root with composer.

**Comment by gmponos** [comment]
@rchavik I understand your point.

But since there is a composer file inside there it should clearly state that cakephp should be in required ones and not as dev dependency. 

Or remove the composer file completely and suggest to the developers though the cakephp official page that they should install the `app-template` you are saying.

**Comment by ravage84** [comment]
Didn't realize it was the one in the app folder.

Though I see [why](https://github.com/cakephp/cakephp/commit/c7a48acd104ea5f9d9f43d273d157d842d95f7e2) there is a second ``composer.json`` in there, I still think we would be better off rremoving it and **officially** recommending [FriendsOfCake/app-template](https://github.com/FriendsOfCake/app-template) in the [related Cookbook section](https://github.com/FriendsOfCake/app-template) instead.

By the way, this second ``composer.json`` or better said this option of installation does not seem to be documented, anyway.

Alternatively, we actually use the [cakephp/app repo](https://github.com/cakephp/app) to provide an **official** Composer compliant CakePHP 2.x app template. Though I don't see the need for that since FriendsOfCake's one works fine.

**Pull request merged**
