### PR TITLE
Return cached results in Query::all()

### PR DESCRIPTION
**Pull request by othercorey**
I think this makes sense for users who have to switch to all() instead of execute(). If they were executing multiple times, it was probably undesired.

### CODE REVIEW

**Review by ADmad — APPROVED** [review]

**Comment by saeideng** [comment]
do we have a way to clear result ?

**Comment by saeideng** [comment]
do we have a way to clear result ?

**Comment by ADmad** [comment]
> do we have a way to clear result ?

What's your use case? Modify the query parts already clears the results.

**Comment by othercorey** [comment]
> do we have a way to clear result ?

If we did, we would just expose `_dirty()`.

**Comment by saeideng** [comment]
> What's your use case?

sometimes it needed in a  loop , but yes use case is in very special cases 
looks clone it would helps
```php
$new = clone $query;
```

it is not common need , so :+1: to not having it (clear result)

**Review by saeideng — APPROVED** [review]

**Comment by othercorey** [comment]
You only need `all()` if you have result decorators. If not, you can just call execute() in a loop and fetchAll().

**Comment by saeideng** [comment]
it is not common need , so :+1: to not having it

**Pull request merged**
