### PR TITLE
Add assertHeaderContains() to IntegrationTestCase

### LINKED ISSUE #8199: assertHeader is asserting equality instead of containment
I am writing unit tests for my API which always returns json responses.
I use `$this->assertHeader('Content-Type', 'application/json');` to make sure that the appropriate json headers are set. However I have the charset=UTF8 header also set. The test fails with:
``` php
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'application/json; charset=UTF-8'
+'application/json'
```

Instead of asserting if the two strings are equal, shouldn't it just assertContains?

### PR DESCRIPTION
**Pull request by half2me**
fixes #8199

### CODE REVIEW

**Comment by dereuromark** [comment]
:+1:

**Comment by dereuromark** [comment]
Is it possible to add a basic test? Check the other tests on how this can be done.

**Comment by half2me** [comment]
@dereuromark I added a test similar to the one used for assertHeader()

**Comment by markstory** [comment]
Thanks @half2me

**Pull request merged**
