### PR TITLE
Rector fixes

### PR DESCRIPTION
**Pull request by Harfusha**
Fixes made by rectorPHP

### CODE REVIEW

**Comment by LordSimal** [comment]
Not really sure what you are trying to achieve here, but a PR containing thousands of changed files won't be merged just like so.

Also rector creates some false positive changes as well (as you can see by the massive amount of failing tests).

So if you want to improve the framework maybe try to explain what exactly you want to improve and then maybe go sub-package by sub-package. This looks like you ran the whole rector suite on the `src` directory and just created a PR without even checking tests, code-style etc. yourself.

**Comment by Harfusha** [comment]
In issue i opened, i asked them if these kind of changes are acceptable, if yes, i will go file by file and fix all issues and tests. 

If these changes are unacceptable, i would spend many hours doing something that will be trashed

**Comment by LordSimal** [comment]
I haven't looked through all of your changes but many of these are related just to code style (so like new empty spaces or adjusted phpdoc annotations)

These should not be fixed/adjusted by rector but instead are checked via the `composer cs-check` and `composer cs-fix` commands. CakePHP has its own set of code style as you can learn [here](https://book.cakephp.org/5/en/contributing/cakephp-coding-conventions.html)

But then there is still the problem of all the failing tests.

Neither do I have the right nor permission to tell you what to do here - I am just giving you a bit of context why this kind of a PR is bad.

**Comment by Harfusha** [comment]
Yeah i know, i just did the eazy ones. I made this PR just to show what changes can be made.

I will close it, so i can do it the correct way, if even.

**Pull request closed without merging**
