### PR TITLE
Fix: unused derault types in TypeMap

### PR DESCRIPTION
**Pull request by StewEucen**
I fix about problem of #6737 
I think that fix policy is probably right.
But now PHPUnit test has 10 errors (5 kinds each 2)

I am seeking the solution, however it is so hard.
Please help for solving them.

### CODE REVIEW

**Comment by markstory** [comment]
The failing tests in this instance make me think that the fix will cause other issues. The tests are failing because query objects have incomplete/incorrect type maps.

I think part of your original issue might be from 2 separate query instances being used, one for the coalesce() and one for the query you want to execute. Did you try using the original query for the coalesce() call?

**Comment by StewEucen** [comment]
@markstory I try to test again to use same query instance as follow.
```
$theTable = $this->Samples;
$theQuery = $theTable->query();
$res = $theQuery
    ->select([
        'id',
        'coalesced_value' => $theQuery->func()->coalesce(
            ['level' => 'literal', -1],
            ['integer']
        )
    ])
    ->all()
;
```

Original source and fixed source gave same results.
```
Original source: '-1' (string)
Fixed source   : -1 (int)
```

Now I need to sleep. I will be back after several hours.

**Comment by StewEucen** [comment]
I try to solve this problem, and got the solution in PHPUnit tests.
There are two problems.
* (1) src\Database\Query::_conjugate() do not use defaultTypes
* (2) src\ORM\Query::applyOptions() do not set defaultTypes to self

I will write details of these in my next comment.
Please wait.

**Comment by StewEucen** [comment]
# (1) src\Database\Query::_conjugate() do not use defaultTypes
I think that the problem must be solued.

## Fix
```
protected function _conjugate($part, $append, $conjunction, $types)
{
    $expression = $this->_parts[$part] ?: $this->newExpr();

    if (!is_string($append) && is_callable($append)) {
        $append = $append($this->newExpr(), $this);
    }

+++ $types = (array)$types + $this->defaultTypes();
    if ($expression->type() === $conjunction) {
        $expression->add($append, $types);
    } else {
        $expression = $this->newExpr()
            ->type($conjunction)
            ->add([$append, $expression], $types);
    }

    $this->_parts[$part] = $expression;
    $this->_dirty();
}

```

## Result
This fix remove 8 errors.

## Side effect
_conjugate() is called from as follows
* src\Database\Query::where()
* src\Database\Query::andWhere()
* src\Database\Query::orWhere()
* src\Database\Query::order()
* src\Database\Query::having()
* src\Database\Query::andHaving()
* src\Database\Query::orHaving()

These methods use types, therefore no side efferct I think.
Please consider about this solution.

**Comment by StewEucen** [comment]
# (2) src\ORM\Query::applyOptions() do not set defaultTypes to self
Firstly see the code in QueryTest.
file: ests\TestCase\ORM\QueryTest.php
line: 835
```
$this->assertEquals($expected, $result);
```

Summary of the assertEquals() subject is follow.
```
$aa = new Query(...)->applyOptions(...)->clause('where');
$bb = new QueryExpression(...);

$this->assertEquals($aa, $bb);
```

## Cause summary

$aa has $this->defaultTypes, but applyOptions(...) does not set it own QueryExpression instance.
$bb has $this->defaultTypes.

#6739 is changed return value of QueryExpression::types().
If the instance of QueryExpression has defaultTypes, it works as backup to types().

$aa->types() does not return $this->defaultTypes
$bb->types() return $this->defautTypes

Therefore $this->assertEquals($expected, $result) throws error.

## Fix
```
--- $expected = new QueryExpression($options['conditions']), $this->fooTypeMap);
+++ $expected = (new QueryExpression($options['conditions']))->typeMap($this->fooTypeMap);

    $result = $query->clause('where');
    $this->assertEquals($expected, $result);
~~~

To remove the second param of new QueryExpression() create QueryExpression instance without defautTypes.
This fix remove 2 error and got OK

## Side Effect
This fix is for only TestCase. I think that it is makeshift.
To fix rightly is that Query::where() should use defaultTypes.

Please consider about this problem.

**Comment by StewEucen** [comment]
I pushed two commits to fix error of TestCase.
Because both commits have defferent meanings.

**Comment by StewEucen** [comment]
@markstory
I restored TestCase by two commits and got to pass the Travis Cl build.
But AppVeyor build is still error.

What should I do to fix it?

**Comment by markstory** [comment]
AppVeyor has been having issues for a while now. For some reason it doesn't pull in the latest phpunit-mock-objects which includes a fix we need.

I'll try to make sometime tonight to look at this issue more and get the fixes merged in.

**Comment by StewEucen** [comment]
@markstory 
Thank you for reply.
I wait the time to fix issue of AppVeyor build.

By the way, I create new Behavior for CakePHP now.
I found some problems in CakePHP core, and used code unsuitable for CakePHP to fix it.
When my pull requests will be all OK, I can remove these codes.

Suitable code always make us happy, I believe so.

**Comment by markstory** [comment]
I tried your fix out with the following as a test case:

```php
        $table = TableRegistry::get('Comments');
        // Force coalesce() to fall to the -1
        $table->updateAll(['published' => null], ['1 = 1']);

        $query = $table->find();
        $query->select([
            'id',
            'coalesced' => $query->func()->coalesce(
                ['published' => 'literal', -1],
                ['integer']
            )
        ]);
        $result = $query->all()->first();
        $this->assertSame(-1, $result['coalesced']);
```

However, both with and without your fix the test always fails as the value is a string and not an integer.  The generated query does bind `-1` as an integer however. Are you trying to correct the casting on the query parameter, or returned value?

**Comment by StewEucen** [comment]
@markstory Good morning I have just wake up.
The type of coalesced is null, because it is virtual field in this query.
When type is null, the value in result is always string.

```
$this->assertSame('-1', $result['coalesced']);
```
or
```
$this->assertSame(-1, (int)$result['coalesced']);
```

**Comment by markstory** [comment]
Ok, I think I have a fix that is much smaller than this fix. I'll have it up tonight.

**Comment by StewEucen** [comment]
@markstory I am looking forward to your fix.
It will give me good skills for this great project.
This is a great experience for me.

**Comment by markstory** [comment]
Fixed with #6765 in a different way.

**Comment by StewEucen** [comment]
@markstory Good morning.
I found the different way to fix. It is smaller than my fix and a range of side effect.
I learned from it. Thank you for your illuminating fix.

**Pull request closed without merging**
