### PR TITLE
RFC - 3.0 EventManager - on & off

### PR DESCRIPTION
**Pull request by markstory**
This may not be well received but I thought I'd propose it anyways. I've always found the attach/detach methods a bit cumbersome to use, as the event name comes at the end of the argument list. Instead, I think we should follow the interface that jQuery and node.js use where the event name is first. This does create some additional argument juggling when priorities are involved, but I think the additional library code is worth it as the developer facing interface is nicer to use.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Yay +1 I *always* hated the ordering.

**Comment by lorenzo** [comment]
I like this!

**Comment by dakota** [comment]
:+1: Yes please!

**Comment by HavokInspiration** [comment]
I am more than ok with this :+1:

**Comment by markstory** [comment]
Should the documentation also be updated to recommend these new methods? I'm also happy to backport this change to 2.7, but I'm not sure it should be recommended in the docs there.

**Comment by jadb** [comment]
I think these methods make more sense and will be easier for new comers who wouldn't have to deal with attach/detach. Should make them defaults in the documentation.

**Comment by markstory** [comment]
I've deprecated attach/detach now, and made on/off the primary implementation. I'll update the book tomorrow.

**Comment by ADmad** [comment]
:clap:

**Comment by antograssiot** [comment]
shoudn't we also trigger a E_USER_DEPRECATED warning to ease the migration for end-user from attach/detach ?

**Comment by markstory** [comment]
@antograssiot No because the attach/detach methods will stick around for quite sometime given we are in RC.

**Pull request merged**
