### PR TITLE
Clean up the doc blocks around mixed.

### PR DESCRIPTION
**Pull request by dereuromark**
Often times we used mixed way to lazy, where there are one or two specific types we can typehint and document instead.

### CODE REVIEW

**Comment by dereuromark** [comment]
Also,

    @return array|null The loaded authorization objects, or null when authorize is empty

Is there a reason we need to return multiple types here? Could have just been always array (empty array if empty) IMO.

**Comment by hmic** [comment]
Could be done IMHO, but not in 3.1 as its not BC strictly...

**Comment by dereuromark** [comment]
Yes, I was thinking 3.3. As 3.2 is now RC1 as well.

**Comment by hmic** [comment]
Milestone is still 3.1.8... Needs update....

**Comment by dereuromark** [comment]
No, this milestone is good for these doc block changes.

**Comment by markstory** [comment]
> Also, for constructAuthorize() and constructAuthenticate()

Removing the null type could be done in 3.2 or 3.3. Its not necessarily a BC break as we're not adding a new return type.

**Comment by dereuromark** [comment]
@markstory Technically people could test for `=== null` in their code ;) That's what hmic meant with BC strict. But thats a nitpick and not too likely.

**Pull request merged**
