### PR TITLE
Try using xdebug to get coverage report.

### PR DESCRIPTION
**Pull request by ADmad**
Let's see if this fixes the drop in code coverage reported by codecov.

### CODE REVIEW

**Comment by ADmad** [comment]
The error of apc.so not being loaded is due to this bug https://pear.php.net/bugs/bug.php?id=21007

**Comment by ADmad** [comment]
Given `ApcEngine` in 3.x uses `apcu_*` functions do we even need to install `apcu_bc`?

**Comment by ADmad** [comment]
> codecov/project — 94.85% (+53.95%) compared to 4518f5e

Booyah!

**Comment by chinpei215** [comment]
Nice work!

**Comment by ADmad** [comment]
Removed installation of `apcu_bu`. Travis doesn't throw any errors anymore and number of skipped tests has also reduced.

**Comment by dakota** [comment]
I see a issue was opened for PHPUnit (https://github.com/sebastianbergmann/php-code-coverage/issues/443) and phpdbg (https://github.com/krakjoe/phpdbg/issues/156)

**Comment by dakota** [comment]
Ah, looks like it's a bug in 7.0.7 (https://bugs.php.net/bug.php?id=72284). Should be fixed in 7.0.8 then. We should probably go back to phpdbg once 7.0.8 is available, it is substantially quicker for code coverage builds.

**Comment by ADmad** [comment]
We can switch back to `phpdbg` if needed after new release for PHP 7 is done. https://bugs.php.net/bug.php?id=72284

**Pull request merged**
