### PR TITLE
Added the method getNames() in AssociationCollection class

### PR DESCRIPTION
**Pull request by keomaborges**
I created a small function to get the association _name property of all the associations. I needed this to customize the plugin friendsofcake/crud to contain related models on View action. Please, accept if you consider this useful.

### CODE REVIEW

**Comment by markstory** [comment]
Any way we could get a test for the new method?

**Comment by keomaborges** [comment]
@markstory I use that function into ViewAction of `friendsofcake/crud`. It works great. How could I use my situation as an test?

**Comment by ndm2** [comment]
Isn't that what AssociationCollection::keys()` already does, unless one would manually add associations to the collection, using an alias that is different to the name of the association?

* https://github.com/keomaborges/cakephp/blob/3.3.12/src/ORM/Table.php#L758
* https://github.com/keomaborges/cakephp/blob/3.3.12/src/ORM/AssociationCollection.php#L50
* https://github.com/keomaborges/cakephp/blob/3.3.12/src/ORM/AssociationCollection.php#L106

**Comment by ndm2** [comment]
Isn't that kind of what `AssociationCollection::keys()` already does, unless one would manually add associations to the collection, using an alias that is different to the name of the association?

* https://github.com/keomaborges/cakephp/blob/3.3.12/src/ORM/Table.php#L758
* https://github.com/keomaborges/cakephp/blob/3.3.12/src/ORM/AssociationCollection.php#L50
* https://github.com/keomaborges/cakephp/blob/3.3.12/src/ORM/AssociationCollection.php#L106

If such an additonal method is required, then the differences somehow need to be documented, as currently the method descriptions read as if they would return the same thing.

**Comment by markstory** [comment]
@keomaborges I believe that the function works. We need automated tests though to ensure the method continues working through any future refactoring/cleanup work that is done.

Ideally a test would setup any required state, invoke the method and check that the return value is correct. The existing tests for AssociationCollection have some examples of the kind of thing we'd be looking for.

**Comment by markstory** [comment]
Closing as this method has quite a bit of overlap with the existing `keys()` method, and I'm not clear on why we would need this method and keys().

**Pull request closed without merging**
