### PR TITLE
Avoid unnecessarily decorating a resultset.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
The diff looks complicated due to formatting changes but the only actual change is:

```php
foreach ($formatters as $callable) {
    $extracted = new ResultSetDecorator($callable($extracted, $query));
}
```
to
```php
foreach ($formatters as $callable) {
    $extracted = $callable($extracted, $query);
    if (!$extracted instanceof ResultSetInterface) {
        $extracted = new ResultSetDecorator($extracted);
    }
}
```

**Comment by othercorey** [comment]
Looks ok but do the formatters ever return a decorator instance?

**Comment by ADmad** [comment]
> Looks ok but do the formatters ever return a decorator instance?

Nope, they just need to be collections but I chose to be safe since this is for `4.x`. We have this implicit undocumented behavior that return value of formatters needs to be collections (since `ResultSetInterface` extends `CollectionInterface`) :unamused:.

**Comment by ADmad** [comment]
Here we don't even check the value type after each formatter call. The check is done after all formatters are run:

https://github.com/cakephp/cakephp/blob/a5f9900b1bdc652dcafc64b525587d54a6b8d48c/src/Datasource/QueryTrait.php#L600-L606

**Comment by othercorey** [comment]
So you want to add checks in 4.next/5.x or just rely on the constructor failing?

**Comment by ADmad** [comment]
I don't want to touch anything in 4.next, will see about 5.x.

**Pull request merged**
