### PR TITLE
Update php config files to return array instead of setting $config var.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
I am undecided whether to keep support for `$config` permanently or just temporarily until stable with a warning to update.

**Comment by dakota** [comment]
My opinion here is that we keep it in place for 3.0 (maybe mark as deprecated) and only remove in 3.1. Simply because 3.0 is already in RC, and this would be a breaking change.

**Comment by markstory** [comment]
Given that it is 2 lines of code to continue supporting, I don't see a problem in keeping both $config and return flavours around for a while.

**Comment by ADmad** [comment]
Okay cool, then this is good to merge.

**Pull request merged**
