### PR TITLE
Issue 6794

### LINKED ISSUE #6794: Bug: I18n translation fails join after TreeBehavior->recover()
I use a  I18n on my table. 
But it throws a DB error after TreeBehavior->recover(); 
It says the following message: "Error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in order clause is ambiguous"

See the screenshot for more details. 

How can I fix this? 

cakeversion: 3.0.6

image

### PR DESCRIPTION
**Pull request by ADmad**
Closes #6794

### CODE REVIEW

**Comment by dereuromark** [comment]
:+1:

**Comment by ADmad** [comment]
Postgres doesn't seem to like the change. Can someone please look into it.

**Comment by markstory** [comment]
I can look at the postgres issues.

**Comment by lorenzo** [comment]
Looks like an issue with identifier quoting

**Comment by markstory** [comment]
@ADmad @lorenzo I think I've fixed the postgres issues. They were highlighting some gaps in the identifier quoting process that should now be fixed.

**Comment by ADmad** [comment]
@markstory Nice side effect this patch had :)  I'll let @lorenzo check the quoting fix and merge.

**Comment by lorenzo** [comment]
Good job guys!

**Pull request merged**
