### PR TITLE
Fix return type issues reported by psalm.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by dereuromark** [comment]
The failing 7.1 tests I fixed in my PR and should now be in master.

> CurlTest::testSendLiveResponseCheck

**Comment by ADmad** [comment]
Boo.. A bad merge seems to have added back the `get_class()` usages making phpcs unhappy.

**Comment by ADmad** [comment]
Any feedback on this?

**Comment by dereuromark** [comment]
The inline suppress are a bit annoying.
But they seem to be outweight by the benefits, the correct types in other places.
:+1:

**Comment by ADmad** [comment]
The inline comments ensure error at that particular location only is ignored. Using the psalm config would ignore that error throughout the file and thus new ones could be missed.

Psalm has another feature which generates a baseline file with existing errors avoiding the need to add specific ignores. I'll look into using that one of these days.

**Pull request merged**
