### PR TITLE
Explicitly check against null, to enable testing attributes of email #0

### PR DESCRIPTION
**Pull request by Zuluru**
The classes for testing email constraints do not work when specifying email #0 (the first email sent). We often send multiple emails to different recipients in one step, and need to ensure the specific contents of each, not just that *some* email contained a certain string. The code as written extracts the specified email if it is truthy, which 0 is not. Changing to specifically check for null resolves this.

I'm not sure what to do about unit testing of this, as there are currently no unit tests at all under TestSuite/Constraint/Email (that folder doesn't exist). If there were other unit tests there, I'd update them to test for this, but I don't have the time right now to build a whole set of test cases for this area of the code.

### CODE REVIEW

**Comment by markstory** [comment]
> I'm not sure what to do about unit testing of this, as there are currently no unit tests at all under TestSuite/Constraint/Email (that folder doesn't exist). 

The tests for email constraints are [here](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/TestSuite/EmailTraitTest.php).

**Comment by Zuluru** [comment]
Okay! I'll get something added there shortly to test this.

**Comment by Zuluru** [comment]
Added a test, but I don't love it. It's referencing things outside of what this file is supposed to be testing. But there's no "assertMailNotSentToAt" set of negative assertion functions, nor do I think there should be. Open to suggestions about how to improve this.

**Comment by Zuluru** [comment]
...and the test fails on 5.6 because LogicalNot isn't available there?

**Comment by markstory** [comment]
> Added a test, but I don't love it. It's referencing things outside of what this file is supposed to be testing. But there's no "assertMailNotSentToAt" set of negative assertion functions, nor do I think there should be. Open to suggestions about how to improve this.

Could you have a separate test that only sends two emails with different addresses and check specifics from the first email with `assertMailSentWithAt(0, ...)`

**Comment by Zuluru** [comment]
The problem is that the original code would succeed with that: when "0" is specified for the email to check, it will assert true if *any* of the emails that were sent match. So such a test would not actually be testing anything useful. The only way to test the fix is to specifically have a negative test.

**Comment by markstory** [comment]
Ok. You could have the current test you've added in a separate method and skip it if the `LogicalNot` class doesn't exist.

**Pull request merged**
