### PR TITLE
Create rows in belongsToMany assoc with primaryKey

### PR DESCRIPTION
**Pull request by Tzaoh**
Setting to create row in target table with belongsToMany assoc when primaryKey of the target table is specified

### CODE REVIEW

**Comment by markstory** [comment]
Without tests or context I don't understand what this pull request is attempting to accomplish.

**Comment by Tzaoh** [comment]
I do not intend to get merge so fast I was just trying to see the possible conflicts and get some feedback. I can try to prepare some tests if you think the functionality can be useful.

**Comment by markstory** [comment]
I'm guessing this code is to force the markNew flag to true on data that is being marshalled with all the primary key values set?

**Comment by Tzaoh** [comment]
The previous code checks if the primary key is in the fields we are trying to save, if so it assumes that the entity does exist. I added a flag which you can set via model Table file to check the existence (or not) of the primaryKey in case you provide one. An example of this setting is the following:
`SummonersTable.php`
```PHP
$this->belongsToMany('Games', [
    'foreignKey'        => 'id',
    'targetForeignKey'  => 'gameId',
    'through'           => 'games_summoners',
    'forceTargetInsert' => true
]);
```
Maybe you could not use an extra setting in the options array, but (always imho) this way you are saving extra queries to the database if the user did not ask for it explicity:

`Line: 312 Marshaller.php`
```PHP
if ($forceTargetInsert && !$target->exists($conditions)) {
    $records[$i] = $this->one($row, $options);
}
```

If the user does not use the "forceTargetInsert" setting we will not ask the primary existence to the db through `Model::exists()`.

**Comment by markstory** [comment]
I don't see how this setting could safely be defaulted to true in an association definition. It seems like it could easily lead to duplicate primary key errors as it bypasses the exists checks.

**Comment by Tzaoh** [comment]
I understand that if we re discussing about the implementation you do not think is a crazy idea the funcionality i described right?

I was thinking setting at false by default and activate it only when you want that behavior.
We can try the cases that you think will be wrong, which one where you thinking specifically?

If you pop up with a new idea about implement this i would love see it

**Comment by markstory** [comment]
Could this instead be done as an option in the marshaller? It seems like that is a better place for this kind of behavior as the entity creation is what needs to be different from my understanding.

**Comment by Tzaoh** [comment]
Just to be sure I understand it. You prefer that the `_belongToMany` method in `Marshaller.php`

```PHP
protected function _belongsToMany(Association $assoc, array $data, $options = [])
```

Receives the setting through its $option parameter, right?

and you should set it this way:

```PHP
$entity = $this->newEntity($data, [
    'associated' => ['Games._joinData'],
    'settingName' => true
]);
```

**Comment by markstory** [comment]
@Tzaoh Something like that I think having an option in the marshaller that let you force entities into a 'new' state for specific associations would be better. It allows the associations for focus on persistence/finding and doesn't introduce new state based behavior.

**Comment by Tzaoh** [comment]
Must I have to recreate a branch and a new pull request? I dont find how to restore the initial versions

**Comment by Tzaoh** [comment]
This continue on #8057

**Pull request closed without merging**
