### PR TITLE
Remove unused constant.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by saeideng** [comment]
since we have it in cakephp/app repo 
https://github.com/cakephp/app/blob/42c089536a32e5362e328e76e8ef5348883d5a31/config/paths.php#L18-L20
seems its enough 
maybe it is useless in core itself
but for other plugins its necessary IMO 
like https://github.com/cakephp/bake/blob/7356656e236bb62733f4fdd4894ce1f26f9e14f6/tests/bootstrap.php#L39

**Comment by dereuromark** [comment]
I actually like it and use it a lot in app and plugin code. 
Much better than the long form.

**Comment by markstory** [comment]
@dereuromark it is still defined in the app template.

**Comment by dereuromark** [comment]
That doesnt help plugins to rely on it IMO.

**Comment by dereuromark** [comment]
Baeh, thats not nice. It builds paths on Windows not consistently IMO then.
Does it hurt to keep it?

**Comment by ADmad** [comment]
> Does it hurt to keep it?

Not really. Closing then.

**Pull request closed without merging**
