### PR TITLE
Ensure deprecated properties like $theme are properly passed to view.

### PR DESCRIPTION
**Pull request by ADmad**
Refs #7012

### CODE REVIEW

**Comment by ADmad** [comment]
Hmm, tests are failing because `View` also uses `ViewVarsTrait` :(

**Comment by markstory** [comment]
What about not triggering a notice?

**Comment by ADmad** [comment]
@markstory False alarm :) Problem was because `ViewTest` had a controller which declared theme property. View class itself never calls `ViewVarsTrait::createView()` which is where the notice is thrown.

**Comment by markstory** [comment]
Looks good to me.

**Pull request merged**
