### PR TITLE
Normalize order of union types in docblocks

### PR DESCRIPTION
**Pull request by othercorey**
Refs https://github.com/cakephp/cakephp/issues/15528

This handles many non-object types.

### CODE REVIEW

**Comment by ADmad** [comment]
Without a phpcs sniff we won't be ensure the ordering is followed for new/updated methods.

**Comment by othercorey** [comment]
> Without a phpcs sniff we won't be able to ensure the ordering is followed for new/updated methods.

That sniff will take some work. This just cleans up a large chunk so the diffs aren't terrible in 5.9.

**Comment by othercorey** [comment]
There are a few docblocks where the object type is last still. I will try to fix them.

**Comment by ADmad** [comment]
On a related noted I am also wondering if we should relax our docblock requirements for 5.0. Repeating the types in docblock when we have language types is redundant. The description like `Response instance` are also pretty useless when the argument is typed as `ServerResponseInterface`.

**Comment by markstory** [comment]
> On a related noted I am also wondering if we should relax our docblock requirements for 5.0. Repeating the types in docblock when we have support for types in the language itself now is redundant (unless we want to expand them in docblocks). The description like Request instance are also pretty useless when the argument is typed as ServerResponseInterface.

💯 agree. The type annotations in docs are generally redundant and it would be good to not have to type everything out twice. The description text is also used in the generated API docs so it isn't always noise.

**Comment by dereuromark** [comment]
I usually only add a text/description if it provides value beyond what is already written :) Repeating it was never useful.

**Comment by othercorey** [comment]
> The description text is also used in the generated API docs so it isn't always noise.

Our parameter descriptions are often terrible, but what would we show if they're missing?

**Comment by dereuromark** [comment]
> Our parameter descriptions are often terrible, but what would we show if they're missing?

Could it then just auto-inflect the name from the param etc? 

    $paramName => Param Name

**Comment by othercorey** [comment]
The API docs do default to the reflected types. However, it will generate a slightly awkward empty parameter description block. Maybe we optimize how those are displayed.

**Pull request merged**
