### PR TITLE
5.x fixes

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
@LordSimal Can you please check the phpstan failures? It doesn't fail for me locally.

**Comment by LordSimal** [comment]
CI seems to download `1.10.21` but we defined `1.10.14` in our phars.xml
https://github.com/cakephp/cakephp/actions/runs/5380672968/jobs/9764022048?pr=17172#step:5:19

I locally also get `1.10.14` and not `1.10.21` so somethings wrong with how CI installs the phive dependencies.

If I adjust the phpstan version to 1.10.21 locally I also get those errors.

**Comment by LordSimal** [comment]
Even though it doesn't seem to be a direct problem in phive I will create an issue in its repo to see if someone else has run into this issue. https://github.com/phar-io/phive/issues/411

**Comment by theseer** [comment]
For the record: This very PR changes the versions defined in [`.phive/phars.xml`](https://github.com/cakephp/cakephp/pull/17172/files#diff-bf3b5b5e32d0c7e309995719d0c867d3fecb8b62dd9d0646f1e99becdb4e3367). This may not have happened intentionally, but I don't see how phive is to blame for this ;-)

**Comment by LordSimal** [comment]
I thought the changes made here were only related to what has been reported in phpstan/psalm.

But instead the used versions have been updated which I completely missed (my bad)

In the end everything is working fine with phive and our CI because I can reproduce these stan failures with the updated phars.xml

**Comment by LordSimal** [comment]
If someones got the time and energy to re-evaluate the baseline files please go forth 😁 
I was just able to fix a few problems but not all of them.

**Comment by ADmad** [comment]
Merging as the build passes now. No idea why I got different/no failures locally.

**Pull request merged**
