### PR TITLE
4.1 - Use junction association bindingKey instead of target primaryKey

### PR DESCRIPTION
**Pull request by othercorey**
Fixes https://github.com/cakephp/cakephp/issues/12061
Fixes https://github.com/cakephp/cakephp/issues/12238

This allows a BelongsToMany association to use a different bindingKey than the primaryKey for the table.  The default value for the bindingKey is the primary key of the target table.

### CODE REVIEW

**Comment by dereuromark** [comment]
Do we need to backport this to 3.next? Or any way people can use it on their own as project overwrite?

**Comment by othercorey** [comment]
Because the default behavior doesn't change, we could consider back-porting this. Although very unlikely, if someone did manually add a `setBindingKey()` call to the junction table association, it could throw an error if they typed the column name wrong.

**Review by markstory — COMMENTED** [review]
Would be good to have an integration test for this. Right now its hard to ensure we actually have the code working correctly.

**Comment by othercorey** [comment]
> Would be good to have an integration test for this. Right now its hard to ensure we actually have the code working correctly.

Added unit test using contain and link with custom binding key.

**Pull request merged**
