### PR TITLE
Update phpstan

### PR DESCRIPTION
**Pull request by dereuromark**
With the recent bugfixes, they removed some of the annoying false positives
Let's try.

### CODE REVIEW

**Comment by dereuromark** [comment]
useful finds in phpstan error report.

**Comment by dereuromark** [comment]
I fixed almost all issues and opened up tickets for the invalid reports:
- https://github.com/phpstan/phpstan/issues/1920
- https://github.com/phpstan/phpstan/issues/1921

**Comment by dereuromark** [comment]
Only left now:

 ------ --------------------------------------------------------------------- 
  Line   Validation/Validation.php                                            
 ------ --------------------------------------------------------------------- 
  1359   Variable $validHeight in isset() always exists and is not nullable.  
  1359   Variable $validWidth in isset() always exists and is not nullable.   
  1362   Variable $validHeight in isset() always exists and is not nullable.  
  1365   Variable $validWidth in isset() always exists and is not nullable.   
 ------ --------------------------------------------------------------------- 

Do we want to fix the code here or silence the phpstan bugs for now?

**Comment by dereuromark** [comment]
All green now.
This should eventually be merged to 4.x then as well.

**Comment by ADmad** [comment]
4.x already uses 0.11 and a higher level for phpstan :)

**Comment by dereuromark** [comment]
I am talking about my fixes, you just silenced them in 4.x :) At least according to the diff.

**Comment by ADmad** [comment]
The changes you did in Validator::imageSize() might be the only ones not done on 4.x.

**Pull request merged**
