### PR TITLE
fix usage of constant in EavStrategy

### PR DESCRIPTION
**Pull request by LordSimal**
caused by https://github.com/cakephp/cakephp/commit/52c8f7b1d36cc7738a8ab2753772cda5130dacad#diff-41a222f58fc084f37e56cd89026e414fb5e804f606164646c3e2e38396f2ec72R137

Seems like we neither have a test for that nor does anyone seem to have set the `onlyTranslated` out there till now ^^

### CODE REVIEW

**Comment by ADmad** [comment]
> Seems like we neither have a test for that nor does anyone seem to have set the onlyTranslated out there till now 

We should add one then :)

**Comment by LordSimal** [comment]
Actually, it seems PHP doesn't care about that whitespace (which seems to odd to me) but look at this: https://3v4l.org/lF2nZ

So this already worked, it just looked weird to me.

**Comment by dereuromark** [comment]
Still could be a code sniffer rule
=> https://github.com/slevomat/coding-standard/issues/1699
In case there is no existing one yet.

**Comment by dereuromark** [comment]
Note that `PhpCollective.WhiteSpace.ObjectAttributeSpacing.TooMany ` rule from https://github.com/php-collective/code-sniffer would cover this.
Could be ported to the CakePHP one.

**Pull request merged**
