### PR TITLE
Response with Status and Body

### PR DESCRIPTION
**Pull request by karmicdice**
Merging `withStatus` and `withStringBody` as a single function to facilitate API responses.

Related to #16962

### CODE REVIEW

**Comment by ADmad** [comment]
New features need to target `4.next`.

**Comment by markstory** [comment]
I've updated the base branch to 4.next, you'll need to rebase onto 4.next though as the history right now contains a bunch of unrelated changes.

**Comment by karmicdice** [comment]
Ya, I will rebase it.

**Comment by othercorey** [comment]
You can rebase the same branch and force-push here.

**Comment by LordSimal** [comment]
@karmicdice it would be nice if you could add a testcase showcasing that your added method works as expected.
Also please refer to https://github.com/cakephp/cakephp/blob/4.x/.github/CONTRIBUTING.md#test-cases-codesniffer-and-static-analysis regarding the code style we use and how to check (and automatically fix) that with the tools provided.

**Comment by LordSimal** [comment]
@karmicdice do you know what to do to clean this PR up? 
Most of these commits shouldn't be here, only what you have adjusted.
What you did in [your PR](https://github.com/karmicdice/cakephp/pull/1) is rebase onto 4.x but you actually needed 4.next since this PR should go into 4.next, not 4.x

**Comment by karmicdice** [comment]
@LordSimal Oh yes, I did it in 4.x instead. Close this PR. I will open another one and send it on 4.next

**Pull request closed without merging**
