### PR TITLE
StaticConfigTrait::getConfig($key) return type

### PR DESCRIPTION
**Pull request by andrii-pukhalevych**
StaticConfigTrait::getConfig($key) may return int/string/float with custom configs

### CODE REVIEW

**Comment by andrii-pukhalevych** [comment]
@dereuromark 
> `mixed` covers all types so it should be the only type mentioned now.

Should I leave only `mixed` or `mixed|null`. I see that in some places @return has all types:
[`EventInterface::getData($key = null)`](https://github.com/cakephp/cakephp/blob/8005880409fce6afebd03053a6060cfd8a3c91d1/src/Event/EventInterface.php#L79) has `@return array|mixed|null`

**Comment by andrii-pukhalevych** [comment]
@dereuromark Is cakephp:3.next correct branch?

**Comment by dereuromark** [comment]
For fixes in docs, usually master is correct.

**Comment by andrii-pukhalevych** [comment]
@dereuromark In this case I want to have this update asap, because its not breaking but affects code analyzer functionality.  At 3.next is 3.9 right? 

Also AppVeyor [failed to run test](https://ci.appveyor.com/project/cakephp/cakephp/builds/26209564#L196):  "./composer.lock" does not contain valid JSON                           
How it can be resolved?

**Comment by dereuromark** [comment]
:-1: I dont think this should have been merged. Not valid as is.

**Comment by markstory** [comment]
Whoops, I'll revert this merge I didn't see that it pulled in other changes from 3.next along with it.

**Comment by markstory** [comment]
Whoops, I'll revert this merge I didn't see that it pulled in other changes from 3.next along with it.

**Pull request merged**
