### PR TITLE
Default value for View::$template

### PR DESCRIPTION
**Pull request by andrii-pukhalevych**
Default value for 'View::$template = ''' is needed to because `View::getTemplate(): string` does not expect to return null
After this PR template will behave the same way as templatePath

### CODE REVIEW

**Comment by dereuromark** [comment]
The test case needs to also change

The alternative could be to allow null (change docblock) and cast this on getting.
Not sure what is better, though.

**Comment by andrii-pukhalevych** [comment]
I'm also not sure, so just did similar to `View::templatePath`.

Regarding test - please help me here, because tests for `View::template` and `View::templatePath`also should be similar.

**Comment by dereuromark** [comment]
If this breaks anything, shouldnt this go to master instead?
Or is this fine to be then for 4.3?

**Comment by markstory** [comment]
I think this change is fine, but why is the template property not being set?

**Comment by othercorey** [comment]
@andrii-pukhalevych Can you follow up on this?

**Comment by andrii-pukhalevych** [comment]
Not sure what more is needed from me

**Pull request merged**
