### PR TITLE
implemented Router::reverseToArray()

### PR DESCRIPTION
**Pull request by bancer**
Resolves https://github.com/cakephp/cakephp/issues/10092

### CODE REVIEW

**Comment by dereuromark** [comment]
You need to use the CakePHP coding standards here.

**Comment by dereuromark** [comment]
If we implement this, we first need to implement this for 3.x IMO, and then backport this to 2.x afterwards.
New features for 2.x only are not something that is actively done anymore these days I think.

**Comment by thinkingmedia** [comment]
Closing as this API is already implemented in `2.x` and also `3.x`.

https://api.cakephp.org/2.9/class-Router.html#_parse

https://api.cakephp.org/3.4/class-Cake.Routing.Router.html#_parse

Routing is a complex process that depends upon context. You can't simply assume a string URL resolves to a specific route. Cake allows for multiple routes from the same URL but with different HTTP methods (GET, POST, PATCH, DELETE, OPTIONS).

If you have a problem where you need to reverse a URL string to a route, then you most like have two problems. Solve the other one first and both are fixed.

**Comment by bancer** [comment]
@thinkingmedia It seems you misunderstood the issue and the changes. reverseToArray() method extracts the URL from CakeRequest, not from a string. _parse() is absolutely unrelated to that.

**Comment by dereuromark** [comment]
I agree, this is merely about handling the URL as array - and the wish to continue to handle it as array as far as I understood. Maybe the method name suggested here is a bit misleading.

**Comment by thinkingmedia** [comment]
@bancer @dereuromark sorry guys. I've re-open it.

**Comment by saeideng** [comment]
I Thing we neet imlement it first for v3.x

**Pull request merged**
