### PR TITLE
Display sorted command list

### PR DESCRIPTION
**Pull request by rchavik**
Better UX

### CODE REVIEW

**Comment by ADmad** [comment]
phpstan is unhappy https://travis-ci.org/cakephp/cakephp/jobs/276148218#L836

**Comment by rchavik** [comment]
What is it talking about?

**Comment by ADmad** [comment]
Problem is due to line 76 `$this->commands = $this->getCommands();`.  `getCommands()` returns an array and you can use `getIterator()` on an array. So the code needs to account for the fact that `$this->commands` can be an array or `\Cake\Console\CommandCollection` instance. Also the typehint of `$commands` property needs to be updated.

**Comment by ADmad** [comment]
Also there is currently no test coverage for line `76` or the `getCommands()` method.

**Comment by rchavik** [comment]
how about now, phpstan seems happy.

**Pull request merged**
