### PR TITLE
HTML5 meta charset

### PR DESCRIPTION
**Pull request by afilina**
Address issue #8111

### CODE REVIEW

**Comment by josegonzalez** [comment]
Also, you can just keep pushing onto this PR and [git squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) when you think everything is ready.

@ADmad Is our custom to squash everything into a single commit? I didn't in #4861...

**Comment by afilina** [comment]
Wow, you guys are really helpful. I'm now looking forward to committing some more!

**Comment by afilina** [comment]
Hm, not sure how my commit decreased coverage. Perhaps it's unrelated. Let me know if there's something else I need to do.

**Comment by dereuromark** [comment]
:+1:

**Comment by ADmad** [comment]
@afilina Ignore coveralls, it's drunk most of the times.

@josegonzalez I personally recommend squashing commits for trivial/small changes. Of course it's not necessary bug fixes / feature additions which require significant changes. Meaningful commit history makes tracking down an issue easier in future.

**Comment by ADmad** [comment]
Thanks @afilina. Looking forward to more PRs :smile:

**Pull request merged**
