### PR TITLE
Add 'locale' option to Hash::sort

### LINKED ISSUE #9190: Hash::sort() function doesnt accept SORT_LOCALE_STRING
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.7.7
* Platform and Target: Windows 7, Apache, MySQL

### What you did
Hash::sort() doesn't allow for type SORT_LOCALE_STRING

### PR DESCRIPTION
**Pull request by hytromo**
In an attempt to resolve #9190 

Now Hash::sort can accept the 'locale' type, resulting in sorting based on the current locale (set via setlocale).

The corresponding test uses the 'de_DE.utf8' locale which has to be installed in the system running the tests.

### CODE REVIEW

**Comment by markstory** [comment]
Can you fix up the indentation?

**Comment by hakermania** [comment]
Hey mark, yes I can fix it.

I will commit the fix and push it to my fork. Then how can I update this pull with the new commit? (sorry new to this)

**Comment by saeideng** [comment]
When you pushed in your branch on your  repo
this PR will update automatic

**Comment by markstory** [comment]
Note to myself: This feature will need to be ported to 3.x as well.

**Comment by saeideng** [comment]
3.next?

**Comment by markstory** [comment]
@saeideng Yes.

**Comment by dereuromark** [comment]
Could also be 3.current as this is fully BC (like it is with merging now into 2.current).

**Comment by markstory** [comment]
@dereuromark Good point.

**Comment by markstory** [comment]
I'm a tool, this pull request was for `master` all along, not `2.x` :blush:

**Comment by sphereweb83** [comment]
Will this be available in 2.X?

**Comment by markstory** [comment]
@sphereweb83 Not unless someone makes a pull request for 2.x

**Comment by sphereweb83** [comment]
We are using a 2.X CakePHP installation. I submitted this bug (#9190) couple months ago and i think this fix was triggered by this bug. I am not familiar with Guthub, would someone be kind and make a pull request for 2.x? Greatly appreciated.

**Comment by dereuromark** [comment]
Sure I can do that.

**Comment by sphereweb83** [comment]
Great thank you very much, after this pull request what is the procedure it will be integrated into the next release of Cake 2.x?

**Comment by dereuromark** [comment]
Yes, the next 2.x release.

**Comment by markstory** [comment]
@sphereweb83 It will likely go into 2.8.7

**Comment by sphereweb83** [comment]
Excellent, greatly appreciated!

**Pull request merged**
