### PR TITLE
fix(gitignore): Ignore .log files

### PR DESCRIPTION
**Pull request by fxleblanc**

### CODE REVIEW

**Comment by ADmad** [comment]
Why is ignoring `*.log` in core repo necessary?

**Comment by fxleblanc** [comment]
phpunit generated debug.log and error.log files. Do we need to track those files?

**Comment by ADmad** [comment]
No we don't. But testsuite should cleanup after itself.

**Comment by dereuromark** [comment]
Or just write to a ignored tmp/logs file.

**Comment by ADmad** [comment]
IIRC the test suite bootstrap uses [system's temp folder](https://github.com/cakephp/cakephp/blob/master/tests/bootstrap.php#L33) for tmp and log files. So this shouldn't be an issue.

**Comment by dereuromark** [comment]
I have also seen this before, maybe it is system dependent. How can we reproduce this? What exactly led to those files in the core?

**Comment by Marlinc** [comment]
I've had the same issue on Ubuntu.

**Comment by fxleblanc** [comment]
According to sys_get_temp_dir(), mine is /tmp. Even with 777 permissions, it still creates debug and error.log files.

**Comment by AD7six** [comment]
Updating the `.gitignore` file is not the right solution.

> I've had the same issue on Ubuntu.

I doubt that is OS is relevant.

If you make the log file not-writable (i.e. using `chmod`) - the error message when something attempts to write to it will indicate why that's happening - as may the contents of those log files.

**Comment by fxleblanc** [comment]
@AD7six you're right, we could close it, I'll try to figure this out on my own copy.

**Pull request closed without merging**
