### PR TITLE
Remove unneeded "use" statements.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by dereuromark** [comment]
What sniff did you run?

**Comment by ADmad** [comment]
https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/Namespaces/UnusedUsesSniff.php  :)

**Comment by dereuromark** [comment]
Ah, I thought maybe https://github.com/spryker/code-sniffer/blob/master/Spryker/Sniffs/Namespaces/UnusedUseStatementSniff.php
If that one is working fine - and maybe even better than my linked one - then maybe we can port it into the core?

**Comment by ADmad** [comment]
Would be great if you could port it to CakePHP standard.

**Pull request merged**
