### PR TITLE
Fixed HTTP Status code when ajaxLogin is set

### PR DESCRIPTION
**Pull request by davidsteinsland**
See #2773

### CODE REVIEW

**Comment by kp2356** [comment]
Documentation is incorrect then!!
http://book.cakephp.org/2.0/en/core-libraries/components/authentication.html#handling-unauthenticated-requests
image

If user is requesting any content with **Accept:text/html, */*; q=0.01** * and doesnt have *.json* in extension, then, I just want the user to see a login form. 

As mentioned in the discussion above the if the client is expecting a JSON response, then the request type would be JSON based or with an *.json* extension, then you can set a 403 response.

Or else then what is the use of it. Like in my requirement, I am using bootstrap modals, loading ajax content in it.

**Comment by davidsteinsland** [comment]
I'm not sure if I understand, but consider this example:

```js
$.ajax({
  statusCode: {
    403: function(data) {
      if (ajaxLoginBoxActive) {
        console.log('Ajax login box is already active');
        return;
      }

      ajaxLoginBoxActive = 1;

      // response contains the login form
      console.log('Displaying login box');
      $('body').append(data.responseText);
      
      // show the login form as a jquery dialog
      $('div#login-dialog').dialog({
        modal: true,
        width: 400
      });
    }
  },
  url: "/some/resource",
  success: function(data) {
    // handle OK response
  },
  complete: function(xhrStatus) {
    if (xhrStatus.status == 200) {
      // remove login box if user logged in again
      if (ajaxLoginBoxActive) {
        removeLoginBox();
      }
    }
  }
});
```

**Comment by kp2356** [comment]
@davidsteinsland thanks for the example code. :+1:

**Comment by cjbars** [comment]
Colleagues.
If I can view the resource after login, the service must return 401 code.
If I can not browse the resource ever, the service must return 403 code.

For example, I can view their profile after login, but can not manage service account holders even after authorization. I think this is perfectly normal and correct cases. Why now can not be set out different codes and code 403 incorporated by default?

**Pull request merged**
