### PR TITLE
HTML5 meta charset

### PR DESCRIPTION
**Pull request by afilina**
Fix issue #8111

### CODE REVIEW

**Comment by ADmad** [comment]
Why do you keep closing the PRs? :)

**Comment by afilina** [comment]
Because I keep screwing it up. The next one will be good.

**Comment by josegonzalez** [comment]
You can `git commit --amend` and force push onto your branch :)

**Comment by afilina** [comment]
I haven't opened a PR in like forever :) Thanks for the tip.

**Pull request closed without merging**
