### PR TITLE
Remove antipattern

### PR DESCRIPTION
**Pull request by davidyell**
I really don't like code which hides it's api from developers. The source code should describe itself through it's api.

### CODE REVIEW

**Comment by dereuromark** [comment]
I think this should be addressed properly, by splitting it into getter and setter instead.
This change is not BC because of the argument modification, and also just continues to be an anti pattern.

**Comment by markstory** [comment]
How would one set `null` with this change?

**Comment by dereuromark** [comment]
Isn't this change already addressed in 3.4 pretty much?

**Comment by markstory** [comment]
@dereuromark Yes, as there are split methods.

**Comment by ADmad** [comment]
Given that the method is already split in next minor release and this one is deprecated, don't see the need to change its signature. Hence closing.

**Comment by davidyell** [comment]
Glad it's been tackled already.

**Pull request closed without merging**
