### PR TITLE
Remove default overwrites that are useless

### PR DESCRIPTION
**Pull request by dereuromark**

### CODE REVIEW

**Comment by lorenzo** [comment]
It would funny if the reason it is the way it is today, because someone overrode the `redirect()` in their controller and complained in a ticket about Auth not redirecting correctly

**Comment by dereuromark** [comment]
That is not the frameworks fault if someone does something stupid like that :) especially in 2.x where this default value cannot be changed without serious consequences.

**Comment by markstory** [comment]
I went through the history to when all the code was accidentally deleted in 2008 and couldn't find the bugfix that re-introduced this. Perhaps that was another line?

**Comment by dereuromark** [comment]
I think it was more meant as a *possibility*, even though very unlikely.

**Pull request merged**
