### PR TITLE
error gives message about config name instead of class name

### PR DESCRIPTION
**Pull request by Graziel**

### CODE REVIEW

**Comment by ADmad** [comment]
A test would be nice.

**Comment by Graziel** [comment]
there is `trigger_error` inside `$email->transport` is it ok to suppress error in tests? ie
```
        $email = new Email();
        @$email->transport('badClassName');
```

**Comment by ADmad** [comment]
The `trigger_error()` in [Email::transport()](https://github.com/cakephp/cakephp/blob/master/src/Mailer/Email.php#L1006) is below the line you have modified in this patch which throws and exception. So if an exception is thrown that line would be never reached. You can use the `@expectException` and `@exceptExceptionMessage` annotation in your test methods docblock to check that expected exception and message is thrown.

**Comment by Graziel** [comment]
@ADmad the conditions to make test work are:
1) you need to be in production mode / suppress error (trigger_error is before the modified line)
2) the class user gave should not exist

if i do the test without suppressing error other way to make it throw that exception (reach the line of code https://github.com/cakephp/cakephp/blob/master/src/Mailer/Email.php#L1013) is to make test go temporary into produciton mode where body of trigger_body is empty

i already have working test im just asking if what im doing is ok or there is better solution to that
```
/**
     * Tests not found transport class name exception
     *
     * @return void
     *
     * @expectedException \InvalidArgumentException
     * @expectedExceptionMessage Transport class "TestFalse" not found.
     */
    public function testClassNameException()
    {
        $email = new Email();
        @$email->transport('badClassName');
    }
```

**Comment by ADmad** [comment]
The `trigger_error()` needs to be wrapped in a `if (!$className) {..}` check.

**Comment by Graziel** [comment]
ok thanks for tip @ADmad

**Comment by ADmad** [comment]
LGTM now.

**Pull request merged**
