### PR TITLE
More subpackages validation.

### PR DESCRIPTION
**Pull request by dereuromark**
Follow https://github.com/cakephp/cakephp/pull/17412

It shows some of the impossible dependencies in the Http package:
I ignored the noise files for now.

Also shows that Datasource is a bit dirty (circular dep towards Database):
```
 ------ --------------------------------------------------------------------- 
  Line   ConnectionManager.php                                                
 ------ --------------------------------------------------------------------- 
  58     Class Cake\Database\Driver\Mysql not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  59     Class Cake\Database\Driver\Postgres not found.                       
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  60     Class Cake\Database\Driver\Sqlite not found.                         
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  61     Class Cake\Database\Driver\Sqlserver not found.                      
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  126    Class Cake\Database\Connection not found.                            
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ --------------------------------------------------------------------- 
```

### CODE REVIEW

**Comment by ADmad** [comment]
The Http Client can(/could) be used standalone. So the only issue would be any error class it uses which extends CakeError. We could probably revert those to extending RuntimeException.

**Comment by dereuromark** [comment]
How do you explain all the Cake\Routing classes missing? How are they there in split usage?

**Comment by ADmad** [comment]
The package is a bit messy/broken currently. Anything besides the Http Client is unusable standalone. We need to look into either making Routing a standalone package or separating http client.

**Comment by ADmad** [comment]
Looking into this, with a couple of `class_exists()` checks the HTTP server should also work standalone without the Router. One would have to use their own routing mechanism :slightly_smiling_face:.

**Comment by dereuromark** [comment]
Is this ready to move forward?

**Comment by dereuromark** [comment]
I rebased now.

**Comment by dereuromark** [comment]
@markstory CI is now green, after last rebase.

**Pull request merged**
