### PR TITLE
Fix entity class for irregular table names

### PR DESCRIPTION
**Pull request by segy**
see #12254

### CODE REVIEW

**Comment by dereuromark** [comment]
Can you provide some example cases as well?
Either in tests or just explaining them here in text form?

**Comment by segy** [comment]
Hi. I mentioned that in the issue - good example is table class `CustomCookies`. This case (word cookie) is handled in `Inflector`, but `getEntityClass` uses `singularize` method, which doesn't take this into account. So it expects entity class `CustomCooky`.

**Review by markstory — COMMENTED** [review]
Does bake need any changes? Is there different inflection being done there?

**Comment by segy** [comment]
It uses `ConventionsTrait::_entityName` to create the class name (from table alias), so probably this method should be also modified.

**Comment by markstory** [comment]
ConventionsTrait is bake only thing. We can't use it in the orm.

**Comment by dereuromark** [comment]
What should we do here?

**Comment by markstory** [comment]
I think it would be ideal to add a test covering the expected changes in inflection. Right now it could be 'optimized' away.

**Pull request merged**
