### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by predominant**
Inclusion of a code of conduct for the main repo.

### CODE REVIEW

**Comment by ADmad** [comment]
We already have a COC [here](https://github.com/cakephp/code-of-conduct/blob/master/CODE_OF_CONDUCT.md) whose text was agreed upon after considerable discussion. So just linking it in readme should suffice.

**Comment by predominant** [comment]
Sure, this was mostly to make it pass the code checks here on Github.

**Comment by dereuromark** [comment]
I wouldnt wry about the GitHub checks, they are more meant as help for beginners IMO.

**Comment by predominant** [comment]
Closing as stupid idea.

**Comment by markstory** [comment]
@ADmad Couldn't the in repo file point to cakephp/code-of-conduct? I think having the conventional file has some value as it makes it easier for folks to find the policy.

**Comment by ADmad** [comment]
It sure could.

**Pull request closed without merging**
