### PR TITLE
Quote column identifier for column names containing utf-8 chars (ä)

### PR DESCRIPTION
**Pull request by benjaminpick**
Ref #12452

This simple query works now with my schema:

```php
TableRegistry::getTableLocator()->get('Tablename')->find()->first();
```
I will test some more with conditions etc.

### CODE REVIEW

**Comment by benjaminpick** [comment]
How the u modifier works:

https://maxivak.com/working-with-regular-expressions-preg_-and-utf-8-strings-in-php/

If PCRE is compiled with Unicode property support, and the PCRE_UCP option is set (by the u modifier):
\w will match any character that \p{L} (Unicode letters) or \p{N} (Unicode numbers) matches, plus underscore

**Comment by markstory** [comment]
Thank you 👍

**Comment by benjaminpick** [comment]
Can someone check it for performance implications, please?

-- 
Theologie zum Anfassen: https://benjaminpick.com

**Comment by benjaminpick** [comment]
I agree but using the u modifier might decrease performance for all who
use quoteIdentifier-escaping. In the same way as the current
implementation first checks the standard cases, then the weird cases, we
could also add the u modifier only for "extra" cases.

**Comment by markstory** [comment]
@benjaminpick We're OK with that. Identifier quoting already adds significant overhead to the ORM that a bit more is just part of that cost now.

**Comment by benjaminpick** [comment]
Ok, I think I was just surprised that it got merged so quickly!
Thanks ...

**Comment by dereuromark** [comment]
I don't know.. Quoting I find totally acceptable, but using non ascii chars for table and field names is a total nogo for me.

**Comment by benjaminpick** [comment]
I also find it very "creative" (in a bad sense) ... It is an ancient
Access database migrated to SQL Server and so on. The primary keys are
called differently in each table etc. ...

**Pull request merged**
