### PR TITLE
Add back $name and __construct() to Type classes.

### PR DESCRIPTION
**Pull request by ADmad**
Refs https://github.com/cakephp/cakephp/pull/9885/files#r93180545

### CODE REVIEW

**Comment by dereuromark** [comment]
I am :-1: on this.
We never do theoretics. We either do something, or we dont.
We can easily do this for 4.0

In this case keeping this for 3.x code does not help anyone.
Even if we removed it some day, it would need all extending classes or custom classes to be adjusted.
And on top it would need an interface then.
So it would still not be BC, thus the value of having this around now is 0. Or am I missing something?

**Comment by markstory** [comment]
@dereuromark We did do something, which was try to prepare the code so we can not need inheritance in the future.

**Comment by dereuromark** [comment]
But how does that work?
Any custom class would still break - so what is to gain at this point?
Why not directly removing the inheritance now then?

**Comment by markstory** [comment]
>  Any custom class would still break - so what is to gain at this point?

We have less work to do when its time to make the breaking change.

>  Why not directly removing the inheritance now then?

I don't think we can as `instanceof` checks will break. We didn't originally have an interface, and are stuck with that mistake for a while.

**Comment by dereuromark** [comment]
The work itself is minimal, I would gladly do it once it is worth doing IMO.

**Comment by dereuromark** [comment]
And speaking of interface. Just because the Interface is now there doesn't mean we have to remove the base class.
Since most the Type extending classes share actually the name setter, why not just keeping the Type base class (and its constructor)?
As abstract one this sure seems to be make sense for DRY code, does it not?
Most of the classes, as the code diff shows then can stay simple and don't need to have any constructor anyway. Sounds cleaner to me the way it currently is.

**Comment by markstory** [comment]
But the various type classes will get a constructor in the next version when the inheritance from Type  is removed, putting this exact code back in.

**Comment by dereuromark** [comment]
Yeah I wonder why removing the Type class inheritance if all those are sharing the same constructor.
Maybe there is no need to change anything here. Abstract Type inheritance + Interface. Both seems to be fine.

**Comment by markstory** [comment]
>  ... I wonder why removing the Type class inheritance if all those are sharing the same constructor.

The motivation was to separate the Type instances and static methods declared on `Type` I don't think a common 1 line constructor justifies an abstract class personally.

**Comment by ADmad** [comment]
The discussion to remove inheritance of the type class from `Type` has already been had before and that's why the constructors were added. Nothing has changed to warrant hashing over it again or reverting that decision.

Merging as I too along with @markstory and @lorenzo support this change.

**Comment by dereuromark** [comment]
This now introduces those warnings again by the way for phpstan:

 ```
Line   src/Database/Type/BinaryType.php
 ------ -------------------------------------------------------------------
  49     Cake\Database\Type\BinaryType::__construct() does not call parent
         constructor from Cake\Database\Type.
 ------ -------------------------------------------------------------------

 ------ -----------------------------------------------------------------
  Line   src/Database/Type/BoolType.php
 ------ -----------------------------------------------------------------
  48     Cake\Database\Type\BoolType::__construct() does not call parent
         constructor from Cake\Database\Type.
 ------ -----------------------------------------------------------------

 ------ ---------------------------------------------------------------------
  Line   src/Database/Type/DateTimeType.php
 ------ ---------------------------------------------------------------------
  93     Cake\Database\Type\DateTimeType::__construct() does not call parent
         constructor from Cake\Database\Type.
 ------ ---------------------------------------------------------------------

 ------ --------------------------------------------------------------------
  Line   src/Database/Type/DecimalType.php
 ------ --------------------------------------------------------------------
  49     Cake\Database\Type\DecimalType::__construct() does not call parent
         constructor from Cake\Database\Type.
 ------ --------------------------------------------------------------------

 ------ ------------------------------------------------------------------
  Line   src/Database/Type/FloatType.php
 ------ ------------------------------------------------------------------
  48     Cake\Database\Type\FloatType::__construct() does not call parent
         constructor from Cake\Database\Type.
 ------ ------------------------------------------------------------------

 ------ --------------------------------------------------------------------
  Line   src/Database/Type/IntegerType.php
 ------ --------------------------------------------------------------------
  48     Cake\Database\Type\IntegerType::__construct() does not call parent
         constructor from Cake\Database\Type.
 ------ --------------------------------------------------------------------

 ------ -----------------------------------------------------------------
  Line   src/Database/Type/JsonType.php
 ------ -----------------------------------------------------------------
  48     Cake\Database\Type\JsonType::__construct() does not call parent
         constructor from Cake\Database\Type.
 ------ -----------------------------------------------------------------
```

This will most likely prevent us from including phpstan as part of the tooling in the near future then, as when all other issues are resolved those above will permanently stay for 3.x as it stands.

**Comment by markstory** [comment]
Is there no way to mark those lines/files/sniffs to be ignored?

**Comment by ADmad** [comment]
@markstory Yes there is.

**Comment by ADmad** [comment]
> This will most likely prevent us from including phpstan as part of the tooling in the near future then..

No it doesn't, you can use a yaml config file for phpstan to set ignores, check it's readme.

**Comment by ondrejmirtes** [comment]
I don't think these changes make sense. There's already protected `$_name` in the parent class and it's always better to call parent constructor (because of encapsulation) instead of setting the property myself. That's why the requirement of calling parent constructor is in PHPStan's basic checks.

For example in Java you have to call parent constructor or otherwise your code doesn't compile.

**Comment by ADmad** [comment]
@ondrejmirtes The inheritance from `Type` parent class is going to be removed in future so we are planning ahead and want to promote the each type class having it's own constructor.

Check for whether `parent::_construct()` is called is fine as a default but there can be cases where it's not required. What Java requires hardly matters, this is PHP :)

**Pull request merged**
