### PR TITLE
4.x Added getRequiredMessage to ContextInterface

### PR DESCRIPTION
**Pull request by jeremyharris**
resf: https://github.com/cakephp/cakephp/issues/12094

### CODE REVIEW

**Comment by dereuromark** [comment]
Test fails seem unrelated - maybe merge master into it again?
Looks good so far.

**Comment by saeideng** [comment]
your branch is not update

**Comment by saeideng** [comment]
`hasRendered` protected here https://github.com/cakephp/cakephp/pull/12179

**Comment by jeremyharris** [comment]
Last 4.x build is failing, that's why. Same problem with https://github.com/cakephp/cakephp/pull/12216 which I rebased today. Check the last 4.x merge, it was a failed build.

**Comment by saeideng** [comment]
see my new PR https://github.com/cakephp/cakephp/pull/12221

**Pull request merged**
