### PR TITLE
Use ellipsis character instead of three dots

### PR DESCRIPTION
**Pull request by forstjiri**
It is not sematically correct to use three dots indicating more content. 
Also as pointed out, three dots can be broken into two lines without additional markup.
#9279

### CODE REVIEW

**Comment by aiphee** [comment]
I gues this PR should be in the .next   branch right?

**Comment by dereuromark** [comment]
That would be safer for those that have tests checking on the "old way" or behavior expecting the former characters.

**Comment by aiphee** [comment]
I will close this and create new, i also should have created new branch in my repository.

**Comment by dereuromark** [comment]
Github now supports rebranching :)

**Comment by ADmad** [comment]
The PR is not mergeable. You will have to rebase your changes on top of 3.next branch.

**Comment by aiphee** [comment]
OK, now i completely broke the PR, i guess i should get to know git better.

**Pull request closed without merging**
