### PR TITLE
Allow cookies to contain square brackets

### PR DESCRIPTION
**Pull request by markstory**
Allow square brackets in cookie names. This allows 3.x cookies to be more compatible with 2.x data.

Refs #6172

### CODE REVIEW

**Comment by patrickconroy** [comment]
I just tried this, and while the Cookie read/write works the way the test is written, it doesn't seem to work after refreshing.

```
$this->Cookie->write('test[ing]', 'hey!');
$value = $this->Cookie->read('test[ing]');
var_dump($value); # 'hey'
```

Then after a refresh..
```
$value = $this->Cookie->read('test[ing]');
var_dump($value); # NULL
```

Even though that cookie is available, non-expired, and has a value. I think it's because the cookie is actually set as an array in php (once the response finishes and does a real set-cookie, so reading it back does this, and that's not compatible with `Cookie->read($string)`.
```
pr($_COOKIE);
Array
(
    [test] => Array
        (
            [ing] => hey
        )

)
```
I wouldn't care so much but there's a business need to have cookies set from the old app be retained in the new app. It's possible I can see about phasing out the array-style in the current app and just doing a string in both places (so when we roll out it'll just work).

**Comment by markstory** [comment]
Good catch. I can take another more thorough stab at this.

**Comment by markstory** [comment]
Are your cookies encrypted with cipher, rijndael, or AES? 3.0 only supports aes, so you'd need to use AES or unencrypted cookies to get compatibility across versions.

I tried setting plain text cookies in 2.x and reading them in 3.x, and it worked fine. I did run into issues where existing cookies from 2.x in the form of `CakeCookie[thing]=value` overwrote cookies written in 3.x, which are in the form of `CakeCookie=...`. PHP seems to prefer array based cookie values when there are both string and array values sharing a top level cookie name. This prevents the data written in 3.0 from being visible in future requests in either version.

I don't have a good idea on how to solve this issue as we had a bunch of issues with array cookies, where you couldn't mix access modes with predictable results.

**Comment by markstory** [comment]
One possible solution would be to write the first dimension of each array. Instead of `CakeCookie={"name":"value"}` the 3.x component could write `CakeCookie[name]=value`. Nested array structures would still end up as serialized blobs. The downside to this is that with encrypted cookies, the top level names are exposed in plain text.

**Comment by patrickconroy** [comment]
Thanks @markstory, the cookie is encrypted with aes. I don't know if the unencrypted workaround is secure enough for most people.. I think I might just go with a custom read/write for now and then migrate old stuff to the new style.

**Comment by markstory** [comment]
You should be able to share simple AES values between 2.x and 3.x, but we'll still have issues with the top level keys causing cross version issues.

**Comment by markstory** [comment]
Closing this as I don't think this actually solves the issue, and I'm not sure of the impact that leaving top level keys unencrypted may have.

**Pull request closed without merging**
