### PR TITLE
Added TableSchema::TYPE_CHAR to replace fixed-length strings

### PR DESCRIPTION
**Pull request by karmicdice**
Ref : https://github.com/cakephp/migrations/issues/362

### CODE REVIEW

**Review by othercorey — COMMENTED** [review]
The string types in testDescribeTable() in sqlserverschematest.php don't need `fixed => null`.  This is causing SqlServer unit test to fail.

**Comment by karmicdice** [comment]
> The string types in testDescribeTable() in sqlserverschematest.php don't need `fixed => null`. This is causing SqlServer unit test to fail.

Yea. Thanks mate..
Noticed it. AppVeyor failed there.

**Comment by markstory** [comment]
Looks good to me :+1:

**Review by othercorey — APPROVED** [review]
Looks good to me too.

**Review by ADmad — APPROVED** [review]

**Pull request merged**
