### PR TITLE
Add deprecations for 4.x API changes.

### PR DESCRIPTION
**Pull request by dereuromark**
Follow https://github.com/cakephp/cakephp/pull/13630 and other 4.x changes that are hard to spot in 3.x and will crash hard on upgrade.
Best to allow people to get up to date here inside 3.x to make the upgrade path easier (as in the diff between them smaller).

### CODE REVIEW

**Comment by dereuromark** [comment]
If we decide to move forward with this super useful and helpful deprecation info for smoother 4.x upgrade experience, I can adjust the tests here.

**Comment by markstory** [comment]
Ok. Once the tests are passing this will be good to merge in.

**Comment by ADmad** [comment]
@dereuromark Ping

**Comment by dereuromark** [comment]
I would be happy if someone can help out. Otherwise after my vacation.

**Comment by dereuromark** [comment]
@ADmad I backported some changes from your PR.

I wasn't sure about the Url/Html Helper deprecations and reverted those for now.
I am not sure how to proceed with them to keep things BC. The deprecation notices would probably stack up here.

**Pull request merged**
