### PR TITLE
Feature/3.0 get tree level

### PR DESCRIPTION
**Pull request by burzum**

### CODE REVIEW

**Comment by markstory** [comment]
Nice work :clap:

**Comment by lorenzo** [comment]
This makes `getLevel()`  the only method in the behavior not accepting an Entity as the argument. I think that should be addressed.

**Comment by dereuromark** [comment]
And some docs update for it incl. migration guide would be cool.

**Comment by markstory** [comment]
@lorenzo I can fix that up. Does accepting either an entity or a scalar ID sound reasonable?

**Comment by lorenzo** [comment]
yes, it does, @markstory

**Pull request merged**
