### PR TITLE
Issue 13303

### PR DESCRIPTION
**Pull request by trenshaw**
Fixes issue #13303 with ExtractTask not extracting those strings generated and passed to Gettext through core helpers.

### CODE REVIEW

**Comment by trenshaw** [comment]
Missed milestone for 2.10.19 please include for 2.10.20

**Comment by ADmad** [comment]
As already mentioned here https://github.com/cakephp/cakephp/issues/13303#issuecomment-497174772 we are no longer accepting feature enhancements for 2.x.

You are welcome to open a pull request for `3.next` instead.

**Comment by trenshaw** [comment]
Happy to put into 3.next but this defect / oversight / shortcoming has been in the I18NShell since the 2.x branch was created.

It should be back ported to 2.10.20 at least to ease in migration to 3.x. Migrating to 3.x is major enough without having to deal with missed / untranslated strings from the core helpers.

Many users likely added unnecessary 'label' and/or 'legend' options to every form element just to wrap the same string as the core helper would generate through __() or worse attempt to manually track core helper generated labels and add these one by one to their POTs.

**Comment by ADmad** [comment]
We have supported 2.x since October 2011 and have [clearly communicated](https://bakery.cakephp.org/2017/07/22/cakephp_2100_released.html) that it will receive only bug and security fixes from June 2017 going forward. 

We can't keep adding new features to 2.x and increase our maintenance overhead. We appreciate your participation in the CakePHP project, but as a small group of volunteers contributing their spare time for free there's only so much we can do, and at the moment we are focused on maintaining 3.x and moving towards 4.x.

You can publish your enhanced shell as a plugin and those upgrading from 2.x could use that. 

Once your enhancements are merged into 3.next you can also see if @dereuromark is interested in incorporating those changes in his [shim](https://github.com/dereuromark/cakephp-shim) which is meant to help those upgrading between major CakePHP versions.

**Pull request closed without merging**
