### PR TITLE
Fix type error.

### PR DESCRIPTION
**Pull request by ADmad**
Refs #16909

### CODE REVIEW

**Comment by othercorey** [comment]
Failure looks related. Does the paginator check for an existing key before adding a default sort?

**Comment by ADmad** [comment]
Failure is related. The paginator is unable to de-duplicate the columns in "order by" clause when the `order` config isn't in associative form. I am not sure how to deal with that.

**Comment by othercorey** [comment]
Can we "give up" if there is a numeric key and only use the user-provided sort?

**Comment by othercorey** [comment]
Maybe we just can't support these kinds of orders.

**Comment by ADmad** [comment]
Yup, so should be throw an exception in this case?

**Comment by othercorey** [comment]
Seems better than a php error or unexpected behavior.

**Review by othercorey — APPROVED** [review]

**Pull request merged**
