### PR TITLE
Implement RoutesShell

### PR DESCRIPTION
**Pull request by markstory**
Using the code @coryjthompson started as part of #4810, I've expanded the code a bit and finished off the tests for the feature. This adds 3 new commands:
- `cake routes` gets the list of routes connected.
- `cake routes check` parses a url string and gets routing parameters.
- `cake routes generate` Generates a URL from a set of key:value pairs.

### CODE REVIEW

**Comment by lorenzo** [comment]
How does the output look like?

**Comment by markstory** [comment]
@lorenzo It isn't "beautiful" but it is functional. I saw your comment on the previous issue about using CLImate, but I figured that could be a separate task.

CLImate might also make testing shell outputs more difficult as we'd need to provide ways to mock the output streams.

**Comment by markstory** [comment]
The output of the various commands looks like

```
$ bin/cake routes

Welcome to CakePHP v3.0.1 Console
---------------------------------------------------------------
App : src
Path: /Users/markstory/Sites/cakephp-app/src/
PHP : 5.4.38
---------------------------------------------------------------
Route name             URI template              Defaults
pages:display          /                         {"controller":"Pages","action":"display","0":"home","plugin":null}
pages:display          /pages/*                  {"controller":"Pages","action":"display","plugin":null}
_controller:index      /:controller              {"action":"index","plugin":null}
_controller:_action    /:controller/:action/*    {"action":"index","plugin":null}

:) 15:26:46 markstory:cakephp-app (master)
$ bin/cake routes generate controller:Articles action:view 2

Welcome to CakePHP v3.0.1 Console
---------------------------------------------------------------
App : src
Path: /Users/markstory/Sites/cakephp-app/src/
PHP : 5.4.38
---------------------------------------------------------------
> /articles/view/2
:) 15:27:00 markstory:cakephp-app (master)
$ bin/cake routes check /articles/view/2

Welcome to CakePHP v3.0.1 Console
---------------------------------------------------------------
App : src
Path: /Users/markstory/Sites/cakephp-app/src/
PHP : 5.4.38
---------------------------------------------------------------
Route name    URI template        Defaults
              /articles/view/2    {"controller":"Articles","action":"view","pass":["2"],"plugin":null}
```

**Comment by lorenzo** [comment]
I think I have the same issue as with the other PR. The feature is cool, but it looks kind of unfinished... Should we invest some time doing a table helper for the CLI?

**Comment by lorenzo** [comment]
I'm fine, with merging this, btw... I would just like to make it better afterwards. Tests are failing, though

**Comment by markstory** [comment]
@lorenzo I agree that is a bit rough visually. Do you think its worth trying to figure out how to integrate CLImate in a way that we can preserve the ease of testing and maintain the existing markup language, or use CLImate as inspiration for how we can do output formatting helpers?  I agree that having a few other 'ui primitives' like tables, progress bars, and padded lists would be helpful.

**Comment by Oxicode** [comment]
A mi también me encanta CLImate

**Comment by antograssiot** [comment]
I've been trying CLimate and my opinion is that the line separator add a lot of noise and it seems that it's not configurable. I'm don't think that it will be more readable than the actual proposal.

image

We could re-use also what @coryjthompson started [here](https://github.com/cakephp/cakephp/compare/master...coryjthompson:consoletable) that looks more like symphony table helper. I think it's nicer than CLImate. I can work on polishing this if you wan't.

**Comment by lorenzo** [comment]
@markstory @antograssiot  I think it is worth trying it, since it possibly means less work for us. The alternative is implementing those helpers on our own

**Comment by antograssiot** [comment]
@markstory @lorenzo Here is the result using symfony/console
image
The diff is [here](https://github.com/cakephp/cakephp/compare/feature-4810...antograssiot:feature-4810) and needs to be polish.
I think it definitely looks nicer but we need to find a way to test the output, didn't had time yet but I can give it a try later.

**Comment by markstory** [comment]
How many helpers are we really looking at reimplementing? I can see us providing table, progress bar, padded list. Integrating with symfony/console is an option but has the same issues around testing that climate would have. It is also a much larger library that duplicates a pile of existing functionality.

We could decide to integrate fully with climate and focus on improving any gaps around testing that exist with it. We would need to solve any backwards compatibility issues and possibly provide a 'simple table' formatter.

**Comment by lorenzo** [comment]
We sort of already require symfony/console in cake 3 (for migrations plugin). How bad would it be to have a direct dependency on that?

**Comment by antograssiot** [comment]
yeah exactly, using CLImate will add extra dependency and using our own helper means extrawork while symfony/console is already here. migrations as @lorenzo said but also Psysh rely on it for cake console.
Anyway I'm not against our own solution but I wonder how many user will really use these helper

**Comment by markstory** [comment]
I'll open an RFC issue with a proposal around a minimal set of 'ui helpers' for the console. Perhaps we'll start with just the table helper.

**Pull request merged**
