### PR TITLE
Set errors with array_replace instead of array_merge

### PR DESCRIPTION
**Pull request by tuna-rootnet**
PR for issue https://github.com/cakephp/cakephp/issues/12249.

This keeps the indexes for errors in addNestedMany() validation errors, instead of resetting them to start at 0.

### CODE REVIEW

**Comment by dereuromark** [comment]
I think we need some test cases here to show what the issue was and that it is fixed now.

**Comment by tuna-rootnet** [comment]
I'm not that experienced with tests yet, just realized my second commit still contains a @group to check only that test...

**Comment by saeideng** [comment]
why target of PR is `3.5` ?

**Comment by tuna-rootnet** [comment]
@saeideng Because I encountered it in 3.5.17, my project is not on 3.6.x yet.

Also, just realized array_replace will break setting multiple errors on one property. Not sure if this PR should be closed, array_replace is in hindsight not such a nice replacement (no pun intended) and I'm not sure what a proper fix would be.

**Comment by markstory** [comment]
Moved to master as 3.5 is only receiving security fixes as this point in time.

**Comment by markstory** [comment]
@tuna-rootnet Do you have a way to reproduce the problem your having? I could help with converting a small validator class into a test case.

**Comment by tunaflish** [comment]
@markstory Sure, see below.

Basic example how I ran into it:
```php
class SomeTable {
    public function doStuff()
    {
        $data = [
            'name' => 'something',
            'records' => [
                [
                    'foo' => 'This record will be fine',
                    'bar' => 'blah'
                ],
                [
                    'foo' => 'This one as well',
                    'bar' => 'blah'
                ],
                [
                    'foo' => 'This record will trigger an error'
                ]
            ]
        ];

        $entity = $this->newEntity($data);

        var_dump($entity->getErrors());
    }

    public function validationDefault(Validator $validator)
    {
        $validator->requirePresence('name');
        $validator->addNestedMany('records', $this->buildNestedValidator());

        return $validator;
    }

    private function buildNestedValidator()
    {
        $nestedValidator = new Validator();

        $nestedValidator->requirePresence('foo');
        $nestedValidator->requirePresence('bar');

        return $nestedValidator;
    }
}
```
Or, by feeding $entity->setError() the data which the validators produce:
```php
$entity = $someTable->newEntity(['name' => 'foo']);
$entity->setError('records', [
    2 => [
        'bar' => ['_required' => 'This field is required']
    ]
]);

var_dump($entity->getErrors());
```
Output of var_dump:
```
array(1) {
  ["records"]=>
  array(1) {
    [0]=> // This index should be 2, corresponding with the record which is invalid
    array(1) {
      ["bar"]=>
      array(1) {
        ["_required"]=>
        string(22) "This field is required"
      }
    }
  }
}
```

The index is actually correct right up to the moment array_merge is called in EntityTrait->setErrors. It's as the PHP manual states:
` Values in the input array with numeric keys will be renumbered with incrementing keys starting from zero in the result array. `

**Comment by markstory** [comment]
Thank you. I'll take a look and see if I can come up with something using what you've started.

**Comment by markstory** [comment]
I finished off the implementation in #12268

**Pull request closed without merging**
