### PR TITLE
refs #13767 don't set csrf cookie on redirect

### PR DESCRIPTION
**Pull request by steinkel**
Fix type issue on unauthenticated redirects trying to set the csrf cookie

### CODE REVIEW

**Comment by ADmad** [comment]
Test case please.

**Comment by steinkel** [comment]
Stan is not happy right now, do you recall any other place with a similar issue fixed?

**Comment by ADmad** [comment]
phpstan only understands `@var` annotations above variable assignment statements. Just add an ignore for that error.

**Comment by steinkel** [comment]
stan fixed, issue reported is not related with this PR

**Pull request merged**
