### PR TITLE
WIP - Template vars 

### PR DESCRIPTION
**Pull request by ADmad**
Refs #6759,  #6848.
### Todo
- [x] tests for button widget.
- [x] tests for checkbox widget.
- [x] tests for label widget.
- [x] tests for file widget.
- [x] tests for datetime widget.
- [x] tests for multi-checkbox widget.
- [x] tests for radio widget.
- [x] tests for select widget.
- [x] tests for textarea widget.

### CODE REVIEW

**Comment by markstory** [comment]
Looks great, the other widgets will need to be updated too.

**Comment by ADmad** [comment]
@markstory Yup I will over the weekend.

**Comment by ADmad** [comment]
I have updated all widgets but few tests are required for the multi input widgets. Wouldn't mind a hand with that :)

**Comment by markstory** [comment]
I can help get the remaining tests passing.

**Comment by ADmad** [comment]
@markstory Thanks, though the failing tests seem unrelated. Just new tests are required for widgets.

**Comment by markstory** [comment]
@ADmad I added a bunch of tests tonight, only a few more to go.

**Comment by ADmad** [comment]
@markstory Great, thanks.

**Comment by markstory** [comment]
Only DatetimeWidget left.

I've tweaked how the option based types work. They now merge the top-level templateVars into each input. This gives even more power to templateVars as the input set can have defaults that are augmented in each input array.

**Comment by ADmad** [comment]
> I've tweaked how the option based types work.

Nice. I had noticed that but skipped over it at that time as it required changing method params to pass extra argument.

**Comment by markstory** [comment]
@ADmad Finally all done.

**Comment by ADmad** [comment]
@markstory Awesome, thanks.

**Pull request merged**
