### PR TITLE
Rename Validation::notEmpty() to Validation::notBlank().

### PR DESCRIPTION
**Pull request by ADmad**
This avoids confusion for new users with Validator::notEmpty().

Refs #6284, #5856.

### CODE REVIEW

**Comment by markstory** [comment]
Does this method provide much value when we already have other ways to accomplish this with the validators?

**Comment by ADmad** [comment]
It's a convenience which some might find useful.  The ones that I would remove are:

- blank() : Personally can't think of a use case where you would want a field to be empty or just whitespace
- userDefined() :  You can directly set a callback as rule so no need for this

**Comment by markstory** [comment]
@ADmad Fair enough. I'm ok with marking those two methods as deprecated too if you want.

**Comment by dereuromark** [comment]
The docs also need updating @ http://book.cakephp.org/3.0/en/core-libraries/validation.html
And I think we should backport this to 2.7.

**Comment by ADmad** [comment]
> The docs also need updating @ http://book.cakephp.org/3.0/en/core-libraries/validation.html

Where do you see the need for updating?  All code examples havve call to `$validator->notEmpty()` which refers to `Validator::notEmpty()`,  not `Validation::notEmpty()`.  The isn't any e.g. which uses `notEmpty` as rule which would call `Validation::notEmpty()`.

**Comment by dereuromark** [comment]
Then I overlooked or vs ion :) All right then.

**Comment by dereuromark** [comment]
Careful, for some reason it throws exceptions after this change in some cases:

    "Trying to invoke non static method Cake\Validation\Validation::notEmpty() without an object"

It is just a dynamic rule addition

    $this->Countries->validator()->add('address', array(
 				'notEmpty' => array(
					'rule' => 'notEmpty',
 					'message' => 'valErrMandatoryField',
 					'last' => true
 				)))

It would probably be good if this would not throw the ReflectionException above.

**Comment by ADmad** [comment]
The reason is evident from the error message, I missed the `static` keyword for the method :)

**Comment by ADmad** [comment]
Fixed in [80bbb52]

**Comment by dereuromark** [comment]
It was late :trollface: 
:+1:

**Comment by dereuromark** [comment]
I suspect the bake plugin to also require changes (e.g. validation bake detection from notEmpty to notBlank).

**Pull request merged**
