### PR TITLE
Workaround for Cache::write() call from DboSource::__destruct()

### LINKED ISSUE #7559: Getting RedisException when using with Redis as Cache engine with persistent = false
Branch 2.8 (2.7.4-53-ga409a3d)

```
Uncaught exception 'RedisException' with message 'Connection closed' in $PROJECT/frontend/Vendor/cakephp/cakephp/lib/Cake/Cache/Engine/RedisEngine.php:126 
Stack trace: 
#0 $PROJECT/frontend/Vendor/cakephp/cakephp/lib/Cake/Cache/Engine/RedisEngine.php(126): Redis->setex('croogo_cake_cor...', 10, 'a:3:{i:0;b:0;s:...') 
#1 $PROJECT/frontend/Vendor/cakephp/cakephp/lib/Cake/Cache/Cache.php(317): RedisEngine->write('croogo_cake_cor...', Array, 10) 
#2 $PROJECT/frontend/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(3584): Cache::write('method_cache', Array, '_cake_core_') 
#3 [internal function]: DboSource->__destruct() 
#4 {main} thrown in $PROJECT/frontend/Vendor/cakephp/cakephp/lib/Cake/Cache/Engine/RedisEngine.php on line 126
```
Currently, I use the following dirty hack as a workaround:

```diff
commit 0f911c5e405e81f1c04caeb4c54a62b9ffb34b09
Author: Rachman Chavik <rchavik@xintesa.com>
Date:   Fri Oct 16 08:45:56 2015 +0700

    Workaround for Cache::write() call from DboSource::__destruct()

diff --git a/lib/Cake/Cache/Engine/RedisEngine.php b/lib/Cake/Cache/Engine/RedisEngine.php
index b8bdd4c..8dd98fb 100644
--- a/lib/Cake/Cache/Engine/RedisEngine.php
+++ b/lib/Cake/Cache/Engine/RedisEngine.php
@@ -113,6 +113,11 @@ class RedisEngine extends CacheEngine {
 		if (!is_int($value)) {
 			$value = serialize($value);
 		}
+
+		if (!$this->_Redis->isConnected()) {
+			$this->_connect();
+		}
+
 		if ($duration === 0) {
 			return $this->_Redis->set($key, $value);
 		}
```

### PR DESCRIPTION
**Pull request by rchavik**
Closes #7559

### CODE REVIEW

**Comment by ADmad** [comment]
Shouldn't this target 2.7?

**Comment by markstory** [comment]
Looks good.

**Comment by tersmitten** [comment]
Is this problem also present in other caching engines (e.g. Memcached)?

**Comment by markstory** [comment]
@tersmitten It very well could be.

**Pull request merged**
