### PR TITLE
fixes Error: Class 'PHP_CodeCoverage' not found error

### PR DESCRIPTION
**Pull request by bancer**
https://github.com/cakephp/cakephp/issues/11528

### CODE REVIEW

**Comment by bancer** [comment]
This fixes the error but the coverage is not visible:

screenshot from 2018-02-23 16 26 29

@markstory It looks like the problem is related to https://github.com/cakephp/cakephp/commit/d2c4bf2bb2eb4f4ff6c715d221f2e485e4f05112#diff-13c04ddad517ba05de14f47eccf17b51

The [similar](https://github.com/cakephp/cakephp/issues/11448) problem was solved [this](https://github.com/cakephp/cakephp/pull/11450/files) way. So I am not sure what else should be done.

**Comment by bancer** [comment]
Actually, `$report = $coverage->getData();` is empty :(

**Comment by markstory** [comment]
@bancer Is this still worth merging?

**Comment by bancer** [comment]
Yes, the error is still generated when coverage report is run in the browser:
`2018-07-13 09:33:10 Error: [Error] (Class 'PHP_CodeCoverage' not found) ()`

**Pull request merged**
