### PR TITLE
3.x Allow to specify 'method' and 'enctype' for FormHelper::create()

### PR DESCRIPTION
**Pull request by inoas**
Ref: https://github.com/cakephp/cakephp/issues/7977
@ADmad is this what you had in mind / considered sane?

### CODE REVIEW

**Comment by inoas** [comment]
Tests pass. If you think this is good, I will add tests for the new feature.

**Comment by markstory** [comment]
Looking good. We'll need a test covering the new options and the doc block for create() updated if possible.

**Comment by dereuromark** [comment]
create() method is way too long IMO (>> one screen even). It would be good if in a future PR we could extract some of the lines into seperate protected methods to make smaller logical chunks here.

**Comment by inoas** [comment]
@dereuromark I'd say we should have more like a builder interface than option strings. Maybe it could be done in one pass?

**Comment by dereuromark** [comment]
Nah, I think builder interface is even more out of scope of this change here :P

**Comment by inoas** [comment]
Still sounds like a builder interface to me, but not within the scope of this PR.

**Review by markstory — CHANGES_REQUESTED** [review]
Could we get tests for the new options?

**Comment by inoas** [comment]
Just moved to a new place, as soon as I find time I will work on all my PRs one by one and supply fixes/unit tests.

**Comment by inoas** [comment]
Thanks!

**Pull request merged**
