### PR TITLE
5.2: Start on cast API.

### PR DESCRIPTION
**Pull request by dereuromark**
Based on https://github.com/cakephp/cakephp/pull/17177 this would be a draft on a cast API
Also refs https://github.com/cakephp/cakephp/issues/9670#issuecomment-257066539 from 2016..^^

Cons
- not as native and fluent as request overloading: `$this->request->getQueryAsInt()`

Pros
- more flexible, can be used across the whole system where needed
- can be customized easily for project adaptation and special use cases

**WIP!**

We need to outline still the basic needs and functionality.
I for example would expect casting to be more lenient than asserts.
So if sth is bool, it should safely be able to convert to int via casts, same other way around.

The main idea is to provide more type-safety for external input, specifically request object.
Main goal is less inline annotations needed for such getters assigned to variables and further down the line.

This is NOT a validation/assert library. Those exist and can be used separately.

So
```php
$intOrNull = IntCast::tryFrom($this->getRequest()->getQuery('test')); //returns int or null
$int = IntCast::from($this->getRequest()->getQuery('test')); //returns int or throws exception
$stringOrNull = StringCast::tryFrom($this->getRequest()->getQuery('test')); //returns string or null
$string = StringCast::from($this->getRequest()->getQuery('test')); //returns string or throws exception
```

What do you think?
Should we add more test cases and asserts and see if it matches our expectations?

So far I added some tests for String cast.
Feel free to PR also more adjustments.

I also dont think we should keep $convertEmptyStringToNull etc
As the idea here is to get a certain type (e.g. string), not `...|null`.

Additional casts/scopes we could add:
- ScalarCast
- UuidCast
- AiidCast (or NaturalNumberCast)

Some validation constraints for this approach:
- Idempotence should be given. Cast `bool => int => string => int => bool` should yield the same output again for such convertable ranges, in this case bool idempotence (basically how also PHP always has worked).

### CODE REVIEW

**Comment by dereuromark** [comment]
I didnt know that https://github.com/cakephp/cakephp/blob/33626a03197758f30a8ce8c2e0a75ed8ddbce40a/src/Core/functions.php#L388-L536 already exist.
They do feel a bit more like sanitizing/assert, however.

I wonder if we can reuse them, or if we want to have a more lenient casting here applied as shown above.

**Comment by asgraf** [comment]
> I also dont think we should keep $convertEmptyStringToNull etc

StringCast::tryFrom() was created that way to prevent nullable VARCHAR fields to be filled with empty strings instead of nulls.
This also allows use ?? $ operator with empty strings
`StringCast::tryFrom($emptyString) ?? 'default'`
Also in StringCast::from() empty string will throw exceptions this way. This is desirable in many scenarios. You can make this option false by default but i would ask you to keep it because it is useful in so many scenarios

**Comment by asgraf** [comment]
min and max options in ints are used mainly like this:

```php
//in some muffin webservice related code
$limit = IntCast::tryFrom($this->getRequest()->getQuery('limit'), 1, 1000) ?? 100; 
```

**Comment by dereuromark** [comment]
But is it really string casting then, if you actually do string|null here based on the saving flow afterwards?
I can see your type useful, if you don't have a "single default" mapping in place in ORM.
I for example like to use https://github.com/dereuromark/cakephp-shim/blob/master/docs/Model/Nullable.md to cleanly avoid that for most of my apps. I find it kind of an anti pattern in most cases to have two "null" values, null and empty string. In 99% of the cases they would mean the same, but then are not together findable via classic lookup unless you do 
```php
['OR' => ['field IS' => null, 'field' => '']]
```
So I solve it on that level, and empty string is the null going in then becoming a real null on save, only having to use the first check to find empty ones.

**Comment by asgraf** [comment]
> So I solve it on that level, and empty string is the null going in then becoming a real null on save, only having to use the first check to find empty ones.

Yes but this option is intended not only for models but also for preparing json data for external APIs or some javascript libraries that does not handle empty strings well. There are so many use cases for it

**Comment by asgraf** [comment]
Another goal should be compatibility with as many popular value object libraries like:
brick/math
php-collective/decimal-object
darsyn/ip
ramsey/uuid
and many others

Such a libraries usually implement `toArray()` `toInt()` `toFloat()` `toString()` methods and/or implement `\Stringable`, `\JsonSerializable` interfaces

**Comment by asgraf** [comment]
> I also dont think we should keep $convertEmptyStringToNull etc

Another idea is to move this logic to NotEmptyStringCast class that will internally call StringCast class

**Comment by dereuromark** [comment]
Looks like this has to be a plugin addition for now.

**Pull request closed without merging**
