### PR TITLE
Add support for the parseHuge option.

### PR DESCRIPTION
**Pull request by markstory**
Sometimes people need to load huge XML files. Add an option to enable people to enable this flag.

Refs #10031

### CODE REVIEW

**Comment by lorenzo** [comment]
so literally you say to the library: This is gonna big HUGE 🕴

**Comment by markstory** [comment]
I'll port this to 3.x tonight.

**Comment by ravage84** [comment]
Cool, should we add this to the Cookbook for 2.x & 3.x, too?

**Comment by markstory** [comment]
Its in the API docs. I'm not sure every option needs to be in the book.

**Comment by jippi** [comment]
image

**Pull request merged**
