### PR TITLE
Fix: unused parenthesis for parameters of FunctionExpression.

### PR DESCRIPTION
**Pull request by StewEucen**
I sent pull request about #6733 

Now I use CakePHP 3.x for creating new Behavior.
This fix work in my behavior, therefore it is OK.

### CODE REVIEW

**Comment by lorenzo** [comment]
@StewEucen do you know how to create a test for this?

**Comment by StewEucen** [comment]
@lorenzo I do not know how to create test case.
If possible, please tell me how to create.

**Comment by lorenzo** [comment]
@StewEucen The first step is to get the test suite running. After cloning cakephp and running `composer install` try executing `vendor/bin/phpunit tests/TestCase/DatabaseSuite`

Let me know if you are able to get the test running

**Comment by StewEucen** [comment]
@lorenzo Thank you for your guide.
I try to make PHPUnit.

**Comment by lorenzo** [comment]
@StewEucen You will also need to fix this test https://travis-ci.org/cakephp/cakephp/jobs/65535719#L385

**Comment by lorenzo** [comment]
@StewEucen Probably fixing that test is good enough, you will not need to create new tests as that particular test is already showing the feature you implemented

**Comment by StewEucen** [comment]
@lorenzo I study about PHPUnit now. Please wait.
I must know custom of CakePHP project.

**Comment by markstory** [comment]
@StewEucen If you start by getting the tests running. Then you should be able to modify the existing tests so they pass. That is enough to help prevent future regressions.

**Comment by StewEucen** [comment]
@markstory Thank you for your message. I had missing experience to be a part of such this community. I must understand how to pull request in CakePHP project completely.

@lorenzo I am sorry to late reply. There is some misunderstanding, I had been slow to work.
I executed 'vendor/bin/phpunit tests/TestCase/DatabaseSuite', and got same error with your suggested 'https://travis-ci.org/cakephp/cakephp/jobs/65535719#L385'.
Please tell me next step.

**Comment by ADmad** [comment]
@StewEucen That error is expected since you changed the code. You now need to asset the test case to match the new expected value.

**Comment by StewEucen** [comment]
@ADmac I have just updated test case, and got OK by local running.
file: test/TestCase/Database/Expression/FunctionExpressionTest.php
line: 82
```
public function testFunctionNesting()
{
    $binder = new ValueBinder;
    $f = new FunctionExpression('MyFunction', ['foo', 'bar']);
    $g = new FunctionExpression('Wrapper', ['bar' => 'literal', $f]);
--  $this->assertEquals("Wrapper(bar, MyFunction(:c0, :c1))", $g->sql($binder));
++  $this->assertEquals("Wrapper(bar, (MyFunction(:c0, :c1)))", $g->sql($binder));
}
```

Next step is to commit and to push the fix into this branch. Is it right?

**Comment by ADmad** [comment]
Yes.

**Comment by StewEucen** [comment]
@ADmad I did it. Thank you for your guide.
Do I have more steps hereafter?

**Comment by ADmad** [comment]
Nope, now just wait for it to be reviewed and merged.

**Comment by StewEucen** [comment]
@Admad The Experience will help me in the next my pull request.
Thank you for all.

**Comment by lorenzo** [comment]
Thanks @StewEucen !

**Pull request merged**
