### PR TITLE
Allow CURRENT_TIMESTAMP for datetime columns - MySQL5.6+.

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/cakephp/issues/7393

### CODE REVIEW

**Comment by lorenzo** [comment]
Tests failing

**Comment by dereuromark** [comment]
How do we avoid the

    PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'limit_date'

by skipIf()?

**Comment by lorenzo** [comment]
Not sure why you would skip here

**Comment by dereuromark** [comment]
I wonder what the MYSQL version is here that is being used.

@kyoclover Does this fix your issue?

**Comment by markstory** [comment]
You can use `SELECT VERSION()` to sniff the version of MySQL being used and conditionally skip the tests.

**Comment by jippi** [comment]
VERSION() is fin, mariadb is on 10.x and oracle is on 5.x :P

**Comment by dereuromark** [comment]
I am running MySQL 5.6.x and it does not skip the test locally and is running fine. Let's see what Travis does.

**Comment by dereuromark** [comment]
Looks good.
I can also apply the enhancement to 3.0 afterwards.

**Comment by markstory** [comment]
A port to 3.x would be awesome @dereuromark

**Pull request merged**
