### PR TITLE
Fix errors reported by psalm

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by othercorey** [comment]
Can you check the psalm errors in the log? It seems psalm failure aren't failing.

**Comment by ADmad** [comment]
There are errors, at the end it shows
```
Error: Process completed with exit code 2
```
So it seems to be exiting with proper error code. Could GA's `continue-on-error` be misbehaving?

**Comment by othercorey** [comment]
> So it seems to be exiting with proper error code. Could GA's `continue-on-error` be misbehaving?

That's definitely it. I remember it showing as passing when we used it for php 8.2.

**Comment by ADmad** [comment]
All errors fixed. Strangely I don't get any of these locally which is why they were missed in the initial for psalm v5.

**Comment by ADmad** [comment]
`continue-on-error` was why the failure wasn't reported. I remember now that I had added it since psalm v4 was crashing earlier.

**Pull request merged**
