### PR TITLE
Update bundled CA file.

### PR DESCRIPTION
**Pull request by markstory**
Update the bundled CA file to the latest one from

https://curl.haxx.se/docs/caextract.html

The cURL folks host the extracted mozilla root CA, which is what we also use.

Refs #8604

### CODE REVIEW

**Comment by ravage84** [comment]
Couldn't this file live as a separate php package?
Just wondering if this file was used by more than CakePHP...

**Comment by markstory** [comment]
> Couldn't this file live as a separate php package?

Probably. But until I find more places to use it, I personally won't spend the time to maintain a separate repo for one file.

**Comment by Seldaek** [comment]
@markstory if you like, we now publish ours as https://packagist.org/packages/composer/ca-bundle and CaBundle::getBundledCaBundlePath() gets you the path to the cert or CaBundle::getSystemCaRootBundlePath() to autodetect system ca bundle + fallback to the bundled one.

**Comment by markstory** [comment]
Thanks @Seldaek  That might be less painful in the future.

**Comment by leonardobazico** [comment]
@markstory after update to 3.2.7 I'm get error on HttpClient->post to https url.

`fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
fopen(): Failed to enable crypto
fopen(https://gcm-http.googleapis.com/gcm/send): failed to open stream: operation failed`

I backed to 3.2.6 and the error was gone.

Any suggestion?

**Comment by markstory** [comment]
Not sure, does that domain have a valid certificate in firefox? The CA bundle should be the same as the one firefox uses.

**Comment by leonardobazico** [comment]
@markstory Yes, the domain have a valid certificate in firefox. You can access https://gcm-http.googleapis.com/gcm for test.

**Comment by mirko-pagliai** [comment]
I have the same problem

**Comment by markstory** [comment]
Are you by any chance using PHP 5.6 or PHP 7? We have a few travis-ci builds failing for those versions. I've not had much luck in figuring out why certificate validation is failing in those environments yet, as the problematic builds pass fine on OSX with PHP 5.6. I am able to reproduce the issue on OSX with a simple curl script

```php
$curl = curl_init();
$options = [
    CURLOPT_URL => "https://gcm-http.googleapis.com/gcm",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_HEADER => 0,
    CURLOPT_CAINFO => './config/cacert.pem',
];
curl_setopt_array($curl, $options);

$result = curl_exec($curl);
var_dump($result);
var_dump(curl_errno($curl));
var_dump(curl_error($curl));
```

I'll suspect the new mozilla bundle is missing a cert that googleapis.com is relying on.

**Comment by thinkingmedia** [comment]
@markstory those Travis failing tests are passing on my Windows 10 with PHP 7.0.3.

**Comment by markstory** [comment]
Looks like Mozilla has removed a few key load bearing certificates. Notably

* Equifax Secure Certificate Authority
* Thawte Server CA
* Digital Signature Trust Co
* ValiCert Class 1 VA
* America Online Root Certification

And a few other CAs that I'm not familiar with. From what I can gather from google searches is that mozilla has been removing CAs with 1024bit keys. The googleapis.com site has the 'Equifax Secure CA' in its chain which seems to be the source of this issue.

**Comment by mirko-pagliai** [comment]
Yes, I'm on php 5.6.20.This is the production server.
In development on localhost, with 5.6.19, I haven't.
I can not replicate the error in development :-(

**Pull request merged**
