### PR TITLE
Create controller instance if one is not provided to constructor.

### PR DESCRIPTION
**Pull request by ADmad**
This ensures static analyzers/IDE don't complain about calling methods on possibly null values.

Fixes error this thrown by psalm
```
INFO: PossiblyNullReference - src/Controller/Component/PaginatorComponent.php:196:55 - Cannot call method getRequest on possibly null value
        $request = $this->_registry->getController()->getRequest();
```

### CODE REVIEW

**Comment by ADmad** [comment]
Alternatively the constructor argument could be made non-optional as tests updated to pass an instance. In actual usage the instance is always passed anyway.

**Comment by dereuromark** [comment]
I was thinking the same yesterday. This makes total sense.

**Comment by dereuromark** [comment]
Others like Table

    public function getConnection(): ?Connection

have the same issue:

nullpointer

**Comment by markstory** [comment]
I think we can make this a required dependency in 4.0. It will break plugin tests and should be included in the migration guide but this change has a simple fix.

**Comment by ADmad** [comment]
Cool, I'll update the PR

**Comment by ADmad** [comment]
`Controller`'s constructor also takes `ComponentRegistry` as an (optional) argument so we kinda have an chicken and egg situation. On second thought I am sure not making `Controller` a required constructor argument for `ComponentRegistry` is the right thing to do.

We can keep the constructor unchanged and instead make `getController()` method throw an exception if controller is not set.

**Review by markstory — APPROVED** [review]
Looks good to me.

**Pull request merged**
