### PR TITLE
Restore 'persist' option for routes.

### PR DESCRIPTION
**Pull request by ADmad**
Refs #6038

### CODE REVIEW

**Comment by markstory** [comment]
What kind of time difference does this make in matching routes?

**Comment by ADmad** [comment]
I haven't done any benchmarks but the alternative to achieve same functionality is using url filter which is run for every url so it's an improvement nonetheless.

I can make `persistParams` protected and move the empty check for `$this->options['persist']` in `match()` itself to avoid extra function call too.

**Comment by markstory** [comment]
I'm just wondering _if_ it has an impact, making the method protected could help.

**Comment by ADmad** [comment]
Changed persistParams() to protected

**Comment by markstory** [comment]
Looks good to me.

**Comment by markstory** [comment]
Docs need updating too :)

**Pull request merged**
