### PR TITLE
4.x Controller

### PR DESCRIPTION
**Pull request by ADmad**
- Made `Controller::$request`, `Controller::$response` protected.
- Removed `Component::$request` and `Component::$request`.

### CODE REVIEW

**Comment by ADmad** [comment]
`CsrfComponent` and `CookieComponent` are to be removed in `4.0` right? Don't want to spend time updating those and their tests in that case.

**Comment by markstory** [comment]
> CsrfComponent and CookieComponent are to be removed in 4.0 right?

I think so. They have been deprecated for a few release cycles now.

**Comment by ADmad** [comment]
@markstory Done :muscle:.

**Comment by ADmad** [comment]
:heavy_check_mark: finally.

**Comment by markstory** [comment]
Awesome work @ADmad :clap:

**Comment by ADmad** [comment]
Thanks :blush:

**Comment by markstory** [comment]
Refs #11934

**Pull request merged**
