### PR TITLE
Fix incorrectly parsed mo file context.

### PR DESCRIPTION
**Pull request by markstory**
The context from mo files should be parsed correctly.

Refs #7118

### CODE REVIEW

**Comment by lorenzo** [comment]
Tests failing :(

**Comment by lorenzo** [comment]
hmm, but it seems like the failing tests are not related

**Comment by ADmad** [comment]
Looks like another wacky datetime related issue.

**Comment by markstory** [comment]
Going to try rebuilding the job. Looks like it got hit with time related issues.

**Pull request merged**
