### PR TITLE
add missing Flash default element

### PR DESCRIPTION
**Pull request by steinkel**
Add missing Flash element to the app folder

### CODE REVIEW

**Comment by ADmad** [comment]
There's one already under `lib/Cake/View/Elements/Flash/`.

**Comment by steinkel** [comment]
Yes but not under the app folder, causing a warning for people using the app folder distributed with the framework right away (the wrong way)

**Comment by ADmad** [comment]
If the file isn't in `app` it will be used from `lib`. It's been like this for years IIRC.

**Comment by steinkel** [comment]
hey @ADmad this is caused by a call to the deprecated $this->Session->setFlash('xxx');
even deprecated, this should not throw a warning right?

I've prepared a stupid example here 
https://pr-9061-steinkel.c9users.io/cakephp-2.next/
https://ide.c9.io/steinkel/pr-9061

```
	public function display() {
		$this->Session->setFlash('Sail Ho!');
```

Thanks,

**Comment by markstory** [comment]
Does FlashHelper not look in the `lib/` directory for elements?

**Comment by ravage84** [comment]
I can't say much about what is wrong or how it should be.
But as much as I understood from @steinkel's description this is a bug and its fix should target the next patch release for 2.8 instead.

**Comment by steinkel** [comment]
Well this is a minor thing indeed, I found it while reviewing some other's code that was using a CakePHP setup unzipped from the latest 2.8 release.

I compared the app folder in the root of the repo with the generated project folder via (cake bake project) and this file app/View/Elements/Flash/default.ctp was generated by the bake shell but not present in app so makes sense for me to add it.

**Pull request merged**
