### PR TITLE
Fix first() failing on unbuffered queries.

### PR DESCRIPTION
**Pull request by markstory**
Re-add first() to ResultSet. Because of how `LimitIterator` and unbuffered queries interact, valid() was being called multiple times, advancing the iterator position beyond the result set data.

By having a specific first() on ResultSet we can ensure that the statement is closed after the first record is read. This of course makes ResultSet forget any additional length they may have.

Refs #5720

### CODE REVIEW

**Comment by ADmad** [comment]
Does this change mean the usage I have [here](https://github.com/ADmad/cakephp-i18n-messages/blob/master/src/I18n/DbMessagesLoader.php#L133) will stop working again? I initially fetch the [first item](https://github.com/ADmad/cakephp-i18n-messages/blob/master/src/I18n/DbMessagesLoader.php#L123) and subsequently iterate over the resultset  for the remaining.

**Comment by ADmad** [comment]
Sqlite builds are failing.

**Comment by markstory** [comment]
Yes, that usage would break. I wasn't sure that having first work differently for unbuffered and buffered queries was a good idea.

Another option would be to only close the statement for umbuffered queries, or expose a method to close the under lying statement. Without that there are annoying open cursor errors.

**Comment by markstory** [comment]
I'm going to try fixing this in a different way this evening. I think the root issue is that `valid()` is not idempotent which is should be.

**Comment by markstory** [comment]
@ADmad passing now and without breaking your use case I think.

**Comment by ADmad** [comment]
@markstory Awesome, thanks.

**Pull request merged**
