### PR TITLE
Fixing a couple incrementers and decrementers

### PR DESCRIPTION
**Pull request by Theaxiom**
This is me splitting up a larger PR, please see #10532 for details.

### CODE REVIEW

**Comment by markstory** [comment]
Why use `++$var` over the more conventional `$var++`?

**Comment by thinkingmedia** [comment]
@markstory Shouldn't the linter have caught this?

**Comment by ADmad** [comment]
@thinkingmedia AFAIK we don't have any CS rule in place for that.

**Comment by dereuromark** [comment]
Some  prefer to always use `++$var` to make sure it is changed prior to using it (and not accidentally using the former value). But without a sniffer in place it will be hard to reach a consistency here anyway :)

**Comment by thinkingmedia** [comment]
@derekperkins 

```
   ++$var; // triggers no error.
   +$var; // triggers no error.
   $var++; // triggers no error.
   $var+; // syntax error
```

I think that's the only reason people prefer the post increment. There is nothing wrong with `++$var;` as a line of code, but an accidental delete of a `+` will yield `+$var;` and could go unnoticed by the programmer since there is no errors.

**Comment by dereuromark** [comment]
@thinkingmedia 
The syntax issue sounds rather unrealistic to me, and probably quite obvious.
Whereas the hidden value issue often times is more common and of course more dangerous as well, doing something different without showing it to the developer.

**Comment by Theaxiom** [comment]
@markstory fixed.

**Comment by ADmad** [comment]
Needs rebase :)

**Comment by Theaxiom** [comment]
Done.

**Comment by ADmad** [comment]
Hmm.. All mysql builds are failing, though it seems to have been caused by another PR.

**Comment by inoas** [comment]
I don't think we should have a linter on `$var++` vs `++$var` as they do different things.

However I do think that we should never use ++$var unless we need specifically what ++$var does over $var++ as a code style guideline (same for --).

**Comment by markstory** [comment]
@ADmad I'll get those failures fixed tonight.

**Pull request merged**
