### PR TITLE
Update Sqlserver.php

### PR DESCRIPTION
**Pull request by celsowm**
a simple check if PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE was set as a pdo config flag or not
to solve this issue: https://github.com/cakephp/cakephp/issues/16848

### CODE REVIEW

**Review by celsowm — COMMENTED** [review]
syntaxe

**Review by celsowm — COMMENTED** [review]
space in end of line

**Comment by celsowm** [comment]
I really do not know what is happening in CI / testsuite in this simple pull request @markstory :(

**Comment by markstory** [comment]
The tests are failing because there is a test that is referencing a SQLserver constant in environments where SQLServer is not installed

```
1) Cake\Test\TestCase\Database\Driver\SqlserverTest::testConnectionConfigCustom
Error: Undefined constant PDO::SQLSRV_CURSOR_FORWARD
```

Is the test that is failing. That test likely needs a skip if sqlserver is not installed.

**Review by celsowm — COMMENTED** [review]
test if sql server

**Review by celsowm — COMMENTED** [review]
syntax

**Comment by celsowm** [comment]
> The tests are failing because there is a test that is referencing a SQLserver constant in environments where SQLServer is not installed
> 
> ```
> 1) Cake\Test\TestCase\Database\Driver\SqlserverTest::testConnectionConfigCustom
> Error: Undefined constant PDO::SQLSRV_CURSOR_FORWARD
> ```
> 
> Is the test that is failing. That test likely needs a skip if sqlserver is not installed.

thanks,
I used:

 `if (defined('PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE') && defined('PDO::SQLSRV_CURSOR_FORWARD')) `

but now codecov is saying is complaining again about:

```
src/Database/Driver/Sqlserver.php#L213-L214
Added lines #L213 - L214 were not covered by tests

```

**Comment by ADmad** [comment]
> That test likely needs a skip if sqlserver is not installed.

That test is already skipped if `pdo_sqlsrv` is not installed.

@celsowm The issue is only with `PDO::SQLSRV_CURSOR_FORWARD`, you don't need to check for `PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE`. 

Are you sure `PDO::SQLSRV_CURSOR_FORWARD` is the correct constant? I don't see any mention of it here https://learn.microsoft.com/en-us/sql/connect/php/cursor-types-pdo-sqlsrv-driver?view=sql-server-ver16

**Comment by celsowm** [comment]
> > That test likely needs a skip if sqlserver is not installed.
> 
> That test is already skipped if `pdo_sqlsrv` is not installed.
> 
> @celsowm The issue is only with `PDO::SQLSRV_CURSOR_FORWARD`, you don't need to check for `PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE`.
> 
> Are you sure `PDO::SQLSRV_CURSOR_FORWARD` is the correct constant? I don't see any mention of it here https://learn.microsoft.com/en-us/sql/connect/php/cursor-types-pdo-sqlsrv-driver?view=sql-server-ver16

image

**Review by celsowm — COMMENTED** [review]
check only 1 constant

**Comment by ADmad** [comment]
> When you create a result set with [sqlsrv_query](https://learn.microsoft.com/en-us/sql/connect/php/sqlsrv-query?view=sql-server-ver16) or with [sqlsrv_prepare](https://learn.microsoft.com/en-us/sql/connect/php/sqlsrv-prepare?view=sql-server-ver16), you can specify the type of cursor.

We are using `PDO`, not `sqlsrv_query()` or `sqlsrv_prepare()`. Also `SQLSRV_CURSOR_FORWARD` is not the same as `PDO::SQLSRV_CURSOR_FORWARD`.

https://learn.microsoft.com/en-us/sql/connect/php/cursor-types-sqlsrv-driver?view=sql-server-ver16

P.S. In future provide the link to the info source instead of an image.

**Comment by celsowm** [comment]
> > When you create a result set with [sqlsrv_query](https://learn.microsoft.com/en-us/sql/connect/php/sqlsrv-query?view=sql-server-ver16) or with [sqlsrv_prepare](https://learn.microsoft.com/en-us/sql/connect/php/sqlsrv-prepare?view=sql-server-ver16), you can specify the type of cursor.
> 
> We are using `PDO`, not `sqlsrv_query()` or `sqlsrv_prepare()`. Also `SQLSRV_CURSOR_FORWARD` is not the same as `PDO::SQLSRV_CURSOR_FORWARD`.
> 
> https://learn.microsoft.com/en-us/sql/connect/php/cursor-types-sqlsrv-driver?view=sql-server-ver16
> 
> P.S. In future provide the link to the info source instead of an image.

ok, I gonna try PDO::SQLSRV_CURSOR_STATIC

**Review by celsowm — COMMENTED** [review]
flag

**Review by celsowm — COMMENTED** [review]
syntax

**Review by celsowm — COMMENTED** [review]
syntax

**Review by celsowm — COMMENTED** [review]
syntax

**Review by celsowm — COMMENTED** [review]
last try

**Comment by ADmad** [comment]
The `flags` options of connection config is meant to be used when creating the PDO connection, not when preparing the PDO statement. I have a made proper fix #18011 to disable client side buffering when it's disabled for the `SelectQuery`.

**Comment by ADmad** [comment]
Closing as the alternate PR which addresses the issue has been merged.

**Pull request closed without merging**
