### PR TITLE
Update dependency constraints.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Review by markstory — APPROVED** [review]

**Comment by othercorey** [comment]
What were the packages that required psr/container 1.0 for users?

**Comment by ADmad** [comment]
Not sure what you mean.

**Comment by othercorey** [comment]
> Not sure what you mean.

We added it because external packages needed it. Do you think that will change by the time 5.0 is released?

**Comment by ADmad** [comment]
With Cake 5 being PHP 8.1+ users will already have to update their dependwncies accordingly. Latest minor of the likes of Symfony are already PHP 8.1+.

**Pull request merged**
