### PR TITLE
Log query execution time and rows (#8077)

### PR DESCRIPTION
**Pull request by berarma**
Issue #8077.

### CODE REVIEW

**Comment by jeremyharris** [comment]
I wonder if a delimiter other than space could be friendlier for tools to parse the logs?

**Comment by dereuromark** [comment]
@jeremyharris You would want to use preg_match anyway, I assume.
And there cannot be any spaces in the first part `duration=x rows=y z`.

**Comment by markstory** [comment]
Looks good to me.

@jeremyharris Spaces are kind of nice as they work really well with tools like `cut` and `awk`.

**Comment by jeremyharris** [comment]
@markstory I was actually thinking about `cut` when I suggested it. 

I suppose as long as the query always comes last it's not that big of a deal :)

**Pull request merged**
