### PR TITLE
Update at() matchers in Console

### PR DESCRIPTION
**Pull request by markstory**
Update more tests to not use at(). Without at() we lose the ability to ensure method orders with mocks, as this is discouraged within PHPUnit mocks.

### CODE REVIEW

**Comment by dereuromark** [comment]
> Without at() we lose the ability to ensure method orders with mocks

`withConsecutive` is the replacement when order matters, right?

**Comment by markstory** [comment]
> withConsecutive is the replacement when order matters, right?

Yes but you can't use that to ensure order across different methods.

**Comment by dereuromark** [comment]
Then I dont find their way of removing useful methods a good way forward.
If people want to use it, they can use at(), otherwise once() or any() etc.
Dictating the removal seems weird and counterproductive. Is there any good argument for it?

Sure, overusing it can create maintenance overhead or failing tests when they don't need to be.
But that's user error, and not the fault of the existence of those in general.

**Comment by dereuromark** [comment]
I see some comments and details here: https://github.com/sebastianbergmann/phpunit/issues/4297

**Comment by othercorey** [comment]
looks ok.

**Pull request merged**
