### PR TITLE
3.3-beta Rename existsIn flag allowPartialNulls to allowNullableNulls

### PR DESCRIPTION
**Pull request by ionas**
Ref: https://github.com/cakephp/cakephp/pull/8908#issuecomment-231591221
If merged I'll update the docs!

### CODE REVIEW

**Comment by ionas** [comment]
I did check the unit tests before pushing, still I'd want CI to check it again.

**Comment by dereuromark** [comment]
Isn't this still a BC break unless we also keep allowPartialNulls option around?
Is this worth it for a minor? Whats the benefit of it over the other option key?

**Comment by ADmad** [comment]
@dereuromark This option was introduced in 3.3 and doesn't exist in 3.2, so there's no question of BC breaking. We can freely modify the 3.3 code until 3.3 RC.

**Comment by dereuromark** [comment]
Ah, gotcha :)
So is that indeed the better name? What is a nullable null in a basic term?

**Comment by ADmad** [comment]
Personally I don't think the name `allowNullableNulls` conveys any more meaning than `allowPartialNulls` :)

**Comment by ionas** [comment]
:( @ADmad Can you think of a really good name? If you look at the commits I tried multiple.
@dereuromark `parent_id IS NULL` when it comes along with value null is a nullable null.

**Comment by htstudios** [comment]
@markstory would you merge or close it as you see fit? TIA!

**Comment by saeideng** [comment]
`allowNulls`

**Pull request merged**
