### PR TITLE
Replace custom code fence with markdown standard fence.

### PR DESCRIPTION
**Pull request by ADmad**
It's better to use the standard markdown fence instead of our custom one.

Requires cakephp/cakephp-api-docs#19 to be merged first.

### CODE REVIEW

**Comment by ADmad** [comment]
Related api-docs PR has been merged.

**Comment by antograssiot** [comment]
:+1:

**Comment by ADmad** [comment]
Rebased

**Comment by ADmad** [comment]
Merging to avoid conflicts again.

**Pull request merged**
