### PR TITLE
Fix disabled attribute calculation.

### PR DESCRIPTION
**Pull request by markstory**
Take the work done in #10770 and account for the complex options and non-empty disabled option sets.

Refs #10770

### CODE REVIEW

**Comment by dereuromark** [comment]
The protected method wraps this nicely 👍

**Comment by saeideng** [comment]
also please update doc block 
now is
```
      * - `disabled` - mixed - Either a boolean indicating disabled state, or the string in
     *   a numerically indexed value.
```

**Comment by dereuromark** [comment]
@saeideng : bool|string then

**Comment by saeideng** [comment]
bool ,string and array @dereuromark

**Comment by dereuromark** [comment]
My point was more about not using mixed ever ;) but listing the concrete types if possible.

**Comment by markstory** [comment]
@saeideng I updated the doc block. I didn't add type information as IDE's and other tools can't read that deeply into doc blocks.

**Comment by alexdd55** [comment]
+1

**Pull request merged**
