### PR TITLE
Using variadic instead of func_* functions

### PR DESCRIPTION
**Pull request by jrbasso**
This PR replaces the use of some of the `func_*` functions by variadic. It reduces the function calls and consequently improves the performance, especially on the `EventManager`, which is very often called.

The signature of few methods were changed, so people extending the method can get a strict error from php, but the functionality is the same. I don't think people extend it very often, but I can revert it to the original. These methods are not often called.
PS: The i18n functions won't matter for this BC since they need to be completely redefined instead of extended.

### CODE REVIEW

**Comment by jippi** [comment]
@jrbasso Do you have any data on any actual performance changes? I'm all for using the "new" features of PHP, but highly curious on the perf improvement :)

**Comment by inoas** [comment]
So will 3.4 be min PHP 5.6 finally?

**Comment by lorenzo** [comment]
@jrbasso style tests failing, but looks good to me :)

**Comment by jrbasso** [comment]
@inoas Yes, see #9297 

@jippi Didn't do any benchmark on the app, but I see some tests running faster while doing that. I will try to run some test on a hello world app.

@lorenzo Weird. It passes on my local and the line they say has an old style array [has no array](https://github.com/jrbasso/cakephp/blob/variadic/tests/TestCase/Utility/XmlTest.php#L389-L390) 😕 . It also [passed on my travis](https://travis-ci.org/jrbasso/cakephp/jobs/183829721). It's probably something on the merge. I will try to check with later on with more time.

**Comment by jrbasso** [comment]
Ah, @ADmad fixed the CS issue on master already (4c545b9facec53043a8ed6b574b1dc1fd172bed3). I will rebase after it gets on 3.next.

**Comment by lorenzo** [comment]
@jrbasso I did it for you :)

**Comment by jrbasso** [comment]
@lorenzo thanks!

**Pull request merged**
