### PR TITLE
StringTemplateTrait uses directly InstanceConfigTrait

### PR DESCRIPTION
**Pull request by mirko-pagliai**
See https://github.com/cakephp/cakephp/issues/9808

### CODE REVIEW

**Comment by mirko-pagliai** [comment]
I hoped it would be easy, however it is not:
https://ci.appveyor.com/project/cakephp/cakephp/build/1.0.5605

`Fatal error: Cake\View\Helper and Cake\View\StringTemplateTrait define the same property ($_config) in the composition of Cake\View\Helper\HtmlHelper. However, the definition differs and is considered incompatible. Class was composed in C:\projects\cakephp\src\View\Helper\HtmlHelper.php on line 1288`

**Comment by markstory** [comment]
You'll likely have to remove `InstanceConfigTrait` from Helper as well.

**Comment by mirko-pagliai** [comment]
Also `Helper` uses the `config()` method ([code](http://api.cakephp.org/3.3/source-class-Cake.View.Helper.html#121))

**Comment by ADmad** [comment]
@mirko-pagliai  Yes it does but since `Helper` uses `StringTemplateTrait` which now uses `InstanceConfigTrait` we shouldn't need `use InstanceConfigTrait` in `Helper`.

**Comment by mirko-pagliai** [comment]
@markstory @ADmad removing `InstanceConfigTrait` from `Helper`, tests fail.
@ADmad do you say that `Helper` **should** use `StringTemplateTrait` (now it does not)? Actually in local tests seem ok.

**Comment by ADmad** [comment]
Sorry my mistake. `FormHelper` (and couple of other helpers) use `StringTemplateTrait` not `Helper` itself. I don't think it should be used in `Helper` itself.

**Comment by mirko-pagliai** [comment]
@ADmad I'm sorry, but I really do not understand what you're sayin.
`Helper` needs to use `InstanceConfigTrait`, because it uses the `config()` method.
The various helpers use `StringTemplateTrait`, which in turn uses `InstanceConfigTrait`.

**Comment by ADmad** [comment]
> Helper needs to use InstanceConfigTrait, because it uses the config() method.

Yes 

> The various helpers use StringTemplateTrait, which in turn uses InstanceConfigTrait.

Yes but you can't add `InstanceConfigTrait` to `StringTemplateTrait` since PHP doesn't like `InstanceConfigTrait` being eventually composed twice into the same class.

Only way to solve the problem is
- Add `InstanceConfigTrait` to `StringTemplateTrait`
- Add `StringTemplateTrait`to `Helper` and remove `InstanceConfigTrait`, but I am not convinced that's the right thing to do.

So personally I would just keep things as they are.

**Comment by markstory** [comment]
Is there also an option where StringTemplateTrait doesn't use methods defined in InstanceConfigTrait? That might break compatibility but is another potential solution. Lastly we could document that StringTemplateTrait requires the implementing class to privide a config() method.

**Comment by mirko-pagliai** [comment]
@ADmad 

> Only way to solve the problem is

I will try.

> So personally I would just keep things as they are.

Perhaps this is so (although not good) for this reason :-(

**Comment by mirko-pagliai** [comment]
This is really very strange. I added `StringTemplateTrait` to `Helper`, but I get this:

```
There was 1 failure:

1) Cake\Test\TestCase\Validation\ValidationTest::testEmailDeep
Failed asserting that true is false.

/home/mirko/Libs/cakephp/tests/TestCase/Validation/ValidationTest.php:1887
/usr/share/php/PHPUnit/TextUI/Command.php:162
/usr/share/php/PHPUnit/TextUI/Command.php:113
```

I canceled the changes and there are no errors. I can not understand what has to do.
Do I try to do the PR?

**Comment by markstory** [comment]
@mirko-pagliai That looks like a DNS issue, and is likely not related to your changes.

**Comment by mirko-pagliai** [comment]
Same error occurs.

I think the best thing for now is this:

> Lastly we could document that StringTemplateTrait requires the implementing class to privide a config() method.

Then change the class description, warning that you must also use the other.

**Comment by markstory** [comment]
Closing as API docs were updated in 2adcead

**Pull request closed without merging**
