### PR TITLE
escape fix

### PR DESCRIPTION
**Pull request by TheLukasMarks**
This 'escape' => true provide a fix for the 'confirm' msg break.

### CODE REVIEW

**Comment by dereuromark** [comment]
What do you mean? Is there a test case along with this?

**Comment by LuMAXW3B** [comment]
I didnt wrote a test case yet, but tested in diff applications, sorry

**Comment by markstory** [comment]
What is the code that caused that issue? Having that would let us craft up a test case so we don't have accidental regressions in the future.

**Comment by LuMAXW3B** [comment]
See the example https://gist.github.com/LuMAXW3B/6894cd92dfa6c43a8fb0

**Comment by lorenzo** [comment]
@LuMAXW3B I think we came up to the conclusion that the confirm option should be escaped no matter what. Wouldn't it be better instead of changing this?

**Comment by LuMAXW3B** [comment]
@lorenzo its up to you guys, I just run into this and wanted to help, I always define 'escape' => true or 'escape' => false when I need it in my code but from the perspective of other developers such an isse can cause headache and maby this could be mention in the docs -> http://book.cakephp.org/2.0/en/core-libraries/helpers/form.html#FormHelper::postLink

**Comment by markstory** [comment]
I tried to reproduce this issue locally, and I didn't get the corrupted markup you had. Setting escape to true or false didn't trigger the corrupted markup. Is it possible there is application code that is causing the behavior to be different?

**Comment by LuMAXW3B** [comment]
@markstory I get this issue when I dont define 'escape' => true || 'escape' => false, when its defined it works splendid. I run into this issue while working on Croogo CMS index forms, I gonna talk to @rchavik and ask him to test it. but thnx for your test and response

**Comment by rchavik** [comment]
Croogo aliases `'Form' => 'CroogoForm'` in the admin, so it might be that CroogoFormHelper needs updating.

**Comment by LuMAXW3B** [comment]
@rchavik maby yes, but in my case I use $this->Form->postLink() straight

**Comment by rchavik** [comment]
It's aliased.

Try: `debug(get_class($this->Form));`

**Comment by markstory** [comment]
Closing as I'm not able to reproduce this issue on a vanilla CakePHP install. I suspect the issue lies in a subclass provided by croogo.

**Pull request closed without merging**
