### PR TITLE
2.x cake bake Controller: Only add Flash component when required

### PR DESCRIPTION
**Pull request by xhs345**
If a user selected no to the question "Would you like to use Session flash messages?" it would still load the Flash component, but not use it

### CODE REVIEW

**Comment by dereuromark** [comment]
Looks good to me.

**Comment by xhs345** [comment]
Ok, will updated the test files as well. 

Where do I have to put the 'project or solution file', so that the AppVoyer build passes?
Thanks

**Comment by dereuromark** [comment]
Travis should be fine for now.

**Comment by markstory** [comment]
@xhs345 Appveyor never passes in 2.x as they only support per project configuration and currently its setup for 3.x

**Comment by xhs345** [comment]
Thank for for the information. 

The PHP5 tests are passing now, but for some reason the PHP7 test fails

**Comment by markstory** [comment]
The PHP7 failures seem un-related. I'll check the tests locally and see if I can reproduce.

**Comment by xhs345** [comment]
Ok, thanks

**Pull request merged**
