### PR TITLE
adjust command code references to use interface instead of implementing class

### PR DESCRIPTION
**Pull request by LordSimal**
Fixes the following warning in my IDE
image

### CODE REVIEW

**Comment by othercorey** [comment]
If we're fixing IDE complaints, this should be a PHPCS rule.

**Comment by dereuromark** [comment]
More like a phpstan extension probably.

**Comment by LordSimal** [comment]
well it was just something I noticed while looking through the code.
Enforcing it via phpstan or psalm would definitely be usefull.

But I also can say that this is not all of those "warnings" in the 5.x branch.
I didn't touch the confusing matter between `Cake\Database\Query` and `Cake\ORM\Query` because after trying the "auto-fix" from PHPStorm it resulted in too many tests being broken.

**Comment by othercorey** [comment]
> More like a phpstan extension probably.

You're right. This couldn't be a PHPCS rule.

**Comment by LordSimal** [comment]
Well I wasn't able to find an already present PHPCS/PHPStan Rule which does this check.
I guess we should then add a custom rule to https://github.com/cakephp/cakephp-codesniffer, right?

**Comment by LordSimal** [comment]
ah right, this can't be a PHPCS rule as said. So should we create a custom cakephp-phpstan plugin?

**Comment by ADmad** [comment]
> So should we create a custom cakephp-phpstan plugin?

This really isn't a Cake specific thing. Maybe phpstan/psalm might be interested in adding a rule for it if you submit an issue.

**Comment by LordSimal** [comment]
Well there won't be a psalm core rule coming for that 😅 
https://github.com/vimeo/psalm/issues/7781#issuecomment-1066158809

**Comment by othercorey** [comment]
I would agree that it's not necessary.

**Comment by ADmad** [comment]
> Well there won't be a psalm core rule coming for that 

Understandable since there's no bug / potential of error here.

**Comment by dereuromark** [comment]
Bottom line: community plugin extension if you feel strongly about it.
That was what we meant in the first place kind of

**Comment by LordSimal** [comment]
Personally I don't really feel strongly about it. I thought its just a small code incosistency since we don't overwrite those interface constants in its sub-classes. Therefore making references to that constant consistent throughout the code would be a "smell" - I thought - we could get rid of.

But since its pretty minor and I only noticed it through PHPStorm I guess we can leave it as be and don't enforce it any further.

**Pull request merged**
