### PR TITLE
[3.next] Disable access to methods of inner iterator of Collection

### PR DESCRIPTION
**Pull request by chinpei215**
Refs #11045

### CODE REVIEW

**Review by markstory — APPROVED** [review]
Looks good to me.

**Comment by chinpei215** [comment]
Thanks. @lorenzo Any thoughts?

**Comment by lorenzo** [comment]
Thanks!

**Comment by ravage84** [comment]
This should probably be included in the migration guide, isn't it?

**Comment by chinpei215** [comment]
Yes, it should.

**Pull request merged**
