### PR TITLE
Implementing a way to get some useful debug info about why a form was bl...

### PR DESCRIPTION
**Pull request by burzum**
...ackholed

### CODE REVIEW

**Comment by greenmanspirit** [comment]
Is there a chance that this will be put into 2.7. I was checking out the RC and it doesn't look like it's there.

**Comment by markstory** [comment]
@greenmanspirit It isn't currently going to make it into 2.7. There were a number of issues around how multiple forms would work which we couldn't easily resolve.

**Comment by jeremyharris** [comment]
Sorry to create noise, but this is really good stuff @burzum. So necessary. I find myself constantly littering debug statements in the security component and form helper to try and figure out odd things like this.

**Comment by greenmanspirit** [comment]
@markstory Thanks for the update. I applied the patch temporarily in my application to debug my issues but if this was going to make it in 2.7, I would have waited and worked on another issue for now.

**Comment by dereuromark** [comment]
I agree with @jeremyharris .
If we could at least have that hashing part in the key, we could make this work.
IMO having this patch working only half as good (and with tab issues) this is still 1000% better than not having it at all and flying blind.

**Comment by burzum** [comment]
@jeremyharris thanks, same issue for me here, that's the reason I was looking for a solution.

I don't see a problem with multiple tabs or on the fly created forms. This is a helper for the developers to figure out what went wrong. If you don't know or remember what form you submitted the last you have a bigger problem than getting blackholed.

However, maybe it's possible to inject a hidden field somehow on debug and use a UUID that is written to the form and session to somehow figure out what form was submitted? Just brainstorming, I haven't looked at this since it was closed.

**Pull request closed without merging**
