### PR TITLE
Add compareWith validation method.

### PR DESCRIPTION
**Pull request by markstory**
Adds a `compareWith` validator that allows two fields to be checked for equality. This came out of the discussion in #5746.

In addition to adding a new `compareWith` validation method, I've also added a naming convention based way for validation methods to opt into receiving the context variable.

### CODE REVIEW

**Comment by jadb** [comment]
:clap:

**Comment by Xety** [comment]
Nice work. :+1:

**Comment by robertpustulka** [comment]
Great!

BTW is it really nessesary to remove $context from arguments in other methods? Having this proxy, reflection, etc?

**Comment by lorenzo** [comment]
Great job @markstory !

**Comment by markstory** [comment]
@robertpustulka I think it is as many validation methods have optional arguments  that cannot be replaced with the context data.

**Comment by robertpustulka** [comment]
@markstory right, I forgot  these arguments can be optional. Thanks for claryfing that!

**Pull request merged**
