### PR TITLE
Use Table::newEmptyEntity() in Marshaller::one()

### PR DESCRIPTION
**Pull request by andrii-pukhalevych**

### CODE REVIEW

**Comment by LordSimal** [comment]
Can you explain why you want to do this?

**Comment by andrii-pukhalevych** [comment]
Code in `Marshaller::one()` is copypaste of `Table::newEmptyEntity()`.
I beleive it comes from times when `Table::newEmptyEntity()` did not exist, and using of `Table::newEntity()` was not optimal solution in this case.

**Comment by andrii-pukhalevych** [comment]
There is should be single point to create entities.
For example, I want to override `newEmptyEntity()` in my project, but marhaller just ignores it.

**Comment by othercorey** [comment]
This looks safe to use, thanks!

**Pull request merged**
