### PR TITLE
Deprecate the requireAuth feature.

### PR DESCRIPTION
**Pull request by markstory**
Its a pretty unintuitive feature, that doesn't work well and should stop existing.

Refs cakephp/docs#3726

### CODE REVIEW

**Comment by ravage84** [comment]
Do you want to remove the mentions in the book, too?
http://book.cakephp.org/3.0/en/controllers/components/security.html#restrict-actions-to-ssl

And shouldn't we add a deprecation note to the migrations guide?

**Comment by dereuromark** [comment]
Yeah we should remove it from the docs and add it to the migration guide just in case.

**Comment by ravage84** [comment]
And how about backporting the deprecation to 2.9?

**Comment by dereuromark** [comment]
You can open a PR of course.

**Comment by ravage84** [comment]
Deprecation of ``requireAuth()`` in 2.x see #8227

**Pull request merged**
