### PR TITLE
Bump up Cake dependencies versions in split packages.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by othercorey** [comment]
This would break an RC, right?

**Comment by ADmad** [comment]
Users might require `minimum-stability=rc` in their composer config.

This change will ensure that same minor of packages are used together. In the past mixing minors of sub packages have caused problems like this one https://github.com/cakephp/cakephp/issues/17624

**Comment by dereuromark** [comment]
It would not break as it would just not download it automatically.

**Comment by othercorey** [comment]
I meant it would break the RC release without adding the stability.

Do we want to start doing this going forward? Don't think we've done it for 4.x.

**Comment by othercorey** [comment]
Maybe this is best since it won't allow someone to have only part of the dependencies listed. 

Not sure if anyone actually tests RC with split packages.

**Comment by ADmad** [comment]
Yeah no one's gonna test the split package  RCs, this is just to ensure we don't forget to bump the versions before the stable release. Don't think the release script takes care of updating the composer configs of split packages.

**Comment by othercorey** [comment]
@markstory What do you think?

**Comment by markstory** [comment]
I agree with ADmad that folks are unlikely to test RC versions. However, I don't think this should merge until we're closer to doing the final release. How about after the RC2 release is done?

**Comment by ADmad** [comment]
> How about after the RC2 release is done?

Fine by me.

**Comment by ADmad** [comment]
@markstory Good to merge now? We aren't going to do any more RCs.

**Comment by dereuromark** [comment]
Was this supposed to be merged without the release?
As is, it seems to fail in CI. I guess we would need `@RC` appending for now

**Comment by ADmad** [comment]
The failures will be fixed upon 5.1.0 release, I don't think it's necessary to add `@RC` just to remove upon final release.

**Pull request merged**
