### PR TITLE
Use View class when rendering error page for nested errors.

### LINKED ISSUE #9830: ExceptionRenderer makes use of AppView, causing an infinite loop when missing a Helper.
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.9
* Platform and Target: Vagrant bento/debian-8.6 with PHP7.0.13-1~dotdeb+8.1

### What I did
I created a new project, where I loaded a git submodule into the plugins in order to start updating my TableHelper plugin. The goal of this project was to setup a sandbox to develop plugins.
I loaded the plugin and then added `$this->loadHelper('TableHelper.Table');` to the `initialize()` method of the default `AppView`.

### What happened
My helper wasn't loaded with the following message on the screen:

> An Internal Server Error Occurred

I checked the error.log of Apache, tried to find an error log of PHP but nothing there. After a couple of hours debugging I found out that my php.ini didn't log php errors. So, changed that and went back into the code and tried to find the log file.

Nothing.

So after a tip on Stackoverflow I kept adding `die()` methods in the core of CakePHP and after another couple of hours, I think I found out what is wrong.

### What I think is wrong

I believe the default `ExceptionRenderer` is using the `AppView` as viewClass, right? Now, when I load a helper that doesn't exist, it will try to render an exception. But, that exception renderer is creating a new instance of `AppView` and thus trying to load the non existing helper again, and again, and again...

At first I thought I was wrong, and I still don't believe it actually, but after some more debugging I think I confirmed this.

### Howto reproduce

- Create a new project, make sure you see the default cake page.
- Add `debug($className);` at https://github.com/cakephp/cakephp/blob/master/src/View/ViewBuilder.php#L362
- Refresh the page, as expected you see `AppView` popup.
- Add an Exception somewhere in `AppController::initialize()`.
- Refresh the page, you'll see `AppView` two times, as expected

This confirms AppView is being used by the ExceptionRenderer.

- Remove the Exception from the AppController
- Add `$this->loadHelper('FooBar')` to `AppView::initialize()`.
- Refresh, your page, now you'll see `AppView` three times and then `An Internal Server Error Occurred`

### What you expected to happen
A 500 Exception with a 'Missing Helper' message of some sort.

### Proposed solution
A dedicated 'ExceptionView' which makes sure no programmer input is messing up the view. If I want the ExceptionRenderer to use my own `AppView` I will have to opt-in, instead of opt-out.

#### PS.
The error.log in the logs dir did log the missing Helper message, but I wasn't expecting this `internal server error` message and so I thought something else was wrong. Therefore I had to dig into it as I believed I was making a mistake.

It was also hard to debug as I tested it on another project (also Cake3) but that uses a custom viewClass (but not for the ExceptionRenderer). So when I loaded a non-existing helper there, it wasn't showing this error as the infinite loop wasn't present. Which caused even more of a headache as I wasn't expecting this simple bug.

### PR DESCRIPTION
**Pull request by ADmad**
Fixes #9830

### CODE REVIEW

**Comment by markstory** [comment]
Looks good to me. If we can't render an error page with the developer's view classes using 'safer' view classes is a pretty reasonable approach.

It does mean that people will have a harder time customizing the developer error pages, but I think that is a reasonable tradeoff to make.

**Comment by ADmad** [comment]
Yeah `_outputSafeMessage()` is used when rending an error page "normally" fails, so it's appropriate to retry with only minimalistic view config.

I replicated @JelmerD's  issue by loading a non existent helper in `AppView` and after this fix I got dev error page using missing helper template.

**Comment by JelmerD** [comment]
@ADmad wasn't the first time I messed something up myself with corrupted files, so nuking the thing was the simplest solution for me :). Who cares with Vagrant, right?. Thank you very much for the quick and simple patch!!!

And concerning what @markstory mentioned. Developer error pages. Might it be a nice addition to make this easily to override as an extra option in the `App.php`?

```
'Error' => [
        'safeOutputMessageView' => 'Cake\View' //default, with an explanatory docblock
    ],
```

Or just do it as the `extraFatalErrorMemory` option, mention it in the docblock, but don't show it in the options, yet.

This way, it's easy to change. Or do we just accept that the developer has to extend the `ExceptionRenderer` and changes the content of `_outputMessageSafe`?

**Comment by ADmad** [comment]
@JelmerD Allowing the safe output message View class to be configurable by user would open the possibility of ending up in the same situation as when using AppView, so that's definitely not a good idea.

**Comment by JelmerD** [comment]
True that. Let's keep it like this :)

**Pull request merged**
