### PR TITLE
Fix case

### PR DESCRIPTION
**Pull request by remicollet**
To match https://github.com/cakephp/cakephp/blob/master/tests/Fixture/BinaryUuidItemsFixture.php

### CODE REVIEW

**Comment by othercorey** [comment]
I'm not sure why just this fixture was changed previously, but many more need to be changed to align it if we want to have `binary_uuid_items` table name.

**Comment by remicollet** [comment]
@othercorey btw, you see the problem, classe name case are inconsistent in code, raising issue with Psr4 autoloader (class not found)

**Comment by dereuromark** [comment]
Yes, all fixture names should have been cleaned up in 4.2.
We should probably fix up the rest as well now.

**Comment by dereuromark** [comment]
Ah, from the looks only this one file has a psr issue
https://github.com/cakephp/cakephp/tree/master/tests/Fixture

The others can remain in the former naming for the time being for BC reasons now.

So all good

**Pull request closed without merging**
