### PR TITLE
Ensure case sensitive method name matching when invoking action.

### PR DESCRIPTION
**Pull request by ADmad**
Refs #12793.

### CODE REVIEW

**Review by markstory — APPROVED** [review]
Looks good to me. This change should be added to the migration guide too.

**Comment by dereuromark** [comment]
If we do this, shouldnt we also care about the controller, plugin and prefix?
Or is this already fixed by design - or not relevant?

**Comment by ADmad** [comment]
For controller/plugin/prefix it needs to match the FQCN which is case sensitive, hence no problem there.

**Comment by dereuromark** [comment]
:+1: 

The checks fails seem unrelated.

**Pull request merged**
