### PR TITLE
Rename LICENSE.txt to LICENSE

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/cakephp/issues/10428
Recommended approach anyway - also consistent with most plugins and other libraries.

### CODE REVIEW

**Comment by inoas** [comment]
Ref: https://github.com/symfony/symfony/blob/master/LICENSE
Ref: https://github.com/rails/rails/blob/master/MIT-LICENSE (LOL they take MIT-LICENSE but not LICENSE.txt - wtf)

**Comment by ADmad** [comment]
Extension doesn't seem to matter, e.g. https://github.com/ADmad/cakephp-glide/blob/master/LICENSE.txt

**Comment by inoas** [comment]
Maybe then the MIT license text itself needs an update?

**Comment by cleptric** [comment]
> In the file name field, type LICENSE or LICENSE.txt (with all caps).

So we should be fine. Don't know why github isn't adding the header to the branch @dereuromark just created.

**Comment by dereuromark** [comment]
OK, maybe its the additional 2nd data row:

    CakePHP(tm) : The Rapid Development PHP Framework (http://cakephp.org)

That messes up their parsing.

**Comment by inoas** [comment]
See my PR here: https://github.com/cakephp/cakephp/pull/10430

However I can see the usefulness of that line.

**Pull request closed without merging**
