### PR TITLE
Fixed Xdebug issue in combination with isConnected() #10836

### PR DESCRIPTION
**Pull request by odan**
Xdebug uses PHP's var_dump() function for displaying variables.
https://xdebug.org/docs/display

Setting a breakpoint at or before a line with a lastInsertId() method call the __debugInfo() method of the Driver object was magically called by Xdebug and PHP.

Within the __debugInfo() a new SELECT 1 statement was called and cleared the lastInsertId of the connection. Instead of a new SELECT we only check the state of the connection object now.

You can find more details here: #10836 (comment)

### CODE REVIEW

**Comment by lorenzo** [comment]
What was the issue?

**Comment by odan** [comment]
You can find the more details here: https://github.com/cakephp/cakephp/issues/10836#issuecomment-311912675

**Comment by jeremyharris** [comment]
Should there be a comment above this change to reference the issue so it doesn't accidentally get reversed?

**Comment by ADmad** [comment]
@jeremyharris The commit message does include the ticket number so if you check file's history or blame you would have the reference to the issue :)

**Pull request merged**
