### PR TITLE
Including a option for calling plugin flash elements through magic method

### PR DESCRIPTION
**Pull request by andre-pdassis**
What happens? __call() always override $options['element'] to instantiate set()
What I did? I added a check for a plugin key in $args

Now there are two options for calling plugin flash elements:
- `$this->Flash->set('Message', ['element' => 'PluginName.element_name']);`
- `$this->Flash->elementName('Message', ['plugin' => 'PluginName']);`

### CODE REVIEW

**Comment by ADmad** [comment]
The magic methods are meant for convince. `$this->Flash->elementName('Message', ['plugin' => 'PluginName']);`  doesn't look any more convenient to me than `$this->Flash->set('Message', ['element' => 'PluginName.element_name'])`.

So I am a :-1: to this.

**Comment by markstory** [comment]
How would this be used, there are no tests.

**Comment by andtxr** [comment]
Actually, I have only found test cases for ``FlashComponent::set()``.
I appreciate if someone could help.

**Comment by jadb** [comment]
@ADmad while I agree with you that it doesn't really add any aesthetics, it does however allow one to stick to using `__call()`'s magic everywhere instead of having different calls for flash (when using a plugin and when not). What do you think? 

:+1:

**Comment by markstory** [comment]
@andtxr Looks like an omission in the original implementation of FlashComponent. I can add some tests for the existing code.

**Comment by ADmad** [comment]
@jadb That's a fair argument.

**Comment by markstory** [comment]
This looks good to me. :+1:

**Comment by ADmad** [comment]
It would help if usage example were added to the api docblock.

**Comment by markstory** [comment]
Thanks :+1:

**Pull request merged**
