### PR TITLE
5.next: add vscodium to Debugger

### PR DESCRIPTION
**Pull request by LordSimal**
Refs: https://discourse.cakephp.org/t/vscodium-editor-support-for-links-on-error-page/12330

### CODE REVIEW

**Comment by ADmad** [comment]
> Regarding the PR … I don’t have a Github account as it is from Microsoft

Only a handful of "special" individuals like them would be using vscodium.

**Comment by LordSimal** [comment]
I don't mind it either way, so it's up2you guys how you want to handle that.

**Comment by dereuromark** [comment]
This single line doesnt seem to hurt to add I guess.
The other option would be to make this list more extendable (configurable).

**Comment by ADmad** [comment]
> The other option would be to make this list more extendable (configurable).

We have already provided the API to add additional editor templates, `Debugger::addEditor()`.

**Comment by LordSimal** [comment]
I guess its more of a question which Editors do we support out of the box?
E.g. textmate and macvim are only available for MacOS.

**Comment by ADmad** [comment]
This comment should be updated too https://github.com/cakephp/app/blob/6b774dcf0a1dae6e02b9c9bb1fce56d9b731299c/config/app.php#L186

**Pull request merged**
