### PR TITLE
using JSON_UNESCAPED_UNICODE with json_encode()

### PR DESCRIPTION
**Pull request by mosaxiv**
It is useful for debug

```
{
    "id": 1,
    "word": "\u30c6\u30b9\u30c81",
    "created": "2018-03-29T01:41:58",
    "modified": "2018-03-29T01:41:58"
}
```

↓

```
{
    "id": 1,
    "word": "テスト1",
    "created": "2018-03-29T01:41:58",
    "modified": "2018-03-29T01:41:58"
}
```

### CODE REVIEW

**Comment by dereuromark** [comment]
This sounds like it would be safer to apply to 3.next (3.6).

**Comment by markstory** [comment]
Couldn't this cause issues with some JSON parsers?

**Comment by dereuromark** [comment]
Could we move the constant integer hardcoded here up into a protected class const? 
This way it could be overwritten on project level more easily?

    const OPTIONS = JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE;

etc?

**Comment by markstory** [comment]
Closing this as I'm not comfortable with the potential risk this presents. For applications that need this option you can use the `_jsonOptions` flag to control the options passed to `json_encode()`.

**Pull request closed without merging**
