### PR TITLE
Adds license file and badges for ORM subtree split

### PR DESCRIPTION
**Pull request by bravo-kernel**

### CODE REVIEW

**Comment by lorenzo** [comment]
Thanks!

**Comment by lorenzo** [comment]
@bravo-kernel It would be nice if you could do this with the rest of the components :D

**Comment by bravo-kernel** [comment]
It would, wouldn't it :wink:

**Comment by bravo-kernel** [comment]
seriously, which ones are we talking about here?

**Comment by lorenzo** [comment]
core, utility, i18n, database, collection, validation, datasource, log, filesystem and event :D

**Pull request merged**
