### PR TITLE
Allow to use the connection name with the option "connectionName" in …

### LINKED ISSUE #7644: 3.1 - Allow to use the connection name with the option "connection" in TableRegistry::get()
Hello,

I'm doing a little application to transfer data from a database to another database.

My config :
```php
use Cake\Datasource\ConnectionManager;

ConnectionManager::config('old', [
    'className' => 'Cake\Database\Connection',
    'driver' => 'Cake\Database\Driver\Mysql',
    'database' => 'old_fmt',
    'username' => 'root',
    'password' => 'root'
]);

ConnectionManager::config('new', [
    'className' => 'Cake\Database\Connection',
    'driver' => 'Cake\Database\Driver\Mysql',
    'database' => 'new_fmt',
    'username' => 'root',
    'password' => 'root'
]);
```

Now, to use the config i must do :
```php
$connection = ConnectionManager::get('old');
$this->Applications = TableRegistry::get('Applications', ['connection' => $connection]);
```

But it would be easy and DRY to use that instead :
```php
$this->ApplicationUsers = TableRegistry::get('ApplicationsUsers', ['connection' => 'old']);
```

What do you think ?

### PR DESCRIPTION
**Pull request by skie**
…TableRegistry::get and TableRegistry::config. Fixes #7644

### CODE REVIEW

**Comment by markstory** [comment]
Looks good to me.

**Comment by lorenzo** [comment]
This new option show be added to the doc block for TableRegistry

**Comment by skie** [comment]
@lorenzo TableLocator is only the place where we had conection options described. TableRegistry::get has very brief documentation without any options specific.

**Comment by markstory** [comment]
Does TableRegistry::get() link to the TableLocator API docs? Having duplicate docs is not always good.

**Comment by skie** [comment]
Do you mean add something like

     *   See options specification in {@link TableLocator::get()}.

**Comment by markstory** [comment]
@skie yes.

**Pull request merged**
