### PR TITLE
Add enum column type support to schema functions

### PR DESCRIPTION
**Pull request by alphp**
The command "Console/cake schema generate/create" does not work with Enum type fields by default. You will always get NOTICE's while doing so, and won't be able to restore them.

Based on: https://github.com/matheuscmpm/cakephp-schema-enum

### CODE REVIEW

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/cakephp/pull/7332

**Comment by alphp** [comment]
PostgreSQL enum type: https://www.postgresql.org/docs/9.1/static/datatype-enum.html
Oracle enum type: https://docs.oracle.com/cd/E17952_01/mysql-5.0-en/enum.html
MySQL/MariaDB enum type: https://dev.mysql.com/doc/refman/5.7/en/enum.html

**Comment by markstory** [comment]
This seems like an incomplete implementation of `enum` support that doesn't include tests. I'm very reluctant to merge this kind of change into 2.x which is in bugfix only mode. 2.x has never supported `enum` columns so I'm not sure how this counts as a bugfix to an existing feature.

**Comment by alphp** [comment]
And then these error messages are just a feature of CakePHP 2?
```
2018-02-15 00:01:44 Debug: Schema generation error: invalid column type enum('Nivel Ã“ptimo','Completado satisfactoriamente','Completado insatisfactoriamente','Incompleto') for ActionPlan.rating does not exist in DBO in [C:\usr\0xFF\angulas\app\Lib\Model\CakeSchema.php, line 628]
2018-02-15 00:01:44 Debug: Schema generation error: invalid column type enum('Completado satisfactoriamente','Completado insatisfactoriamente','Incompleto') for ActionPlanItem.rating does not exist in DBO in [C:\usr\0xFF\angulas\app\Lib\Model\CakeSchema.php, line 628]
2018-02-15 00:01:44 Debug: Schema generation error: invalid column type enum('proyectos','valores','competencias','bolos') for Item.type does not exist in DBO in [C:\usr\0xFF\angulas\app\Lib\Model\CakeSchema.php, line 628]
2018-02-15 00:01:44 Debug: Schema generation error: invalid column type enum('responsable','orientador') for Orientator.rol does not exist in DBO in [C:\usr\0xFF\angulas\app\Lib\Model\CakeSchema.php, line 628]
2018-02-15 00:01:44 Debug: Schema generation error: invalid column type enum('admin','rrhh','responsable','guiado') for User.type does not exist in DBO in [C:\usr\0xFF\angulas\app\Lib\Model\CakeSchema.php, line 628]
```
If there was no solution or if it was a complex and extensive, I would understand that even minimal support was not implemented.
However, a single line added to Cake/Model/Datasource/Database/MySQL.php and six in Cake/Model/CakeSchema.php support the scheme with ENUM in MySQL.

There are already plugins to support the ENUM in the forms, so it would not be necessary to add support for the forms and you can always add the warning that the only support is for the maintenance of the scheme, which in my opinion is the most important and complex maintain.

**Comment by alphp** [comment]
By the way, the existing feature is "Schema Shell" ... but if you do not want to continue maintaining it ...

We could argue that support for the SET type, or other types of other databases, will also be requested. But the truth is that this PR solves the support for the ENUM type to the "Schema Shell" ... because let's be honest the complete support for all the data types of all the databases will never be achieved, but if someone uses a type of data in your CakePHP projects and add the necessary code for your support. Why should that support be relegated to something external to CakePHP?

**Comment by josegonzalez** [comment]
A few notes:

### This is a new feature, not a bugfix

The error message is actually a generic one:

```
trigger_error(__d('cake_dev', 'Schema generation error: invalid column type %s for %s.%s does not exist in DBO', $value['type'], $Obj->name, $name), E_USER_NOTICE);
```

From: https://github.com/cakephp/cakephp/blob/f1db01395b89e5b43cb3f330ba25a51a3192ecc4/lib/Cake/Model/CakeSchema.php#L627-L629

We've traditionally not supported enums for a few reasons, but as CakePHP 2 has never had this functionality, I'd consider this a new feature.

### The implementation is incomplete

When we say incomplete, we mean that your pull request does not feature is not implemented for each datastore in the CakePHP 2.x core. Even beyond the fact that not all - sqlite - databases do not support enums, in order for this to be merged, I would say that this would _definitely_ be required to support Postgres and SQL Server.

### There are no tests

We absolutely cannot introduce new functionality/bug fixes without tests. When we add code to the core, it increases our support footprint. While I'm sure the above works well, it will inevitably have bugs in random edge cases (thats just programming). We can at least ensure that basic functionality will continue working with any refactor/fix.

This isn't specific to just this pull request, but all pull requests. We - and our users! - greatly appreciate our test coverage :) .

### CakePHP 2.0 is in maintenance mode

We have supported 2.x long enough and [clearly communicated](https://bakery.cakephp.org/2017/07/22/cakephp_2100_released.html) that it's in bugfix only mode now. We both cannot:

- backport 3.x features to 2.x
- add new functionality to 2.x

Doing so will add to our maintenance overhead. As a group of volunteers contributing their spare time for free there's only so much we can do, and at the moment we are focused on maintaining 3.x and moving towards 4.x.

### Closing thoughts

I personally don't like enums in databases for various reasons.

- They are hard/annoying to change on tables will millions of records.
- They go against data normalization.
- You can use enums in code and store integer constants instead, and use validation rules to validate the range (doesnt scale across codebases/languages, but neither does using hardcoded strings).
- You may eventually need to add metadata to each constant, so a related table is better (premature optimization though).
- Forms require you to query for all possible values before returning the possibilities.
- If you need the same enum on multiple tables, it's going to eventually get out of sync somewhere. MySQL will cast invalid values to empty string - might not anymore, haven't checked = which isn't great.
- Doing i18n translation on the values is kinda weird, and can't be done within the database.

While we appreciate this pull request - all contributions are welcome! - I don't think we're in a position to merge the pull request at this time.

If you'd like to continue using this functionality, I encourage you to vendor these changes locally or use a forked version of cakephp 2.x with this patch in your composer manifest.

**Comment by alphp** [comment]
Are we really going to discuss here about the suitability or not of the ENUM types?
Does anyone really think that I, who have been programming for more than 30 years, have not thought very well if I used those guys in those fields enough to determine what was the least bad option?
NO, please, do not get into useless discussions, thank you.

**Comment by ADmad** [comment]
I don't think we need to get into the suitability of enums here.

The lack of enum support is a known limitation and not a bug. Since 2.x is in bugfix only mode now, we cannot accept any new feature additions. Hence closing this PR.

**Comment by alphp** [comment]
As I see it, the questions to answer are:
- Should the "Shell Schema" be left without support for a type of data that is used in projects and causes errors?
- Is it necessary to include a test to admit the PR?
- Is it necessary to have full support to admit the PR?
- Does this PR break compatibility with other databases?

But apparently the "only bugfix" does not work in this way.
Enum already existed before CakePHP 2, the lack of support of "Shell Schema" has always been, at least, a TO-DO.
In the past there was already someone who was interested in adding support, and also who was interested in having support for the ENUM type.
But the same complaints were made that I summarize in: "I hate ENUM and nobody should use it"
But that is not a correct or realistic position.
You have already made the decision, I do not share it but I have to comply with it. I will continue to use and support CakePHP, of course. I will continue trying to contribute what I can. But today I am sad and angry about the decision made.

**Pull request closed without merging**
