### PR TITLE
Drop usage of deprecated phpunit API

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
The "6.0 Ideas" WIKI page has an item `Replace PHPUnit mock provided by getMockForModel with Mockery instance`.
Should we go ahead with that change?

**Comment by LordSimal** [comment]
as far as I remember we said:

If possible convert the mock object into a real object.
If certain methods need to be overwritten or adjusted, then an anonymous class should be used instead of mocking.
If anonymous class overwrites are not possible for the given usecase, then use Mockery.

**Comment by ADmad** [comment]
@LordSimal What you listed out applies to how we should use classes/mocks in the core. We can't dictate/control how the community uses mocks and the API we provide for generating them.

So in case of `getMockForModel()` we mainly need to think from the community POV. Changing it to return mockery instance instead of phpunit mock would mean users having to change all their expectation calls.

**Comment by LordSimal** [comment]
Right, for users this shouldn't change imho.

Users need to decide for themselves if they want to change to Mockery or not.

**Comment by ADmad** [comment]
Okay, so this is patch should be enough.

There are about 15 uses of `getMockForModel()` in the core. We can try and get rid of them.

**Comment by ADmad** [comment]
> There are about 15 uses of getMockForModel() in the core. We can try and get rid of them.

Actually only 2-3. Rests are tests for the method itself.

**Pull request merged**
