### PR TITLE
Include sniff name in error message

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by othercorey** [comment]
I remember trying this and found it broke the GA reporting. Maybe I was testing incorrectly though.

**Comment by ADmad** [comment]
> I remember trying this and found it broke the GA reporting. Maybe I was testing incorrectly though.

In that case I'll generate an error to test.

**Comment by othercorey** [comment]
That might have been before cs2pr was added. I don't remember exactly what order I made the changes :(.

**Comment by ADmad** [comment]
So using the `-n` flag doesn't break the GA reporting but doesn't show the sniff name either :(

@markstory Stickler needs looking into, it's passing even though there is an error.

**Comment by markstory** [comment]
> Stickler needs looking into, it's passing even though there is an error.

I've not updated the phpcs version in a bit I'll try that.

**Comment by othercorey** [comment]
We can merge this if you want. I recall this is the issue I had. The checkstyle output seems to omit that info.

**Pull request merged**
