### PR TITLE
Add support for Table magic findBy* methods in phpstan

### PR DESCRIPTION
**Pull request by segy**
see title

### CODE REVIEW

**Comment by markstory** [comment]
Looks good. How does PHPStan know how to use these files?

**Comment by inoas** [comment]
What about removing magic findByX automagic finders in 4.x?

**Comment by dereuromark** [comment]
@ionas Those can maybe be extracted into an own plugin extension or sth?
This way people can use it if they want, but it wouldn't be core anymore directly.

**Comment by markstory** [comment]
Why would we remove them? They are well documented, tested and easily not used if they are not your taste.

**Pull request merged**
