### PR TITLE
Include previous exception in log message if present

### PR DESCRIPTION
**Pull request by ceeram**
Allow to opt-in for including previous exceptions (if present) in logging.

### CODE REVIEW

**Comment by dereuromark** [comment]
Why not including by default? Would make the config for it unneeded.

**Comment by ceeram** [comment]
That would change logging output, who knows it might break someones tooling. Personally i would indeed enable it by default in our applications.

**Comment by ceeram** [comment]
how would one make this pass: https://ci.appveyor.com/project/cakephp/cakephp/builds/19730534

**Comment by dereuromark** [comment]
3.7 by default could be an idea then.
i dont think we need an option to enable/disable here.

**Comment by lorenzo** [comment]
I'd love to have that by default :)

**Comment by ceeram** [comment]
so, no opt-in config? or no config at all, and just always include it?

**Comment by ceeram** [comment]
btw, we could have app.default.php in cakephp/app have it enabled by default, if we choose to keep the config, no matter the default value we use here, so we wont break old logging output and new applications get this by default. Or maybe we dont need to support BC on format of error logs at all

**Comment by markstory** [comment]
I don't think we need a config flag if it is in 3.7.0. We can document that the log format is changing in the migration guide. Folks who are munging logs will have to update their tooling.

**Review by markstory — APPROVED** [review]
Looks good to me.

**Review by ADmad — APPROVED** [review]

**Comment by ADmad** [comment]
@ceeram Can you please open a PR updating the docs too.

**Pull request merged**
