### PR TITLE
Added Json api & 

### PR DESCRIPTION
**Pull request by pbaire**
Added jsonapi media type to response media types [ http://jsonapi.org/format/ ]
Added jsonapi deserializer to RequestHandler

### CODE REVIEW

**Comment by ravage84** [comment]
Can you add a test for each class, please?

**Comment by pbaire** [comment]
sure! but in what class?
i've looked for similar test but I haven't found!
I've checked RequestHandlerComponentTest and in ResponseTest
and i don't see any test for others content type (for example 
 'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' )

**Comment by ravage84** [comment]
May be they actually don't exist, which would be bad, but no excuse for us not to cover new functionality witha proper test. :smirk_cat: 

Could you try to set up a test for each class that only tests your new functionality?
Once done and merged, we can cover the rest accordingly.

**Comment by ADmad** [comment]
Adding more default input type mapping would go against #7212. I would rather people explicitly configure the mapping they need.

**Comment by ADmad** [comment]
We should just add the mime type in response class.

**Comment by markstory** [comment]
> We should just add the mime type in response class.

Yes. Also jsonapi feels like the kind of thing that belongs in the app, and not a default mapped type.

**Comment by ADmad** [comment]
@pbaire Please update your PR to just add the mime type to Response class.

**Comment by pbaire** [comment]
@ADmad , @markstory I totally agree! 
I haven't checked the #7212 before sending the pull request! and I really like its result #7315 ! 
pull request updated with just the add of mime type in response class.

**Comment by markstory** [comment]
Thanks @pbaire

**Comment by pbaire** [comment]
My pleasure @markstory

**Pull request merged**
