### PR TITLE
Removed MariaDB version check

### PR DESCRIPTION
**Pull request by othercorey**
This was left from the CommonTableExpression work. We don't support MariaDB in the mysql driver directly anywhere else. I assume users will have a separate driver for this.

If we do need to support it, we should decide and fix it now so we can have proper version checks in other places.

### CODE REVIEW

**Comment by ADmad** [comment]
While we may not officially document it I am sure there are people using the `Mysql` driver for MariaDB so we should keep support for it. We can move the check to a more appropriate location if necessary.

**Comment by othercorey** [comment]
> While we may not officially document it I am sure there are people using the `Mysql` driver for MariaDB, so we should keep support for it. We can move the check to a more appropriate location if necessary.

I'm ok with that. To summarize my thoughts/discussion in the CTE PR:

- Makes sense to have a separate MariaDB version
- Doing versions checks off the mysql version that mariadb version "supports" sounds dangerous

I think in most places we could just do something like `if mysql version > X or maria version > Y` and not check if it's actually one or the other. So the empty maria version should fail any version check.

**Comment by ADmad** [comment]
@markstory Wasn't this merged prematurely? The alternate code to removal of MariaDB version check in current PR hasn't been implemented.

**Comment by markstory** [comment]
My bad. Sorry about that.

**Comment by ADmad** [comment]
No problem. I'll create a new separate issue.

**Pull request merged**
