### PR TITLE
3.x - Add github actions and reduce travis to prefer-lowest

### PR DESCRIPTION
**Pull request by othercorey**

### CODE REVIEW

**Comment by othercorey** [comment]
This is mostly working except for some locale-specific tests.

**Comment by othercorey** [comment]
I cannot get the memcache clear() test to pass on 5.6 even with a 2s delay.

**Comment by othercorey** [comment]
> I cannot get the memcache clear() test to pass on 5.6 even with a 2s delay.

The issue appears to be `getAllKeys()` which is returning CLIENT_ERROR.

**Comment by markstory** [comment]
We could skip the problematic test if getAllKeys() fails.

**Comment by othercorey** [comment]
> We could skip the problematic test if getAllKeys() fails.

I cleaned up my fixes. I'm not familiar with memcached api someone else will have to finish this.

**Comment by markstory** [comment]
I can take a look.

**Pull request merged**
