### PR TITLE
Fix regression in integration testing

### PR DESCRIPTION
**Pull request by dereuromark**
This resolves the regression introduced in 3.6.5 via
https://github.com/cakephp/cakephp/compare/3.6.4...3.6.5#diff-3d58de79d11037069356ea3dd5556605R126

Resolves ticket https://github.com/cakephp/cakephp/issues/12577

Any side effects, any other (better) solutions to fix the issue?

Proof:
- status quo, failing: https://github.com/dereuromark/cakephp-sandbox/pull/12
- with this branch, passing: https://github.com/dereuromark/cakephp-sandbox/pull/13

### CODE REVIEW

**Comment by markstory** [comment]
Without this `reload()` call routes loaded as part of resolving a testcase URL are retained, and then when `RoutingMiddleware` goes to load routes again during the request applications using named routes will likely hit a duplicate route error.

**Comment by dakota** [comment]
This was part of the fix that allowed our large application to be upgraded to CakePHP 3.6.

**Comment by dereuromark** [comment]
Any ideas then how we can solve the regression in integration test cases without compromising the other use cases?

**Comment by saeideng** [comment]
@dereuromark
what I'm seeing here , this related to this commit https://github.com/cakephp/cakephp/commit/135957df21e54436ece2a068457c9c3ea02458eb#diff-3d58de79d11037069356ea3dd5556605R81
see order of using `Router::reload();` before/after this commit

**Comment by dereuromark** [comment]
I saw the same. I bet there is no test for extension routing. That would probably show the issue.

**Comment by markstory** [comment]
An alternative option could be to have the test harness call (a new not yet implemented method) that just resets the connected routes. Something like:

```php
Router::getRouteCollection()->clear()
```

This would leave extensions and middleware untouched but clear routes preventing duplicate named route errors.

**Comment by dereuromark** [comment]
I am fine either way as long as we find a way quickly to resolve this regression.
Tests all being red for months is not good for CI and continues integration testing.

An alternative could also be to modify

    return new MiddlewareDispatcher($this, $this->_appClass, $this->_appArgs);

call to allow the test harness to configure/flag-switch the above PR change (new optional argument?), this way we could shim it down for the cases needed.
Even though that would more be a quick fix for 3.6 for now, as your suggestion seems to aim more into a long-term solution.

**Comment by markstory** [comment]
Closing in favour of #12695

**Pull request closed without merging**
