### PR TITLE
Properties should not be accessible after dumping.

### PR DESCRIPTION
**Pull request by markstory**
Adds tests for #6822. @lorenzo I wasn't able to reproduce the issue you had with a userland class. What version of PHP did you bump into this with?

### CODE REVIEW

**Comment by lorenzo** [comment]
I'm using 5.6

**Comment by lorenzo** [comment]
@markstory maybe it is only specific with datetime?

**Comment by markstory** [comment]
Could be a native extension vs. userland class issue. I'll try adding a test with native objects.

**Comment by markstory** [comment]
So it was an issue specific to DateTime it seems, as updating the test to use `DateTime` it then fails, as timezone is left accessible. Marking the property as not accessible did not help, I'll see if there is an existing bug in PHP for this, or I'll make a new one.

But for now, I'll close this as we can't do much in CakePHP. The following script shows the issue we've bumped into:

```php
<?php
$subject = new DateTime('2015-06-24 22:09:00');
var_dump(isset($subject->timezone));

$reflection = new ReflectionObject($subject);
foreach ($reflection->getProperties() as $prop) {
    $prop->setAccessible(true);
    $prop->setAccessible(false);
}
var_dump(isset($subject->timezone));
```

**Comment by markstory** [comment]
[PHP bug opened](https://bugs.php.net/bug.php?id=69925).

**Pull request closed without merging**
