### PR TITLE
Fix invalid type hint

### PR DESCRIPTION
**Pull request by bancer**

### CODE REVIEW

**Comment by dereuromark** [comment]
That is a heavy BC break
Please see the discussion of https://github.com/cakephp/cakephp/pull/13457 for details why this is not a good change at this time.

**Comment by ADmad** [comment]
Yeah technically typehints shouldn't be changed in bugfix releases (or even minor as per our BC guidelines).

This change can be done in 4.x instead.

**Comment by bancer** [comment]
@dereuromark Sorry, I saw your comments there only after I committed here.

**Comment by dereuromark** [comment]
Instead of removing interfaces, we should have more interface contracting in 4.x.
Maybe we should get better at interface segregation and providing more correct "contracts" per scope instead.

**Comment by ADmad** [comment]
Please reopen a new PR targeting `4.x` branch.

**Pull request closed without merging**
