### PR TITLE
test function to confirm #9711

### PR DESCRIPTION
**Pull request by rrd108**
Test function to confirm issue #9711

### CODE REVIEW

**Comment by dereuromark** [comment]
@ all: Is here something to be done still?

**Comment by robertpustulka** [comment]
@dereuromark tests fail

**Comment by dereuromark** [comment]
Sure, I just wonder why no fix PR is provided then. Is the fix necessary, or is the assumption here on how it should work wrong. We should resolve this PR either way.

**Comment by dereuromark** [comment]
Closing as this has gone stale.

**Pull request closed without merging**
