### PR TITLE
WIP - 3.0 - Connection prefix

### PR DESCRIPTION
**Pull request by HavokInspiration**
As mentionned in #3843, a fresh start to implement the connection prefix feature.
At this point, this commit puts the PR back to the state it was, but with an up to date Cake 3.0 version (and better managed branches on my side)

Refs #2666 and #4118 

To do :
- Update Schema system so it takes into account the connection prefix (if any)
- Maybe update the \ORM\Table class (I have a written note about that on my desk, so I guess "past me" put the finger on something I may have forgotten)
- Make Fixtures apply connection prefixes

I'll probably have some questions about testing with / without a prefix and making the fixtures apply the prefix. I know I got stuck on something regarding this but can't exactly remember what. I'll dive in this again and ask you as they come up.

### CODE REVIEW

**Comment by HavokInspiration** [comment]
Hi there.
Sooooo. Where am I more than a month since my last post ? I surely did not give up on this.

About the pluginization (is that a word ?) of the feature, I did give up.
While very tempting as it would have been simpler to manage, it turns out that there was too much things to rewrite and it would have been really messy to maintain.

Right now, I started almost from scratch but I did not go for a "node" based solution (meaning without a TableNameExpression as in this PR). I instead went with a regex based solution which is, in my opinion, a bit cleaner as most of the heavy lifting will be done only by two classes (instead of having to modify the QueryCompiler and everything with expression). 

It's too early for me to submit a PR right now, I have some polishing to do as well as some tests to add and fix (I've just set up Travis to work on my fork and it tells me that Postgre does not really like me).
I will probably close this PR when the new one is ready.

Cheers.

**Comment by markstory** [comment]
Sounds good @HavokInspiration. Thanks for the update.

**Comment by josephzidell** [comment]
@HavokInspiration While I don't have the time to work on this, can I suggest a different approach? Instead of defining a prefix on the connection, define it on the `Table`. Would that simplify things?

**Comment by HavokInspiration** [comment]
@josephzidell Thanks for your input. It also crossed my mind at some point.

However, the Connection object is the common object between everything that needs to apply a prefix to table names : Schema | Schema\Table object, ORM\Table object, the Query system, etc.
Fixtures are also created using an instance of Connection (through a Schema\Table object to be precise) and they are populated with a Query instance generated from the Connection.
Which is why having the prefix in the Connection object is the perfect place to have it work with the entire framework, even though it needs more work to implement it.

**Comment by burzum** [comment]
@HavokInspiration nice work so far! Please keep working on it! :+1:

**Comment by HavokInspiration** [comment]
Yup, I'm still working on it.
Fixtures and adding permutations to the DatabaseSuite gave me a hard time though.
I'm adding some tests right now. And after that I'll have to do some polishing (I have a couple of things to make DRY).

**Comment by lorenzo** [comment]
For people still wanting support for prefixes in their tables, there is a way to support it using events. This will probably work for all table operations. Add it to your bootstrap.php file:

```php
EventManager::instance()->on('Model.initialize', function ($event, $instance) {
    $instance->table('prefix_' . $instance->table());
});
```

**Comment by AD7six** [comment]
If that suggestion works @lorenzo I am very much in favor of documenting and promoting it - it's much less code, and removes all potential complexity from cakephp's code.

**Comment by ionas** [comment]
Does it work on a per plugin basis? Does it work with cake bake?

**Comment by lorenzo** [comment]
@ionas works for plugin, but not bake

**Comment by ionas** [comment]
@lorenzo any "holistic" approach that works on a per plugin basis (plugin's AppModel) and is respected by cake bake, and the whole ORM. Use case would be plugin models that have generic names like User, Product, Address, Article, Content, etc.

**Comment by HavokInspiration** [comment]
Closing this.
The code base has been out of sync for months, and it doesn't seem to fit what people expects from the feature.
If the decision to deal with prefix at the Connection level is taken, I'll submit a new one with another approach of the solution I've been working on.
Thanks for everyone's attention, I learnt a lot :)

**Comment by burzum** [comment]
@lorenzo will this work also with fixtures? Or will you have to change that for tests to not use the prefix? Haven't tried and don't have the time to do so right now.

```php
EventManager::instance()->on('Model.initialize', function ($event, $instance) {
    $instance->table('prefix_' . $instance->table());
});
```

**Comment by lorenzo** [comment]
I would as long as you apply the prefix conditionally depending on the connection

**Comment by gonzela2006** [comment]
Hello,

Is there any plan to support table prefix for CakePHP 3?

Thanks

**Comment by markstory** [comment]
@gonzela2006 Not unless someone puts together a set of changes to add it that doesn't add a disproportionate amount of complexity to the database/ORM layers. This thread contains several ways to achieve prefixes as well.

**Pull request closed without merging**
