### PR TITLE
Fix #6097

### LINKED ISSUE #6097: newEntity - update with primary key
```
$this->Articles->newEntity([
    'id' => 2,
    'title' => 'updated title',
    'text' => 'updated text'
]);
```
I would suspect that the entity contains the primary key and the updated title and text but it contains the record from the database with all fields.
This is done in ORM/Marshaller.php::one() since the fix #6086

### PR DESCRIPTION
**Pull request by markstory**
Fix #6097 by allowing newEntity() to operate on existing entities when request data contains a matching primary key. While its somewhat questionable that the marshaller is doing queries for 'new' entity creation, we have to accept that people will create and update/join entities at the same time.

I've also implemented `Table::aliasField()` as discussed in #6086

### CODE REVIEW

**Comment by lorenzo** [comment]
I'm not too happy with this. It basically breaks all the security design in newEntity that prevented unintended row updates.

**Comment by lorenzo** [comment]
I think we should revert to the secure behavior and add special cases for associations:
 
* If the the association is `BelongsToMany` or `BelongsTo` allow the primary key lookup but disallow setting fields in the target association.
* If the association is `BelongsToMany` allow setting the `_joinData` property
* If `HasOne` or `HasMany` disallow primary key lookup when marshalling new entities (Basically rollback to previous behavior)

**Comment by markstory** [comment]
@lorenzo Those are fair points. I thought the query lookups added in #6086 were a bit fishy too. I agree that this change makes the boundary between new/patch very blurry.

I will split out the aliasField changes as those seem less contentious.

**Comment by mylux** [comment]
Maybe it could be possible to enable the the primary key lookup in the case we have *only* the primary key in the data structure. So, it would allow to do updates if additional data is passed. If I pass only the primary key of this entity, then I want it to be retrieved from the database. If I pass additional data, probably I don't want them to be overridden with "old" data from the database. What do you think?

**Comment by markstory** [comment]
@lorenzo Updated to only handle belongsToMany in a special way.

**Comment by lorenzo** [comment]
I'll move this to 3.1 as I think it has a lot of value, but lacks some work

**Comment by lorenzo** [comment]
Great job @markstory !

**Pull request merged**
