### PR TITLE
Add additional tests for ru translations

### PR DESCRIPTION
**Pull request by markstory**
Add additional tests for ru plural forms handling. Refs #9554

### CODE REVIEW

**Comment by Sensetivity** [comment]
How run this tests?

**Comment by markstory** [comment]
@Sensetivity You'll need to clone cakephp with git

```
git clone git://github.com/cakephp/cakephp
cd cakephp
git checkout issue-9554
composer install
vendor/bin/phpunit tests/TestCase/I18n/I18nTest.php
```

We don't include tests in zipball downloads (the default composer uses) as they are almost never used, and more than double the size of our zip files.

**Comment by Sensetivity** [comment]
Log

> Микола@МИКОЛА-ПК e:\Web\OpenServer\domains\tests.dev\cakephp\vendor\bin
> $ phpunit ../../tests/TestCase/I18n/I18nTest.php
> PHPUnit 5.6.1 by Sebastian Bergmann and contributors.
> 
> EFFFFEEEFEFFFFFFFFFEFEEE                                          24 / 24 (100%)
> 
> Time: 327 ms, Memory: 5.00MB
> 
> There were 9 errors:
> 
> 1) Cake\Test\TestCase\I18n\I18nTest::testDefaultTranslator
> InvalidArgumentException: The "_cake_core_" cache configuration does not exist.
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:148
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:190
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\I18n\I18n.php:80
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\I18n\I18n.php:139
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:70
> 
> 2) Cake\Test\TestCase\I18n\I18nTest::testCreateCustomTranslationPackage
> InvalidArgumentException: The "_cake_core_" cache configuration does not exist.
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:148
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:190
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\I18n\I18n.php:80
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\I18n\I18n.php:263
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:56
> 
> 3) Cake\Test\TestCase\I18n\I18nTest::testPluginMesagesLoad
> Cake\Core\Exception\MissingPluginException: Plugin TestPlugin could not be found.
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Core\Plugin.php:149
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Core\Plugin.php:117
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:168
> 
> 4) Cake\Test\TestCase\I18n\I18nTest::testPluginOverride
> Cake\Core\Exception\MissingPluginException: Plugin TestTheme could not be found.
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Core\Plugin.php:149
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:191
> 
> 5) Cake\Test\TestCase\I18n\I18nTest::testGetTranslatorByDefaultLocale
> InvalidArgumentException: The "_cake_core_" cache configuration does not exist.
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:148
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:190
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\I18n\I18n.php:80
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\I18n\I18n.php:263
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:56
> 
> 6) Cake\Test\TestCase\I18n\I18nTest::testTranslatorCache
> InvalidArgumentException: The "_cake_core_" cache configuration does not exist.
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:148
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:190
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:318
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:568
> 
> 7) Cake\Test\TestCase\I18n\I18nTest::testFallbackTranslator
> InvalidArgumentException: The "_cake_core_" cache configuration does not exist.
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:148
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:190
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\I18n\I18n.php:80
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\I18n\I18n.php:263
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:56
> 
> 8) Cake\Test\TestCase\I18n\I18nTest::testFallbackTranslatorDisabled
> InvalidArgumentException: The "_cake_core_" cache configuration does not exist.
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:148
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:190
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\I18n\I18n.php:80
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\I18n\I18n.php:263
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:56
> 
> 9) Cake\Test\TestCase\I18n\I18nTest::testFallbackTranslatorWithFactory
> InvalidArgumentException: The "_cake_core_" cache configuration does not exist.
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:148
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\Cache\Cache.php:190
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\I18n\I18n.php:80
> E:\Web\OpenServer\domains\tests.dev\cakephp\src\I18n\I18n.php:263
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:56
> 
> --
> 
> There were 15 failures:
> 
> 1) Cake\Test\TestCase\I18n\I18nTest::testTranslatorLoadMoFile
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'Plural Rule 6 (translated)'
> +'Plural Rule 1'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:83
> 
> 2) Cake\Test\TestCase\I18n\I18nTest::testPluralSelection
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'1 is 1 (po translated)'
> +'1 = 0 or > 1'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:97
> 
> 3) Cake\Test\TestCase\I18n\I18nTest::testPluralSelectionBasicFormatter
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'There is only one'
> +'There are {0} things'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:116
> 
> 4) Cake\Test\TestCase\I18n\I18nTest::testPluralSelectionRussian
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'1 months ends in 1, not 11'
> +'1 months'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:128
> 
> 5) Cake\Test\TestCase\I18n\I18nTest::testDefaultLocale
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'en_US'
> +'uk_UA'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:206
> 
> 6) Cake\Test\TestCase\I18n\I18nTest::testBasicTranslateFunction
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'%d is 1 (po translated)'
> +'%d = 1'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:243
> 
> 7) Cake\Test\TestCase\I18n\I18nTest::testBasicTranslatePluralFunction
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'1 is 1 (po translated)'
> +'singular msg'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:256
> 
> 8) Cake\Test\TestCase\I18n\I18nTest::testBasicDomainFunction
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'Le moo'
> +'Cow'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:279
> 
> 9) Cake\Test\TestCase\I18n\I18nTest::testBasicDomainPluralFunction
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'Le Moo'
> +'Cow'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:307
> 
> 10) Cake\Test\TestCase\I18n\I18nTest::testBasicContextFunction
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'The letters A and B'
> +'letters'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:344
> 
> 11) Cake\Test\TestCase\I18n\I18nTest::testBasicContextFunctionNoString
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -''
> +'letter'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:386
> 
> 12) Cake\Test\TestCase\I18n\I18nTest::testPluralContextFunction
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'The letters A and B'
> +'letters'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:421
> 
> 13) Cake\Test\TestCase\I18n\I18nTest::testDomainContextFunction
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'The letters A and B'
> +'letters'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:476
> 
> 14) Cake\Test\TestCase\I18n\I18nTest::testDomainPluralContextFunction
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'The letters A and B'
> +'letters'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:533
> 
> 15) Cake\Test\TestCase\I18n\I18nTest::testloaderFactory
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'%d is 1 (po translated)'
> +'%d = 1'
> 
> E:\Web\OpenServer\domains\tests.dev\cakephp\tests\TestCase\I18n\I18nTest.php:623
> 
> ERRORS!
> Tests: 24, Assertions: 31, Errors: 9, Failures: 15.

**Comment by markstory** [comment]
Odd the tests shouldn't be failing. It looks like the default `phpunit.xml` file isn't being used. I think that is because of how you are running phpunit. Instead could you try

```
cd e:\Web\OpenServer\domains\tests.dev\cakephp
vendor/bin/phpunit tests/TestCase/I18n
```

**Comment by Sensetivity** [comment]
> Микола@МИКОЛА-ПК e:\Web\OpenServer\domains
> $ cd e:\Web\OpenServer\domains\tests.dev\cakephp
> 
> Микола@МИКОЛА-ПК e:\Web\OpenServer\domains\tests.dev\cakephp
> $ vendor/bin/phpunit tests/TestCase/I18n
> 'vendor' is not recognized as an internal or external command,
> operable program or batch file.
> 

Maybe should I put path to phpunit to variable path?

**Comment by markstory** [comment]
I'm not sure. I don't use windows very often. Perhaps the `/` need to be `\`? You might also need to do `php vendor\bin\phpunit`? again I'm not well versed in working on windows.

**Comment by Sensetivity** [comment]
The same.

> Микола@МИКОЛА-ПК e:\Web\OpenServer\domains\gogoeurope.dev
> $ vendor\bin\phpunit tests\TestCase\I18n
> Cannot open file "tests\TestCase\I18n.php".

**Comment by markstory** [comment]
Ok. That makes me think there might be a problem with the po/mo file you're using as the tests added cover the ru plural rules being used correctly.

**Pull request merged**
