### PR TITLE
Add PHP 8 and coverage builds to Github Actions

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
Don't know why pgsql got salty on PHP 7.4 :disappointed:.

**Comment by othercorey** [comment]
Looks ok.

I've been dropping a few of the inconsistent but repeating failures in issue to look at later.

**Comment by othercorey** [comment]
My only thought is about the php to db version match. Originally, I was testing the extremes of both (7.2 + mysql 8 and 7.4 + mysql 5.6). I can see that we want to test latest db with the most builds though.

**Comment by ADmad** [comment]
Feel free to switch back / change the combinations as you see fit.

**Pull request merged**
