### PR TITLE
Test against PHP 7.2

### LINKED ISSUE #11346: 2.x support PHP 7.2?
What is the official word on 2.x with PHP 7.2?

- [`.travis.yml`](https://github.com/cakephp/cakephp/blob/2.x/.travis.yml) does not list it
- [`composer.json`](https://github.com/cakephp/cakephp/blob/2.x/composer.json) seems carte blanche >= 5.3.0
- The [installation page of the cookbook](https://book.cakephp.org/2.0/en/installation.html) seems that you can, as long as you install `mcrypt` through PECL, although does not mention 7.2 explicitly.
- The [security page](https://book.cakephp.org/2.0/en/core-utility-libraries/security.html) makes no mention.

If it is supported, can we mention it in the docs? If it will *not* be supported, also mention it in the docs.

I know 2.x is old. I get that. The reason I'm going though this hassle is that 2.x will be the last version of CakePHP for us, and I want it to last as long as possible. I found no information on StackOverflow or anywhere on the Googles.

Thanks!

### PR DESCRIPTION
**Pull request by josephzidell**
Add explicit support for PHP 7.2. Fixes #11346

### CODE REVIEW

**Comment by ravage84** [comment]
The [AppVeyor build error](https://ci.appveyor.com/project/cakephp/cakephp/build/1.0.8863) seems to be unrelated.

**Comment by josephzidell** [comment]
@ravage84 Yes, that is what I'm referring to. No idea how to run the tests, though

**Comment by markstory** [comment]
closed/reopened to try and tickle travisci.

**Comment by josephzidell** [comment]
@markstory Same thing

**Comment by markstory** [comment]
I got nothing then :/

**Comment by dereuromark** [comment]
all builds also in plugins are dead..der

**Comment by josephzidell** [comment]
Is it working for other PRs?

**Comment by markstory** [comment]
@josephzidell Yes. #11350 was opened after this pull request and travis ran fine.

**Comment by josephzidell** [comment]
Perhaps due to 2.x vs 3.x? Are 2.x PRs running travis?

**Comment by saeideng** [comment]
https://github.com/cakephp/cakephp/pull/11353

**Comment by josephzidell** [comment]
@dereuromark @ravage84 Anything glaringly missing from `.travis.yml`?

**Comment by dereuromark** [comment]
Try to rebase and run again.

**Comment by josephzidell** [comment]
Not sure how to do that

**Comment by josephzidell** [comment]
Any other way to re-trigger?

**Comment by antograssiot** [comment]
Appveyor build is not expected to be working on 2.x @josephzidell

**Comment by josephzidell** [comment]
@antograssiot Thanks.

@markstory @dereuromark Can we merge this PR? Or run travis another way?

**Comment by saeideng** [comment]
Travis result https://travis-ci.org/cakephp/cakephp/builds/295810851

**Comment by josephzidell** [comment]
@ravage84 Thanks. Would you know why PECL won't install `mcrypt`?

**Comment by ravage84** [comment]
@josephzidell no, as I didn't have to care about this up until now.

**Comment by josephzidell** [comment]
@markstory Would you know why `pecl install mcrypt` might fail?

**Comment by markstory** [comment]
@josephzidell No idea. mcrypt was removed from PHP core because it was unmaintained. Perhaps it is now also broken?

**Comment by josephzidell** [comment]
@markstory Moved to [PECL](https://pecl.php.net/package/mcrypt)

**Pull request merged**
