### PR TITLE
skip trace + dont show deprecation warnings in html

### PR DESCRIPTION
**Pull request by saeideng**
Refs: https://github.com/cakephp/cakephp/pull/11889

### CODE REVIEW

**Comment by ADmad** [comment]
This should be configurable. I want to see errors in HTML while developing.

**Comment by saeideng** [comment]
>and error display should be enabled by default.

in the html?

**Comment by saeideng** [comment]
>This should be configurable. 

skipping the `trace` or showing in `html`

**Comment by inoas** [comment]
both independent of each other?

**Comment by saeideng** [comment]
>both independent of each other?

yes

**Comment by ADmad** [comment]
> skipping the trace or showing in html

Showing error in html. Errors/warnings should be loud and in your face by default.

**Comment by saeideng** [comment]
@ADmad  for showing in html done.

**Comment by saeideng** [comment]
in favor of https://github.com/cakephp/cakephp/pull/11964

**Pull request closed without merging**
