### PR TITLE
return the image path

### PR DESCRIPTION
**Pull request by alexsmonte**
Return the path of the image using the option pathImage => true

echo $this->Html->image("cake.icon.png", ['fullBase' => true, 'pathImage' => true]);
Example: http://localhost/test/img/cake.icon.png

### CODE REVIEW

**Comment by markstory** [comment]
This option would make the helper not do what the method name says. I'm not a fan personally.

**Comment by jadb** [comment]
I'd prefer adding methods to the `UrlHelper` to cater for the different types of assets but not modifying the current `HtmlHelper::image()` behaviour.

**Comment by dereuromark** [comment]
I agree with @jadb

**Comment by alexsmonte** [comment]
I was thinking about the possibility of adding in UrlHelper, but thought it might be simpler to use as well.

Will provide the change to UrlHelper

**Comment by markstory** [comment]
UrlHelper already returns URLs through the assetUrl() method. Are you thinking of having pre-baked methods for image URLs?

**Comment by jadb** [comment]
@markstory i was thinking something that would already take care of reading the config - so a helper method on top of assetUrl if that makes sense.

**Comment by markstory** [comment]
@jadb Like `$this->Url->imageUrl()`? I think helper methods on the helpers makes sense :smile:

**Comment by jadb** [comment]
@markstory yup!

**Comment by markstory** [comment]
@jadb Is that something you could take a pass at implementing?

**Comment by jadb** [comment]
@markstory will do :)

**Comment by markstory** [comment]
Closing as @jadb will be working on a different approach that puts the desired behavior on the UrlHelper.

**Pull request closed without merging**
