### PR TITLE
3.0 - fix psr2 cs

### PR DESCRIPTION
**Pull request by antograssiot**
after squizlabs/PHP_CodeSniffer 2.2.0 release we had several CS errors.

I choose to use the `//@codingStandardsIgnore` annotation to keep he better readabilty of arrays in the tests but i can flatten them if you prefer.

### CODE REVIEW

**Comment by dereuromark** [comment]
What if we just freeze the cs lib at versions prior to 2.2.0 until they can fix it?
It is clearly not a valid CS error, and adjusting the code base to this errorprone syntax only to silence that faulty error is maybe not the best approach.

**Comment by ADmad** [comment]
> What if we just freeze the cs lib at versions prior to 2.2.0 until they can fix it?

Assuming they consider it a bug and fix it.

> It is clearly not a valid CS error

It may not be an errors strictly as per PSR2 (i havent bothered to check) but remember adopting this new standard is all about appearances, not because like it. :)  Most people will consider the errors thrown by phpcs when using standard=PSR2 as a failure to adhere to PSR2.

**Comment by dereuromark** [comment]
Let's do it then. We can always revert that PR again later :trollface:

**Comment by markstory** [comment]
The array changes are bizarre and look like an issue in phpcs. Perhpas we should report that issue?

**Comment by AD7six** [comment]
I will be unsurprised if that's not a bug. [The spec states] (https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#1-overview):

> Opening parentheses for control structures MUST NOT have a space after them, and closing parentheses for control structures MUST NOT have a space before.

I remember reading a discussion about it, maybe it was somewhere in https://github.com/php-fig/fig-standards/issues/102

**Comment by dereuromark** [comment]
@AD7six "a space" != "whitespace" for most. I think the main intention of that sentence is to address `if ([space]$foo`.
But yeah I can see the confusion around it.

See the next part `closing parentheses for control structures MUST NOT have a space before`.
That would still be violated and is not reported.
That proofs that only a real space was actually meant here IMO.

**Comment by dereuromark** [comment]
See https://github.com/squizlabs/PHP_CodeSniffer/issues/454

**Comment by markstory** [comment]
Merging to fix build issues until phpcs is updated.

**Pull request merged**
