### PR TITLE
Simplify type check

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Review by ndm2 — COMMENTED** [review]
There's probably not very much root for optimization when the type is `mixed`. I guess it could be changed to `object|array|string|int|float|bool`, then only a check for an empty array should be needed.

**Comment by ADmad** [comment]
I didn't want the reader to wade through that list just to avoid a null check :)

**Comment by ndm2** [comment]
I guess it's either that, or a more complex check, as otherwise the simplified variant lets invalid types slip through.

**Comment by ADmad** [comment]
> otherwise the simplified variant lets invalid types slip through.

What invalid value would my updated checks let through?

**Comment by ndm2** [comment]
Resource handles 😉

**Comment by ADmad** [comment]
Ah sorry, will fix it.

**Comment by ndm2** [comment]
How would you feel about checking for `TypeError` exceptions too?

I know there's only a few tests that currently do that, half of them by me, so I'm biased, but I would actually be happy to see more of them, as with the introduction of union types and the subsequent removal of `InvalidArgumentException`s and the related tests, we've kinda dropped quite some coverage, even though it's not visible. But that's probably a discussion for another day 🙃

**Comment by ADmad** [comment]
I am not too keen on adding tests for TypeError. Getting a type error means the execution didn't enter inside your method, so you would be basically testing the language feature rather than your own code. That seems a bit unnecessary to me.

**Comment by ndm2** [comment]
Yeah, my thinking is just that if a type is being changed at some point, possible problems could go unnoticed with no explicit checks for invalid types being present anymore. But I'm also a fan of over-engineering things (at least when it's _me_ who's doing it), so... :)

**Comment by ADmad** [comment]
That said the argument types is "our" code so we would be ensuring that we have narrowed down the types well enough :) But for e.g. the chances of someone passing a resource to this method is very miniscule.

**Comment by ndm2** [comment]
Admittedly, for this method there would need to be kind of a radical change for this to become a problem, like changing it back to `mixed`. It's just something that's generally on my mind ever since the introduction of union types to the core.

**Review by ndm2 — APPROVED** [review]

**Pull request merged**
