### PR TITLE
Reduce required precision in tests.

### PR DESCRIPTION
**Pull request by markstory**
Attempt to fix the builds by not requiring as much precision.

### CODE REVIEW

**Comment by garas** [comment]
The [same build](https://github.com/garas/cakephp/runs/383315660) on fork finished without problems... 

Something wrong with Github Actions.

**Comment by markstory** [comment]
> Something wrong with Github Actions.

I wonder what though, as these tests have been failing consistently for a few days on mysql/postgres in github-actions.

**Comment by othercorey** [comment]
> > Something wrong with Github Actions.
> 
> I wonder what though, as these tests have been failing consistently for a few days on mysql/postgres in github-actions.

Did they change the version of mysql and postgres?

**Comment by ADmad** [comment]
This repo contains the build scripts for GH's VMs for anyone interested in investigating https://github.com/actions/virtual-environments.

**Pull request merged**
