### PR TITLE
Fix up doc blocks and issues around mixed return type.

### PR DESCRIPTION
**Pull request by dereuromark**
Follow https://github.com/cakephp/cakephp/pull/13557

Found a few more issues around too broad "mixed". mixed here is evil, as it basically kills all possible static analysis.
We could check if even more concrete (ideally interface) types could be set as objects in some of those cases.

Fixed also a few other issues found with missing typehints along the way.

### CODE REVIEW

**Comment by dereuromark** [comment]
Issues found in static anal. are side effect issues of bad API as referenced in https://github.com/cakephp/cakephp/issues/13559
We should silence those until API is fixed.

**Review by ADmad — COMMENTED** [review]
Psalm is unhappy with some of the changes.

**Comment by dereuromark** [comment]
See my comment "We should silence those until API is fixed."

**Comment by ADmad** [comment]
I pushed a commit. Once docblock type was incorrect and adding inline annotations took care of the remaining errors.

**Pull request merged**
