### PR TITLE
Dispatch new events App.init and App.shutdown

### PR DESCRIPTION
**Pull request by rchavik**
For example:

``` php
// Config/bootstrap.php
App::uses('MyApp', 'Lib');
CakeEventManager::instance()->attach(new MyApp());

// Lib/MyApp.php
class MyApp implements CakeEventListener {
    public function implementedEvents() {
        return array(
            'App.init' => array('callable' => 'init'),
            'App.shutdown' => array('callable' => 'shutdown'),
        );
    }
    public static function init() {}
    public static function shutdown() {}
}
```

### CODE REVIEW

**Comment by lorenzo** [comment]
What are the use cases for this?

**Comment by ravage84** [comment]
Wouldn't that mean that every CakePHP 2.8+ app now throws two new events on each request, which will be very very rarely used?
This is certainly better than #7224 but I'm still  :unamused: .

**Comment by markstory** [comment]
@ravage84 I was talking with @rchavik last night about this. Initially he had configuration options that used a list of callbacks. I suggested using events for a few reasons:

1. Its far more consistent with the rest of CakePHP's 'hooks'.
2. Firing an event with no listeners is very cheap from what I remember.

@lorenzo The events could be useful as a post-bootstrap, startup event and pre-shutdown scenario. If the event is used, plugins can use their bootstrap to register an init listener, and control the priority their listener is triggered at more easily.

**Comment by HavokInspiration** [comment]
I kind of like the idea.
I remember I had to register my own shutdown function (using ``register_shutdown_function``) once in an app. I don't remember the details or why I had to do it but an event sure would have been nicer and "better integrated".

**Comment by lorenzo** [comment]
I don't really like the idea, what other uses other than incrementing the memory limit can we come up with? I think adding a code for a feature that we are actually not providing is not worth it.

Either we add this code and the feature it was inspired from, or we don't really need to have it.

**Comment by dereuromark** [comment]
With the other PR moving forward we can probably close this then.

**Pull request closed without merging**
