### PR TITLE
Experiment with paratest library

### PR DESCRIPTION
**Pull request by bancer**

### CODE REVIEW

**Comment by markstory** [comment]
What cha doin?

**Comment by bancer** [comment]
Just experimenting.

**Comment by othercorey** [comment]
I'm not sure how you'll get parallel tests to work with fixtures.

**Comment by bancer** [comment]
> I'm not sure how you'll get parallel tests to work with fixtures.

By using a different database for each parallel test. https://github.com/paratestphp/paratest#test-token

**Pull request closed without merging**
