### PR TITLE
Fix lower bound of total pages

### PR DESCRIPTION
**Pull request by dereuromark**
This seems to be the fix for https://github.com/cakephp/cakephp/issues/11052

Before (problematic):
```
		'page' => (int) 1,
		'pageCount' => (int) 0,
		'count' => (int) 0,
		...
```

After:
```
		'page' => (int) 1,
		'pageCount' => (int) 1,
		'count' => (int) 0,
		...
```

If you want to easily read the total number of pages and we currently display page 1, you would probably expect the pageCount to also be 1, and not having to do additional operations here based on another field.
If you need to know the results count in total, you can always check count 0.

### CODE REVIEW

**Review by lorenzo — COMMENTED** [review]
I'm not sure saying that there is always one page is the right thing to do. It is a valid interpretation, though: there is one page, with no results. 

But that's more like a mathematical definition that I'm sure would surprise many

**Comment by dereuromark** [comment]
Isnt pageCount our "max page value" whereas page is the "min page value"?
max shouldnt be below min.

> there is one page, with no results.

That's why you for this check "count" key IMO, not pages.

**Comment by markstory** [comment]
If you check the `count`  key why would this change need to be made?

**Comment by dereuromark** [comment]
Yes. My point was about others checking it.
The above is needed to always know the current max page size per request without the need to calculate.

**Comment by dereuromark** [comment]
$pageCount = $params['pageCount'] ?: 1;

would sure work, but shouldnt be necessary maybe.

**Comment by dereuromark** [comment]
I added a test to avoid regressions.

**Comment by ravage84** [comment]
I spontaneously asked to of my colleagues. Both agreed quite fast with what @dereuromark wants to express.

I think it's a kind of philosophical question, what this ``pageCount`` means, but since we are in a context of a "pagination" and pages are the main thing of a pagination, I think it does not make much sense to express that there are no pages in that set of pages. Especially if you express at the same time, that you are currently on page one. 😼  

It's like saying this is a book that has no pages in it, as there are no words to be found, but you are curently on page one.... 😆

**Pull request merged**
