### PR TITLE
Load ClassRegistry Once

### PR DESCRIPTION
**Pull request by emolr**
ClassRegistry should only be loaded once. 
Cc: @dereuromark

### CODE REVIEW

**Comment by dereuromark** [comment]
Why cc to me?

**Comment by ADmad** [comment]
@emolr What's the reason for this change?

**Comment by antograssiot** [comment]
@ADmad I think it just because the exact same line is also 2 lines above.

**Comment by ADmad** [comment]
@antograssiot Indeed. I failed at reading the diff :)

**Pull request merged**
