### PR TITLE
Generate milliseconds for datetime-local inputs only if "step" is decimal.

### LINKED ISSUE #14226: Datetime field cleared after saving
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3

### What you did
- Started a new project using the command `composer create-project --prefer-dist cakephp/app:4.*  .`
- From an existing database I baked all the code with the command `bin\cake bake all Games`, including the migration below:
`this->table('games', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'uuid', [
                'default' => null,
                'limit' => null,
                'null' => false,
            ])
            ->addColumn('event_id', 'uuid', [
                'default' => null,
                'limit' => null,
                'null' => false,
            ])
            ->addColumn('created_at', 'datetime', [
                'default' => null,
                'limit' => null,
                'null' => true,
            ])
            ->addIndex(
                [
                    'event_id',
                ]
            )
            ->create();
`

### What happened
When I go to the view `games/add`, I could save a record for the entity `Game`.
When I go to the view `games/edit/ID` I can change the date and it is saved correctly.
When I go to the view `games/edit/ID` and I change only the event, the date is saved as an empty value.

### What you expected to happen
As the date has not changed, I expect the value remains.

After some research I figured  out it is caused by this commit:
https://github.com/cakephp/cakephp/commit/c63778cbcc6baf5905e2b9454e77babd115057d0

### PR DESCRIPTION
**Pull request by ADmad**
Fixes #14226

Alternative to #14236

### CODE REVIEW

**Comment by markstory** [comment]
This seems like the simpler solution. What do you think @othercorey ?

**Comment by othercorey** [comment]
I'm fine with it. I made the change already.

**Comment by markstory** [comment]
So which pull request are we merging? :smile:

**Comment by othercorey** [comment]
> So which pull request are we merging? smile

Your choice.

**Pull request closed without merging**
