### PR TITLE
Defer support

### PR DESCRIPTION
**Pull request by zunnu**
This pull request introduces **deferred task execution** support to optimize response times by offloading non-essential tasks to run in the background after the main response has been sent to the client. The `defer()` method allows you to add tasks that don’t need immediate execution, improving performance and user experience by reducing perceived wait times.

The new `defer()` functionality enables controllers to queue tasks that will execute after the response has been finalized and sent to the client. This approach is ideal for background processing tasks, such as sending emails, refreshing cache data, logging, or performing database updates that aren’t critical to the immediate response.

The deferred tasks are registered using the `defer()` method, which queues a callable or closure for execution. Upon request completion, these tasks are automatically executed in the shutdown phase, ensuring the client isn’t kept waiting.

While CakePHP offers a Queue plugin for handling background jobs, it introduces additional overhead, such as setting up a queue system (e.g., Redis, Beanstalkd) and managing queue workers. For lightweight background tasks that don’t require persistent queues or complex workflows, `defer()` provides a simpler, faster alternative that avoids the setup and maintenance requirements of a full queue system. This approach is especially useful for tasks that can run immediately after the main response, without requiring a long-running worker process.

### Use Cases for `defer()`

1. **Sending Emails**
   - **Example**: After a user registers or requests a password reset, an email can be sent in the background.
   - **Usage**:
     ```php
     $this->defer(function () use ($userEmail) {
         $mailer = new UserMailer();
         $mailer->sendWelcomeEmail($userEmail)->send();
     });
     ```

2. **Caching Frequently Accessed Data**
   - **Example**: For frequently accessed data (e.g., an active users list), we can defer a cache check and refresh task to keep the cache up-to-date without delaying the main response.
   - **Usage**:
     ```php
     $this->defer(function () use ($cacheKey) {
         $this->checkAndRefreshCache($cacheKey);
     });
     ```

3. **Logging and Analytics**
   - **Example**: Tracking user actions, page visits, or other metrics that are valuable but don’t require immediate processing.
   - **Usage**:
     ```php
     $this->defer(function () use ($userId, $action) {
         Log::info("User {$userId} performed action: {$action}");
     });
     ```

### Example Code for Implementation

Here’s an example of how the `defer()` method is integrated within the `UsersController` to send a welcome email and refresh the active users cache:

```php
// In UsersController.php

public function registerUser()
{
    // Registration logic here...

    // Send welcome email in the background
    $this->defer(function () use ($userEmail) {
        $mailer = new UserMailer();
        $mailer->sendWelcomeEmail($userEmail)->send();
    });

    // Return response to user
    $this->Flash->success('Welcome.');
}
```

### Limitations and Best Practices
While `defer()` is a powerful tool for background processing, it comes with some limitations:

- **PHP-FPM Process Locking**: When using defer(), the PHP-FPM process remains occupied until all deferred tasks are completed. This can impact server performance if too many requests have deferred tasks running, as it reduces the availability of PHP-FPM workers.
- **Avoid Long-Running Tasks**: `defer()` should not be used for long-running tasks such as large database updates, extensive API calls, or complex data processing. These tasks should be handled by a job queue system to avoid overloading PHP-FPM and to keep the server responsive.
- **Recommended Use**: `defer()` is best suited for lightweight tasks like sending emails, refreshing cache entries, logging, and simple cleanup operations.

### CODE REVIEW

**Comment by ADmad** [comment]
We already have the `Server.terminate` event to execute tasks after sending the response to the client.
https://github.com/cakephp/cakephp/blob/e15d186e05e9e02231d53ba3bb6daa9290c3a470/src/Http/Server.php#L134

**Comment by zunnu** [comment]
@ADmad 

Im having hard time finding examples about this.
Could you provide an example of sending an welcome email from controller after user registers.

**Comment by ADmad** [comment]
We surely need to improve the docs for using that event.

**Comment by ADmad** [comment]
```php
EventManager::instance()->on('Server.terminate', function () use ($userEmail) {
        $mailer = new UserMailer();
        $mailer->sendWelcomeEmail($userEmail)->send();
    }
);
```

**Comment by zunnu** [comment]
Seems to work I used.
```php
EventManager::instance()->on('Server.terminate', function (Event $event) {
    sleep(4);
    file_put_contents(TMP . 'post_response_log.txt', "Deferred Email Notification Sent\n", FILE_APPEND);
});
```

What a shame that I could not find any info about this feature as I just wasted many hours.
What if I for some weird reason would need to run this even if the request fails?

Lets say I have analytics or logging that would need to run even if the request fails, how to do that?

**Comment by dereuromark** [comment]
You write it into a deferred queue for processing.
This would anyway be a good idea if that process takes a bit more than just a few ms.

**Comment by zunnu** [comment]
True, that was my mistake. But let’s consider the situation from another angle. Suppose I want to send a welcome email when a user registers, but if an error occurs during the registration process, I don’t want the email to be sent.

It might seem like an unusual scenario, but would it make sense to have a parameter or flag to ensure that only certain processes continue when an error happens?

For instance, if I were to set it up like this:
```php
EventManager::instance()->on('Server.terminate', function () use ($passkey, $name, $user) {
    $userMailer = new UserMailer();

    try {
        $userMailer->passwordReset($passkey, $name, $user->email)->send();
        Log::info("Password reset email sent successfully to {$user->email}");
    } catch (\Cake\Mailer\Exception\MailerException $e) {
        Log::error("Failed to send reset email to {$user->email}: " . $e->getMessage());
    }
});

throw new \Exception('Something went wrong');
```

In this example, the email is still sent, but the end user receives the typical "something went wrong" page. I understand that I could queue the email to send only once the process is confirmed as successful. However, it seems helpful to have a failsafe option where a queue only processes if a specific parameter or condition is met, even when an error is encountered.

**Comment by zunnu** [comment]
I would prefer to have a flag something like `always` if the queued task can always be processed.
Because the error might happen outside of controller like in template, cell, helper. So having some queued tasks only run when the actual request was successful would be a good thing.

**Comment by ADmad** [comment]
> What if I for some weird reason would need to run this even if the request fails?

You can set the event listener in `Application::bootstrap()` for that.

**Comment by zunnu** [comment]
@ADmad  Please give an example

**Comment by dereuromark** [comment]
You dont even need an event listener or deferred code directly here.
Just directly send the data to the queue afterwards inside the same code flow.
Then also it will not trigger if there is an issue beforehand already.
```php
			$user = $this->Users->patchEntity($user, $data);
			if (!$this->Users->save($user)) {
				$this->Flash->success(__('Account created'));
				$this->Auth->setUser($user);

				$this->loadModel('Queue.QueuedJobs');
				$this->QueuedJobs->createJob('RegistrationMail', ['id' => $id]);

				return $this->redirect(['controller' => 'Overview', 'action' => 'index']);
			}
```
NO magic, easier to test and verify each of the elements.

You should move this conversation into the support channels instead now. As this is not related to feature or bug tracking.

**Comment by ADmad** [comment]
I have created an issue on the docs repo regarding the `Server.terminate` event.

**Comment by zunnu** [comment]
> You dont even need an event listener or deferred code directly here. Just directly send the data to the queue afterwards inside the same code flow. Then also it will not trigger if there is an issue beforehand already.
> 
> ```
> 			$user = $this->Users->patchEntity($user, $data);
> 			if (!$this->Users->save($user)) {
> 				$this->Flash->success(__('Account created'));
> 				$this->Auth->setUser($user);
> 
> 				$this->loadModel('Queue.QueuedJobs');
> 				$this->QueuedJobs->createJob('RegistrationMail', ['id' => $id]);
> 
> 				return $this->redirect(['controller' => 'Overview', 'action' => 'index']);
> 			}
> ```
> 
> NO magic, easier to test and verify each of the elements.
> 
> You should move this conversation into the support channels instead now. As this is not related to feature or bug tracking.

This is very wrong. First there is no such method as `loadModel` in CakePHP 5 its called `fetchTable`.
Second like the PR description says using a third-party queue system brings too much overhead.
The defer functionality in this PR conversation talks about executing stuff after we have given the user a response.
Currently there was no documentation about the `Server.terminate` and how to use it so I spend hours doing it and now Im trying to validate if the `Server.terminate` can be used.

**Comment by dereuromark** [comment]
I copy pasted from an existing app.
The bottom line should be clear: Doing sth on top that takes 10-15ms does not bother the code flow. And is easier to debug, test and maintain in the long run.

Anyway, discussion in support channels it is.

**Pull request closed without merging**
