### PR TITLE
Added initialize hook to base helper.

### PR DESCRIPTION
**Pull request by sdustinh**
Ref #7645

### CODE REVIEW

**Comment by ADmad** [comment]
What's the use case for this?

**Comment by markstory** [comment]
@ADmad One useful thing is having consistency across the framework. But I suspect @sdustinh has a more concrete use case as well.

**Comment by sdustinh** [comment]
Sorry, yesterday was a crazy day on my side. Yes! There are a bunch of reasons that I have come across.

I use helpers very similarly to components but for the view level. Part of that is sometimes inspecting the environment the helper was loaded into (SubnavigationHelper) and changing the configuration based on that.

Another useful thing is extending something like the FormHelper. If I'm extending an established helper most of the time I need a space to do general changes, load other classes or maybe even load additional helpers. I have a helper that I use which works similar to the FormHelper's context objects but they are swapped when it is initialized.

I'm sure there are points that I am missing but I have on more than one occassion thrown an `initialize()` into a helper expecting it to work and then realizing it doesn't. It really just saves me from having to throw another `use` in there and running a `parent::__construct($view, $config)`.

**Comment by ADmad** [comment]
Okay you have me convinced :)

Wonder what's up with the failing builds.

**Comment by markstory** [comment]
Added to the new Migration guide in 04c9b7ef7a9c9857775ebf878a0facd06186bfb7

**Pull request merged**
