### PR TITLE
Load phpunit aliases in tests/bootstrap.php

### PR DESCRIPTION
**Pull request by nojimage**
fixes for #11577

### CODE REVIEW

**Review by ADmad — APPROVED** [review]

**Comment by dereuromark** [comment]
Doesnt that break all 5.6 builds now in all plugins?
See https://travis-ci.org/cakephp/bake/builds/322319651 etc

**Comment by saeideng** [comment]
@dereuromark 
related to loading  `tests/phpunit_aliases.php` by `loadPHPUnitAliases();`
because `tests/phpunit_aliases.php`  did not load before

**Comment by dereuromark** [comment]
Also 7.1 tests now fail: https://travis-ci.org/dereuromark/cakephp-shim/jobs/322374951
What do you think we should do?

**Comment by markstory** [comment]
@dereuromark This change was merged *after* the release of 3.5.9. I applied the wrong milestone to this change.

**Comment by dereuromark** [comment]
Ah ok. You are saying that this will be fixed with the next release then?

**Comment by markstory** [comment]
> Ah ok. You are saying that this will be fixed with the next release then?

I hope so.

**Pull request merged**
