### PR TITLE
Replaced nested loop in merging hasMany children with one pass each t…

### PR DESCRIPTION
**Pull request by tharlinsmith**
When a set of parents with hasMany relationships are fetched, the process of associating the children with the parents was implemented with a nested loop.  In situations with a large number of parents this is inefficent (O(n)^2).  Replaced it with a single pass through the children and another through the parents to do the association, and realized an order of magnitude improvement for some datasets.

### CODE REVIEW

**Comment by markstory** [comment]
Your code has conflicts and cannot be merged.

**Comment by markstory** [comment]
Your change should target the `2.x` branch and not the `master` branch which contains CakePHP 3 code.

**Comment by tharlinsmith** [comment]
Ok, just trying to follow the guidelines, which says bug fixes should go against master (no functionality change so I wouldn't classify this as a feature addition).  There shouldn't be any conflicts since I checked out of master and right back in, yes?

This "improvement" applies to all the active development branches, just with some name changes.  How should I proceed?

Cheers,
- Tom

On Mar 15, 2016, at 6:15 PM, Mark Story <notifications@github.com<mailto:notifications@github.com>> wrote:


Your change should target the 2.x branch and not the master branch which contains CakePHP 3 code.

**Comment by markstory** [comment]
> Ok, just trying to follow the guidelines, which says bug fixes should go against master (no functionality change so I wouldn't classify this as a feature addition). There shouldn't be any conflicts since I checked out of master and right back in, yes?

This is correct, but the `master` branch currently contains CakePHP *3* code. Your change is for CakePHP *2*, which is on the `2.x` branch. The guidelines recommend master, as we get far more contributions to 3.x than 2.x at this point in time.

**Comment by markstory** [comment]
You need to re-open your pull request with `2.x` as the target branch.

**Pull request closed without merging**
