### PR TITLE
RFC: add config key to enable default TransactionStrategy for testing

### PR DESCRIPTION
**Pull request by LordSimal**
This PR adds the Config Key `Test.enableTransactionStrategy` to enable the TransactionStrategy by default.

The [docs](https://book.cakephp.org/4/en/development/testing.html#fixture-state-managers) already mention that you either can create a base class or a trait to basically do the same for a selected amount of test classes but I thought it would be nice to just enable it "globally" via one config key.

Unfortunately I am not very accustomed to write a test for that since I haven't dealt with this topic that much.

I also started a new "root" Config key `Test` since this is not really `App` specific/relevant and therefore should have its own "config space" in my opinion.

Happy to hear your thoughts 😄

### CODE REVIEW

**Comment by othercorey** [comment]
I'm not so sure about this. If we do want this, I think the config name needs to be different.

**Comment by pabloelcolombiano** [comment]
I think it is a good idea to let the user define the default truncation strategy, defined per connection.
We could add say a `fixtureStrategy` config key under `Datasources.test`, to specify which strategy to use for that provided connection:

```php
[
   'Datasources' => [
      ...
      'tests' => [
         ...
         'fixtureStrategy' => 'FullyQualifiedNameOfTheFixtureStrategy',
      ],
   ],
]

```

**Comment by markstory** [comment]
> I think it is a good idea to let the user define the default truncation strategy, defined per connection.

Currently fixture strategies are not related to the connections. When would you need different fixture reset behavior for different connections?

**Comment by pabloelcolombiano** [comment]
There could be some use cases, e.g. a user with a test DB and a test_logs DB. The test DB should be cleared in a casual way, say with transactions. But the test_logs does not need at all to be cleaned-up, or only in a handfull amount of tests. A `do nothing` fixture strategy would do the job and speed up the tests.

On the one hand I agree we should make the user experience as simple and intuitive as possible, and on the other hand some advanced developers will want to tune their test suites as fine as it gets. Thinking for example of @liqueurdetoile.

EDIT: this is another aspect, which also brings BC issues along. Let's keep things simple and leave the strsategy unrelated to a particular connection.

**Comment by othercorey** [comment]
Overriding `getFixtureStrategy()` seems like the obvious way to do most of this.

**Comment by pabloelcolombiano** [comment]
No @othercorey, this is exactely why the discussion started.

Overwritting `getFixtureStrategy()` means that all test cases should extend a home made class. This is much more effort for the developer, and prone to errors if some developer forgets about it and wonders why things behave differently suddently.

It is IMO quite intruding from CakePHP to impose a Fixture Strategy and force the developer to extend the vanilla TestCase. Defining the default global strategy at one single place is, I think, simpler.

**Comment by othercorey** [comment]
> It is IMO quite intruding from CakePHP to impose a Fixture Strategy and force the developer to extend the vanilla TestCase. Defining the default global strategy at one single place is, I think, simpler.

This is silly. It's the default behavior. We only have one other experimental strategy.

**Comment by othercorey** [comment]
> Overwritting `getFixtureStrategy()` means that all test cases should extend a home made class. This is much more effort for the developer, and prone to errors if some developer forgets about it and wonders why things behave differently suddently.

This part also seems a little drastic. What if a project has custom asserts and they forget to extend from the project's TestCase or include the project's TestAssertionsTrait? It's just part of being a developer.

I understand the desire to customize and configure something new, I'd rather keep it simple.

**Comment by LordSimal** [comment]
Well, I think I have my answer 😄 
Thanks for your comments and the insight you brought to this topic.

I now also agree with @othercorey that this shouldn't be configurable out of the box and those who need to have it configurable should create a trait / base class and need to adjust all their test classes.... once.

**Comment by pabloelcolombiano** [comment]
That's a shame, it would have been quite useful.

**Pull request closed without merging**
