### PR TITLE
Change collection function return types

### LINKED ISSUE #14367: Return specific types for CollectionInterface methods
`CollectionInterface` methods all return type `CollectionInterface`.

```
public function listNested($dir = 'desc', $nestingKey = 'children'): CollectionInterface;
```

However, these methods are sometimes implemented with specific types that provide extra methods that we reference in documentation. However, there is no type hinting for these methods.

https://book.cakephp.org/4/en/core-libraries/collections.html#Cake\Collection\Collection::listNested

This causes issues with static analyzers and other type resolvers that require special work-arounds.

```
/** @var \Cake\Collection\Iterator\TreeIterator $nested */
$nested = $results->listNested();

return $nested->printer($options['valuePath'], $options['keyPath'], $options['spacer']);
```

### PR DESCRIPTION
**Pull request by Zwartpet**
Fixes #14367

Collection function all returned a CollectionInterface, but this gives issues with typehinting.

### CODE REVIEW

**Comment by Zwartpet** [comment]
@othercorey proposed this change for [the issue you made](https://github.com/cakephp/cakephp/issues/14367), I've changed the actual return types as well but maybe that should stay a CollectionInterface?

**Comment by othercorey** [comment]
I don't know if we can do this for 4.1, however we rely on these types returned by these methods. For example, a generic `CollectionInterface` returned by `listNested()` doesn't help.

All of the internal implementations use `CollectionTrait`, but it's possible someone out there implemented an entirely different `CollectionInterface`. It wouldn't be compatible with documented use of these methods though.

**Comment by ADmad** [comment]
Also having methods of Collectioninterface be type hinted with methods of its child interfaces feels odd.

**Comment by othercorey** [comment]
> Also having methods of Collectioninterface be type hinted with methods of its child interfaces feels odd.

That is awkward. I would like to find something better than non-hinted method calls.

**Comment by dereuromark** [comment]
This breaks the public API and usually cannot be done before the next major.
Could we add those as docblock return annotations?
That would be BC.
Just not sure if it should replace or be a combination of both (using `&` or `|` ?)

**Comment by Zwartpet** [comment]
Something like this? Or only the docblock and removing the actual return type in the trait?

**Comment by dereuromark** [comment]
Does this work for you regarding typehinting? And for everyone else?

**Comment by othercorey** [comment]
@Zwartpet I will revisit this when I have time to see if the types fix the psalm errors at least.

**Pull request closed without merging**
