### PR TITLE
Use PSR7 request methods in helpers

### PR DESCRIPTION
**Pull request by markstory**
Use undeprecated and PSR7 methods in helpers/view classes. I've also tried to remove the remaining ArrayAccess uses in the tests.

I added in a few `...` operators in the Request class to avoid some `func_get_args()` calls as I know removing those is a minor goal for 3.4.0.

Refs #9325

### CODE REVIEW

**Review by lorenzo — COMMENTED** [review]
Nice!

**Comment by lorenzo** [comment]
Is params with array accede deprecated now?

**Comment by saeideng** [comment]
https://github.com/cakephp/cakephp/blob/3.next/src/Network/Request.php#L601

**Comment by markstory** [comment]
@lorenzo Yes. All the public properties are deprecated.

**Pull request merged**
