### PR TITLE
Run phpstan at level 5.

### PR DESCRIPTION
**Pull request by ADmad**
This should help us ensure we have proper typehints and such from the get go.

### CODE REVIEW

**Comment by ADmad** [comment]
Hmm.. Don't know why the phpstan build doesn't show up here https://travis-ci.org/cakephp/cakephp/builds/370464759.
Pretty sure I have setup the yml properly as per docs https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail.

**Comment by dereuromark** [comment]
You need to keep it in the matrix + add it to the allow failure :)
Otherwise it won't exist anymore.

**Comment by ADmad** [comment]
Ah, fixed. Thanks :)

**Comment by dereuromark** [comment]
Only 415 errors  :P

**Pull request merged**
