### PR TITLE
Updated naming strategy

### PR DESCRIPTION
**Pull request by Spriz**
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

Always follow the [contribution guidelines](https://github.com/cakephp/cakephp/blob/master/.github/CONTRIBUTING.md) when submitting a pull request. In particular, make sure existing tests still pass, and add tests for all new behavior. When fixing a bug, you may want to add a test to verify the fix.

### CODE REVIEW

**Comment by Spriz** [comment]
This was a test - nevermind.

**Comment by ravage84** [comment]
@Spriz if you want to test against CakePHP's Travis, you can configure Travis for your own fork of the repo.

**Comment by Spriz** [comment]
@ravage84 I wanted to showcase a group of students how to contribute to open source! :D

**Comment by ravage84** [comment]
Haha... OK 😹

**Pull request closed without merging**
