### PR TITLE
Dbosource isConnected

### PR DESCRIPTION
**Pull request by pbaire**
Class DboSource method isConnected now check the actual status of connection by executing a dumb query

### CODE REVIEW

**Comment by markstory** [comment]
This should target 2.7 instead. The 2.6 branch is only used for security fixes these days.

**Comment by markstory** [comment]
Other than the branch target this looks great.

**Comment by markstory** [comment]
Cherry picked onto 2.7 in a7b5f8c3af2398da3f6d0c35b4ac5bf77331468b

**Comment by burriko** [comment]
Closing a database connection and then using this to check if it's connected causes a fatal error.
```Fatal error: Call to a member function query() on null```

I've just pushed a simple fix to #7426

**Pull request closed without merging**
