### PR TITLE
Configure read default

### PR DESCRIPTION
**Pull request by jadb**

### CODE REVIEW

**Comment by markstory** [comment]
Doesn't this encourage adding default values all over the app? Shouldn't we encourage default config files instead?

**Comment by ravage84** [comment]
Having the option does not seem to be such a bad thing...

**Comment by jippi** [comment]
:-1: from personal experience, having defaults scattered all over the place is sad

if you insist on it use Configure::read('meh') ?: 'meh';

**Comment by markstory** [comment]
> Having the option does not seem to be such a bad thing...

In isolation I agree, but in practice it leads to code that is hard to understand. Think of the mess you'd be in if the following happened:

```php
// In one place
Configure::read('Security.salt', 'abc123');

// In another
Configure::read('Security.salt', '123abc');
```

Having a centralized place for default values (like a default config file) makes it impossible for configuration values to diverge.

**Comment by jadb** [comment]
Am happy either way. 

The raised concerns make perfect sense when put in place to enforce good practices.

**Pull request closed without merging**
