### PR TITLE
correct use statement order

### PR DESCRIPTION
**Pull request by antograssiot**
to fix cs issue

### CODE REVIEW

**Comment by robertpustulka** [comment]
Sorry, I just did find & replace and didn't check use order.

**Comment by ADmad** [comment]
@robertpustulka No problem. It's the merger's fault too for not checking the phpcs build :stuck_out_tongue:

**Comment by lorenzo** [comment]
Still some errors in the View folder

**Comment by antograssiot** [comment]
@lorenzo should be ok now, sorry I was too lazy to run phpcs localy

**Comment by markstory** [comment]
@ADmad I should have checked PHPCS - my bad.

**Comment by ADmad** [comment]
@markstory No biggie, it's easy to miss phpcs build failure due to other one off build failures.

**Pull request merged**
