### PR TITLE
Set .htaccess indentation to 4 spaces

### PR DESCRIPTION
**Pull request by luissquall**
Followed 4 space indentation from app/.htaccess & app/webroot/.htaccess.

### CODE REVIEW

**Comment by markstory** [comment]
Thanks :+1:

**Comment by ADmad** [comment]
I don't think this was particularly necessary for 2.x but meh.

**Comment by ravage84** [comment]
Actually, this goes against what's defined in the ``.editorconfig`` file:
https://github.com/cakephp/cakephp/blob/2.7.1/.editorconfig#L6-L7

**Comment by ADmad** [comment]
Yup, i would suggest reverting this.

**Comment by luissquall** [comment]
I'm sorry, I was not aware of this file and just applied the format the other .htaccess files had. :/

**Comment by markstory** [comment]
Or just change it to tabs.

**Pull request merged**
