### PR TITLE
Contain the junction table when proxying finders.

### PR DESCRIPTION
**Pull request by markstory**
When proxying finder methods from a belongstomany association, if that association has conditions we should contain the junction table as the conditions very likely use columns on that table.

Refs #7707

### CODE REVIEW

**Comment by lorenzo** [comment]
Tests failing

**Comment by markstory** [comment]
Hmm. Looks like find() is also used when building eagerLoaded() results. The `_buildQuery` method attaches the relevant join. I might have to move the join() call into find() instead. I'll take another look.

**Comment by lorenzo** [comment]
I had some logic in the BelongsToMany class that was used to override a previous join with the junction table. Maybe that code is not necessary anymore? https://github.com/cakephp/cakephp/blob/master/src/ORM/Association/BelongsToMany.php#L1042-L1056

**Comment by markstory** [comment]
@lorenzo Removing that code causes a few tests to fail, so I've left it. The new joins are only added when the association uses conditions. The override logic, does replace the contents of the join definition but doesn't _reorder_ the join to be at the end of the array. There is some logic shared between the code you linked to, and the new code. I'll try and extract a common method.

**Comment by ADmad** [comment]
Hmm.. Coveralls claims the PR brings down code coverage by 2%.

**Comment by lorenzo** [comment]
@ADmad Something is wrong with coveralls. It says the same for each in all pull requests

**Comment by lorenzo** [comment]
@markstory any idea why this seems to be affecting one of the php 7 builds?

**Comment by markstory** [comment]
@lorenzo No idea why that one test is failing on PHP7. Strangest part of it is, that the test that is failing doesn't use the ORM at all, and is just a test for selecting basic results.

**Comment by markstory** [comment]
@lorenzo Oddly the [push build](https://travis-ci.org/cakephp/cakephp/builds/95189588) did not have the same failure :cry:

**Comment by lorenzo** [comment]
Ok, let's merge this and take care of the failing error later. I can take a look at it

**Pull request merged**
