### PR TITLE
Enable coverage and codecov hook for appveyor builds.

### PR DESCRIPTION
**Pull request by ADmad**
Hopefully coverage for Sqlserver driver should now be included in reports and codecov should show a bump in total coverage.

### CODE REVIEW

**Comment by markstory** [comment]
For some reason appveyor didn't run this pull request 😕

**Comment by ADmad** [comment]
It's hard to get the damn machines to play ball :unamused:

**Comment by ADmad** [comment]
@lorenzo Can you please try and manually trigger appveyor build for this PR?

**Comment by ADmad** [comment]
I ran the build on my fork https://ci.appveyor.com/project/ADmad/cakephp but it seems to keep running for an hour at which point appveyor kills it. Got same result upon restarting too.

**Comment by ADmad** [comment]
I don't want to spend anymore time on this so anyone else it welcome to continue or just close the PR. A possible fix would be use build matrix and run coverage only for DatabaseSuite instead of whole test suite.

**Comment by markstory** [comment]
Closing as I don't have time to poke at this, and I don't think having the SQLServer code be 'covered' will bump us up that much higher.

**Pull request closed without merging**
