### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by oldskool**
Setting proper vendor-dir.
Without one, doing a composer install will dump all requirements in /vendor, rather than /vendors (or /app/Vendor, but that doesn't seem too clean, since you would expect app-specific Vendor files there).

When the files are in /vendor, it won't be found by `App::path('vendors')`, causing stuff like the TestShell not to run (since it can't find the PHPUnit Vendor files).

### CODE REVIEW

**Comment by dereuromark** [comment]
Won't this break all existing apps that rely on app/Vendor being used?

**Comment by oldskool** [comment]
@dereuromark Hmm, yeah it could. This fix is based upon a "fresh" install. I noticed that after doing a composer install, all files were stored in a newly created /vendors dir (in the project root), but that's not a valid vendor path either. So as far as I can tell, this shouldn't work as expected currently either.

Another option would be to set `app/Vendor` as vendor-dir, but then all require-dev packages would also end up there and I'm not sure if that's desirable.

**Comment by dereuromark** [comment]
I think this should not be a setting in the cakephp repo, but in the specific app repo file, see https://github.com/dereuromark/cakefest/blob/master/composer.json#L34 for an example.
Here I specifically *want* it to be "Vendor" in this kind of composer setup.

**Comment by markstory** [comment]
Yeah, I'm not sure this config makes sense given that the root app's composer.json should be used instead, and that composer.json should be in app/.

**Comment by oldskool** [comment]
@markstory Agreed on the app composer.json, but that's why this change would make sense. As core-level requirements should be put in /vendors and not in /vendor (which is currently happening). To reproduce:

1. Do a fresh clone of the current repo
2. Download and install composer (if not yet globally installed)
3. Run `composer install`

The requirements like DebugKit and PHPUnit will now be installed in a newly created folder called /vendor. This is not a default/valid Vendor path, thus when running something like:

```bash
cd app
Console/cake/test app AllTests
```

It will start complaining that PHPUnit can not be found (since the /vendor dir is not scanned for files by `App::path('vendors')`).

**Comment by markstory** [comment]
@oldskool I buy that argument, but I wonder if this will cause app vendor files to be installed incorrectly.

**Comment by lorenzo** [comment]
Closing this PR as it cannot be merged to master. Please reopen targeting 2.6 or 2.7

**Pull request closed without merging**
