### PR TITLE
Support Chronos extending DateTimeImmutable again

### PR DESCRIPTION
**Pull request by othercorey**
refs https://github.com/cakephp/chronos/pull/417

### CODE REVIEW

**Comment by othercorey** [comment]
psalm has a bug where it thinks DateTimeImmutable::__unserialize() incorrectl implements DateTimeInterface::__unserialize().

https://github.com/vimeo/psalm/issues/10218

Seems to happen only with PHP 8.2.

**Comment by dereuromark** [comment]
These are quite heavy signature changes.
This will be important when setting constraints (and prefer lowest compatibility) from dependencies to core in the future, as it will have to be `^5.0.1` etc

**Comment by othercorey** [comment]
Many of the signature changes are for correctness, but it doesn't affect behavior. Chronos now implements DateTimeInterface so Chronos and DateTimeInterface are considered duplicate types.

The version constraints could be tricky. CakePHP 5.0.0 won't work with Chronos 3.1 and we can't really prevent that, but I don't think anyone is going to update only Chronos and not CakePHP.

For CakePHP 5.0.1, we'll have to release Chronos 3.1 first and then immediately release 5.0.1.

**Review by ADmad — APPROVED** [review]
Replacing all the `Chronos|DatetimeInterface` with just `DatetimeInterface` is a win in my book.

**Pull request merged**
