### PR TITLE
Allow deep options for radio() just as for select().

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/cakephp/pull/6768

### CODE REVIEW

**Comment by markstory** [comment]
Looks good, we will need to port this to 3.0 as well.

**Comment by lorenzo** [comment]
Tests fail

**Comment by lorenzo** [comment]
well, only in 5.2...

**Comment by markstory** [comment]
I removed 5.2 from the build matrix again as I don't its worth the time to fix.

**Pull request merged**
