### PR TITLE
Use PHP_SAPI instead of php_sapi_name()

### PR DESCRIPTION
**Pull request by FrankFFFF**
#6179

Shorter and Faster.

### CODE REVIEW

**Comment by dereuromark** [comment]
Would this create issues with not being able to mock out this anymore? Constants cannot be changed.
Other than that I am fine with using the constant as micro-speed-optimization.

**Comment by Fieah** [comment]
Hi @dereuromark 
Hmm, i don't get what you mean by mock out.
`php_sapi_name()` can only return the SAPI type, you can't mock anything.

**Comment by dereuromark** [comment]
I thought with tools like https://github.com/tcz/phpunit-mockfunction it was possible to mock even basic PHP functions, and that wouldn't be possible anymore with constants.
But I am not sure if people actually do that and if that would be an issue.

**Comment by Fieah** [comment]
Interesting tool, never seen that before.
Hmm. For me, i might not debug that way with SAPI,
And in this case, we only check for CLI mode, so, i think it won't be an issue.

**Comment by markstory** [comment]
I think this is reasonable given that we don't currently mock `php_sapi_name()` anywhere.

**Comment by Fieah** [comment]
`fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=No such file or directory`
How can i make it re-run?

**Comment by markstory** [comment]
You don't.

**Comment by Fieah** [comment]
OK, i thought something was broken.

**Pull request merged**
