### PR TITLE
Only array-wrap 'order' if it's not already an array.

### PR DESCRIPTION
**Pull request by dereuromark**
Follow up on https://github.com/cakephp/cakephp/pull/7146

The changed tests show that it works as expected.

### CODE REVIEW

**Comment by ravage84** [comment]
:+1:

**Comment by ADmad** [comment]
Builds failing. Seem updating a test has been missed.

**Comment by dereuromark** [comment]
All good now :)

**Comment by ADmad** [comment]
:+1:

**Comment by markstory** [comment]
Thanks @dereuromark :+1:

**Pull request merged**
