### PR TITLE
Fix: void unreturn

### PR DESCRIPTION
**Pull request by lustyrain**
Hi.

Is not return unnecessary?

### CODE REVIEW

**Comment by dereuromark** [comment]
Technically it is not even allowed :) Void return methods must not return something.
Nice find!

**Comment by inoas** [comment]
Could this be caught by some linters/checkers in future?

**Comment by dereuromark** [comment]
I doubt that in 2.x - any phpstan might not work due to the lack of namespaces.

**Comment by markstory** [comment]
Thanks!

**Pull request merged**
