### PR TITLE
LICENSE.txt update to help github detect

### PR DESCRIPTION
**Pull request by inoas**
Taken from https://choosealicense.com/licenses/mit/ which is also the source for github's licensing features.

### CODE REVIEW

**Comment by inoas** [comment]
Maybe we can change:
`Copyright (c) 2005-2017, Cake Software Foundation, Inc. (http://cakefoundation.org)`
to
`Copyright (c) 2005-2017, Cake Software Foundation, Inc. (http://cakefoundation.org); also see http://cakephp.org`

**Comment by inoas** [comment]
Ref: https://github.com/cakephp/cakephp/issues/10428

**Comment by markstory** [comment]
Looks good to me. Any concerns @phpnut ?

**Comment by cleptric** [comment]
@inoas I looked at the branch in your fork. The license meta isn't showing their either.

**Comment by inoas** [comment]
That's true @ https://github.com/inoas/cakephp/blob/patch-3/LICENSE.txt

**Comment by inoas** [comment]
@markstory these are the steps you need to do: https://help.github.com/articles/adding-a-license-to-a-repository/

I assume you can keep your original license text. All you would need to do is adding LICENSE (instead of LICENSE.txt) then chose MIT in the box that will appear on the right side, then remove LICENSE.txt. I assume LICENSE can then be renamed to LICENSE.txt

**Comment by inoas** [comment]
In my local repo it only worked when I removed the link to cakephp.org and changed the first line title to MIT License

https://github.com/inoas/cakephp/blob/master/LICENSE

**Pull request closed without merging**
