### PR TITLE
added composer scripts like in cake 3

### PR DESCRIPTION
**Pull request by bancer**
This makes it easier to run tests on localhost: `composer run-script test`.

### CODE REVIEW

**Comment by jeremyharris** [comment]
Should this use the `--stderr` flag to allow tests that use the session to pass?

**Comment by bancer** [comment]
@jeremyharris It uses that: `"test": "./lib/Cake/Console/cake test core AllTests --stderr"`.

**Comment by jeremyharris** [comment]
@bancer sorry I was looking at the wrong script :)

**Comment by bancer** [comment]
@markstory I think this was merged too early. The tests didn't pass. I am going to fix tonight.

**Comment by markstory** [comment]
The tests were failing for a reason not related to changes in the composer.json file.

**Comment by markstory** [comment]
I'll revert off the change to models.php. I think that may have broken the builds.

**Pull request merged**
