### PR TITLE
Fix tests in mysql 5.7.3+

### PR DESCRIPTION
**Pull request by greew**
TestFixtures `Cake\Test\Fixture\SiteAuthorsFixture` and `Cake\Test\Fixture\SiteArticlesFixture` both doesn't work on MySQL 5.7.3+. This can be traced down to the fact that they both contain a nullable field in their primary key, and which isn't allowed in MySQL, but from 5.7.3 and forward, this actually gives and error and the field isn't silently changed to NOT NULL.

Link to [MySQL 5.7.3 change log](http://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-3.html):

> Columns in a PRIMARY KEY must be NOT NULL, but if declared explicitly as NULL produced no error. Now an error occurs. For example, a statement such as CREATE TABLE t (i INT NULL PRIMARY KEY) is rejected. The same occurs for similar ALTER TABLE statements. (Bug #13995622, Bug #66987, Bug #15967545, Bug #16545198)

This caused 

```
Fatal error: Uncaught exception 'Cake\Core\Exception\Exception' with message ' in /Users/jesper/code/cakephp/src/TestSuite/Fixture/FixtureManager.php on line 331

Cake\Core\Exception\Exception: Unable to insert fixture "Cake\Test\Fixture\SiteAuthorsFixture" in "Cake\Test\TestCase\ORM\BindingKeyTest" test case: 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test_content.site_authors' doesn't exist in /Users/jesper/code/cakephp/src/TestSuite/Fixture/FixtureManager.php on line 331
```

and

```
Fatal error: Uncaught exception 'Cake\Core\Exception\Exception' with message ' in /Users/jesper/code/cakephp/src/TestSuite/Fixture/FixtureManager.php on line 331

Cake\Core\Exception\Exception: Unable to insert fixture "Cake\Test\Fixture\SiteArticlesFixture" in "Cake\Test\TestCase\ORM\CompositeKeyTest" test case: 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test_content.site_articles' doesn't exist in /Users/jesper/code/cakephp/src/TestSuite/Fixture/FixtureManager.php on line 331
```

This PR changes both fixtures such that they are able to be converted to valid SQL again.

### CODE REVIEW

**Comment by markstory** [comment]
Thank you :+1:

**Comment by ravage84** [comment]
@greew do you know whether CakePHP 2.x is also affected?

**Comment by greew** [comment]
@ravage84 After quickly looking over the fixtures in CakePHP 2.x, I don't see any that specifically states both that null is allowed and that the field is primary, so I guess not.

**Comment by tharlinsmith** [comment]
There are also a large number of broken tests due to the change in the default value for _sql-mode_. The ONLY_FULL_GROUP_BY option being enabled by default causes a number of these:

> SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cake_test.Thread.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Pull request merged**
