### PR TITLE
Fix inline docblocks.

### PR DESCRIPTION
**Pull request by dereuromark**
Running [InlineDocBlock](https://github.com/spryker/code-sniffer/blob/master/Spryker/Sniffs/Commenting/InlineDocBlockSniff.php) sniff
I recommend adding this to the core one as well to avoid this happening in the future.

### CODE REVIEW

**Comment by ADmad** [comment]
Your changes helped fixed some errors earlier reported by pslam and found some new ones. So I tacked on some additional fixes and update psalm's baseline file.

**Comment by dereuromark** [comment]
I didnt expect that one :)

**Comment by markstory** [comment]
Looks good to me. There is one more phpstan error.

**Comment by ADmad** [comment]
I took care of the phpstan error.

**Pull request merged**
