### PR TITLE
4.x - Add suggestions for missing command name

### PR DESCRIPTION
**Pull request by markstory**
When a command is run and it doesn't exist, we can suggest potential commands based on edit distances and prefix matching.

If folks like this approach I can extend it to missing options as well. I'm not really happy with the name `NoOptionException` and welcome any suggestions for a better name.

### CODE REVIEW

**Comment by othercorey** [comment]
@markstory auto hinting is very cool.  I think InvalidOption is more common than NoOption.

**Comment by saeideng** [comment]
`CommandNotFoundException` for name

**Comment by saeideng** [comment]
`bin/cake bak` 
------
Unknown command `cake bak`. Run `cake --help` to get the list of commands. Did you mean: `bake mailer`, `bake all`, `bake helper`, `bake middleware`, `bake template all`, `bake fixture`, `bake component`, `bake task`, `bake plugin`, `bake form`, `bake template`, `bake fixture all`, `bake test`, `bake command`, `bake controller all`, `bake model all`, `bake behavior`, `bake cell`, `bake controller`, `bake shell_helper`, `bake model`, `bake shell`?

could we have output like this
```
Command 'cake bak' not found, did you mean:

App:
 - bakery

Bake:
 - bake all
 - bake behavior
 - bake cell
 - bake command
 - bake component
 - bake controller
 - bake controller all
 - bake fixture
 - bake fixture all
 - bake form
 - bake helper
 - bake mailer
 - bake middleware
 - bake model
 - bake model all
 - bake plugin
 - bake shell
 - bake shell_helper
 - bake task
 - bake template
 - bake template all
 - bake test

 Run `cake --help` to get the list of commands.

```

or another better output

**Comment by markstory** [comment]
@saeideng Getting the grouping would be hard, as we won't have that context available. But a bulleted list is doable.

I'm not sure `CommandNotFound` is a good exception name as I hope to reuse this exception when an invalid `--option` is used as well.

**Comment by markstory** [comment]
I've changed the approach a bit by moving more of the guessing logic into the exception class and also consolidated the code in ConsoleOptionParser into the exception to better show the end state.

**Comment by saeideng** [comment]
```
bin/cake vers
Unknown command `cake vers`. Run `cake --help` to get the list of commands. Did you mean: `version`?

Other valid choices:

- version
- help
- plugin
- cache clear
- cache clear_all
- cache list
- completion
- i18n
- i18n extract
- i18n init
- routes check
- routes
- routes generate
- schema_cache build
- schema_cache clear
- server
- upgrade
- console
- bake mailer
- bake all
- bake helper
- bake middleware
- bake template all
- bake fixture
- bake component
- bake task
- bake plugin
- bake form
- bake template
- bake fixture all
- bake test
- bake command
- bake controller all
- bake model all
- bake behavior
- bake cell
- bake controller
- bake shell_helper
- bake model
- bake shell
- benchmark
- debug_kit.benchmark
- compile
- wyri_haximus/twig_view.compile
```

why in `Other valid choices:` that returns all commands ? even unrelated

**Comment by saeideng** [comment]
>Getting the grouping would be hard

:+1:  for not grouping

**Comment by markstory** [comment]
> why in Other valid choices: that returns all commands ? even unrelated

Would you want to only see results that match a fuzzier condition?

**Comment by ADmad** [comment]
> Would you want to only see results that match a fuzzier condition?

Yes

**Comment by markstory** [comment]
@ADmad Updated to use an edit distance of 8 instead of all options.

**Comment by ravage84** [comment]
1. How about ``NoMatchingOptionException`` or ``NoMatchingCommandException``?
2. I think the ``Did you mean: `xyz`?`` should go on a new line for better readability (might be off scope of this PR)

**Pull request merged**
