### PR TITLE
Make it possible to define a custom routeClass for builder redirects

### PR DESCRIPTION
**Pull request by patrickconroy**
Refs #10144

### CODE REVIEW

**Comment by dereuromark** [comment]
:+1:

**Review by markstory — CHANGES_REQUESTED** [review]
A test would be 🌈

**Comment by dereuromark** [comment]
@patrickconroy Are you still interested in picking this up?

**Comment by jeremyharris** [comment]
Feel free to ping me if you need help with the tests.

**Comment by saeideng** [comment]
I will add a test to this tonight unless someone added test before me

**Comment by dereuromark** [comment]
Looks like a test is now already in place.
:+1: All green it seems.

**Comment by lorenzo** [comment]
Thanks!

**Pull request merged**
