### PR TITLE
added `cssBlock()`, `cssStart()` and `cssEnd()` methods

### PR DESCRIPTION
**Pull request by mirko-pagliai**
What do you think about these?

If there are methods for JavaScript, I do not see why they should not exist for css.

I still have to add the test, for now I would just like to have your own opinion.

### CODE REVIEW

**Comment by saeideng** [comment]
You can write an example?
How to use it

**Comment by mirko-pagliai** [comment]
They work similar to `scriptBlock()`, `scriptStart()` and `scriptEnd()`.

Example:

    $this->Html->cssBlock('body { color: red; }');

or:

    <?php  $this->Html->cssStart(); ?>
    body {
        color: red;
    }
    <?php $this->Html->cssEnd(); ?>

**Comment by markstory** [comment]
> I do not see why they should not exist for css.

How often do you create inline snippets of CSS? I've only ever needed to generate standalone CSS files from PHP code.

**Comment by mirko-pagliai** [comment]
> How often do you create inline snippets of CSS?

For me this question makes no sense, because I could ask: how often do you create inline snippets of js?

It's clear it's better to put CSS code in a separate style sheet. As it's clear it's better to put javascript code in a separate file.

But it can happen that you need to have a code (css or javascript) only for a template file. Sometimes it happens to me.

Of course, these methods can use the `block` option, which clearly allows you to generate code cleaner.

**Comment by inoas** [comment]
> For me this question makes no sense, because I could ask: how often do you create inline snippets of js?

More often than for CSS. The JS is usually deferred to the bottom of the page load because its hopefully unobstrusive. And it usually plays with ajax and/or data that the rest of the app/pages do not need.
 
> It's clear it's better to put CSS code in a separate style sheet. As it's clear it's better to put javascript code in a separate file.

However that is not necessarily true. Depending on your app you may want to put things directly into the footer of your document.
Especially in the case of considering to build css from PHP (minification aside) it may be very specific to this action/element/cell. It is amount-of-requests VS code-size. For small code blocks you maybe don't want extra requests and document css is okay.

> But it can happen that you need to have a code (css or javascript) only for a template file. Sometimes it happens to me.

Same here.

> Of course, these methods can use the block option, which clearly allows you to generate code cleaner.

Little point without this feature.

**Comment by markstory** [comment]
> For me this question makes no sense, because I could ask: how often do you create inline snippets of js?

I do this in _every_ app I work on. It is the easiest way to pass state from PHP/HTML context into Javascript.

The reason I ask, is that we _could_ add a vast number of methods and end up with a very large/wide API. I don't think we should be adding methods for the sake of having them. A wider API is more intimidating to new developers, creates more complexity in CakePHP and creates more maintenance work in the future. 

I asked how frequently you create inline CSS, as its not a scenario I've ever had and was looking to see if you had use-cases I didn't. If however, you wouldn't often use this method I question why we would want to have it? Having methods that very few people need is wasteful, and this is a method that could easily be implemented in a plugin for folks that need it.

**Comment by ADmad** [comment]
I too am not in favor of adding these methods for the same reasons pointed out by @markstory above.

**Comment by mirko-pagliai** [comment]
> A wider API is more intimidating to new developers, creates more complexity in CakePHP and creates more maintenance work in the future

Clear!

**Comment by thinkingmedia** [comment]
I'm okay with this. I would use it.

When I do scaffolding for a table the width of the columns are inline styles, but using a style block would be better to reduce the number of bytes in the HTML.

What would be better is a add to add CSS styles as an array and have it injected in to the `<head>`.

**Comment by inoas** [comment]
As far as I know all prominent browsers defacto-support style-tags in the body. You should be able to choose if it goes into the head or is deferred.

**Comment by jadb** [comment]
Thanks for the initiative! 

However, I side by @markstory's suggestion of releasing those as part of a plugin for folks who have a need for them.

**Comment by mirko-pagliai** [comment]
I do not think is very useful an helper with 3 methods. But I fully understand what you have said and I agree, so ok!

**Comment by inoas** [comment]
@mirko-pagliai you can always extend `HtmlHelper` and alias it when loading so it appears to be 100% HtmlHelper + your three methods. As a plugin towards awesome cakephp.

I like the feature and I like the consistency (it is expected what works for javascript should work for css too), however I can see the point for no-feature-creep-please.

**Comment by mirko-pagliai** [comment]
@inoas It is what I have already done :-)

**Pull request closed without merging**
