### PR TITLE
Implements QueryExpression::exists and QueryExpression::notExists 

### PR DESCRIPTION
**Pull request by skie**
Implements QueryExpression::exists and QueryExpression::notExists metods. Solves #8820 issue.

### CODE REVIEW

**Comment by dereuromark** [comment]
Looks good!

**Comment by skie** [comment]
Docs in PR "Added exists and notExists query expression docs. #4213"

**Comment by lorenzo** [comment]
Thanks!!

**Comment by skie** [comment]
Please close #8820

**Comment by ADmad** [comment]
For convenience would be nice if support was also added for usage like `$query->where(['field EXISTS' => $subquery])` and similarly for `field NOT EXISTS`.

**Comment by skie** [comment]
Have sense, @ADmad. I found Cake\Database\Expression\QueryExpression::_parseCondition method where all magic happens. How we could check here that $subquery in this case is valid expression? Should we allow string value in this case? Should throw exception if string value passed instead of QueryInterface?

**Comment by ADmad** [comment]
Since only value value for `EXISTS` seems to be a sub query, check that `$value` implements `QueryInterface` should suffice I guess.  Or we could just let the database throw an error in case of an invalid value :)

**Comment by ADmad** [comment]
I just realized the example in my earlier comment `$query->where(['field EXISTS' => $subquery])` doesn't make sense since `EXISTS` isn't preceded by a field name. So usage would be more like `$query->where(['EXISTS' => $subquery])`.

**Comment by skie** [comment]
So lets keep it simple and avoid adding such complexity. Way to use EXISTS provided and documented.

**Pull request merged**
