### PR TITLE
Added missing comment function to ConsoleIo

### PR DESCRIPTION
**Pull request by GrandFelix**
Added missing function to ConsoleIo which is presented in documentation https://book.cakephp.org/4/en/console-commands/input-output.html#creating-output

### CODE REVIEW

**Comment by othercorey** [comment]
Looks ok for 4.2 if we want to add it. Need to re-target merge.

**Comment by ADmad** [comment]
This seems more like a case of docs being outdated. The methods were more likely updated to match the standard error levels in 4.x.

**Comment by markstory** [comment]
I think having the `comment()` method is a nice addition. It is low cost to us and makes building pleasant terminal UIs a bit easier.

**Comment by markstory** [comment]
I've cherry picked the relevant changes onto 4.next. Thank you @GrandFelix

**Pull request closed without merging**
