### PR TITLE
CounterCacheBehavior: Allow callback to refuse update

### PR DESCRIPTION
**Pull request by ypnos-web**
In some circumstances (see below) it is desirable to allow the refusal of updating a counter field. This is easy to do with a callback function, as the function may just return `null` instead of a count. A simple patch that you might like to accept.

My Motivation:
Currently, the CounterCacheBehavior only works if there is no condition on the association. A counter example for a Comments table:

```php
$this->belongsTo('Articles')
    ->setConditions(['belongs_to' => 'articles'])
    ->setForeignKey('foreign_id');
$this->addBehavior('CounterCache', [
    'Articles' => [ 'comment_count' => ['conditions' => ['belongs_to' => 'articles']]]
```
This works for all Comment entities that are associated with an Article. Comments that are not associated with an Article will still lead the behavior to try an update on the Articles table. With the patch, a custom callback can be used instead:
```php
$this->addBehavior('CounterCache', [
    'Articles' => [ 'comment_count' => function ($event, $entity, $table) {
        if ($entity->belongs_to != 'articles')
            return null;
        …
    ]]);
```

I am happy to provide corresponding tests if you would like to accept this pull request.

### CODE REVIEW

**Comment by markstory** [comment]
Isn't this a breaking change? You are changing the semantics of what null does.

**Comment by ypnos-web** [comment]
This is a valid point, in the current implementation it is possible to set the database field to NULL by returning null.

Do you think we should find a more complex solution to address the needed functionality, or would you say there is no demand in extending the Behavior for something like this?

**Comment by markstory** [comment]
Using false or raising an exception might be a safer way to handle aborts. False would mirror aborts in event listeners, and an exception would be very safe from a compatibility perspective.

**Comment by ypnos-web** [comment]
This is a solution using `false`. What do you think?

**Comment by markstory** [comment]
Looks good outside of a few phpcs erorrs.

**Comment by ypnos-web** [comment]
Yeah that was some stuff my IDE was doing.

**Comment by markstory** [comment]
Rebased and merged into `3.next` in 66633f741d1b2e1f720e67e10b7bf589a732e878

**Pull request closed without merging**
