### PR TITLE
Change to allow the class name in the setting of the fixture

### PR DESCRIPTION
**Pull request by slywalker**
Now, the setting of the class but possible with the class name that contains the name space, the setting of the test case of the fixture is this is not possible.

For setting of the class name that contains the name space is friendly to the IDE, I want to come to adopt.

### CODE REVIEW

**Comment by markstory** [comment]
Looks decent to me.

If you're interested in changing the default syntax for fixtures you could open a pull request on cakephp/bake.

**Comment by slywalker** [comment]
@markstory 
I'm not going to change the default syntax.
For example, in the setting of the association for us to accept this format.

```php
$this->belongsTo('Authors', [
    'className' => \Publishing\Model\Table\AuthorsTable::class,
    'foreignKey' => 'authorid',
    'propertyName' => 'person'
]);
```

Perhaps this is may not be what the development team had hoped, but it is very useful for people who use the IDE.
I just want to apply it to the fixture.

**Comment by markstory** [comment]
> Perhaps this is may not be what the development team had hoped, but it is very useful for people who use the IDE.

It is completely a feature we thought people might find useful :smile:

**Comment by slywalker** [comment]
Thanks 😄

**Pull request merged**
