### PR TITLE
remove all reference to DS contant

### PR DESCRIPTION
**Pull request by antograssiot**
ref comments in #8298 reagrding `DS` usage in the source code.

I intentionaly left [this definition](https://github.com/cakephp/cakephp/blob/master/src/Core/functions.php#L17-L23) to avoid to break things for people using cakephp/core in a standalone way but I'm open to if other thinks that it's a good idea.

Also I didn't remove it in the testsuite as it define in the [tests/bootstrap.php](https://github.com/cakephp/cakephp/blob/master/tests/bootstrap.php#L26-L28) but I could also remove it there and in the testsuite if you want to.

### CODE REVIEW

**Comment by dereuromark** [comment]
I really liked the short DS.. :/

**Comment by lorenzo** [comment]
I think I just merged something that caused a merge conflict for you :(

**Comment by antograssiot** [comment]
@lorenzo no pb, I resolve it, should be good now.

@dereuromark the short DS is still here as explained in the PR description

**Comment by antograssiot** [comment]
is there a way to restart the codecov check ?

**Comment by markstory** [comment]
@antograssiot You have to re-run the build in travis.

**Comment by jippi** [comment]
any reason for this change? I'm indifferent about the change, but just curious what it fixes / improves

compile-wise / performance-wise there are no difference 

can't find any discussion in #8298 regarding DS

**Comment by lorenzo** [comment]
fixes possible fatal errors when installing cakephp components separately and failing to manually define the constant

**Pull request merged**
