### PR TITLE
Remove the call to triggerBeforeFind from cleanCopy method

### PR DESCRIPTION
**Pull request by bancer**
#15141

### CODE REVIEW

**Comment by ndm2** [comment]
Won't this possibly break "complex" query assesment? [**`Query::_performCount()`**](https://github.com/cakephp/cakephp/blob/master/src/ORM/Query.php#L902) will asses the complexity, and use the query as a subquery if determined neccesary. Moving triggering `beforeFind()` so that it will apply to the count query, will cause `Query::_performCount()` to possibly not see the final count query when it's being modified in `beforeFind()`, thus it will not be able to asses its final complexity.

I have a feeling that this change would generally break many applications out there that never expected count queries to end up in their `beforeFind()` callbacks, as that seems to have been the behavior ever since CakePHP 3 was released.

**Comment by bancer** [comment]
@ndm2 Could you give an example so that it would be possible to write a unit test for that?

**Comment by ADmad** [comment]
@ndm2 Yes, given how long this behaviour has existed it would definitely need a good amount of thought. Perhaps we should even consider only changing things in 4.x (if at all) and leave 3.x as is.

**Comment by ADmad** [comment]
@bancer What use case do you have that's causing problem for you due to this behaviour?

**Comment by bancer** [comment]
> @bancer What use case do you have that's causing problem for you due to this behaviour?

We need to migrate some code from 2.x to 3.x. In some 2.x models in beforeFind callback we change the count query generated by the paginator in order to achieve acceptable performance. It is not possible to do that in 3.x table class at the moment because the query object is wrong in beforeFind for that paginator's count query.

**Comment by ADmad** [comment]
Since the pagination code has been extracted into a separate `Paginator` class in 3.9, what you want can be achieved in a better way by extending it and overriding its `getCount()` method. The PaginatorComponent can be configured to use your own paginator class.

**Comment by ndm2** [comment]
> @ndm2 Could you give an example so that it would be possible to write a unit test for that?

I'd have to do quite some trial and error first, I'm not quite sure what underlying problems exactly `Query::_performCount()` is trying to prevent by doing this subquery for "complex" cases. Given that there's no failing test yet, the problem might not have been tested properly, or the feature might even not be required, but that would need to be evaluated properly.

**Comment by ndm2** [comment]
> Since the pagination code has been extracted into a separate `Paginator` class in 3.9, what you want can be achieved in a better way by extending it and overriding its `getCount()` method. The PaginatorComponent can be configured to use your own paginator class.

Defining a custom count query in `beforeFind()` via `Query::counter()` might also work.

**Comment by ADmad** [comment]
Right, using Query::counter() might be a simpler option.

**Comment by bancer** [comment]
> Since the pagination code has been extracted into a separate Paginator class in 3.9, what you want can be achieved in a better way by extending it and overriding its getCount() method.

There is no `getCount()` method. In my understanding the count query is generated in `paginate()` method - https://api.cakephp.org/3.8/source-class-Cake.Datasource.Paginator.html#185:
```
$cleanQuery = clone $query;
$results = $query->all();
$numResults = count($results);
$count = $cleanQuery->count();
```
Refactoring this code to `getCount()` method would actually make it possible to override it.

> Defining a custom count query in beforeFind()...

That's what we basically do in 2.x but cannot do in 3.x because it is not possible to detect the paginator's count query in beforeFind.

> Given that there seems to be no failing existing test related to that, the problem might not have been tested properly, or the feature might even not be required, but that would need to be evaluated properly.

According to [pull request](https://github.com/cakephp/cakephp/pull/5151/files) where `$query->triggerBeforeFind();` was added to `cleanCopy()` method the intention was to remove `ORDER BY` clause from the count query - https://github.com/cakephp/cakephp/issues/5150. That unit test still passes.

**Comment by bancer** [comment]
Ah... `getCount()` exists in 3.9.

**Comment by othercorey** [comment]
Closing old draft.

**Pull request closed without merging**
