### PR TITLE
fix error at change type of text field to integer in PostgreSQL

### PR DESCRIPTION
**Pull request by kaz29**

### CODE REVIEW

**Comment by dereuromark** [comment]
@kaz29 Any chance you can provide the requested updates? We would like to release 2.6.1 the next days and it would be cool if we could include this fix. Thank you.

**Comment by kaz29** [comment]
THX!

**Comment by dereuromark** [comment]
@kaz29 Did you see the remarks above? Are you able to address them? Thank you.

**Comment by kaz29** [comment]
@dereuromark Yes, I will try fix that. but now i have no time. Please wait few days.

**Pull request merged**
