### PR TITLE
Refactor fieldType Method to Use match Expression

### PR DESCRIPTION
**Pull request by salehhashemi1992**
Replace the `switch` statement in the `fieldType` method with a PHP 8 `match` expression.

### CODE REVIEW

**Comment by othercorey** [comment]
I'm not sure this is easier to read. The `match(true)` statements can be hard to read with all the different types of checks in each case.

The switch() statement isn't great either. This feels like it should be individual if return blocks if anything.

**Comment by ADmad** [comment]
I find such match() usage readable enough. I think since it's a new syntax people still haven't got accustomed to it.

**Review by ADmad — APPROVED** [review]

**Comment by salehhashemi1992** [comment]
I'm checking the big repos a lot these days, and match expressions are everywhere. They are replacing old switch statements.

**Comment by othercorey** [comment]
> I think since it's a new syntax people still haven't got accustomed to it.

That isn't what I said. I didn't think this case was more readable. The switch(true) isn't a great choice IMO so didn't think match(true) made it easier to read.

But, if it's considered and improvement, then no problem with it.

**Comment by othercorey** [comment]
@salehhashemi1992 Thanks for the contribution :) Looks good regardless of the style discussion.

**Pull request merged**
