### PR TITLE
Fix issue 2.x Debugger class not found #7376

### PR DESCRIPTION
**Pull request by SanderSander**
Fix issue 2.x Debugger class not found #7376

### CODE REVIEW

**Comment by ravage84** [comment]
The commit messages could be a bit more helpful :smirk_cat:

**Comment by dereuromark** [comment]
Indeed, it should rebased/squashed and in the process you can define a more meaningful message.

**Comment by markstory** [comment]
I can fix up & squash the commits when merging.

**Comment by markstory** [comment]
Squashed commit merged into 2.7 in e8ce841ffbedd2eaf20c8229841c8e7289156cc3

**Pull request closed without merging**
