### PR TITLE
Remove dead code in ORM.

### PR DESCRIPTION
**Pull request by markstory**
These classes were undocumented, and aren't part of the current ORM implementation.

Refs #5755

### CODE REVIEW

**Comment by ADmad** [comment]
Tests failing. I already have a branch with passing test https://github.com/ADmad/cakephp/compare/cakephp:3.0...3.0-defunct-classes  I can PR it if you want.

**Comment by markstory** [comment]
@ADmad I'm just a muppet and can't commit code.

**Comment by jeremyharris** [comment]
Mark Story Coding

^ mark coding ;)

**Comment by AD7six** [comment]
Compared to a 1x developer:

**Comment by markstory** [comment]
@jeremyharris I feel like that quite often :smile:

**Comment by jeremyharris** [comment]
I think we all have moments of both comments haha

**Pull request merged**
