### PR TITLE
fix URL rewriting warning

### PR DESCRIPTION
**Pull request by marcinwenger**
currently giving a false negative

### CODE REVIEW

**Comment by ADmad** [comment]
Nope, current code is correct. The warning would have hidden if the css files exists and url rewriting is working.

**Comment by marcinwenger** [comment]
Well, it's actually quite the opposite. The warning hides if that css file isn't there. Correct me if I'm missing something.

**Comment by ADmad** [comment]
> The warning hides if that css file isn't there.

Yes it does. Since the display of warning relies on css rules in that file without that file the warning can't be hidden even if url rewriting is working. Basically the warning is relevant only upon initial install. Once you start your app development and delete the default css file you can't rely on this warning.

**Comment by marcinwenger** [comment]
ok, gotcha!

**Pull request closed without merging**
