### PR TITLE
add options of preg_replace limit

### PR DESCRIPTION
**Pull request by gnineh**

### CODE REVIEW

**Comment by dereuromark** [comment]
I would be nice if those commit messages where in English.
Otherwise we cannot read and understand them.

Apart from this the changes look good to me.

**Comment by ADmad** [comment]
We appreciate the contribution but as mentioned the commit messages needs to be in English.

**Review by markstory — CHANGES_REQUESTED** [review]
New features require tests to be merged.

**Comment by dereuromark** [comment]
I added a test.

**Pull request closed without merging**
