### PR TITLE
Switch to codecov for code coverage reporting.

### PR DESCRIPTION
**Pull request by ADmad**
It now uses GH annotations to show lines without test coverage on the pull request itself.
As seen here https://github.com/cakephp/cakephp/pull/14987/files

### CODE REVIEW

**Comment by othercorey** [comment]
Does it support using the .codecov.yaml filename?

**Comment by ADmad** [comment]
The docs only show use of `codecov.yml` https://docs.codecov.io/docs/codecov-yaml

**Comment by othercorey** [comment]
I assume you added the `comment: false` setting after it added the coverage comment.

Looks good to me other than the large number of existing code lines marked as not covered. Will this happen for each PR?

**Comment by markstory** [comment]
>  Looks good to me other than the large number of existing code lines marked as not covered. Will this happen for each PR?

There sure are a lot of line warnings on each pull request. Is there a way to scope the warnings to only the changed files.

**Comment by othercorey** [comment]
Looks like it is possible:

https://docs.codecov.io/docs/codecov-yaml#can-i-name-the-file-codecovyml

**Comment by ADmad** [comment]
@markstory I am pretty sure the annotations are only for lines changed in current PR.

@othercorey Moved to `.github/.codecov.yml`

**Comment by othercorey** [comment]
Lets see what happens

**Pull request merged**
