### PR TITLE
Ensure loading of deprecated classes.

### PR DESCRIPTION
**Pull request by ADmad**
This fixes "Class not found" errors when they are used in type declarations or instanceof checks.

### CODE REVIEW

**Comment by garas** [comment]
Up-to-date apps should not be penalized by loading two files.
_New_ class file should contain only `class_alias`, so _old_ class file is not loaded at all.
_Old_ class file should have contain `class_exists` + warning.

**Comment by ADmad** [comment]
Yes my bad, will update the PR.

**Comment by othercorey** [comment]
I've done this backwards for some classes.  We should have put the class_exists() in the old class location.

**Comment by dereuromark** [comment]
Sounds like we should finalize this validation Script for CI afterwards

**Pull request merged**
