### PR TITLE
Prefix all native PHP functions with backslash.

### PR DESCRIPTION
**Pull request by ADmad**
I am hoping someone can run some benchmarks and check if this gives any noticeable performance gains :slightly_smiling_face:.
Refs. https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/

### CODE REVIEW

**Comment by markstory** [comment]
We could use the apps in phpbenchmarks.com suite. They exercise a hello world scenario, and heavily exercise the router.

**Comment by ADmad** [comment]
Yeah is checked the phpbenchmark app but couldn't find any instructions on how to run the benchmarks.

**Comment by markstory** [comment]
I think they are using siege and apachebench to run their tests.

**Comment by tersmitten** [comment]
Do you have a "before" and "after" app that I can deploy easily?

We have some benchmarking machines / scripts in place

**Comment by markstory** [comment]
@tersmitten You could use https://github.com/cakephp/cms-tutorial and use 3f9db2b13ed8f3b3cbc4f60acd1131a4e5a1ed4d (dev-master) as the before, and this branch as the after.

**Comment by lorenzo** [comment]
Maybe have a composer script to this instead of having it in the core? It is going to be annoying for us, and userland code will not benefit from this.

**Comment by lorenzo** [comment]
Here's one https://github.com/nilportugues/php-backslasher

**Comment by tersmitten** [comment]
@markstory But that application uses a databases connection, right? The hello world app is probably data-less.

And do you want it benchmarked with or without opcache enabled?

**Comment by ADmad** [comment]
> Maybe have a composer script to this instead of having it in the core? It is going to be annoying for us, and userland code will not benefit from this.

I don't understand what you mean. 

> Here's one https://github.com/nilportugues/php-backslasher

I used `php-cs-fixer` for this. Was as easy as `php  php-cs-fixer-v2.phar fix src/ --rules=native_function_invocation --allow-risky yes`

**Comment by ADmad** [comment]
@tersmitten You can try using https://github.com/phpbenchmarks/cake-php-3-5/
Benchmarks with both opcode caching on and off would be nice.

**Comment by lorenzo** [comment]
I meant, this should not be in the core.

This should, if proved valuable, be offered as a part of a deploy script.

**Comment by markstory** [comment]
@lorenzo Are you concerned with the overhead of maintaining the `\` or the visual clutter it adds?

**Comment by robertpustulka** [comment]
Wouldn’t adding `use function strlen;` on top be the same as calling `\strlen`?

Backslashes look just ugly and it would be annoying to remember to add them. IDEs add the `use function` to the top of the class automatically.

**Comment by ADmad** [comment]
> Wouldn’t adding use function strlen; on top be the same as calling \strlen?

Yup it would be the same. If there's a tool which can automatically update existing files to add those "use" statement then we can use that.

> Backslashes look just ugly and it would be annoying to remember to add them. 

Add the backlash on file save can be automated by using tools like `php-cs-fixer`.

> IDEs add the use function to the top of the class automatically.

That depends on the IDE/editor. For e.g. VSCode automatically adds backslash when autocompleting php functions.

**Comment by thinkingmedia** [comment]
This smells like JavaScript where we must maintain two versions of our source code. The developer version with comments and the minified/optimized production version. I've never seen a PHP library do this.

If we incorporate this as a coding style we're forcing developers to work with the *production* version of the source code. It's hard enough to get past Stickler with missing spaces. I don't want to be chasing missing slashes or having to *productionize* each pull request.

I didn't real all the above comments and if this has already been discussed/resolved than great. I'm just fearful of having to remember to slash my functions.

This seems like a broad performance issue for all PHP source code. We could start a CakePHP/optimizer project?

**Comment by dereuromark** [comment]
@thinkingmedia No one forces you to use it in production
We still didnt even find out how much of a gain it would be - this is not even clear yet.
So I agree with @lorenzo 
For the time being this can be don on production server deployment as nano-opt if needed, but otherwise this is not something useful for anyone at this point in time most likely :)

**Comment by thinkingmedia** [comment]
@derekperkins Yeah, I figured I was just jumping into the middle of a discussion.

**Comment by inoas** [comment]
I am very much in agreement, I don't want to run deployment scripts that rewrite source code. I am pretty much happy with the core:
- staying the way it is
- getting prefixed
- having namespaces added on the top
... but I really would not want any deployment script (to be shipped as part of cakephp)

**Comment by lorenzo** [comment]
@markstory both, but mainly that it will become an extra burden for us during development, when it is something a machine can do for us at the time it actually matters

**Comment by inoas** [comment]
Well that machine would run on regexp and if not every single line is unit tested couldn't you have problems with the code transliteration in production?

**Comment by markstory** [comment]
@inoas I would expect a code-munging tool that is used when creating production code would be well tested. We trust other forms of code generation, how is this different?

**Comment by inoas** [comment]
It does not happen before deployment time for those generators, does it? I'd also prefer if we had a consistent code base in production, development and across different apps and developers (same framework). Just my 2 cents.

**Comment by ADmad** [comment]
> but mainly that it will become an extra burden for us during development..

We already have the burden of adding "use" statement for classes, compared to that adding a prefix to PHP functions (or "use" statements) ain't much more IMO. Plus editors/IDE help do it automatically or one can simply have a pre commit hook to do so using automated tools.

I too don't like the idea of modifying code during development.

All this discussion will become moot if benchmarks don't show any noticeable gains :)

**Comment by tersmitten** [comment]
I'll do my best to produce some results soon

**Comment by tersmitten** [comment]
Machine used:

screenshot from 2017-12-28 22-54-43

**Comment by tersmitten** [comment]
Benchmark script used:

```sh
# cat ab 
#!/usr/bin/env bash
#
# set -x;
#
# Ansible managed

ulimit -n 65535;
echo '1024 65535' > /proc/sys/net/ipv4/ip_local_port_range;

jot -s '' -b '#' 120;
echo '# ab.example.com | baseline';
jot -s '' -b '#' 120;

# Warm up
ab \
  -t 10 \
  -c 1 \
  -H 'Accept-Encoding: gzip,deflate' \
  -k \
  -l \
  'http://cakephp-11566-0.example.com/hello-world/hello-world' \
> /dev/null;

ab \
  -t 300 \
  -n 1000000 \
  -c 50 \
  -H 'Accept-Encoding: gzip,deflate' \
  -k \
  -l \
  'http://cakephp-11566-0.example.com/hello-world/hello-world' \
;
jot -s '' -b '#' 120;
sleep 60;
ab \
  -t 300 \
  -n 1000000 \
  -c 50 \
  -H 'Accept-Encoding: gzip,deflate' \
  -k \
  -l \
  'http://cakephp-11566-0.example.com/hello-world/hello-world' \
;
jot -s '' -b '#' 120;
sleep 60;
ab \
  -t 300 \
  -n 1000000 \
  -c 50 \
  -H 'Accept-Encoding: gzip,deflate' \
  -k \
  -l \
  'http://cakephp-11566-0.example.com/hello-world/hello-world' \
;
jot -s '' -b '#' 120;
sleep 60;

echo '32768 61000' > /proc/sys/net/ipv4/ip_local_port_range;
```

**Comment by tersmitten** [comment]
I tried the "cake-php-3-5" app but had some issues getting it up and running. Therefore I used https://github.com/cakephp/app with a "Hello world" controller:

```php
# cat src/Controller/HelloWorldController.php 
<?php
namespace App\Controller;

use Cake\Http\Response;

class HelloWorldController extends AppController
{
    public function helloWorld()
    {
        return new Response(['body' => 'Hello World !']);
    }
}
```

**Comment by tersmitten** [comment]
The **original app**: http://cakephp-11566-0.example.com/hello-world/hello-world
The **modified app**: http://cakephp-11566-1.example.com/hello-world/hello-world

**Modifications made**:

```sh
wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O bin/php-cs-fixer;
chmod 0755 bin/php-cs-fixer;

bin/php-cs-fixer fix src --rules=native_function_invocation --allow-risky yes;
bin/php-cs-fixer fix vendor/cakephp --rules=native_function_invocation --allow-risky yes;
```

**Comment by tersmitten** [comment]
```
########################################################################################################################
# ab.example.com | baseline
########################################################################################################################
Finished 668 requests
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking cakephp-11566-0.example.com (be patient)
Completed 100000 requests
Completed 200000 requests
Completed 300000 requests
Completed 400000 requests
Completed 500000 requests
Completed 600000 requests
Completed 700000 requests
Completed 800000 requests
Completed 900000 requests
Finished 996751 requests


Server Software:        Apache
Server Hostname:        cakephp-11566-0.example.com
Server Port:            80

Document Path:          /hello-world/hello-world
Document Length:        Variable

Concurrency Level:      50
Time taken for tests:   300.000 seconds
Complete requests:      996751
Failed requests:        0
Keep-Alive requests:    986901
Total transferred:      198916850 bytes
HTML transferred:       12957763 bytes
Requests per second:    3322.50 [#/sec] (mean)
Time per request:       15.049 [ms] (mean)
Time per request:       0.301 [ms] (mean, across all concurrent requests)
Transfer rate:          647.52 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   1.1      0      18
Processing:    13   15   2.1     14      63
Waiting:       13   15   2.1     14      63
Total:         13   15   2.3     14      68

Percentage of the requests served within a certain time (ms)
  50%     14
  66%     15
  75%     15
  80%     16
  90%     17
  95%     20
  98%     24
  99%     25
 100%     68 (longest request)
########################################################################################################################
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking cakephp-11566-0.example.com (be patient)
Completed 100000 requests
Completed 200000 requests
Completed 300000 requests
Completed 400000 requests
Completed 500000 requests
Completed 600000 requests
Completed 700000 requests
Completed 800000 requests
Completed 900000 requests
Finished 995294 requests


Server Software:        Apache
Server Hostname:        cakephp-11566-0.example.com
Server Port:            80

Document Path:          /hello-world/hello-world
Document Length:        Variable

Concurrency Level:      50
Time taken for tests:   300.000 seconds
Complete requests:      995294
Failed requests:        0
Keep-Alive requests:    985479
Total transferred:      198626925 bytes
HTML transferred:       12938822 bytes
Requests per second:    3317.65 [#/sec] (mean)
Time per request:       15.071 [ms] (mean)
Time per request:       0.301 [ms] (mean, across all concurrent requests)
Transfer rate:          646.57 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   1.1      0      17
Processing:    13   15   2.2     14      67
Waiting:       13   15   2.2     14      67
Total:         13   15   2.4     14      75

Percentage of the requests served within a certain time (ms)
  50%     14
  66%     15
  75%     15
  80%     16
  90%     18
  95%     20
  98%     24
  99%     25
 100%     75 (longest request)
########################################################################################################################
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking cakephp-11566-0.example.com (be patient)
Completed 100000 requests
Completed 200000 requests
Completed 300000 requests
Completed 400000 requests
Completed 500000 requests
Completed 600000 requests
Completed 700000 requests
Completed 800000 requests
Completed 900000 requests
Finished 997731 requests


Server Software:        Apache
Server Hostname:        cakephp-11566-0.example.com
Server Port:            80

Document Path:          /hello-world/hello-world
Document Length:        Variable

Concurrency Level:      50
Time taken for tests:   300.001 seconds
Complete requests:      997731
Failed requests:        0
Keep-Alive requests:    987876
Total transferred:      199112623 bytes
HTML transferred:       12970503 bytes
Requests per second:    3325.76 [#/sec] (mean)
Time per request:       15.034 [ms] (mean)
Time per request:       0.301 [ms] (mean, across all concurrent requests)
Transfer rate:          648.15 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   1.1      0      17
Processing:    13   15   2.5     14     224
Waiting:       13   15   2.5     14     224
Total:         13   15   2.7     14     224

Percentage of the requests served within a certain time (ms)
  50%     14
  66%     15
  75%     15
  80%     16
  90%     17
  95%     20
  98%     24
  99%     25
 100%    224 (longest request)
########################################################################################################################
```

**Comment by tersmitten** [comment]
```
########################################################################################################################
# ab.example.com | php-function-backslash
########################################################################################################################
Finished 665 requests
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking cakephp-11566-1.example.com (be patient)
Completed 100000 requests
Completed 200000 requests
Completed 300000 requests
Completed 400000 requests
Completed 500000 requests
Completed 600000 requests
Completed 700000 requests
Completed 800000 requests
Completed 900000 requests
Finished 973473 requests


Server Software:        Apache
Server Hostname:        cakephp-11566-1.example.com
Server Port:            80

Document Path:          /hello-world/hello-world
Document Length:        Variable

Concurrency Level:      50
Time taken for tests:   300.001 seconds
Complete requests:      973473
Failed requests:        0
Keep-Alive requests:    963859
Total transferred:      194271628 bytes
HTML transferred:       12655149 bytes
Requests per second:    3244.90 [#/sec] (mean)
Time per request:       15.409 [ms] (mean)
Time per request:       0.308 [ms] (mean, across all concurrent requests)
Transfer rate:          632.39 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   1.1      0      18
Processing:    13   15   2.6     14      65
Waiting:       13   15   2.6     14      65
Total:         13   15   2.8     14      76

Percentage of the requests served within a certain time (ms)
  50%     14
  66%     15
  75%     16
  80%     16
  90%     18
  95%     21
  98%     25
  99%     27
 100%     76 (longest request)
########################################################################################################################
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking cakephp-11566-1.example.com (be patient)
Completed 100000 requests
Completed 200000 requests
Completed 300000 requests
Completed 400000 requests
Completed 500000 requests
Completed 600000 requests
Completed 700000 requests
Completed 800000 requests
Completed 900000 requests
Finished 973436 requests


Server Software:        Apache
Server Hostname:        cakephp-11566-1.example.com
Server Port:            80

Document Path:          /hello-world/hello-world
Document Length:        Variable

Concurrency Level:      50
Time taken for tests:   300.001 seconds
Complete requests:      973436
Failed requests:        0
Keep-Alive requests:    963825
Total transferred:      194264349 bytes
HTML transferred:       12654668 bytes
Requests per second:    3244.78 [#/sec] (mean)
Time per request:       15.409 [ms] (mean)
Time per request:       0.308 [ms] (mean, across all concurrent requests)
Transfer rate:          632.37 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   2.5      0    1011
Processing:    13   15   3.4     14     451
Waiting:       13   15   3.4     14     451
Total:         13   15   4.2     14    1025

Percentage of the requests served within a certain time (ms)
  50%     14
  66%     15
  75%     16
  80%     16
  90%     18
  95%     21
  98%     25
  99%     27
 100%   1025 (longest request)
########################################################################################################################
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking cakephp-11566-1.example.com (be patient)
Completed 100000 requests
Completed 200000 requests
Completed 300000 requests
Completed 400000 requests
Completed 500000 requests
Completed 600000 requests
Completed 700000 requests
Completed 800000 requests
Completed 900000 requests
Finished 974505 requests


Server Software:        Apache
Server Hostname:        cakephp-11566-1.example.com
Server Port:            80

Document Path:          /hello-world/hello-world
Document Length:        Variable

Concurrency Level:      50
Time taken for tests:   300.001 seconds
Complete requests:      974505
Failed requests:        0
Keep-Alive requests:    964890
Total transferred:      194477945 bytes
HTML transferred:       12668565 bytes
Requests per second:    3248.34 [#/sec] (mean)
Time per request:       15.392 [ms] (mean)
Time per request:       0.308 [ms] (mean, across all concurrent requests)
Transfer rate:          633.06 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   1.1      0      17
Processing:    13   15   2.5     14      60
Waiting:       13   15   2.5     14      60
Total:         13   15   2.7     14      63

Percentage of the requests served within a certain time (ms)
  50%     14
  66%     15
  75%     16
  80%     16
  90%     18
  95%     21
  98%     25
  99%     27
 100%     63 (longest request)
########################################################################################################################
```

**Comment by dereuromark** [comment]
Looks like we can close this as irrelevant then :)

**Comment by tersmitten** [comment]
```sh
# grep opcache /etc/php/7.1/apache2/php.ini | grep -v ';'
[opcache]
opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=16229
opcache.validate_timestamps=1
opcache.revalidate_freq=0
opcache.fast_shutdown=1
```

**Comment by tersmitten** [comment]
```sh
# cat /etc/apache2/mods-enabled/mpm_prefork.conf 
# prefork MPM
# StartServers: number of server processes to start
# MinSpareServers: minimum number of server processes which are kept spare
# MaxSpareServers: maximum number of server processes which are kept spare
# MaxRequestWorkers: maximum number of server processes allowed to start
# MaxConnectionsPerChild: maximum number of requests a server process serves

<IfModule mpm_prefork_module>
  StartServers           350
  MinSpareServers        100
  MaxSpareServers        350
  ServerLimit            350
  MaxRequestWorkers      350
  MaxConnectionsPerChild 0
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

**Comment by tersmitten** [comment]
> Looks like we can close this as irrelevant then :)

I agree, but let's agree that my benchmarks are OK

**Comment by ADmad** [comment]
Aren't the request per second actually marginally decreasing with backslash prefixed functions? :smile: 

A test which hits the DB and on a slightly modest machine would have been better IMHO, but based on these results I doubt that would have shown any worthwhile gain either.

**Comment by dereuromark** [comment]
One - and the most important - aspect has also not been mentioned once:
As a framework it should always be open for modification when needed - taking away functions to be exchangable in the case of project need is also not a good thing. E.g. __() or other ones that might need small custom adjustments to work in a specific env.
Sure, most should never have to - but just taking that possibility away for no good reason..

Looks like future discussion can then move to forum, irc or other channels and are out of scope of the issue and PR section of core then.

**Comment by dereuromark** [comment]
I sure hope it wont come that far.

**Pull request closed without merging**
