### PR TITLE
Added method getError() to Form #17219

### PR DESCRIPTION
**Pull request by Staubiii**
Implements  #17219

### CODE REVIEW

**Comment by ravage84** [comment]
Do we need to merge this into 4.5 instead?

**Comment by othercorey** [comment]
@Staubiii Please rebase your branch into 4.next

**Comment by ravage84** [comment]
@othercorey rebased.

**Comment by Murl080** [comment]
Added example for Form getError method in https://github.com/cakephp/docs/pull/7668

**Comment by markstory** [comment]
Thank you 🎉

**Pull request merged**
