### PR TITLE
Update cake.php

### PR DESCRIPTION
**Pull request by EOM**
Hi, 
Now feature in cake Console, add o set ENVIRONMENT in CLI, it's possible..?

Example use CRON limit use:
/usr/bin/php /var/www/clients/client508/web1676/dev/app/Console/cake.php get_num_rest APP_ENV=pro

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

Always follow the [contribution guidelines](https://github.com/cakephp/cakephp/blob/master/.github/CONTRIBUTING.md) when submitting a pull request. In particular, make sure existing tests still pass, and add tests for all new behavior. When fixing a bug, you may want to add a test to verify the fix.

### CODE REVIEW

**Comment by markstory** [comment]
Any reason you aren't using your shell's ability to set env vars? I do something like

```
FOO=stuff Console/cake do_task
```

And it works quite well.

**Comment by EOM** [comment]
Hi Markstory,
The problem prevails when there are cron's that are very limited to run.
For example in ISPConfig in VPS does not allow more than just run URL or a simple command, and does not allow chaining "&&" command or use bash ".sh".
Example was the case of my problem in an ISPConfig, where I could execute just something like this.

/usr/bin/php /var/www/clients/dev/app/Console/cake.php get_num_rest APP_ENV=pro DEBUG_ENV=0

Not suport ;(
APP_ENV=pro DEBUG_ENV=0 ./Console/cake get_num_rest bla bla ....
export APP_ENV=pro && export DEBUG_ENV=0 && ./Console/cake get_num_rest bla bla...

Markstory, do not you think that's a good idea, to have something inside the code that supports that ...?
Inside the cake.php code or inside the class ShellDispatcher.

To have more flexibility in more hosting environments ..? ;)

**Comment by markstory** [comment]
> For example in ISPConfig in VPS does not allow more than just run URL or a simple command, and does not allow chaining "&&" command or use bash ".sh".

In these environments you could use wrapping shell scripts. I'm reluctant to add features to the framework that duplicate features that are generally operating system features. The CLI library also has the ability to set options/arguments which can be used to change application behavior.

**Comment by EOM** [comment]
Ahh very good. I did not know that I could extend and modify the behavior so I can load parameters before I load bootsrap. Because I try u can not and in the cake manual I did not find anything.

**Comment by rchavik** [comment]
Closing as workaround exists.

**Pull request closed without merging**
