### PR TITLE
Use null coalescing assignment.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by othercorey** [comment]
Looks ok to me. Seems like a couple possible static analyzer bugs with nullable parameters.

**Comment by dereuromark** [comment]
The one downside: cloaking where it wasnt needed so far.
But with static analyzer maybe to some degree less an issue.

**Comment by othercorey** [comment]
You mean hiding code coverage since it's a single expression? I wish code coverage could show more than just a line number.

**Comment by dereuromark** [comment]
No, empty()/isset() cloaking where it is not needed and if ever changed would hide that by not producing notice.

**Comment by dereuromark** [comment]
Thats why I prefer ?: over ?? where null and empty values have no valid meaning.

**Comment by ndm2** [comment]
> You mean hiding code coverage since it's a single expression? I wish code coverage could show more than just a line number.

This. I like all the new fancy null coalescing functionality that PHP now has, but I very much dislike how it hides coverage 😢 PCOV can't generate path coverage, but even if it could, I don't think that Codecov supports it.

**Comment by ADmad** [comment]
@ndm2 Your concerns about path coverage are valid but I think the static analyzers would complain about null value usage if we were to actually miss properly initializing a property/variable. Only for the rare cases where `null` is also a valid value would it be an issue.

**Comment by ADmad** [comment]
> Thats why I prefer ?: over ?? where null and empty values have no valid meaning.

Need to be careful using `?:` for strings/numeric types as it would gobble up `0` and `'0'`. For objects both `?:` and `??` become effectively the same.

**Comment by ADmad** [comment]
Also PHP doesn't allow using `?:` for assignment so there's that.

**Comment by dereuromark** [comment]
Jep, it sure isnt ideal. Just saying: Using the cloaking ones are not the silver bullet either in many of these cases.
Would be nice if there were also proper operators for the existing ("supposed to exist") keys/props.

**Comment by markstory** [comment]
Couldn't we also address some of the cloaking issues via parameter/return types? Most of these changes seem like they would be covered from cloaking because of the surrounding runtime type checks.

**Comment by ADmad** [comment]
Yup the param/return types we have would safeguard against cloaking in most cases.

**Comment by ADmad** [comment]
So can this be merged?

**Pull request merged**
