### PR TITLE
Set max php version for split packages

### PR DESCRIPTION
**Pull request by othercorey**
Copy the changes from https://github.com/cakephp/cakephp/commit/a7bedf10bb41ed68d9e0281ee26945ab3960fd3f to split packages.

### CODE REVIEW

**Comment by dereuromark** [comment]
Interesting
We don't try to allow PHP8 for Cake3?

Isn't the compatibility doable in a 3.next? And preferrable to forcing the devs running an outdated PHP 7 at some point?

**Comment by othercorey** [comment]
It requires an unknown amount of work and people are trying to use it thinking it's just a single variable patch. If someone decides to backport everything to 3.10 and we release that, then we can update these.

**Comment by markstory** [comment]
> Isn't the compatibility doable in a 3.next? And preferrable to forcing the devs running an outdated PHP 7 at some point?

It is potentially doable, but getting 3.next to PHP8 requires bumping PHPUnit and that requires breaking changes in CakePHP or runtime hacks.

**Comment by dereuromark** [comment]
Well, the source could might still be very well compatible with it. So restricting that then could be cumbersome for many.
The testing harness is sure a different problem, though.

**Comment by othercorey** [comment]
What is the concern here?

3.10 is not in development and we don't know what breaks with php 8. We don't have any way to test patches.

Are you saying it should not be restricted in case someone works on a patch in a year? We can't tell users it will be done at the moment.

**Comment by dereuromark** [comment]
I would suggest breaking API now in a branch just to see how PHP8 is running with Cake3.
And then make an informed decision based on that - rather than just closing it down due to the test harness issue
As 99% the core works fine with PHP8 :)

**Comment by othercorey** [comment]
Feel free.

**Comment by othercorey** [comment]
Also, if you decide to test and enable support, need to revert the commit mentioned in the summary. This PR just fixes it.

**Comment by ADmad** [comment]
Just stumped upon this: https://github.com/Yoast/PHPUnit-Polyfills

**Comment by othercorey** [comment]
We should merge this or revert the original commit - to be consistent.

**Pull request merged**
