### PR TITLE
2.6.2: cake bake / ModelTask should respect decimal

### PR DESCRIPTION
**Pull request by ionas**
PR for https://github.com/cakephp/cakephp/issues/6066

### CODE REVIEW

**Comment by markstory** [comment]
Looks reasonable to me.

**Comment by jhli** [comment]
2.7 or 2.6.4?

**Comment by markstory** [comment]
2.6. It feels like abugfix size change.

**Comment by ADmad** [comment]
@markstory Then it's need to be backported as this PR was merged to 2.7 :)

**Comment by markstory** [comment]
Whoops. 2.7 it is then :-)

**Comment by ionas** [comment]
Meh :/ ok.

**Pull request merged**
