### PR TITLE
Fix regression caused by #6942

### PR DESCRIPTION
**Pull request by ADmad**
I don't think it's possible to fix the regression while keeping the new feature added in #6942, so I reverted it.

### CODE REVIEW

**Comment by markstory** [comment]
Could we also store the undotted path in the registry? That might allow both the old behavior and new 'fix' to continue working?

**Comment by ADmad** [comment]
I don't really like the unnecessary duplication and extra memory use. Plus it would cause problem if some tries to use cache config names `foo` as well as `foo.bar`.

**Comment by markstory** [comment]
Yes the duplication in key names could be a problem. I think reverting is probably the best option unfortunately.

**Comment by lorenzo** [comment]
Can we add an exception if we have className and a dotted name?

**Comment by ADmad** [comment]
@lorenzo You mean allow dot in name if className is provided in config?

**Comment by ADmad** [comment]
Closing in favor of #7057

**Pull request closed without merging**
