### PR TITLE
Allow camelBacked virtualProperties to be accessed.

### PR DESCRIPTION
**Pull request by markstory**
This fixes a regression introduced in while optimizing entity accessors.

Refs #8246

### CODE REVIEW

**Comment by markstory** [comment]
MySQL+PHP5.6 build failed for a seemingly random reason.

**Comment by lorenzo** [comment]
Those random fails sure are annoying

**Comment by markstory** [comment]
@lorenzo Yes. I've been adding skips here and there, but every few weeks/days it seems that another PHP5.6 test fails.

**Comment by lorenzo** [comment]
@markstory I have an idea to fix it

**Comment by markstory** [comment]
@lorenzo Cool :+1:

**Pull request merged**
