### PR TITLE
4.x - Added sqlserver support for fractional datetime schema types

### PR DESCRIPTION
**Pull request by othercorey**
This adds fractional schema type support as well as some sqlserver maintenance.

- Maps types to the new datatimefractional type
- Changes the data type to schema type mapping from `TYPE_TIMESTAMP` to `TYPE_DATETIME`
- Changes the SQL generation for 'datetime' fixture type to `datetime2` sqlserver data type
- Allows for default values to be functions like `sysdatetime()` which return `datetime2` types
- Make sure boolean types are cast to int only after a null check

### CODE REVIEW

**Comment by othercorey** [comment]
@ADmad @markstory This is finally ready for review.

**Review by markstory — APPROVED** [review]
Looks good to me.

**Comment by markstory** [comment]
What does the timestamp abstract type generate in sqlserver now?

**Comment by othercorey** [comment]
> What does the timestamp abstract type generate in sqlserver now?

It generates a `datetime2` column data type the same as `datetime`.  It's just an alias ... similar to how postgres works.

**Pull request merged**
