### PR TITLE
Add test to show bug in SqlserverSchema when using `DEFAULT NULL`.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
I don't have any knowledge about Sqlserver so would appreciate it if someone would help fix the issue.

**Comment by markstory** [comment]
I can try and figure this out. I lost my windows7 VM when my hard drive failed last month, but I should be able to get another one going.

**Comment by ADmad** [comment]
@markstory A gentle reminder :)

**Comment by markstory** [comment]
@ADmad I've not had a chance to build a new windows VM. This is still on my radar though :smile:

**Comment by ADmad** [comment]
@markstory Okay, no problem :)

**Pull request merged**
