### PR TITLE
Issue #17011

### PR DESCRIPTION
**Pull request by fr3nch13**
Check to make sure the $template is specifically a string in src/View/StringTemplate::_compileTemplates()

### CODE REVIEW

**Comment by markstory** [comment]
Thank you 🎉

**Comment by ADmad** [comment]
I would rather use `assert()` here instead of `is_string()` since templates should always be string or null.

**Comment by fr3nch13** [comment]
But shouldn't you only ever be doing str_replace and preg_match_all on strings?
Or are you thinking to throw an exception if it isn't.
In my specific case, I could use null for the template if I don't want that specific template included in my output, in this case json.

**Comment by dereuromark** [comment]
The merge of this made https://github.com/cakephp/cakephp/pull/17012 invalid
I also think that assert() should be fine to use here. It also makes it bubble up, right now any invalid casing would just be a no-op and silent.

**Comment by ADmad** [comment]
> But shouldn't you only ever be doing str_replace and preg_match_all on strings?

Templates should always be strings, if you don't want any output use an empty string. I just mentioned null too as there already seems to be added check for it.

**Pull request merged**
