### PR TITLE
Using _cookieName() instead session_name()

### PR DESCRIPTION
**Pull request by phpnut**
This should fix the issues reported in #8062

### CODE REVIEW

**Comment by markstory** [comment]
Looks good to me.

**Comment by dereuromark** [comment]
Should we port this to 2.7?

**Comment by phpnut** [comment]
Yes I think the session_name() in CakeSession::renew() has been there for a while.

**Comment by dereuromark** [comment]
Yeah, I didnt see any recent changes, therefore it was strange to me that those issues occurred in the 2.7 branch...

**Comment by chinpei215** [comment]
Thank you, @phpnut.

**Pull request merged**
