### PR TITLE
3.next - HTTP method route creation helpers

### PR DESCRIPTION
**Pull request by markstory**
Add methods to RouteBuilder that make connecting routes for a single HTTP method simpler.

Refs #10689

### CODE REVIEW

**Review by lorenzo — COMMENTED** [review]
I feel like the new methods should have an optional $options arguments, for stuff like setting regular expressions for the capture arguments.

**Comment by markstory** [comment]
@lorenzo From the previous discussions people were leaning towards using the fluent interface methods added to Route. I am open to adding an options parameter like connect() has if it will be used.

**Comment by lorenzo** [comment]
Do we expose methods for setting each of the options separately? In my view it is still a good idea to have it, even though we can encourage to use the fluent methods

**Comment by markstory** [comment]
@lorenzo Not yet we don't but all the options will have methods in the next week or so.

**Comment by markstory** [comment]
@lorenzo If it is ok with you, I'd like to hold off on adding the options parameter right now. Lets require use of the fluent interface and see how people respond. It will be a quick change for a future release.

**Pull request merged**
