### PR TITLE
Implement Table::name()

### PR DESCRIPTION
**Pull request by AD7six**
We don't currently have a means to know the table name, accounting for auto-table instances.

### CODE REVIEW

**Comment by markstory** [comment]
How do you see this being used? Does the table name need to be mutable? It seems like the kind of thing that shouldn't be modified.

**Comment by AD7six** [comment]
> How do you see this being used?

See [the discussion in the translate behavior about alias/'model' usage](https://github.com/cakephp/cakephp/pull/5983#discussion_r25559784)

> Does the table name need to be mutable?

I don't think so, though I made it so just because.

**Comment by markstory** [comment]
If name() doesn't need to be mutable right now. I would leave it as immutable until a good use case comes up.

**Comment by AD7six** [comment]
Ok, I removed the ability to change name.

**Comment by lorenzo** [comment]
I'm not convinced of the use case for this, wouldn't the problem for the translate behavior be solved by using the registryAlias instead. Having 3 different names for the same object seems like too much for me

**Comment by AD7six** [comment]
After discussing with Jose, not merging this and instead [implementing it directly in the translate behavior](https://github.com/cakephp/cakephp/commit/a764fcffe7a960b686c7beaa05e35f4e77cf0e50) as it's the only known use case. 

I'm sceptical we won't need this - but if/when it proves necessary, we can simply resurrect this PR.

**Pull request closed without merging**
