### PR TITLE
Adds default value parameter to the env() function.

### PR DESCRIPTION
**Pull request by michaelze**
This adds an additional parameter to the env() function that allows to provide a default value in case the requested environment variable is not defined.
So instead of writing

```
$setting = env('SETTING') != null ? env('SETTING') : 'default value';
```

one can now simply write

```
$setting = env('SETTING', 'default value');
```

### CODE REVIEW

**Comment by lorenzo** [comment]
Looks like a good idea to me

**Comment by ADmad** [comment]
Shouldn't this be added to `Request::env()` instead?

**Comment by josegonzalez** [comment]
@ADmad instead/as well.

**Comment by ADmad** [comment]
Can't one just use `$setting = env('SETTING') ?:  'default value';`.  Are there are cases where non-existent and empty string environment values need to be treated differently?

**Comment by josegonzalez** [comment]
Userland code looks nicer.

**Comment by ADmad** [comment]
Using core PHP operator looks more readable to me personally, but ok.

**Comment by michaelze** [comment]
Thanks for your comments.
Adding this to `Request::env()` is a nice idea, haven't thought of this yet. Do you have any suggestions on how to implement this? `Request::env()` already has a second parameter that allows to set an environment variable instead of reading it.

**Comment by markstory** [comment]
Test failures look like XML formatting differences again.

**Comment by michaelze** [comment]
I just realized, that my example in the PR description was wrong. Corrected!

**Comment by michaelze** [comment]
Also implemented the default value parameter into the `Request::env()` method. Not very happy with having to provide `null` for the `$value` parameter. Any thoughts on this? Maybe an additional method that implements the default behaviour (like `Request::envDefault($key, $default = null)`)?

**Comment by ADmad** [comment]
Yeah I forgot Request::env() already had a second param when I suggested changing it. Better to keep it as it is.

**Comment by markstory** [comment]
The combined get/set in `Request` have caused nothing but trouble. #7328 is another example for other similar methods. Perhaps making separate get/set methods and allow getters to return defaults is something we should consider for 4.0.

**Comment by michaelze** [comment]
So I guess I remove the second commit modifying `Request::env()` from the PR?

**Comment by Oxicode** [comment]
+1

**Comment by markstory** [comment]
I think the third argument is ok for now. We could always add new `getX`, and `setX` methods to avoid breaking compatibility now.

**Comment by dereuromark** [comment]
:+1:

**Comment by michaelze** [comment]
Just celebrating my first real code contribution to an open source project :)! Thanks for all your feedback and effort!

**Comment by lorenzo** [comment]
:clap:

**Pull request merged**
