### PR TITLE
Add support for placeholders in validation message

### PR DESCRIPTION
**Pull request by jadb**
Something like this would now be possible:

```
$validator->add('picture', 'file', [
    'rule' => ['mimeType', ['image/jpeg', 'image/png']],
    'message' => 'Wrong mime type. (Got :mimeType)',
]);
```

### CODE REVIEW

**Comment by jadb** [comment]
Am closing this - on a second thought - I think there is better and investigating before just jumping to conclusions ;)

**Comment by jadb** [comment]
For the record, a callable that returns the message string I think is the right way. Documentation in the book is missing and I tried hurrying out a solution for someone instead of reading a little more first.

**Comment by ravage84** [comment]
@jadb could you create an issue for the docs repo?

**Comment by jadb** [comment]
Done :)

**Pull request closed without merging**
