### PR TITLE
Fix path docs

### PR DESCRIPTION
**Pull request by dereuromark**
https://github.com/cakephp/app/tree/master/templates

- layout
- element

and consolidate paths

### CODE REVIEW

**Comment by othercorey** [comment]
We use \*\*bold\*\* in the book docs for paths. Should we do the same here? Users won't always see it rendered as bold.

**Comment by dereuromark** [comment]
I dont think we should use ** inside docblocks, the code fencing is especially for this case (and was also already in a lot of other places).
We could instead render those code blocks in the API docs if we want, as <code></code> etc.

**Comment by markstory** [comment]
> We use **bold** in the book docs for paths. Should we do the same here? Users won't always see it rendered as bold.

We've been using inline code for paths in the API, which is inconsistent with the docs. We could change the API docs, to also use bold formatting, but I'm not sure the API docs and book need to be consistent.

**Comment by ADmad** [comment]
I too don't see the need to use bold for paths.

**Pull request merged**
