### PR TITLE
Closes Issue 6240 for CakePHP 3.x branch

### PR DESCRIPTION
**Pull request by justinyost**
Includes a test case to cover this.

### CODE REVIEW

**Comment by antograssiot** [comment]
looks good now

**Comment by jtyost2** [comment]
So much singularizing/pluralizing going on in there I messed up the tests first time around.

**Comment by ADmad** [comment]
Please squash the commits into a single commit.

**Comment by jtyost2** [comment]
Squashed as requested.

**Comment by jtyost2** [comment]
@ADmad Thanks for shepherding this across the metaphorical finish line.

**Pull request merged**
