### PR TITLE
Create logs directory when not in debug mode (resolves issue #7512).

### PR DESCRIPTION
**Pull request by davehensley**

### CODE REVIEW

**Comment by dereuromark** [comment]
Yes, this is done deliberately. This debug auto-create is just a handy thing for local development. It is not meant to be used in production. 
Your deploy script should take care of creating necessary folders for production mode.

**Comment by Marlinc** [comment]
I'm not sure if the directory layout of a application should be changed by the core when not in debug mode.

**Comment by davehensley** [comment]
Cake\Cache\Engine\FileEngine already creates directories when it needs them. Is there a good argument for not making FileLog behave the same way?

**Comment by Marlinc** [comment]
Then do be honest I think that should be removed from the cache engine as well. Directory layouts shouldn't be changed by the core.

**Comment by ADmad** [comment]
:-1: for me too.

`FileEngine` shouldn't be doing it either. But removing it now would probably be a backwards compatibility so cannot be changed at least until 3.2.

**Pull request closed without merging**
