### PR TITLE
Use CURSOR_FWDONLY instead of CURSOR_SCROLL

### PR DESCRIPTION
**Pull request by othercorey**
Running tests on changing the cursor type to default `CURSOR_FWDONLY`. This should help performance while keeping the ability to buffer results.

### CODE REVIEW

**Comment by othercorey** [comment]
Interesting result running fixtures:

```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: [Microsoft][ODBC Driver 13 for SQL Server]Connection is busy with results for another command in C:\projects\cakephp\src\Database\Driver.php:222
Stack trace:
#0 C:\projects\cakephp\src\Database\Driver.php(222): PDO->beginTransaction()
#1 C:\projects\cakephp\src\Database\Connection.php(477): Cake\Database\Driver->beginTransaction()
#2 C:\projects\cakephp\src\Core\Retry\CommandRetry.php(69): Cake\Database\Connection->Cake\Database\{closure}()
#3 C:\projects\cakephp\src\Database\Connection.php(478): Cake\Core\Retry\CommandRetry->run(Object(Closure))
#4 C:\projects\cakephp\src\Database\Connection.php(688): Cake\Database\Connection->begin()
#5 C:\projects\cakephp\src\TestSuite\Fixture\FixtureManager.php(391): Cake\Database\Connection->transactional(Object(Closure))
#6 C:\projects\cakephp\src\TestSuite\Fixture\FixtureManager.php(441): Cake\TestSuite\Fixture\FixtureManager->_runOperation(Array, Object(Closure))
#7 C:\projects\cakephp\src\TestSuite\Fixture\FixtureInjector.php(1 in C:\projects\cakephp\src\Database\Driver.php on line 222
```

**Comment by iomariani** [comment]
> Interesting failure immediately running fixtures on appveyor:
> 
> ```
> PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: [Microsoft][ODBC Driver 13 for SQL Server]Connection is busy with results for another command in C:\projects\cakephp\src\Database\Driver.php:222
> Stack trace:
> #0 C:\projects\cakephp\src\Database\Driver.php(222): PDO->beginTransaction()
> #1 C:\projects\cakephp\src\Database\Connection.php(477): Cake\Database\Driver->beginTransaction()
> #2 C:\projects\cakephp\src\Core\Retry\CommandRetry.php(69): Cake\Database\Connection->Cake\Database\{closure}()
> #3 C:\projects\cakephp\src\Database\Connection.php(478): Cake\Core\Retry\CommandRetry->run(Object(Closure))
> #4 C:\projects\cakephp\src\Database\Connection.php(688): Cake\Database\Connection->begin()
> #5 C:\projects\cakephp\src\TestSuite\Fixture\FixtureManager.php(391): Cake\Database\Connection->transactional(Object(Closure))
> #6 C:\projects\cakephp\src\TestSuite\Fixture\FixtureManager.php(441): Cake\TestSuite\Fixture\FixtureManager->_runOperation(Array, Object(Closure))
> #7 C:\projects\cakephp\src\TestSuite\Fixture\FixtureInjector.php(1 in C:\projects\cakephp\src\Database\Driver.php on line 222
> ```
> 
> Similar error about 50% of the way through on github actions:
> 
> ```
> PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: [Microsoft][ODBC Driver 17 for SQL Server]Connection is busy with results for another command in D:\a\cakephp\cakephp\src\Database\Driver.php:222
> Stack trace:
> #0 D:\a\cakephp\cakephp\src\Database\Driver.php(222): PDO->beginTransaction()
> #1 D:\a\cakephp\cakephp\src\Database\Connection.php(477): Cake\Database\Driver->beginTransaction()
> #2 D:\a\cakephp\cakephp\src\Core\Retry\CommandRetry.php(69): Cake\Database\Connection->Cake\Database\{closure}()
> #3 D:\a\cakephp\cakephp\src\Database\Connection.php(478): Cake\Core\Retry\CommandRetry->run()
> #4 D:\a\cakephp\cakephp\src\Database\Connection.php(688): Cake\Database\Connection->begin()
> #5 D:\a\cakephp\cakephp\src\TestSuite\Fixture\FixtureManager.php(391): Cake\Database\Connection->transactional()
> ```

I had that exception thrown every time I forgot to close a statement before opening another one.
Even with `CURSOR_SCROLL` though...

**Comment by othercorey** [comment]
I will debug the connection issue when I get a chance. We should be able to use a normal cursor here.

**Comment by othercorey** [comment]
Looks like the connection is blocked on something other than closeCursor().

**Pull request closed without merging**
