### PR TITLE
Use Elvis operators instead

### PR DESCRIPTION
**Pull request by Theaxiom**
This is me splitting up a larger PR, please see #10532 for details.

### CODE REVIEW

**Comment by ADmad** [comment]
Looks good, needs rebase.

**Comment by markstory** [comment]
I fixed conflicts in the web-ui, just waiting for builds to pass.

**Comment by ADmad** [comment]
I fixed CS error using web-ui. :smile:

**Comment by Theaxiom** [comment]
I love the ability to edit PR's directly using the web-ui. 👍

**Pull request merged**
