### PR TITLE
Log Viewer tools, can't read rotated log file

### PR DESCRIPTION
**Pull request by elbakai**
After log file rotate, the filename end by a timestamp value, which give us a file without extension (ex: error.log.1474473727), and when we try to read the log to analyse it using some Logviewer tools ex.(OtrosLogViewer), it can not read it, the same thing when we try to open the file directly from remote server using Filezilla. so we should rename the log file and add a log extension (error.log.1474473727.log) to make it work.

after this edit it's be fine

### CODE REVIEW

**Comment by ADmad** [comment]
If we are gonna fix this let's do it the right way and generate names like `error.1474473727.log` and avoid duplicate `.log` in the file name. Or can also do `1474473727.error.log`.

Also this change should target `3.next` so that it goes into next minor release. Someone might be relying on the current naming space and changing that in bugfix release can cause them problem.

**Comment by markstory** [comment]
This is fine by me. We'll need the tests updated though as they are currently failing.

**Comment by josegonzalez** [comment]
I'm actually 👎 . If you ship your logs to centralized logging, the pattern is usually to ship with `/path/to/log/dir/*.log`. If we added `*.log` to the end, those logs will be re-shipped in full.

Personally I think any remote log-viewers can and should be configured to accept reading log files without a `.log` extension.

**Comment by markstory** [comment]
@josegonzalez If you are using centralized logging would you also use application level log rotation? I see app-layer file log rotation as a poor-person's `logrotate`

**Comment by josegonzalez** [comment]
Application log rotation is enabled by default, so whether I'd use it or not is irrelevant, no?

**Comment by markstory** [comment]
@josegonzalez Fair point.

**Comment by ADmad** [comment]
Log rotation is done only in `FileLog` engine. If you switch to a centralized logger you would be using another log engine without any applicable level rotation.

**Comment by josegonzalez** [comment]
Many of my applications log to a file, whose contents are then shipped via something like nxlog, beaver, or logstash to a central server. I think thats a pretty common pattern, and in that case, I'd be using the FileLog engine.

**Comment by markstory** [comment]
Closing as @josegonzalez has raised good points about this complicating deployment and operations.

**Pull request closed without merging**
