### PR TITLE
Use self instead of $this for IDE compatibility.

### PR DESCRIPTION
**Pull request by dereuromark**
`$this` breaks the IDE completely, even in the newest PHPStorm version.
Using `self` actually works fine.

Why did we cling to `$this` again? Can we switch to `self` now when this confirmed to work properly as expected?

Follow up on https://github.com/cakephp/cakephp/pull/9892

### CODE REVIEW

**Comment by dereuromark** [comment]
Should we do this on master instead to avoid merge conflicts between 3.x?

**Comment by markstory** [comment]
> Why did we cling to $this again? 

It was either recommended in the PHPDoc guidelines, or a previous round of IDE advocacy.

**Comment by ndm2** [comment]
AFAIR `$this` was choosen because it's the technically correct type. `self` indicates that a new instance of the class where the type is being declared is being returned, that's very different to `$this`, which indicates that a reference to the same object is being returned.

This change will for example break completion and inspections on inherited classes, as the wrong return types will be assumed. Take a `\Cake\ORM\Query` instance for example, as soon as you call one of the methods defined in `\Cake\Database\Query`, completion will break, as the `return self` will make the IDE think that a `\Cake\Database\Query` instance is being returned, causing the reference to `\Cake\ORM\Query` to get lost.

```php
\Cake\ORM\TableRegistry::get('Foo')->find()->order('Bar')->hydrate(false);
```

You should see `hydrate` being marked as not found here.

It's PHPStorms fault that it doesn't handle `$this` correctly in some situations, currently usually in places where multiple return types including `$this` are defined (**https://youtrack.jetbrains.com/issue/WI-32807**) It would be better give the PHPStorm peeps a slap or too, so that they start spending more time on fixing bugs before adding new functionality.

**Comment by dereuromark** [comment]
I dont agree. Lets slack.

**Comment by ndm2** [comment]
Sorry, no time to slack around, I'm sick, gotta get some more sleep... not sure what you disagreee with, but what I've described is how `self` is handled by PhpStorm, and its also the phpdoc definition: **https://www.phpdoc.org/docs/latest/guides/types.html#keywords**, so basically this change will just exchange one problem for a different one.

**Comment by dereuromark** [comment]
$this is not really a type, It is a concrete value and merely a trick phpdoc uses to distinguish between those two you described. The type still in both cases is `self`.
IMO `@return self $this` would be the most appropriate annotation in the case you mentioned.

Maybe we can revisit this in the future? Before that we have to first get rid of those mixed return types of the combined wrappers, as `$this|...` or `self|...` really is a bad thing to have in the code.

**Comment by markstory** [comment]
Does `static` work in IDEs?

**Comment by ADmad** [comment]
> self : An object of the class where this type was used, **if inherited it will still represent the class where it was originally defined.**
>
> $this : This exact object instance, **usually used to denote a fluent interface.**

I have quoted the phpdoc above for convenience. Based on @ndm2's explanation and the text I have highlighted in bold above using `$this` is the correct thing to do.

**Comment by ADmad** [comment]
I tried out the example 
```php
\Cake\ORM\TableRegistry::get('Foo')->find()->order('Bar')->hydrate(false);
``` 
provided by @ndm2 in Atom (which provide pretty nice autocompletion using the https://php-integrator.github.io package) and indeed it fails to provide autocompletion for `hydrate()` after this change. If the return type for `Cake\Database\Query::order()` method is changed back to `$this` the autocompletion starts working again.

**Comment by dereuromark** [comment]
> It's PhpStorms fault that it doesn't handle $this correctly in some situations

The root issue is that phpdoc started to introduce a specific $this type instead of doing it the right away as I mentioned above - as comment to further narrow down self to $this there.

But none the less you are then right, that we need to keep the old behavior.

We can revert once
- https://github.com/cakephp/cakephp/pull/9793
- https://github.com/cakephp/cakephp/pull/9769

have been merged and
- All mixed $this|... have been removed or deprecated and are not used anymore

Then also IDEs like PHPStorm will behave as expected for the time being.

**Comment by dereuromark** [comment]
@ndm2 Maybe you can add a better description on what the IDE needs to fix at this linked ticket? I reported 3 methods as an example that can easily reproduce it.

**Pull request merged**
