### PR TITLE
Do not fallback to insecure randomBytes, should be called explicitly

### PR DESCRIPTION
**Pull request by ceeram**
Throw exception instead of trigger_error. Exceptions can be avoided by calling `insecureRandomBytes()` instead of `randomBytes()` in applications.
This is however a BC breaking change, might not fit in a bugfix release.

### CODE REVIEW

**Comment by lorenzo** [comment]
> Exceptions can be avoided by calling insecureRandomBytes() instead of randomBytes() in applications

Well, the core uses `randomBytes` in many places. That may not be a possible for many, but I think it is the most secure option.

**Comment by ceeram** [comment]
hmm right, if core uses this, then we cannot merge it, unless we try catch everywhere and fallback to insecure, but that defeats the purpose of this PR. Guess we cannot enforce secure until php7 which has random_bytes

**Comment by markstory** [comment]
> Guess we cannot enforce secure until php7 which has random_bytes

We can because ext/openssl is still an option and there are [polyfill libraries](https://packagist.org/packages/paragonie/random_compat) that we could 'suggest' via composer.

**Comment by markstory** [comment]
Moving to 3.6 so we don't surprise people with new exceptions.

**Pull request merged**
