### PR TITLE
Making the integer marshaller accept negative numbers, fixes #7697

### LINKED ISSUE #7697: Negative Integers are interpreted as "string" in marshaller
Post data of negative integers are patched to the entity as string.

This happened after I upgraded to 3.1.4.

I found where you convert the data;

\Cake\Database\Type\IntegerType::mashal($value) {
...
}

also, I confirmed negative integers are not recognized as integers.

This seems to be the problem because all integer field of all databases accept negative integers,
and there are no reason to exclude negative integers from this function.

These days no one recommends == instead of ===, 
and using === cause errors when negative integers are set to the post data.

Is this already argued?

### PR DESCRIPTION
**Pull request by lorenzo**
Also making the marshaller more strict on the passed data, in order
to align it with the rest of the other type classes, which will return
null in case of invalid arguments.

### CODE REVIEW

**Comment by markstory** [comment]
Some [failing tests](https://travis-ci.org/cakephp/cakephp/jobs/91493247). But otherwise looks reasonable.

**Comment by dereuromark** [comment]
Wouldn't that false positive any is_numeric() passing number, as well?
Like `2.2` etc?

**Comment by lorenzo** [comment]
@dereuromark Yes, it will. It is not different to what was happening before.

**Comment by dereuromark** [comment]
Ah I see. The Type class will now just already return the marshalled data in the form it will be persisted. So it will already return 2 instead of 2.2 and save it as two anyway.
:+1:

**Pull request merged**
