### PR TITLE
Fix url generation when paging using modulus

### PR DESCRIPTION
**Pull request by edoardocavazza**
There was an error while generating the current link url in the pagination helper when using modulus. The `generateUrl` function call was not using the correct params.

### CODE REVIEW

**Comment by dereuromark** [comment]
Would you be able to provide also a failing test that would now be "fixed"?

**Comment by markstory** [comment]
Or a way to reproduce the issue the problem you're observing?

**Comment by edoardocavazza** [comment]
I am not sure how to produce the right test case. In order to raise the error, I forced the active link to show the generated url. You can see it is wrong without the fix.

In our case, an exception is raised because the `generateUrl` method failed to find a routes since passed params are wrong.  
I could not reproduce the exact case because the test router always matches on the Articles/index route and I am not confident enough to rewrite the entire test.

In any case, the problem can be experienced with the provided test. If you have suggestions for improvement, I am available to update it.

**Comment by markstory** [comment]
Thank you 🎉

**Pull request merged**
