### PR TITLE
Use 2.x branch of chronos.

### PR DESCRIPTION
**Pull request by ADmad**
Depends on cakephp/chronos#189

Adding `Cake\Chronos\DifferenceFormatterInterface` didn't help much to make static analyzers happy since `Cake\I18n\RelativeTimeFormatter` has extra methods.

### CODE REVIEW

**Comment by ADmad** [comment]
The static analysis job failure is unrelated and caused by new release of psalm. I'll fix that separately.

**Comment by ADmad** [comment]
@markstory Ping

**Comment by mirko-pagliai** [comment]
I do not open a new issue.
It seems `2.x-dev` requires PHP 7.2: https://github.com/cakephp/chronos/commit/4ce270b62879fafb5e2f0fb56cae0e2e6e8be436

**Comment by mirko-pagliai** [comment]
I apologize, I realized only now that even cakephp requires  PHP 7.2.
However, this temporarily makes the `4.0.0-alpha1` release unusable.

**Comment by ADmad** [comment]
You can use `4.x-dev` branch instead.

**Comment by markstory** [comment]
>  However, this temporarily makes the 4.0.0-alpha1 release unusable

We'll have another alpha release out soon.

**Pull request merged**
