### PR TITLE
Revert "Minor optimization for DateTimeType"

### PR DESCRIPTION
**Pull request by markstory**
This reverts commit 2d153f080c16483c8a44346b5ddfce1673263c5e. While this minor optimization should have helped improve performance, but has created subtle issues in at least one application.

Refs #9066

### CODE REVIEW

**Comment by lorenzo** [comment]
Any chance we can add a test to prove / prevent the regression?

**Comment by markstory** [comment]
I don't really understand the conditions in which this change broke userland code. I was never able to get a straight answer out of the reporter.

**Comment by lorenzo** [comment]
so we are not sure reverting this actually fixes it?

**Comment by markstory** [comment]
I was able to get the reporter to confirm that the revert resolved his issue.

**Pull request merged**
