### PR TITLE
Fix translate behavior tests.

### PR DESCRIPTION
**Pull request by ADmad**
EavStrategy of TranslateBehavior needs translated fields to be explicity specified.

Refs #13422

//cc @ndm2

### CODE REVIEW

**Comment by ADmad** [comment]
I am not sure how to fix the failing tests.

**Comment by ADmad** [comment]
"EavStrategy" is reference from 4.x as that's where I started digging the issue :)  It's the only and default implementation in 3.x.

**Comment by ndm2** [comment]
> I am not sure how to fix the failing tests.

These tests were ment for the exact situation when the translate behavior "does nothing" so to speak, in that case it shouldn't cause an association property to be created, but it's basically a misconfiguration scenario, so that might not be the best way to test the problem.

I'm not sure though that the translate behavior should even cause the associated data to be loaded/injected when fields _are_ specified, without an explicit `contain()` this seems rather unexpected. @lorenzo Any thoughts on that?

**Comment by ADmad** [comment]
> These tests were ment for the exact situation when the translate behavior "does nothing" so to speak, in that case it shouldn't cause an association property to be created, but it's basically a misconfiguration scenario, so that might not be the best way to test the problem.

Yeah having tests relying on mis-configuration of plugin makes no sense. (I am going to make EavStrategy show an exception in 4.x if `fields` are not specified).

I'm not sure though that the translate behavior should even cause the associated data to be loaded/injected when fields are specified, without an explicit contain() this seems rather unexpected. @lorenzo Any thoughts on that?

While there is no explicit contain there is an implicit once, in `beforeFind()` of the behavior:

https://github.com/cakephp/cakephp/blob/bb06ced5d450c00d484039a6b22a4bb026cb17f3/src/ORM/Behavior/TranslateBehavior.php#L261

**Comment by ndm2** [comment]
> While there is no explicit contain in your tests there is an implicit once, in `beforeFind()` of the behavior

I know, but that's a "sub-containment" for the translation table, and since it's applied to the `Comments` association query, it shouldn't cause association data to be placed in the results when the `Comments` association is not explicitly contained. The `Comments` association is implicitly contained by `matching()`, but that shouldn't cause any association data in the results except for in `_matchingData`.

At some point the containment from the behaviors `beforeFind()` results in an additional, non-joinable, non-matching `Comments` containment to slip in for the main query, causing the association map in `ResultSet::_calculateAssociationMap()` to look like this:

```php
[
	(int) 0 => [
		'alias' => 'Comments',
		'instance' => object(Cake\ORM\Association\HasMany) {
			// ...
		},
		'canBeJoined' => true,
		'entityClass' => 'Cake\ORM\Entity',
		'nestKey' => 'Comments',
		'matching' => true,
		'targetProperty' => 'comments'
	],
	(int) 1 => [
		'alias' => 'Comments',
		'instance' => object(Cake\ORM\Association\HasMany) {
			// ...
		},
		'canBeJoined' => false,
		'entityClass' => 'Cake\ORM\Entity',
		'nestKey' => 'Comments',
		'matching' => false,
		'targetProperty' => 'comments'
	]
]
```

I can't tell whether that might be a bug, but IMHO it's at least undesirable, it doesn't affect the main queries SQL, and it wasn't explicitly requested.

**Comment by ADmad** [comment]
For find call in `testMatchingDoesNotCreateAssociationProperty()` due to the `contain()` in `beforeFind()` you eventually end up with nested/deep contain

```php
        'contain' => [
                'Comments' => [
                        'Comments_comment_translation' => [
                                'queryBuilder' => object(Closure) {

                                }
                        ]
                ]
        ],
```
for the query. (debug the query before calling `first()` and you will see).

And that's why we end up with `comments` property for the article entity.

So from what I understand the issue cannot be resolved without replacing use of `contain()` with explicit joins and field selection as I suggested above.

On a side note I personally avoid using `matching()` at all. It's too magical for my liking.

**Comment by ndm2** [comment]
> due to the `contain()` in `beforeFind()` you eventually end up with nested/deep contain

I know, I'm just not sure that this is really the correct behavior. From what I could figure so far, this happens in `Association::_bindNewAssociations()`, there it will grab the containment that the behavior added to the association query, and applies it on the main query.

I don't fully understand the original purpose of `Association::_bindNewAssociations()` yet, but the association for which that happens here is a matching-containment, so I'm wondering whether that could maybe be avoided without breaking things (the current tests don't break when bailing out for matching containments, but that doesn't mean too much of course, it could very well be an untested scenario).

**Comment by ndm2** [comment]
OK after some more digging it seems this is generally used for chaining nested matching and containments that are being defined in callbacks with query builders, and there's actually two tests that fail when also disabling the matching inheritance.

I guess my question boils down to whether this

```php
$mainQuery->matching('Foo', function ($query) {
    return $query->contain('Bar');
});
```

and this:

```php
$mainQuery->innerJoinWith('Foo', function ($query) {
    return $query->contain('Bar');
});
```

is valid, ie whether this nested `contain()` should affect the main queries contain graph. If it should, then I guess just ditch the two tests, and if it shouldn't, then maybe it can be fixed, and then the tests should remain.

Sorry for all the noise :)

**Comment by markstory** [comment]
I would think both those scenarios *should* impact the contain graph or should emit an exception indicating that the developer has asked for something we cannot complete.

**Comment by ADmad** [comment]
I removed the 2 tests which are not expected to pass.

**Pull request merged**
