### PR TITLE
Bugfix about unused param in Query::update()

### PR DESCRIPTION
**Pull request by StewEucen**
I modified src/ORM/Query::update() for bugfix.

reference issue
https://github.com/cakephp/cakephp/issues/6458

### CODE REVIEW

**Comment by lorenzo** [comment]
Thanks!

**Comment by ADmad** [comment]
No tests?

**Comment by lorenzo** [comment]
@ADmad I'm working on them as we speak

**Comment by ADmad** [comment]
Cool, thanks.

**Comment by StewEucen** [comment]
For all.

Thanks for your work about this issue.
I am glad to be a part of this great project.

**Pull request merged**
