### PR TITLE
Make beforeMarhal $options an ArrayObject.

### PR DESCRIPTION
**Pull request by markstory**
Use consistent types across the various event methods.

Refs #5711

### CODE REVIEW

**Comment by antograssiot** [comment]
CS fail but it's not related to the PR.
It seems to be linked to squizlabs/PHP_CodeSniffer release 2.2.0
Mostly due to 
```php
if (
   cond 1
   || cond2
)
```
I'll try to take a look at it later in the day if no one does it before

**Comment by ADmad** [comment]
@antograssiot More PSR2 fun :stuck_out_tongue:

**Comment by robertpustulka** [comment]
So if $options can be modified during the beforeMarshal event loop, shouldn't it be returned back to marshaller?

**Comment by markstory** [comment]
@robertpustulka Ok but the beforeMarshal event is well after the options/associations have been determined and built.

**Comment by robertpustulka** [comment]
@markstory So maybe dispatch this event first?

```php
$options += ['validate' => true];
list($data, $options) = $this->_prepareData($data, $options);
$propertyMap = $this->_buildPropertyMap($options);
...
```

**Comment by dereuromark** [comment]
Merging to avoid confusion - as the docs already reflect the new behavior.

**Pull request merged**
