### PR TITLE
Ignore debug.log and error.log

### PR DESCRIPTION
**Pull request by cleptric**
It's always tempting to commit `debug.log` and `error.log` when doing a PR.
@dereuromark Can you add the `plugin` thing?

### CODE REVIEW

**Comment by ADmad** [comment]
Would be nice if we could find the offending test which creates these log files on root.

**Comment by cleptric** [comment]
`ConsoleErrorHandlerTest::testHandleFatalError` adds the `error.log`

**Comment by cleptric** [comment]
`ConsoleErrorHandlerTest::testHandleError` add the `debug.log` in the first place, but a some other test write to this file as well.
`Debug: command 'sample' in plugin 'TestPlugin' was not aliased, conflicts with another shell` and some stuff from `DebuggerTest`

**Review by dereuromark — APPROVED** [review]
I think it is fair enough to add those two lines.

**Pull request merged**
