### PR TITLE
2.x Console: Display error message when unknown option is specified

### PR DESCRIPTION
**Pull request by tenkoma**
Implementation of #10914

Display error as follows:

error-message

### CODE REVIEW

**Comment by Oxicode** [comment]
+1

**Comment by markstory** [comment]
Any tests that could be updated for this?

**Comment by tenkoma** [comment]
@markstory Added test.

**Review by ravage84 — APPROVED** [review]
Just came accross this yesterday, again.

**Review by dereuromark — APPROVED** [review]

**Pull request merged**
