### PR TITLE
return value for __invoke was wrong

### PR DESCRIPTION
**Pull request by eather009**
Corrected  __invoke return value.

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

Always follow the [contribution guidelines](https://github.com/cakephp/cakephp/blob/master/.github/CONTRIBUTING.md) when submitting a pull request. In particular, make sure existing tests still pass, and add tests for all new behavior. When fixing a bug, you may want to add a test to verify the fix.

### CODE REVIEW

**Comment by dereuromark** [comment]
I wonder how this was passing tests and stuff?

**Comment by eather009** [comment]
It should give Fatal error instead.

**Comment by ADmad** [comment]
Maybe this class isn't actually used in tests? If so we can remove it.

**Comment by markstory** [comment]
Merging as this is more correct than before. Removing the class entirely can be done as a separate change.

**Pull request merged**
