### PR TITLE
Properly require laminas components

### PR DESCRIPTION
**Pull request by remicollet**
Missing in 0defa45cbfa6cf222998d05a8dec40a7d936bdaf

### CODE REVIEW

**Comment by dereuromark** [comment]
Why closing?

**Comment by saeideng** [comment]
`4.x` branch is stale , and will remove 
open new PR on `master`

>Why closing?

I was writing the reason :)

**Comment by dereuromark** [comment]
You could have just changed target to master maybe :)

**Comment by saeideng** [comment]
maybe :)

thanks @remicollet

**Pull request closed without merging**
