### PR TITLE
Fix failing tests related to year rollover.

### PR DESCRIPTION
**Pull request by markstory**
I flubbed a few tests and they started to fail once GMT got ahead of my timezone. This also fixes some invalid values cases that aren't actually invalid, namely `null` and `-1`.

### CODE REVIEW

**Comment by ADmad** [comment]
Builds failing

**Comment by markstory** [comment]
I will get those fixed. :cry:

**Comment by markstory** [comment]
Tests should be fixed now.

**Comment by lorenzo** [comment]
coolio

**Pull request merged**
