### PR TITLE
Fix dynamic property creation warnings on PHP 8.2.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
@othercorey This should sort out all the dynamic property creation warnings.

**Comment by ADmad** [comment]
Running the 8.2 test with mysql to ensure some tests aren't missed.

**Comment by ADmad** [comment]
Found an unrelated error :)

```
1) Cake\Test\TestCase\Database\QueryTest::testSQLFunctions
TypeError: ltrim(): Argument #1 ($string) must be of type string, int given

/home/runner/work/cakephp/cakephp/tests/TestCase/Database/QueryTest.php:3523
```

**Comment by ADmad** [comment]
Above failure can be addressed in a separate PR. Using `assertSame()` instead of `assertEquals()` for the last assertion in `QueryTest::testSQLFunctions()` causes type related errors on PHP 8.1 too.

**Comment by othercorey** [comment]
Looks good.

**Pull request merged**
