### PR TITLE
Add .scrutinizer.yml

### PR DESCRIPTION
**Pull request by ADmad**
Let's see what potential mess we have :)

Will probably require enabling the scrutinizer webhook and/or enabling the repo on scrutinizer-ci.com

### CODE REVIEW

**Comment by ravage84** [comment]
We're not using it yet? I'm surprised. :+1:

**Comment by ADmad** [comment]
@ravage84 We didn't need to earlier since we had jenkins to those static analysis for us. But recently we stopped using jenkins, one less thing of maintain for us.

**Comment by ravage84** [comment]
@ADmad :cool: 

We could make use of CakePHP's Codesniffer standard, too:

````
checks:
    php:
        custom_coding_standard:
            ruleset_path: 'vendor/cakephp/cakephp-codesniffer/CakePHP.ruleset.xml'
````

https://scrutinizer-ci.com/docs/tools/php/code-sniffer/

**Comment by ADmad** [comment]
Or just disable that check since we already have a travis build for phpcs.

**Comment by ADmad** [comment]
Of course in general the config might require some tweaking, but first let's get it started.

**Comment by markstory** [comment]
Sure, lets see what comes out the other side.

**Comment by markstory** [comment]
I set up hooks in scrutinizer-ci.com, with all the default settings.

**Pull request merged**
