### PR TITLE
#6935 Fix deep saving for hasMany could not handle validation errors correctly

### PR DESCRIPTION
**Pull request by hiromi2424**
refs #6935

### CODE REVIEW

**Comment by hiromi2424** [comment]
Weird CI errors..

**Comment by hiromi2424** [comment]
travis log shows it was rarely time-specific error.
What is the error of appveyor?

**Comment by antograssiot** [comment]
@hiromi2424 don't worry about appveyor,  it's not configured for 2.x

**Comment by hiromi2424** [comment]
@antograssiot OK thanks.

**Comment by markstory** [comment]
Nice work @hiromi2424 :+1:

**Pull request merged**
