### PR TITLE
Camelize route prefix when trying to load controller.

### LINKED ISSUE #8134: Lowercased prefixes instead of camelized
In 3.1.9 this commit, 351faea8640a72351bbc1bfc6f7757f422431a34, made it to the release. This currently breaks this [3.x project (Croogo)](https://github.com/croogo/croogo/tree/3.0) because all prefixes are camelized in the folder structure and the namespaces. When chancing a camelized prefix folder and namespace to lowercase, it works flawless. On the error page (thrown by the `MissingControllerException`) also shows camelized prefix folders and namespaces, so I don't think it should be lowercased.

When reverting the code in `ControllerFactoryFilter` it works flawless with camelized prefixes.

We're using the `DashedRoute`.

### PR DESCRIPTION
**Pull request by ADmad**
Fixes #8134

### CODE REVIEW

**Comment by jadb** [comment]
But then, is it still necessary to do it also at the router level https://github.com/cakephp/cakephp/commit/351faea8640a72351bbc1bfc6f7757f422431a34#diff-d42640da5778c9518653f2c9c9900571R53?

**Comment by ADmad** [comment]
@jadb Yes it is, that one is for `plugin` key not `prefix`.

**Comment by dereuromark** [comment]
Looks good.

**Comment by Wouter0100** [comment]
Awesome, looks great :+1:

**Comment by ADmad** [comment]
I wonder if we need to account for `/` in prefix. Do we supported nested prefixes? Can't say since there were no tests for it.

**Comment by jadb** [comment]
Unless I am mistaking (which I very well could be), looking at old code, it did not support nested prefixes (I never used it so can't confirm).

**Comment by dereuromark** [comment]
Nice work. Now it works again in 3.2. Should be backported to 3.1, though.

**Comment by ADmad** [comment]
@jadb Old code did.

**Comment by ADmad** [comment]
Or to be precise old code did account for "/" in prefix. No idea if it actually translates to supported nested prefixes.

**Comment by ADmad** [comment]
@dereuromark Yeah backporting to 3.1 would be nice. It's a non-trival issue and given the PHP version bump everyone might not be able to upgrade to 3.2 immediately.

**Comment by markstory** [comment]
> Do we supported nested prefixes? Can't say since there were no tests for it.

We do support nested prefixes. There should be tests in the Router test case.

**Pull request merged**
