### PR TITLE
Enable App::build added paths for plugins

### PR DESCRIPTION
**Pull request by letstalk-nl**
Original pull request: https://github.com/cakephp/cakephp/pull/5657
Reopened pull request to correct branch, will add a test soon

### CODE REVIEW

**Comment by dereuromark** [comment]
Can you add a test case for this? Or at least an example on what this resolves please?

**Comment by letstalk-nl** [comment]
Example: We have a plugin that has a bunch of e-commerce models that are shared throughout several CakePHP projects. Inside this plugin we wish to separate the Product models from the Customer information models thus we have a couple of subdirectories inside the plugin's Model directory splitting the models up by type. 

I can try and make a test case for this but I'd probably be busy with this for a while since I'm not very experienced with either php unit nor the CakePHP test suite. Perhaps this example can help someone who can do this in 5 minutes.

**Comment by dereuromark** [comment]
Can you maybe give a code example of what you do? And how it works? I still didn't quite get it.
Maybe we can then add a quick test for it.

**Comment by letstalk-nl** [comment]
So I have models that reside in:
/Plugin/WAXEngine/Model/Order/
Models like OrderRow.php, Customer.php

I wish to use these models, and normally if you would create /Model/Order/* you would be able to add this path using App::build. However when I do this and then do an App::uses the added paths are ignored (try and debug $path before and after the if statement included in my commit).

So for my above example I can now do App::build('Model', '/my/root/Plugin/WAXEngine/Model/Order');
and App::uses('OrderRow', 'WAXEngine.Model');  will use /my/root/Plugin/WAXEngine/Model/Order/OrderRow.php

Hope that clears it up! :)

**Pull request closed without merging**
