### PR TITLE
Don't emit errors when clauses are undefined.

### PR DESCRIPTION
**Pull request by markstory**
Refs #10734

### CODE REVIEW

**Review by lorenzo — COMMENTED** [review]
Shouldn't it be an error though?

**Comment by markstory** [comment]
@lorenzo The issue reporter thought it shouldn't be an error. If we're going to have an error it shouldn't be an `E_NOTICE`. I'm ok with raising a `RuntimeException` though.

**Comment by lorenzo** [comment]
I agree it should not be a `E_NOTICE`. Looking again at the original error report, it would have been even more difficult for him to realise that `matching` is not a query clause, had we returned null instead of reporting the error.

Converting this to an exception sounds like a better idea.

**Comment by markstory** [comment]
@lorenzo I added an error with what I think is a good error message.

**Comment by markstory** [comment]
@lorenzo I added an error with what I think is a good error message.

**Comment by lorenzo** [comment]
Looks great!

**Pull request merged**
