### PR TITLE
added cache to reverse route

### LINKED ISSUE #17113: Reverse routes are extremely slow on large sites
### Description

I've got a site with more than 15.000 routes.
Everytime we call a reverse-router (for example to get the translated url of that page), we wait up to 8 seconds.

We have created a little improvement in the function

Router::reverse()
in file /src/Routing/Router.php

```php
    public static function reverse($params, $full = false): string
    {
        // massimoi: add a fast cache here
        $h = md5(serialize($params));
        $cparams = Cache::read("rev-route-$h");
        
        if ($cparams === null) {
            $params = static::reverseToArray($params);
            Cache::write("rev-route-$h", $params);
        } else {
            $params = $cparams;
        }
        return static::url($params, $full);
    }
```

### CakePHP Version

4.x

### PHP Version

7.4

### PR DESCRIPTION
**Pull request by impronta48**
Please see issue #17113
We need a cache in reverse routing in order to get a reasonable time on a large site

### CODE REVIEW

**Comment by markstory** [comment]
These changes are failing CI, and could cause application code to fail as well

I have concerns that this can lead to remote resource exhaustion as URLs often contain arbitrary user input. User input would lead to unbounded keyspace which could consume all storage in the cache.

Your application and use case seem pretty specific, couldn't this caching logic be added as an application wrapper?

**Comment by impronta48** [comment]
Thanks @markstory,
the only error I get in the CI is 
Cake\Cache\InvalidArgumentException: The "default" cache configuration does not exist.
what is a good practice to indicate the Cache configuration in cakephp core?

Second question: this modification is necessary in order to reduce the page load from 8 secs -> 0.5 sec in my site (large number of url). How could I override reverse route without touching the core?

Thanks
Massimo

**Comment by ADmad** [comment]
> How could I override reverse route without touching the core?

Just make your own function/method which has the code you modified for `Router::reverse()`. Only change would be to call `Router::url()` instead of `static::url()`.

**Comment by ADmad** [comment]
Closing as this is an uncommon issue and caching can be easily added at app level if required.

**Pull request closed without merging**
