### PR TITLE
Update HasMany to avoid ambigous columns

### PR DESCRIPTION
**Pull request by greew**
This is a new PR based on #8391.

It's newly created because it's created in a new branch without all the previous crap.

I've changed the conditions from a basic array to a QueryExpression,
which I aftewards traverse to add alias to all fields.

### CODE REVIEW

**Comment by dereuromark** [comment]
You can also just squash your commits, no need to make a new PR.

**Comment by greew** [comment]
@dereuromark Cool.. will do the next time :)

**Comment by greew** [comment]
Ok, when Travis fails because of 

    [Composer\Downloader\TransportException]   
    Could not authenticate against github.com  

What to do?

**Comment by dereuromark** [comment]
Rate limit if github, no big deal.

**Comment by greew** [comment]
Ok, I'm just curious if I can restart it myself or if one of you guys have to?

**Comment by lorenzo** [comment]
Thanks again!!

**Pull request merged**
