### PR TITLE
Re-add the Equifax Secure Certificate Authority

### PR DESCRIPTION
**Pull request by ravage84**
Port change https://github.com/cakephp/cakephp/pull/8636/commits/343e206360908969904c48aef63b5a856d4405ef from 3.x to 2.x

### CODE REVIEW

**Comment by markstory** [comment]
Tests are still failing. I'm guessing we use a different domain for testing sockets in 2.x I'll find an update it.

**Comment by markstory** [comment]
The failing test is caused by another removed root CA. This time its GTE CyberTrust Solutions, Inc. I'm considering changing that test as relying on some random website to have poorly configured SSL leads to a pretty fragile test case.

**Comment by ravage84** [comment]
Problems like these are why it makes sense to put the file into a centralized repo, as we have now with https://github.com/composer/ca-bundle :wine_glass: 

With this, a lot more people can help out finding problems early :smirk_cat: 

To bad, we cannot make use of it for 2.x...

**Comment by markstory** [comment]
Yea :(

**Pull request merged**
