### PR TITLE
Add Search expression: "LIKE %...%"

### PR DESCRIPTION
**Pull request by half2me**
This is an expression like the "LIKE" expression, except it uses "LIKE %...%" wildcards to do the search. This is a common way of searching, so I figured an expression would be useful. This is useful especially on integer types where using `$query->where(['integerField LIKE' => '%' . $value . '%'])` doesn't work. (The %-s are being parsed in as the input data, where instead they should be used completely separately.

### CODE REVIEW

**Comment by lorenzo** [comment]
Thanks but the pull request, but did you check the tests for like() ? Specifically this one:

https://github.com/cakephp/cakephp/blob/master/tests/TestCase/Database/QueryTest.php#L572

**Comment by half2me** [comment]
@lorenzo That test is working on a string column, this works fine. But try the same on an integer column ;)

**Comment by markstory** [comment]
Why are you doing `LIKE %:val%` on integer columns?  I'm pretty sure you could do like on integer columns if you gave the right type hints to the ORM.

**Comment by half2me** [comment]
@markstory could you show me an example?

**Comment by lorenzo** [comment]
this is an example:

```php
$query->where(['number like' => '%text%'], ['number' => 'string']);
```

A possible improvement we could make is to always bind a the like function to the string type

**Comment by half2me** [comment]
@lorenzo But this way it binds to a string. It would be nice to bind to an integer, if its an integer we are dealing with, and leave the % out of the parsed value. This way %num% we could make sure that "num" is actually a number.

**Comment by markstory** [comment]
Any chance this could be updated so the tests pass again?

**Comment by dereuromark** [comment]
> Why are you doing LIKE %:val% on integer columns?

The issue actually now came up in the search plugin, where id is just one of a few fields to look into via LIKE. So maybe we can get this back on track here?

**Comment by half2me** [comment]
@dereuromark I totally agree, but I don't think I will have time to finish this PR, I have exams coming up :/

**Comment by dereuromark** [comment]
@half2me Are you still interested in finishing this up?

**Comment by half2me** [comment]
@markstory unfortunately I don't have enough time to finish this :(

**Comment by dereuromark** [comment]
For reference for anyone who has the resources to look into this more, this is the solution I found for search plugin: https://github.com/FriendsOfCake/search/pull/152

**Comment by dereuromark** [comment]
Given that

    ['number' => 'string']

as col type overwrite - as linked from the PR of search plugin - could solve the issue, should we close this then as works-for-me?

**Comment by half2me** [comment]
@dereuromark sounds good to me

**Pull request closed without merging**
