### PR TITLE
solves issue #8197: Inflector::slug() to preserve space between non-ascii characters

### PR DESCRIPTION
**Pull request by mekhtiari**
First of all replacing spaces with $replacement parameter and then other symbols.

### CODE REVIEW

**Comment by ADmad** [comment]
Not sure what this changes without seeing a testcase but slugs aren't meant to contain spaces.

**Comment by AD7six** [comment]
This is the wrong place to solve https://github.com/cakephp/cakephp/issues/8197

**Comment by markstory** [comment]
Closing as there isn't any view caching in 3.x (which is what the master branch is for). If you need to fix an issue in 2.x use the `2.x` branch.

**Comment by AD7six** [comment]
@mohsen-ekhtiari can you please provide a test case for this change; the reason for the change is invalid but potentially the change itself is desirable.

Is the goal to change this:

    α β -> αβ

to this:

    α β -> α-β

?

**Comment by mohsen-ekhtiari** [comment]
I think I was wrong to target space character. In targeting url, I should consider plus sign (+) instead of space character. In fact, I meant to make difference between αβ and α+β.

**Comment by mohsen-ekhtiari** [comment]
@AD7six: Although not related to the issue, but I think this change (to branch 2.x ?) is desirable. At least It makes difference between "%CE%B1 %CE%B2" and "%CE%B1%CE%B2", with the following test case:

    $result1 = Inflector::slug("%CE%B1 %CE%B2");
    $result2 = Inflector::slug("%CE%B1%CE%B2");
    $this->assertNotEqual($result1, $result2);

**Comment by AD7six** [comment]
@mohsen-ekhtiari I don't know what that test is supposed to mean, asserting that a result is not the same as another result doesn't demonstrate what you _do_ expect either to be.

This result does not match the expected behavior of that function:

    CE-B1--CE-B2
          ^

Now that I think I understand what you're expecting, I do not think that's desirable - as you expect 2 replacements one after another - and the function is designed not to do that.

**Comment by mohsen-ekhtiari** [comment]
@AD7six By using assertNotEqual() I meant no matter of the proposed way to preserve word boundaries, there should be a difference between the results of having or not having spaces between characters.
I don't think two underscores `CE_B1__CE_B2` is unexpected. At least it is better than mapping both strings to the same slug.

@markstory I think if we don't consider View Caching, changing Inflector::slug() to preserve word boundaries between non-ascii characters could be applied to master branch. Although my pull request needs some modifications and tests.

**Pull request closed without merging**
