### PR TITLE
Removed useless if statement

### PR DESCRIPTION
**Pull request by TeckniX**
Refer to:
https://gist.github.com/TeckniX/27e90cab5206cfb95ecc

### CODE REVIEW

**Comment by markstory** [comment]
CI builds disagree with you.

**Comment by TeckniX** [comment]
The test do look for the double-output of the HTML tag, which I don't believe is correct. 
I can cleanup the tests to make them pass if my initial statement that only 1 html meta icon tag should be output. 
If both the  'icon' and 'shortcut icon' html meta tags should be there, then I'll delete this pull. 

Just let me know. (mea culpa on always forgetting to unit test my code ) :[

**Comment by markstory** [comment]
Both should be output as old IE needs both from what I remember.

**Comment by ravage84** [comment]
@markstory if tha's the case, we should add a comment to the doc block.
So we don't need to re-discuss this in the future. :smirk_cat:

**Comment by markstory** [comment]
@ravage84 I can take care of that.

**Comment by TeckniX** [comment]
That was a lot of discussion for nothing - Sorry chaps, and thanks to all for chiming in. I'll delete this patch so we can all forget it ever existed :+1:

**Pull request closed without merging**
