### PR TITLE
Load Request/Response aliases

### PR DESCRIPTION
**Pull request by markstory**
Ensure that if an application never references the old aliases that they are still setup. Without this applications with typehints against the old aliases can sometimes fail depending on file load order.

### CODE REVIEW

**Comment by ADmad** [comment]
The testsuite throws "Cannot redeclare class.." error :unamused:

**Comment by ADmad** [comment]
Just need to make phpcs happy now.

**Comment by dereuromark** [comment]
> A file should declare new symbols (classes, functions,
   |         | constants, etc.) and cause no other side effects, or
   |         | it should execute logic with side effects, but should
   |         | not do both. The first symbol is defined on line 37
   |         | and the first side effect is on line 2134.

Can we silence those for class_alias() things maybe?

**Comment by ADmad** [comment]
I updated `phpcs.xml.dist` to ignore the `PSR1.Files.SideEffects` sniff for these 2 files. Using the coding standards inline annotations doesn't work this is sniff as it's a per file sniff.

**Comment by markstory** [comment]
@ADmad PHPCS seemed sad even after your changes. I moved the compat aliases into a composer autoload shim file instead.

**Comment by ADmad** [comment]
> PHPCS seemed sad even after your changes.

That's cause the command in travis.yml is using the ruleset from codesniffer folder instead of phpcs.xml.dist

**Comment by ADmad** [comment]
Doesn't composer.json have to be updated to load the `backwards_compat.php` you added?

**Pull request merged**
