### PR TITLE
RFC-822 of mail address validation

### PR DESCRIPTION
**Pull request by hekep**
Just to follow RFC.

http://www.ex-parrot.com/~pdw/Mail-RFC822-Address.html
http://stackoverflow.com/questions/20771794/mailrfc822address-regex

### CODE REVIEW

**Comment by inoas** [comment]
1. Did you actually read http://stackoverflow.com/questions/20771794/mailrfc822address-regex ?
Especially http://stackoverflow.com/a/20773069
2. I'd not remove the existing validation regexp
3. I'd be careful about adding a new one. Maybe as a stand alone rule like emailRfc822()

**Comment by markstory** [comment]
What does this solve? What email addresses didn't validate before but do now? We've also made a conscious decision to not allow all RFC-822 addresses as that standard allows a number of addresses that are not 'deliverable' by standard SMTP servers.

**Comment by hekep** [comment]
Well current Validation::email('äction@äction.com')  lets  scandics suchs as ä ö å go  as valid.

I was hoping RFC822 to fix this. May be wrong hopes.

**Comment by chinpei215** [comment]
This change would introduce another problems. RFC 6530 does support internationalized email addresses, and Gmail seems to follow it.

https://googleblog.blogspot.jp/2014/08/a-first-step-toward-more-global-email.html

If you were using CakePHP3, you could use the [ascii](https://github.com/cakephp/cakephp/blob/86e6a8071c7cac63e270aef5d7b9623551f84b96/src/Validation/Validation.php#L1241-L1248) validation together to solve your issue. I would suggest you to backport it instead.

**Comment by ADmad** [comment]
The regex used by email validator intentionally doesn't match RFC822 in order to cater to more "real world" usage. Since you can pass the regex as an argument please do so as per your needs or make your own method with modified regex.

Closing as changing the default regex would cause regression.

**Review by hekep — COMMENTED** [review]
Another attempt

**Comment by hekep** [comment]
Ok, thank you very much.

**Pull request closed without merging**
