### PR TITLE
Unset element in EntityTrait::$_original in EntityTrait::unsetProperty()

### PR DESCRIPTION
**Pull request by andrii-pukhalevych**
Unset element in EntityTrait::$_original along with elements in EntityTrait::$_properties and EntityTrait::$_dirty in EntityTrait::unsetProperty()

### CODE REVIEW

**Comment by ADmad** [comment]
Why? If a property currently has a value and you unset it then it should remain marked as dirty.

**Comment by ADmad** [comment]
Sorry, I see the dirty flag is already removed, I guess in that case the original value should be removed too.

**Comment by andrii-pukhalevych** [comment]
Is there is a way to fix/restart `continuous-integration/appveyor/pr` tests?
It was not started:
`Command "cinst --no-progress --params ""/InstallDir:C:\php"" --ignore-checksums -y php --version" failed with exit code 1. `

**Comment by garas** [comment]
AppVeyor was fixed in `master`, but not yet merged to `3.next`

**Comment by dereuromark** [comment]
You can ignore AppVeyor
But we might want to add a test for this part.

**Comment by markstory** [comment]
Won't this remove the ability to see what a property's value was before it was unset? Unset properties won't change the persisted entity (as the dirty flag is removed) but I could see wanting to know what the previous state was.

**Comment by andrii-pukhalevych** [comment]
@markstory Unsetting property is not equal to set it to `null`. For this method unsetting property without cleanup of original value looks like uncollected garbage.

**Review by dereuromark — DISMISSED** [review]
I find it interesting that
https://book.cakephp.org/3.0/en/orm/entities.html
doesnt even mention this method yet.

**Comment by andrii-pukhalevych** [comment]
@dereuromark Its also used in `EntityTrait::__unset()` implicitly to users

**Comment by dereuromark** [comment]
Well, it would be used by magic invocation of the usage of `unset($entity->prop)` then.

That said:
We have indeed 11 usage of this inside the core code - some of those might actually be intended to only set it to null instead of unsetting.
We have to check this IMO.

One is for example in BaseAuthenticate
```
$result->unsetProperty($passwordField);
```

**Comment by markstory** [comment]
> For this method unsetting property without cleanup of original value looks like uncollected garbage.

Fair enough, but what problems does the current behavior cause? Changing methods in EntityTrait can have far reaching and hard to detect impact, so unless there is a problem being caused by the current behavior, I'm hesitant to change it.

**Comment by ADmad** [comment]
How about we make this change in 4.x and keep 3.x as is?

**Comment by dereuromark** [comment]
@andrii-pukhalevych Did you open a PR against 4.x?

**Comment by andrii-pukhalevych** [comment]
Created [PR for 4.x](https://github.com/cakephp/cakephp/pull/13621) instead

**Pull request closed without merging**
