### PR TITLE
Fix err() to highlight error as red similar to warn() which is yellow.

### PR DESCRIPTION
**Pull request by dereuromark**
Consistency to
- warn(): yellow
- success(): green

Now:
- err(): red (instead of looking like out())

Also returning the byte count as the others do.

### CODE REVIEW

**Comment by markstory** [comment]
You've made all the [builds sad](https://travis-ci.org/cakephp/cakephp/builds/129677603). Other than that it seems like a reasonable idea.

**Comment by dereuromark** [comment]
Yeah will take care of it tomorrow :)

**Comment by dereuromark** [comment]
Failures seem DB related - so unrelated here.

**Comment by markstory** [comment]
Looks good. I'm going to try and look into those test failures. I think its more MySQL sillyness.

**Pull request merged**
