### PR TITLE
Added support for mediumtext and longtext

### PR DESCRIPTION
**Pull request by wouter-corpoflow**
Added support for mediumtext and longtext. Before this change all mediumtext and longtext columns were changed to text.

### CODE REVIEW

**Comment by wouter-corpoflow** [comment]
@dereuromark shouldn't this be added to milestone for 2.10.21 since 2.10.20 is the current release?

**Comment by othercorey** [comment]
I think this will need tests added before it is considered.

**Comment by othercorey** [comment]
@wouter-corpoflow do you plan to follow up? If not, we will close this as 2.x isn't receiving any new features.

**Comment by wouter-corpoflow** [comment]
I would love to add some tests and fix some more issues, for example char isn't recognised either, but I currently don't have time for this :(

**Comment by othercorey** [comment]
Feel free to start a discussion again when ready, but remember 2.x isn't going to release a new minor version so only bug fixes are allowed.

**Pull request closed without merging**
