### PR TITLE
Fix missing stack frame in error pages

### LINKED ISSUE #13869: Exception call stack shows frame with the parent frame's source
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 4.x-dev

### What you did
Throw class not found exception

### What happened
The stack frames are linking the function being called with the current source file instead of the function currently executing.

stack

### PR DESCRIPTION
**Pull request by markstory**
Exceptions in PHP don't include the frame that the error originated from in the result of Exception::getTrace(). To workaround that we need to use the exception's file & line attributes as an additional frame.

Fixes #13869

### CODE REVIEW

**Comment by dereuromark** [comment]
Is this specific to 4.x or do we also need this in master?

**Comment by markstory** [comment]
@dereuromark It should be backported to 3.x as well.

**Comment by dereuromark** [comment]
Ah ok
I thought we made bugfixes to master first, and new features to 4.x (to backport).
But if that also works, sure.

**Comment by othercorey** [comment]
Looks ok to me.  Unit tests are saying it shouldn't run though!

**Pull request merged**
