### PR TITLE
Add assertArrayContentEquals

### PR DESCRIPTION
**Pull request by half2me**
I need to compare associative arrays a lot, and using assertEquals() will take the ordering of the array into account. Would it be useful to have something like this? It checks the equality of the contents of the arrays without taking their order into account. If there is a need for this, I could enhance it to work with === as well.

### CODE REVIEW

**Comment by lorenzo** [comment]
`[1, 2, 3] == [3, 2, 1]` will return false Is that expected in your case?

**Comment by half2me** [comment]
@lorenzo well it should return true for this function. I know == is not going to cut it. I'll probably go through it with a recursive foreach loop. Do you think this is a needed/useful function?

**Comment by lorenzo** [comment]
Can you explain our use case?

**Comment by half2me** [comment]
@lorenzo well what I would use it for, is when doing unit testing of APIs, it can be used to check the result where the ordering doesn't really matter. Or when testing resultsets. I can say: $this->assertArrayContentEquals(['field' => 'value', 'otherfield' => 'othervalue'], $resultSet);

**Comment by half2me** [comment]
I was thinking of implementing something along the lines of this:
https://stackoverflow.com/questions/5678959/php-check-if-two-arrays-are-equal

**Comment by lorenzo** [comment]
assertEquals() does not care about the ordering of key => value arrays. Only that all keys match with the values and that there are the same amount of keys in both

**Comment by half2me** [comment]
@lorenzo If that's the case, then why do I get this?
```php
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
         {
-            "DT_RowId": "222222-001|6.5",
             "size": "6.5",
             "amount": 4,
+            "DT_RowId": "222222-001|6.5",
```
Just by changing the order in my $expected array:
```php
$expected = [
            'data' => [
                [
                    'DT_RowId' => '111111-001|11',
                    'size' => '11',
                    'amount' => 1,
                    ...

$this->assertEquals($expected, $this->_response->body());
```

But using this, runs just fine:
```php
'data' => [
                [
                    'size' => '11',
                    'amount' => 1,
                    'DT_RowId' => '111111-001|11',
                    ...

$this->assertEquals($expected, $this->_response->body());
```

**Comment by markstory** [comment]
Do you ever need to only test a subset of the array contents? Or are you always testing ensuring all the keys/values in the array?

**Comment by half2me** [comment]
@markstory there are times when an array subset test is enough for me, but the assertArrayContentEquals() should make sure there is no extra data in the array. My problem with ArraySubset as far as I recall, is the order of keys are not ignored.

**Comment by half2me** [comment]
@lorenzo the reason why assertEquals fails to see these two arrays as equal is probably due to the fact that I converted them to json, and I am comparing the two strings. That is what was suggested in the documentation of CakePHP. I'll try instead to json_decode from the reply of the API, and compare that with the expected array.

**Comment by markstory** [comment]
Comparing JSON strings will totally make array comparisons order sensitive. I don't think this proposed method will solve that either though.

**Comment by half2me** [comment]
@markstory True.

**Pull request closed without merging**
