### PR TITLE
Another set of phpstan reported errors

### PR DESCRIPTION
**Pull request by antograssiot**

### CODE REVIEW

**Comment by ADmad** [comment]
How did you find there errors?  They aren't reported at phpstan level 1.

**Comment by antograssiot** [comment]
I add a look to high level locally @ADmad and picked some that were not false positive

**Comment by ADmad** [comment]
Are there too many errors reported at level 2?  If not we could fix them all and bump the level in travis config :)

**Comment by antograssiot** [comment]
level 2 reports 121 errors 😞 
level 4 reports 243 errors

**Comment by lorenzo** [comment]
Good job!

**Pull request merged**
