### PR TITLE
Add short list sniffer rule.

### PR DESCRIPTION
**Pull request by dereuromark**
Add SlevomatCodingStandard.PHP.ShortList sniff

Refs https://github.com/cakephp/cakephp-codesniffer/issues/226

### CODE REVIEW

**Comment by dereuromark** [comment]
Fails seem unrelated to changes?

**Comment by ADmad** [comment]
The fails are taken care off in my other PR.

**Comment by ADmad** [comment]
These fails though are caused by this PR https://travis-ci.org/cakephp/cakephp/jobs/494816458#L596

**Comment by markstory** [comment]
Nice :clap: I totally forgot about short list syntax.

**Comment by dereuromark** [comment]
Should be green now then on those.

**Pull request merged**
