### PR TITLE
[Rector] Start Add Rector to CI start with php5.5 set

### LINKED ISSUE #17865: Add rector to CI
### Description

Add rector to CI with --dry-run param
Add guide how to use rector to https://github.com/cakephp/cakephp/wiki

Based on this issue: https://github.com/cakephp/cakephp/issues/17756

### CakePHP Version

_No response_

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/cakephp/cakephp/issues/17865

@Harfusha @markstory @dereuromark Here I start Add Rector to CI, start with php 5.3 set, it can be incremently in multiple PRs for easier to review.

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready to merge 👍

**Comment by Harfusha** [comment]
Why templates are not checked using rector?

**Comment by Harfusha** [comment]
And is there need to split it into multiple PRs when the whole config from the closed issue is not making any changes? It has all the ignores and all the rules that were approved.

**Comment by samsonasik** [comment]
`templates` files start with short open tag `<?=`, it skipped by rector as may cause invalid print on apply changes, see PR:

- https://github.com/rectorphp/rector-src/pull/6068

`templates` under `tests` directory also mostly fixtures files :)

The idea is start with php5.3, increment to php 5.4 and so on, I list to directories with php files, and that may have change later on increment feature

**Comment by Harfusha** [comment]
This made those changes because you are on wrong branch. All rector fixes were made on 5.next.

**Comment by samsonasik** [comment]
sure 👍 I just changed target branch and updated to use php55 set, as this that make initial change ;)

**Comment by Harfusha** [comment]
Here is the PR with all the approved rules
https://github.com/cakephp/cakephp/pull/17900

(It changes only 9 files)

**Comment by Harfusha** [comment]
Changes you are making right now should be ignored. The class string to ::class

**Pull request closed without merging**
