### PR TITLE
Find table from class

### PR DESCRIPTION
**Pull request by fxleblanc**
## Explanation

When both $import and $fields are not specified in the Fixture class, the class name should be used instead of throwing an exception.
## _modelFromClass

I took the liberty of extracting the logic to get the Class name. It doesn't change anything but it give more flexibility to the developer.

### CODE REVIEW

**Comment by markstory** [comment]
What does the previously problematic fixture look like?

**Comment by fxleblanc** [comment]
There were no problematic fixtures. The enhancement I propose only opens up the possibility to declare a fixture with minimum configuration, mainly no $import or $fields declared. Before, you had to specify the table or model in the $import variable to not throw an error.

**Comment by markstory** [comment]
@fxleblanc Having to be a little bit more explicit was one of the goals with CakePHP 3. I'm not sure defining an import is difficult task and being explict that you want to import schema has some value.

I might be alone in this opinion though :smile:

**Comment by HavokInspiration** [comment]
If both ``$import`` and ``$fields`` property are not defined, your change should not have any effect since the method ``_schemaFromImport()`` is called only if ``$import`` is defined.
If both are not defined, the schema will be reflected directly from the datasource (this was implemented in the last release).

But I may be missing something.

Can you show us a Fixture that would fail without your change and work with the change ?

**Comment by fxleblanc** [comment]
@HavokInspiration you're right, I totally missed that. If you don't specify anything and the table exists, the tests pass without my change. I'll amend my commit.

**Comment by fxleblanc** [comment]
I guess you could still merge this since the new test offers some documentation.

**Comment by markstory** [comment]
The tests look good. I'm not sure we need another hook method inside a hook method.

**Comment by fxleblanc** [comment]
To be honest, this started out as a way to get the model name from the class when I was trying to change the logic in _schemaFromImport. There is no particular reason other than to give more utility. In the end, it's your call.

**Comment by HavokInspiration** [comment]
To me, the tests should not be modified. See [this highlight](https://github.com/fxleblanc/cakephp/blob/model-from-class/tests/TestCase/TestSuite/TestFixtureTest.php#L305-L327)

The highlighted parts are exactly the same in two different methods. This does not serve any purpose.

As for the ``_modelFromClass()`` method addition, I'm not against it. However, if the model is needed after a call from ``_tableFromClass()``, it's always possible to inflect the table name back to a model name using ``Inflector::classify()``.
But in a big tests suite, maybe doing two inflections for nothing can have an impact of perf ?

I actually don't have a very solid opinion on this.

**Comment by dereuromark** [comment]
I am quite sure the Inflection does not impact performance, compared to the DB operations.
But I don't have a solid opinion apart from that either.

**Comment by fxleblanc** [comment]
@HavokInspiration thanks for pointing that out. I'll remove the test. However, keeping the utility method _createLettersTable could prove to be usefull. In this case, it cleans up the testInitNoImportNoFields test method.

**Comment by fxleblanc** [comment]
Also, if I follow correctly, the Inflector would be a better choice performance wise compared to a database call. In the same vein, would the Inflector be more performant than the TableRegistry. I say this because we could replace this line:
```
$import['table'] = TableRegistry::get($import['model'])->table();
```
with this line:
```
$import['table'] = Inflector::classify($import['model'];
```
What's the advantage of using TableRegistry in this case?

**Comment by dereuromark** [comment]
This would not be a DB lookup as the schema information will most likely already be available.

**Comment by fxleblanc** [comment]
Right, so the only question left is which of the two is better: Inflector or TableRegistry.

**Comment by dereuromark** [comment]
TableRegistry as you could change the name via init and table().
As such Inflector could give you the wrong thing.

**Comment by fxleblanc** [comment]
Ok. Thanks for your explanation. To be honest, I don't know much about TableRegistry. I'll check it out. For the rest, I'm gonna let you decide if you want the utility methods.

**Pull request closed without merging**
