### PR TITLE
added json_encode option into jsonType

### PR DESCRIPTION
**Pull request by saeideng**
my suggested sample code to : https://github.com/cakephp/cakephp/issues/11311
```php
Type::build('json')
    ->encode(function($value){
             return json_encode($value, JSON_HEX_TAG,  100);
           });

```
feel free to accept or close :)

### CODE REVIEW

**Comment by davidyell** [comment]
This could do with a test case.

**Comment by saeideng** [comment]
yes after accepting by core team

**Comment by ADmad** [comment]
A callback seems overkill to me. I would just allow setting encoding options. Changing depth seems like a very uncommon use case and for that one should just use a custom type class.

**Comment by saeideng** [comment]
And what is your suggest for json_decode()

**Comment by markstory** [comment]
> And what is your suggest for json_decode()?

I still think we shouldn't be adding methods for this and instead get developers who need custom JSON handling to replace the JSON type.

**Comment by ADmad** [comment]
I guess it's `..or close` then :stuck_out_tongue:

**Comment by saeideng** [comment]
>I still think we shouldn't be adding methods for this (json_decode)
>I guess it's ..or close then 

do you agree with `setEncodeOption()` ?
if no ,please close the PR
(I don't understand that  you agree with `json_encode option` or no)

**Comment by markstory** [comment]
@saeideng I don't think providing a callback to entirely replace the encoding process is the right approach. I could see having `setEncodeOptions(JSON_UNESCAPED_UNICODE | JSON_HEX_TAG)` and having a `setDecodeOptions()` method to allow control over the decoding.

I'm not confident that needing to customize how JSON is handled is a common enough requirement that we _should_ do this. Adding more methods for what seem like infrequent scenarios adds complexity to CakePHP. Replacing the Type mapping gives people complete control over json types and requires no work from us.

**Comment by davidyell** [comment]
I agree, this is exactly what custom data types are for.

**Comment by saeideng** [comment]
thanks @markstory  
closed

**Pull request closed without merging**
