### PR TITLE
Backported few Table class methods

### PR DESCRIPTION
**Pull request by bancer**
Partially backported initialize(), belongsTo(), hasOne(), hasMany() and belongsToMany(), addAssociations() methods from Table to Model.

### CODE REVIEW

**Comment by markstory** [comment]
I'm wary of adding features to a release that is in 'bugfix' mode. These new methods could cause strict errors with userland code.

**Comment by bancer** [comment]
That would make the migration from 2.x to 3.x a bit easier.

**Comment by dereuromark** [comment]
That's what the [Shim](https://github.com/dereuromark/cakephp-shim) plugin can help with IMO.

**Comment by ADmad** [comment]
I too am not in favor of adding new methods/features to 2.x.

You can add these methods to your AppModel or use dereuromark's shim plugin.

**Comment by bancer** [comment]
It is not easy to understand why are you so reluctant to backporting. It is quite depressing. These changes do not break any existing CakePHP interfaces or functionality and the risk that the userland code would have the same methods is minimal. But even if it would have them then it would be quite easy to rename there and the project with such code would only benefit from being closer to migrating to Cake 3. Shim plugin is great but it is more convenient to have non-breaking backports in the core code. Everybody could benefit from that but not only those who install the plugin. And maybe it would not seem so damn difficult to migrate from 2.x to 3.x.

**Comment by ADmad** [comment]
> But even if it would have them then it would be quite easy to rename there...

That's easy for you to say but we can't risk breaking people's apps in bugfix releases. If you don't want use the Shim plugin just add those methods to your `AppModel`. That achieves what you want without the risk of causing problems to anyone else.

We have supported 2.x long enough and clearly communicated that it's in bugfix only mode now. We cannot keep on backporting 3.x features to 2.x and add to our maintenance overhead. As a group of volunteers contributing their spare time for free there's only so much we can do.

**Comment by dereuromark** [comment]
So please PR against shim or use your own plugin base classes here.
Closing as bugfix mode for 2.x cannot extend to the proposed changes.

**Pull request closed without merging**
