### PR TITLE
Allow retrieving entity from EntityContext.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by dereuromark** [comment]
I wonder if you need to leave the protected method in there for BC, it is highly unlikely, but someone could have extended it maybe?

**Comment by ADmad** [comment]
@dereuromark It's a one in a million chance, I'll happily accept that persons curses :)

**Comment by jadb** [comment]
:+1:

**Comment by markstory** [comment]
@dereuromark We don't have [strong API guarantees around protected methods](http://book.cakephp.org/2.0/en/contributing/backwards-compatibility.html).

**Pull request merged**
