### PR TITLE
Allow array based URLs as parameter for Response::location()

### PR DESCRIPTION
**Pull request by waltervos**
Saves you from having to rewrite these redirects when changing routes.

### CODE REVIEW

**Comment by ADmad** [comment]
I am curious what's your use case which requires directly using `Response::location()` instead of `Controller::redirect()`.

**Comment by AD7six** [comment]
> I am curious what's your use case which requires directly using Response::location()

Me too

**Comment by ADmad** [comment]
Regardless, you could just do `reponse->location(Router::url($url))`. Having `Router` as dependency in `Response` feels icky.

**Comment by waltervos** [comment]
@AD7six @ADmad Well, I thought `Controller::redirect()` was supposed to redirect right away correct? It might just be my own ignorance, but I sometimes set the redirect location at one point in the script, and perform some additional work after. I now use `reponse->location(Router::url($url))`, indeed.

**Comment by ADmad** [comment]
> but I sometimes set the redirect location at one point in the script, and perform some additional work after.

People usually do the additional work first and redirect at the end :)  Also in 3.x Controller::redirect() returns object instance. So save it in a local var, do your additional stuff and then do `return $response` from method.

**Comment by dereuromark** [comment]
Closing as works-for-me then.

**Comment by waltervos** [comment]
@ADmad Yeah, upon further inspection this began to dawn on me too... :-#

**Comment by AD7six** [comment]
@waltervos I'd say your reasoning is valid, though not ideal. 

I'd recommend looking at using background workers rather than redirecting and not closing the request; For one if whatever you're doing after redirecting takes time you're tying up your web-server workers - other requests can easily end up being queued/dropped whilst that processing is still going on.

**Pull request closed without merging**
