### PR TITLE
Made $options array in @methods of FlashComponent optional

### PR DESCRIPTION
**Pull request by Xymanek**
Follow up to #7691 with small fix that was requested in that discussion

### CODE REVIEW

**Comment by dereuromark** [comment]
Minor issue: it also must to be string or it does not work with PHP < 7:

    @method void success($message, array $options = []) Set a message using "success" element

**Comment by ndm2** [comment]
@dereuromark Not sure if something changed with PhpStorm 10, I haven't upgraded yet, but AFAIK type hints in `@method` tags should be treated as equivalents of type hints in `@param` tags.

**Comment by dereuromark** [comment]
They are parsed and should be consistent to what PHP version is used along with the code.
The Cake3 code is for PHP5.4+ and as such must be compatible with it. Removing it seems like the only option for now.
We can re add it once we are PHP7+ as composer requirement.

**Comment by dereuromark** [comment]
unbenannt

**Comment by ndm2** [comment]
@dereuromark But how does them being "parsed" affect anythig? See http://manual.phpdoc.org/HTMLSmartyConverter/PHP/phpDocumentor/tutorial_tags.method.pkg.html , the example has `int` type hints ever since, AFAICT this should never have been interpreted as a 1:1 signature represenation, if PhpStorm does that, then I'd say that PhpStorm is wrong (it wouldn't be the first `@method` tag related problem, it still can't handle for example multiple types).

**Comment by dereuromark** [comment]
All I know is that adding it breaks the whole thing and makes it pointless to have it in there in the first place :)
Removing it makes it work. The logical conclusion for me is the latter then.

**Comment by ndm2** [comment]
@dereuromark Ah ok, I see... I'd still say that PhpStorm is wrong here though, other IDEs can handle this just fine.

https://youtrack.jetbrains.com/issue/WI-18194

**Comment by dereuromark** [comment]
For me PhpStorm is correct, though. Defining those on this level, but not in the code itself would be inconsistent. We cannot typehint scalar anywhere, so why should this documentation method typehint be able to do that if the methods cannot do that themselves?
For PHP7 this is possible for methods itself, thus the documentation may also use this IMO.
At least what parsing doc block annotions are concerned.

**Comment by ndm2** [comment]
It should be able to because there simply is no other way to define the types in an `@method` tag :)

As I said, IMHO type hints in `@method` signatures should be treated as `@param` tag type hint equivalents, they should not be parsed by the normal PHP parser rules, which PhpStorm falesy does/did.

https://youtrack.jetbrains.com/issue/WI-28354 Looks like it could be this problem, which should have been fixed, so it might be a regression.

**Comment by dereuromark** [comment]
And IMO there is no need to, as PHP cannot assert it anyway :) There should be an alternative format here for doc only stuff probably.

But either way you are right, seems like a regression in this IDE :(

**Comment by Xymanek** [comment]
When I've started making these changes, I was still using PhpStorm 9.0.1 or so. And back then it didn't say it was a problem. Also, I've followed these docs http://www.phpdoc.org/docs/latest/references/phpdoc/tags/method.html which say that any type is allowed in a `@method` tag.

Before adding `= []` I've upgraded to PhpStorm 10 and after upgrade it started giving me an error as well. However, since it worked OK before and even in PhpStorm 10 it correctly hints when you try to use those methods, I decided to leave it as it is.

So yes, looks like a bug in the IDE :(

P.S. When I try adding `\Exception` as second possibility for $message then it gives me `Expected: variable` error and stops hinting correctly. Anyone knows any way around this?

**Comment by dereuromark** [comment]
IMO we should hint as easy as possible. It should aim to help us (and provide typehinting here) not block us from working. So I still say, keep it simple and ommit the breaking scalar typehint for now.

**Comment by ndm2** [comment]
@Xymanek Multiple types not being supported is another PhpStorm bug, please vote for https://youtrack.jetbrains.com/issue/WI-18194, now with their new payment model in place, they should have sooooo much free time to fix things :)

**Comment by dereuromark** [comment]
As if.. my return void bug is still open for years :P

**Comment by ndm2** [comment]
Yeah, like so many others ;( Just noticed that the scalar thingy seems to be fixed in 10.2 EAP already https://youtrack.jetbrains.com/issue/WI-28587, so it should be safe to use I guess.

**Pull request merged**
