### PR TITLE
3.0 remove deprecated assertTag for RC...

### PR DESCRIPTION
**Pull request by antograssiot**
and a  comment on deprecated function

### CODE REVIEW

**Comment by markstory** [comment]
Looks good, this will probably cause breaks in more than a few apps/plugins.

**Comment by antograssiot** [comment]
@markstory so do you want to keep it and throw a warning so it can be removed maybe later ?

**Comment by markstory** [comment]
Emitting an error might give us a chance to fix all the plugins.

**Comment by antograssiot** [comment]
updated to throw an error.

**Pull request merged**
