### PR TITLE
Load default EmailConfig if it exists

### PR DESCRIPTION
**Pull request by oldskool**
Refs #5764

### CODE REVIEW

**Comment by dereuromark** [comment]
Why not just adjusting the default value as I suggested and do?

**Comment by ADmad** [comment]
This can potentially break existing apps. The change should target 2.7 branch not master.

**Comment by oldskool** [comment]
@dereuromark Because if a `app/Config/email.php` does *not* exist, a `ConfigureException` is thrown. This way, you can make sure the config will only be set if the config file itself exists. So with this fix, it works for both apps that have and haven't got a email config file.

**Comment by oldskool** [comment]
@ADmad Good point. Created a new PR under #5768

**Pull request closed without merging**
