### PR TITLE
Add test selecting a single field of associated table with null value.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
Unfortunately this is expected behavior based on [this](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/ORM/ResultSetTest.php#L272) test. It does make sense setting the property to null when associated records doesn't actually exist. But in the test case I have the associated record does exist just the field I have selected has null value. Not sure how we can differentiate between the 2 cases.

**Comment by ADmad** [comment]
Not sure if this is the correct fix but I used autoFields to check whether the associated record should be set to null or not.

**Comment by markstory** [comment]
Looks reasoable to me.

**Comment by lorenzo** [comment]
Nice, this is an elegant solution :)

**Comment by ADmad** [comment]
Yay!

**Pull request merged**
