### PR TITLE
Reset base column type when column type is changed.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by othercorey** [comment]
Do we have any examples where the column type and base type are different?

**Comment by ADmad** [comment]
> Do we have any examples where the column type and base type are different?

Checking the code I only found examples in tests where they are different. But whether the base type is same or different than the column type is not the issue here.

The problem is that `TableSchema` caches the base type when you call `baseType()`. So unless you clear it when changing the column type using `setColumnType()`, `baseType()` will continue returning the old cached type, which would be incorrect.

**Comment by othercorey** [comment]
I was trying to ask if we have a test where they aren't the same to ensure it resets to the correct base type. The test you fixed seemed to show the both type for column and base.

**Comment by ADmad** [comment]
Without my fix the test on line `177` will fail and return the stale base type `string` instead of `json`.

**Comment by othercorey** [comment]
I was thinking we needed to ensure the correct base type was set after this (by having one that wasn't the same as the column type).

But, I was wrong and the unset() doesn't need that test. Looks good!

**Review by othercorey — APPROVED** [review]

**Pull request merged**
