### PR TITLE
replace @method docbloc with @mixin where possible

### PR DESCRIPTION
**Pull request by LordSimal**
If methods are simply proxied through via `__call()` then a simple `@mixin` helps stan to understand whats happening

### CODE REVIEW

**Comment by ADmad** [comment]
Does method name autocompletion in IDEs also work as expected with this?

**Comment by LordSimal** [comment]
It does for PHPStorm
image

**Comment by LordSimal** [comment]
It does not work for VSCode and the free version of intelephense, but as far as I can tell it works for the [paid version of intelephense](https://github.com/bmewburn/vscode-intelephense/issues/2958#issuecomment-2248937828)

**Comment by LordSimal** [comment]
I would hope that NeoVim's default PHP LSP has support for `@mixin`. @markstory would be the best to verify that 😁

**Review by ADmad — APPROVED** [review]

**Comment by ADmad** [comment]
The free version of "PHP Tools" vscode plugin also supports `@mixin`.

**Comment by markstory** [comment]
> I would hope that NeoVim's default PHP LSP has support for `@mixin`

Neovim's LSP uses intelliphense or phpactor, so it will inherit support for `@mixin` from those tools.

**Pull request merged**
