### PR TITLE
Deprecate non assoc options usage.

### PR DESCRIPTION
**Pull request by dereuromark**
Follow https://github.com/cakephp/cakephp/pull/15806

Will simplify the documentation for this method to just `array<string, mixed>` in 5.0

### CODE REVIEW

**Comment by othercorey** [comment]
Seems like this would throw a deprecation warning too many times, but @markstory did add some cache logic.

**Comment by dereuromark** [comment]
What do you mean?
Doesnt seem like a feature widely used, pretty much no one even knows it exists or is expected to work :)

**Comment by othercorey** [comment]
Sorry, I was looking at the _initInputHelper() function only. You're right.

**Review by ADmad — APPROVED** [review]

**Comment by othercorey** [comment]
@dereuromark Can you add this to the 4.3 migration notes?

**Pull request merged**
