### PR TITLE
Rename Table to Schema for consistency and less confusion.

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/cakephp/issues/9683
I didnt change any tests, just moved the class and class_aliased it.

With class_alias() this should be safe for 3.next, right?
Would otherwise extension be a solution, since then instance_of() would still be true for checks on the old class.

### CODE REVIEW

**Comment by inoas** [comment]
Did you do a test passing a Table object to a function that typehints Schema?

**Comment by ADmad** [comment]
Wondering if renaming it to `TableSchema` would be more indicative.

**Comment by chinpei215** [comment]
Dejavu. See https://github.com/cakephp/cakephp/pull/8718

**Comment by dereuromark** [comment]
@ionas Since those are class aliases I suspect them to be fine. But someone could sure add a test here to be certain.
Since I didnt modify any tests there could very well already be a test for it by the way.

**Comment by markstory** [comment]
Looks good to me.

**Comment by chinpei215** [comment]
@markstory Though I don't oppose this change, I think it is important to mention that users will get E_STRICT errors, when we release 3.4.

**Comment by chinpei215** [comment]
@markstory Never mind. Using aliases in the method signature seems to work as expected. Probably, I might misunderstand meaning of [your comment](https://github.com/cakephp/cakephp/pull/8718#r61697606).

**Pull request merged**
