### PR TITLE
3.0 database split

### PR DESCRIPTION
**Pull request by lorenzo**
Added a README for the database package that does is not explained through the use of the full ORM and added a composer.json so it can be split.

### CODE REVIEW

**Comment by lorenzo** [comment]
The docs in the readme are not 100% complete, bu I think it is a good start that will at least help people getting started with it.

**Comment by markstory** [comment]
@lorenzo I did my updates as commits.

**Comment by lorenzo** [comment]
@markstory Thanks! Also added `database` in the list of namespaces to split in the `Makefile`

**Comment by lorenzo** [comment]
Merging so I can create the repo

**Pull request merged**
