### PR TITLE
Add changes from rector rule ReturnBinaryOrToEarlyReturnRector

### PR DESCRIPTION
**Pull request by Harfusha**
https://github.com/cakephp/cakephp/issues/17756

### CODE REVIEW

**Review by dereuromark — APPROVED** [review]

**Comment by ADmad** [comment]
I don't see how this change is an improvement. It changes a single statement into multiple code paths.

**Comment by dereuromark** [comment]
I guess bail early on a simple case makes it easier to read as dev maybe?

**Comment by ADmad** [comment]
Bailing out early does make sense when there are additional statements, here both are already single statements.

I don't understand why rector dislikes `||` and splits them into separate statements. There's another PR too where the `||` in `if` checks are split into 2 `if` blocks.

**Comment by othercorey** [comment]
Going to skip this one so we can review just meaningful changes not just "ran rector rules".

**Comment by Harfusha** [comment]
I think the new syntax is much more readable, because conditions not dependent on each other are splited.

**Pull request closed without merging**
